lib/bundler/templates/newgem/test/test_newgem.rb.tt

`MiniTest::Unit::TestCase` was renamed to `Minitest::Test` in minitest 5.0.

use `Minitest::Test` instead of deprectaed `MiniTest::Unit::TestCase`

---

lib/bundler/cli.rb
lib/bundler/cli/cache.rb
lib/bundler/cli/package.rb
lib/bundler/definition.rb
lib/bundler/runtime.rb
spec/commands/package_spec.rb

so that a single cache directory can be used with multiple ruby versions
we use bundle package to build a package that we then push out to all servers, but when slow-rolling a new version of ruby (i.e. upgrading from 1.9 to 2.1), the cache directory will only have the gems pertinent to the version of ruby used to package. by adding --all-platforms, the cache directory will have them all, and a subsequent bundle install --deployment --local will work correctly, regardless of if the server is running 1.9 or 2.1.

implement all_platforms options for cache/package

---

lib/bundler/source.rb

IMHO the method is easier to understand if all the tasks to be done in case of locked gems is in one section.
I considered pulling out the getting of `locked_spec_version` into a private method like so:
```ruby
def get_locked_spec_version(spec)
locked_spec = Bundler.locked_gems.specs.find { |s| s.name == spec.name }
locked_spec.version if locked_spec
end
def version_message(spec)
message = "#{spec.name} #{spec.version}"
if Bundler.locked_gems
locked_spec_version = get_locked_spec_version_of(spec)
if locked_spec_version && spec.version != locked_spec_version
message << " (was #{locked_spec_version})"
end
end
message
end
```
But I thought it might be too much. Feel free to close if this is undesirable. :smile:

Realign Source#version_message to reveal intent

---

lib/bundler/fetcher.rb
spec/install/gems/dependency_api_spec.rb
spec/support/artifice/endpoint_api_forbidden.rb

Previously, it tried to make an unauthenticated request first, then retried with authentication if the first request failed.
This causes issues on some gem servers. For example, Gemfury supports the dependency API and allows a mix of public and private gems in the same repository. It does not forbid unauthenticated requests, but it returns partial information.
Now configured credentials are always used.
Fixes #3297, #3296, #3180.

Always use source credentials

---

CHANGELOG.md
lib/bundler/templates/newgem/lib/newgem/version.rb.tt
spec/bundler/gem_helper_spec.rb
spec/commands/newgem_spec.rb

I noticed that the FAQ section of the Semantic Versioning 2.0.0 spec suggests that you should start versioning from `0.1.0` but bundler currently sets the version of new gems to `0.0.1` - this is a very small change that makes new gems start with `0.1.0` as their version.

Change the initial version of new gems to 0.1.0

---

lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/shared_helpers.rb
man/bundle-config.ronn
spec/commands/config_spec.rb
spec/install/gemfile_spec.rb

- `bundle config` can be used to set a custom gemfile name for a
project (specifying an absolute path)
- using other bundle commands will now search up parent directories
for a .bundle dir and use the gemfile specified in .bundle/config if
it is set
- does not require a file named 'Gemfile' to exist
- Revert "Correct bundle-config manpage"
This reverts commit 0a814573363d48f8cd860d672f1c935fe1d89fca.
- An added bonus: you can now both set and *delete* a global bundler
setting from *anywhere*: `bundle config --delete foo`
In an empty directory `/foo/bar/`:
`echo "source 'https://rubygems.org'" > MyGemfile`
`echo "gem 'rake'" >> MyGemfile`
`bundle config --local gemfile /foo/bar/FooGemfile`
`bundle install`
`bundle show` # Should show the rake gem
`mkdir spec && cd spec && bundle show` # …

`bundle config --local gemfile /foo/bar/MyGemfile` now works

---

bundler.gemspec

Backport changes by hand from ccb06d14451c0e762dfc207f93ac2286881d168a(#3318) to fix a warning on `1.7.x`.

Fix warnings in test suite and gemspec

---

lib/bundler/rubygems_ext.rb

require fails by security error, in condition of:
* $SAFE is 1
* gems from git or github. ex: gem 'bar', :github => 'foo/bar'
original full_gem_path method in rubygems is untaint all paths of gems (in find_full_gem_path method), but Bundler override the method without untaint.

untaint gem path loaded from github

---

lib/bundler/settings.rb
spec/commands/config_spec.rb

Long config values get wrapped to a second line. If they contain certain special characters they will also get surrounded by quotes. When this happened, we would add extra quotes to the value each time the config file was saved. 94fd250935314aee86759de3e9b0e98a709823ed fixed this issue for non-wrapped lines. Now it is fixed for wrapped lines as well.
/cc @indirect #3261

Don't add extra quotes to quoted wrapped config values

---

lib/bundler/index.rb
lib/bundler/source/rubygems.rb
spec/install/gems/dependency_api_spec.rb
spec/support/artifice/endpoint.rb
spec/support/artifice/endpoint_extra_api.rb
spec/support/builders.rb
spec/support/path.rb

Consider the following scenario:
* You have two API gem sources named A and B.  (It is important that both sources are API sources).
* Source A and only source A contains version 1.0.0 of a gem named foo.
* The foo gem explicitly depends on version 1.2.0 of a gem named bar.
* Version 1.2.0 of bar exists only in source B.  However, another version of bar exists in source A.  (The version in source A does not satisfy the dependency of the foo gem).
In this case, a bundle install of the following Gemfile will fail with an error message saying it can't find version 1.2.0 of bar in any sources:
source "http://sourcea.example.com"
source "http://sourceb.example.com"
gem 'foo', '1.0.0'
Removing the bar gem from source A causes the error to stop happening.
We ran into this situation in real life …

Api source index fix

---

lib/bundler/cli/gem.rb
spec/bundler/gem_helper_spec.rb

Fix #3374
Fix an issue where double underscores in gem's name throw error while building a new gem skeleton via ```bundle gem lorem__ipsum``` command.

Handle double underscores in new gem's name

---

lib/bundler/templates/newgem/newgem.gemspec.tt
spec/commands/newgem_spec.rb
spec/support/helpers.rb

Also adds an integration test to make sure that generated gem templates can build.
Fixes #3392.

Set spec.bindir to the new executables location in the new gem template

---

lib/bundler/cli/gem.rb
lib/bundler/templates/newgem/newgem.gemspec.tt

The changed behaviour is to see if the last segment in the Bundler version contains any letters, and if so, tack it on.
So with Bundler 1.9.0.dev, you get:
```ruby
spec.add_development_dependency "bundler", "~> 1.9.dev"
```
and with Bundler 1.8.2, you get the same as before:
```ruby
spec.add_development_dependency "bundler", "~> 1.8"
```

Allow dev versions when creating a new gem

---

man/bundle-package.ronn

Added as per request by @TimMoore.
(New version of #3442, against bundler/1-8-stable.)

Add documentation for `bundle package --all-platforms`

---

lib/bundler/templates/newgem/Rakefile.tt
spec/commands/newgem_spec.rb

* Before
```shell
$ bundle gem foobar
$ cat foobar/Rakefile
require "bundler/gem_tasks"
$ cat foobar/Rakefile | wc -l
2
```
* After 
```shell
$ bundle gem foobar
$ cat foobar/Rakefile
require "bundler/gem_tasks"
$ cat foobar/Rakefile | wc -l
1
```

Remove unnecessary blank line

---

lib/bundler/cli/install.rb

Hello!
I've started looking into bundler sources recently and found that dups call in cli/install.rb can be removed, options already dups in cli.rb before passing into cli/install.rb initializer.
Tests successfully passes locally and I hope I've no broke anything.
Thank you for your hard work!
Sincerelly, Nikolay.

Remove unused dups

---

lib/bundler/inline.rb
spec/runtime/inline_spec.rb

Closes https://github.com/bundler/bundler-features/issues/47.
Enables scripts such as the following to work on their own, as long as bundler is installed:
```ruby
#!/usr/bin/env ruby
require 'bundler/inline'
gemfile do
gem 'json'
gem 'nap', require: 'rest'
gem 'cocoapods', '> 0.pre'
end
puts Pod::VERSION
```

[Inline] Add bundler/inline to allow using Bundler without a Gemfile

---

Rakefile

```
$ ruby --version
ruby 2.0.0p598 (2014-11-13) [x64-mingw32]
$ rake spec:deps
DL is deprecated, please use Fiddle
c:/Ruby200-x64/bin/ruby.exe -S gem list -i '^mustache$' -v '= 0.99.6' || c:/Ruby
200-x64/bin/ruby.exe -S gem install mustache -v '= 0.99.6' --no-ri --no-rdoc
true
c:/Ruby200-x64/bin/ruby.exe -S gem list -i '^rdiscount$' -v '~> 1.6' || c:/Ruby2
00-x64/bin/ruby.exe -S gem install rdiscount -v '~> 1.6' --no-ri --no-rdoc
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
Illformed requirement ["~ "]
ERROR:  While executing gem ... (Gem::Requirement::BadRequirementError)
Illformed requirement ["~ --no-ri --no-rdoc"]
rake aborted!
Command failed with status (1): [c:/Ruby200-x64/bin/ruby.exe -S gem list -i...]
c:/workdir/git-workdir/bundler/Rakefile:90:in …
```

fix "rake spec:deps" fails on MinGW Ruby 2.0

---

spec/quality_spec.rb

[QualitySpec] Properly ignore warnings coming from vendored libs

---

CHANGELOG.md
lib/bundler/templates/newgem/.travis.yml.tt

As seen in [this](https://travis-ci.org/kodnin/defekt/jobs/55475451) Travis CI build and the screenshot below, Bundler 1.9 is not installed by default on Travis CI. This leaves us a problem, which can be resolved by installing Bundler 1.9 [before](http://docs.travis-ci.com/user/languages/ruby/#Dependency-Management) running Bundler.

add before_install to .travis.yml template for new gems

---

lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt

Fix URL for Contributer Covenant

---

lib/bundler/cli/install.rb
spec/install/gems/post_install_spec.rb

Implements this [Trello Card](https://trello.com/c/FPapFE0I) on ignoring specific gem's post-install messages.
```bash
bundle config ignore_messages.rack true
```
Oh and I also cleaned up gem/post_install_spec.rb by consolidating two describe groups and switching it to context blocks but git wasn't a fan so the commits got mixed together...sorry.

Setting to ignore post_install messages per-gem

---

lib/bundler/templates/newgem/Rakefile.tt
spec/commands/newgem_spec.rb

After this PR, we can run `bundle gem foo; cd foo; bundle exec rake` and it should run all the tests.
(this needs to go after https://github.com/bundler/bundler/pull/3513)
review @indirect @andremedeiros

Add test files to default rake test task

---

lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb

This makes `Bundler::Molinillo::Resolver::Resolution` warning-clean, in turns making Bundler warning-lcean.
I [opened this in Molinillo](https://github.com/CocoaPods/Molinillo/pull/21) as well, but it seems Bundler’s version is vendored and namespaced, so I wasn’t sure whether this should or should not be opened here as well.

[Molinillo] Make warning-clean

---

lib/bundler/lazy_specification.rb

Closes https://github.com/bundler/bundler/issues/3522, but I'm not convinced this is the right thing to do.

[LazySpecification] Uniq dependencies in lockfile representation

---

lib/bundler/dsl.rb
man/gemfile.5.ronn

This allows a glob option for gemspec to pass through.
An example case for when this is useful would be a lazy static test suite where running `bundle exec rake test` for a second time is a no-op and changing some source files will only cause its dependent test to be rerun on the next `bundle exec test`. That can be done by mapping test outputs to textfiles such as something_test.rb.txt (mainly for the timestamp ) and a) keeping file dependencies of tests explicitly in rake/make/whatever b) plugging in a build system like tup or fabricate.py, which handles such dependencies implicitly by tracking file reads that take place during each build (build = test run). This can be a huge time-saver for repos with large test-suites that take a long time, especially if the tests only `require` the …

gemspec should accept a glob option in its argument hash

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

I encountered the bug that the gem generator would fail on gem names containing two dashes (like `a--a`). I updated the module name generator to use a more robust regex based approach.

Improve generating module name from gem name in gem generator

---

.travis.yml

This currently has an allowed failure listing. Trying to add rbx to builds of popular Gems to test for compatibility.

Add Rubinius to Build Matrix

---

lib/bundler/cli.rb
lib/bundler/cli/install.rb
lib/bundler/definition.rb
lib/bundler/deployment.rb
lib/bundler/dsl.rb
lib/bundler/settings.rb
man/bundle-install.ronn
man/gemfile.5.ronn
spec/install/gems/groups_spec.rb

The lack of discussion in https://github.com/bundler/bundler-features/issues/68 and https://github.com/bundler/bundler-features/issues/59 is depressing, so here's some meat to get things going, hopefully.

 Implement optional groups

---

lib/bundler/friendly_errors.rb
spec/bundler/friendly_errors_spec.rb

This is to prevent super-long error messages like in #3554.

Only use first line of error messages in the issue search URL

---

spec/bundler/gem_helper_spec.rb
spec/commands/newgem_spec.rb

a72df72c7719bcb7677e5cb140cf7cdb11be652d removes the exception that prevents public pushes on RubyGems < 2.0, but one test was restoring the gemspec back to the original contents (https://github.com/bundler/bundler/commit/a72df72c7719bcb7677e5cb140cf7cdb11be652d#diff-7e091e8293b0ca921df62d6995b5b909R137).
Now it restores the TODOs, but not the removed exception.

Fixes a build failure introduced in a72df72

---

lib/bundler/cli/gem.rb
lib/bundler/ui/shell.rb

Fixes #3443 (nmarley's problem at the bottom)
The issue was that `alpha =~ beta` returns nil if `alpha` doesn't contain `beta` and the position—e.g. 6—instead of `false` and `true` respectively like was assumed by whomever wrote the original logic. It coincidentely worked for yes because everything—like 6 using my above example—except for `false` and `nil` resolve to `true`. However, when they selected no for coc or mit they were always reasked because it resolved to `nil` which for boolean settings doesn't get transformed into `false`.

Fix `bundle gem` boolean settings

---

lib/bundler/rubygems_integration.rb
lib/bundler/shared_helpers.rb
spec/runtime/setup_spec.rb

This is follow up of #3237 including the fix to the last test failure on Ruby 1.8.7 and RubyGems 2.2.2.

Fix rubygems 2.2+ compatibility

---

lib/bundler/definition.rb
spec/install/gems/sources_spec.rb

Previously, an up-to-date lock file would retain the aggregate gem
source on all dependencies, so if the gems were not installed locally,
you'd get an ambiguous gem warning and possibly the wrong source
selected.
Fixes #3585

Replace locked gem sources with Gemfile equivalents.

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

Since 17a4fc47bfad02de553e5a53b00ad38b4c905e18 (#3123), any gem name starting with an
existing const name has been regarded as "Invalid gem name" by `bundle gem` command.
However, "gem-foo" or "rails-bar" should be totally valid and rather preferable
naming for plugins for RubyGems/Rails.
This patch changes the rule to raise error only when the new gem name fully
matches an existing const name.
invalid: `gem`, `gem-version` (because `Gem::Version` already exists)
valid : `gem-foobar`, `gem-version-foobar` (when `FooBar`module does not exist)

Bundler >= 1.9.0 fails to create gem plugins

---

spec/install/force_spec.rb

Use include expectation instead of unneeded regular expression

---

lib/bundler/rubygems_integration.rb

Since rubygems/rubygems@4fa03bb7aac9f25f44394e818433fdda9962ae8d
rubygems lazily loads specs from the filesystem for a particular name.
So if you request the "foo" gem, then rubygems will go to the FS and
find the gemspecs with the "foo" name.  **Before** the change, rubygems
would search through the loaded spec list for a gem with that name.
Bundler assumed that rubygems would always search through that spec
list, so it sets the specs and relies on that internal behavior.  Since
the internal behavior changed, we need to take that in to account in the
bundler internals.
This patch changes bundler to search through the spec list for a gem
with a particular name.  Gem::Specification.stubs should be supported in
the future (though not recommended because loading every spec isn't
super …

loop through the spec list to find gems with a certain name

---

lib/bundler/rubygems_integration.rb

Depends on https://github.com/rubygems/rubygems/pull/1239.

[RubyGemsIntegration] Use .stubs_for when available

---

lib/bundler/installer.rb
lib/bundler/source/rubygems.rb

Closes #3401.
This is a deceptively simple diff -- hunting this down took a while.

[RubyGems] Allow standalone caching of builtin gems

---

lib/bundler/definition.rb
lib/bundler/lockfile_parser.rb
spec/commands/lock_spec.rb
spec/install/gems/flex_spec.rb
spec/install/gems/install_if.rb
spec/lock/lockfile_spec.rb

This makes the lockfile compatible at least back to 1.3.x, I was too lazy to switch Rubies to check back even further. It also is the ugliest, wackiest possible fix I could think of :(.

[Lockfile] Make the BUNDLED WITH section backwards compatible

---

lib/bundler/templates/newgem/README.md.tt

This adds instructions for running tests to the README template. Note that the instructions are conditional depending on whether RSpec or Minitest was selected as the default test runner.

Add instructions for running tests; fixes #3596

---

lib/bundler/fetcher.rb
spec/bundler/fetcher_spec.rb
spec/support/helpers.rb

This patch add CI information on the user_agent in order for us to track
if a given command was run by a CI, as discussed in #3233.

Distinguish CI command runs

---

lib/bundler/rubygems_integration.rb
spec/bundler/rubygems_integration_spec.rb

Closes https://github.com/bundler/bundler/issues/3680.
Fixes a regression introduced in https://github.com/bundler/bundler/commit/73cec1c5b51dd6f9a7d6712ea6832f89ce9cb4f8.
\c @indirect @rafaelfranca

[RubyGemsIntegration] Check for chdir monitor after its been backported

---

lib/bundler/cli/check.rb
lib/bundler/definition.rb
lib/bundler/environment.rb
lib/bundler/inline.rb
lib/bundler/runtime.rb
spec/commands/check_spec.rb
spec/runtime/setup_spec.rb

When either `bundle check` is run, or any application requires the `bundler/setup` file, Bundler will automatically check whether it is possible to lock the Bundle. During the lock process, Bundler updates the lock if the implicit locking changes the lock file.
Starting with the 1.10 release, Bundler includes a lockfile section named BUNDLED WITH that includes the version of Bundler that generated the lockfile. In order to minimize git churn, and guarantee that the lockfile will only be changed when the user runs an explicit Bundler command, Bundler will now only add or update the BUNDLED WITH section during commands where the user asks for changes to the lock. This includes, but is not limited to, `install`, `update`, `lock`, and `package`.
Running the `check` command or loading an …

Implicit lock preservation

---

lib/bundler/gem_helper.rb
spec/runtime/gem_tasks_spec.rb

Useful when working with multiple remotes (origin/upstream/downstream).
`rake release[remote]` will push tags into the specified remote instead of the default one.

Added optional remote argument for the rake release task

---

lib/bundler.rb
lib/bundler/definition.rb
lib/bundler/settings.rb
spec/bundler/definition_spec.rb
spec/bundler/settings_spec.rb

I moved the message display when there is not permission to write to `Gemfile.lock` to `Bundler::SharedHelpers` (is there a better place?) and reused for when writing to `config` (local or global) fails for the same reason (or the directory path cannot be created).
Should I also write specs to cover the `File.open(file, "w")` ?
Fixes #3703

Improves the message displayed when cannot create config

---

lib/bundler/templates/newgem/bin/setup.tt

bash may not always be located at `/bin/bash`.

Use `#!/usr/bin/env bash`

---

man/bundle-install.ronn

The man page originally explained that `--deployment` is not appropriate for the `test` environment, which is misleading. In a CI environment, you *do* want to use `--deployment`, despite the fact that CI will likely be using `RAILS_ENV=test` when running tests.
This PR clarifies that `--deployment` is for production and CI, and avoids explicitly referencing Rails environment names.

Clarify the purpose of --deployment

---

lib/bundler/resolver.rb
lib/bundler/spec_set.rb

Makes it more clear that the circular dependent gems are not necessarily declared in the `Gemfile` (they could be in the `Gemfile.lock`).
Closes #3738.

Improve error message for circular dependency case

---

lib/bundler/fetcher.rb

Is this enough to handle #3765 (where an issue related to not handling Errno::ENETUNREACH was reported)?

added Errno::ENETUNREACH to list of handled HTTP errors

---

man/bundle-config.ronn

My team recently ran into this and wanted to help clarify this.
I'm not intimately familiar with all the use cases for BUNDLE_PATH but I think I have the gist of what I needed clarified.
* BUNDLE_PATH is used for installing AND finding gems
* It's easy to confuse GEM_PATH and BUNDLE_PATH
* GEM_PATH is an array of paths in addition to GEM_HOME that rubygems
uses to find gems.
* BUNDLE_PATH is a single path used for gem installs and retrieval.
* GEM_PATH is ignored when you have BUNDLE_PATH set by enabling
BUNDLE_DISABLE_SHARED_GEMS

Clarify BUNDLE_PATH documentation.

---

lib/bundler/remote_specification.rb
spec/bundler/remote_specification_spec.rb

The `RemoteSpecification#sort_obj` method was added in e5d936e (which was cherry-picked from #3767) to fix #3762, but it still fails when comparing two instances of `RemoteSpecification`.
As `#sort_obj` is private, the check for `other.respond_to?(:sort_obj)` returns `false`, which means the `<=>` check falls back to the default (from `Object`) which returns `nil` if the objects being compared don't match. This then results in an `ArgumentError` when (e.g.) sorting an array containing multiple instances of `RemoteSpecification`.
The fix is simple: make `RemoteSpecification#sort_obj` public.

Ensure two RemoteSpecifications are comparable

---

lib/bundler/dsl.rb
spec/install/gems/install_if.rb

The new `install_if` command was not clearing `install_conditions` properly.
All gems defined after a `install_if -> false do ... end` would not be installed.
I think that fixes the problem.

Fix install_if not clearing install conditions

---

lib/bundler/cli/exec.rb
lib/bundler/current_ruby.rb
spec/commands/exec_spec.rb

It seems that jruby's exec does not understand that option:
```
uri:classloader:/jruby/kernel/kernel.rb:28: warning: unsupported exec option: close_others
```
The warning was skipped for rubies under 2.0 (like latest released
jruby) but the new jruby 9.0.0.0 is 2.0 compatible by default so the
check needs to be refined.

Removes a warning in jruby

---

lib/bundler/cli.rb

The `--bin` option incorrectly had the description "Set a default with `bundle config gem.mit true`." I've moved this text to the appropriate place in the `--mit` description.

Fix option description for `bundle gem`

---

lib/bundler/cli.rb
spec/bundler/cli_spec.rb

Addresses https://trello.com/c/OpuOdTZl/112-print-help-when-bundle-is-run-without-arguments.

[CLI] Print help as the default no-args command

---

lib/bundler/settings.rb
spec/bundler/settings_spec.rb

Undoes changes made in https://github.com/bundler/bundler/commit/3d76c8fefb4eed7a082719e693396b7cdb0d58b0. 2-0-dev isn't quite ready for them, yet.

Undo changes in initial "stop autoremembering flags" commit

---

DEVELOPMENT.md

Quick documentation change to let people know where they can get notifications when there is a prerelease or beta release to test.
I'm happy to update wording - I just took a first stab.

Add instructions for getting prerelease notifications

---

lib/bundler.rb
spec/install/gemfile/path_spec.rb

since invalid specs were allowed by 1.0-1.9, this change allows them in all 1.x versions. we'll go back to throwing an exception on invalid gemspecs in Bundler 2.0.
/cc @segiddins @smlance

downgrade invalid specs to a warning for now

---

DEVELOPMENT.md

It looks like bundler's executable was moved from `bin` to `exe` at some point but this documentation was not updated. This tripped me up when I was setting up my dev environment for the first time today. An easy fix!

bin should be exe in `alias dbundle` instructions

---

spec/support/helpers.rb

When running `spec/cache/gems_spec.rb:213` on master, I got the following error due to the monkey patch of `Gem::Platform::local` in `spec/support/hax.rb` not getting loaded when the spec runs `bundle :install`.
```
➜ ~/dev/bundler (master)↑⚡ $ /Users/aunger/.rvm/rubies/ruby-2.2.0/bin/ruby -S rspec ./spec/cache/gems_spec.rb:213
Run options:
include {:focused=>true, :locations=>{"./spec/cache/gems_spec.rb"=>[213]}}
exclude {:rubygems_master=>true, :rubygems=>"=< 2.4.5", :ruby=>"=< 2.2.0", :realworld=>true, :sudo=>true}
bundle cache
when previously cached
Updating files in vendor/cache
doesn't remove gems that are for another platform (FAILED - 1)
Failures:
1) bundle cache when previously cached doesn't remove gems that are for another platform
Failure/Error: …
```

Make sure that monkeypatch of Gem::Platform gets loaded on subshells

---

lib/bundler/resolver.rb
spec/commands/update_spec.rb
spec/install/bundler_spec.rb

[Resolver] Allow mis-matches in bundler requirements, and warn

---

spec/commands/newgem_spec.rb

On my work laptop, I was seeing failures in `spec/commands/newgem_spec.rb` due to the presence of  local `.git/config` files.
On my work computer, my global config is my work (private gitlab) credentials. Each github repo has a local config with my “cdwort” credentials. For example, I have one placed in `/Path/To/Bundler/.git/config`. 
Unfortunately, when a new gem is created within the test file noted above, it is created within the /Path/To/Bundler/ directory. This means it picks up my local config. All the tests for when there is no git config information fail because instead of getting nothing (which those tests expect because the test overrides my global amy.unger@corporatecompany.com setting), it gets my GitHub email.
I am using the `--remove-section` flag because if you only …

Make test suite work with local git configs

---

lib/bundler/cli/gem.rb
lib/bundler/settings.rb
lib/bundler/templates/newgem/newgem.gemspec.tt

If `BUNDLE_GEM__TEST: false` or `BUNDLE_GEM__TEST: "false"` are in `~/.bundle/config`, the README.md that is generated when creating a new gem includes instructions under the Development heading that say "Then, run \`rake false\` to run the tests."
The logic on line 29 of  README.md.tt (`if config[:test]`) fails because `config[:test]` returns the string "false" instead of the boolean.
As a patch, I changed the logic of `Bundler::Settings#[]` to convert the string "false" to a boolean.
It seems that the root of the issue is that `Bundler::Settings::BOOL_KEYS` does not include "gem.test", and it can't because it is only sometimes a boolean (when it is not 'rspec' or 'minitest'). A future fix for this could be to have two separate options, a boolean for whether or not the gem has tests and …

fix bug that causes "run `rake false`" to appear in README.md

---

lib/bundler/cli/gem.rb
lib/bundler/templates/newgem/newgem.gemspec.tt
spec/commands/newgem_spec.rb

Use a pessimistic version requirement for RSpec and Minitest in
gemspecs generated by the bundle gem command. It is best practice to
at least depend on major versions of development dependency gems.
refs #3811

Depend on major version of test gems

---

lib/bundler/fetcher/dependency.rb

URI.encode prints a warning that it's obsolete.
Fixes #3892

Use CGI instead of URI for escaping URL params

---

lib/bundler/cli/install.rb
lib/bundler/cli/update.rb
lib/bundler/installer.rb
lib/bundler/source/git.rb
lib/bundler/source/path.rb
lib/bundler/source/rubygems.rb
spec/commands/update_spec.rb
spec/install/force_spec.rb
spec/install/gemfile/git_spec.rb
spec/runtime/setup_spec.rb
spec/update/git_spec.rb
spec/update/path_spec.rb

For this issue bundler/bundler-features#33
Thanks for making great gem :)

Summarize the number of using gems

---

lib/bundler/cli.rb
man/bundle-gem.ronn
man/bundle.ronn
man/index.txt

This is my first time working with man pages, so please let me know if I missed something obvious here. I tested `bundle help gem` and the man page appeared as expected with the correct format. Is there anything else I can check?

Add man page for `bundle gem`

---

spec/realworld/edgecases_spec.rb
spec/realworld/parallel_spec.rb
spec/support/rubygems_ext.rb
spec/support/sometimes.rb

One of the causes of builds that fail late is gems that didn't install but also didn't raise an error (until the tests that depend on them fail, much much later). This tries to fail those quickly, and maybe means that we can add some retry logic.

Try failing fast if prereq gems fail to install

---

lib/bundler/dep_proxy.rb
lib/bundler/resolver.rb
lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb
lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
spec/commands/install_spec.rb
spec/install/bundler_spec.rb
spec/install/gems/flex_spec.rb
spec/install/gems/resolving_spec.rb
spec/install/gems/sources_spec.rb
spec/install/post_bundle_message_spec.rb
spec/runtime/inline_spec.rb

Closes https://github.com/bundler/bundler/issues/3803

Resolver error formatting

---

lib/bundler/source/git/git_proxy.rb
spec/bundler/source/git/git_proxy_spec.rb

Pull-request #2825 added support for authorization credentials provided by bundle-config for rubygems source. This change adds the same support for HTTP(S) URL of git source.
Users can provide username and password as following:
bundle config https://github.com/bundler/bundler.git username:password
or
export BUNDLE_GITHUB__COM=username:password
Especially for private repositories on Github, users can use personal OAuth tokens:
export BUNDLE_GITHUB__COM=abcd0123generatedtoken:x-oauth-basic
This enables us to easily deploy ruby code hosted on github private repositories to production servers where storing shared password in plain text at `~/.git-credentials` is security risk.

Private access credentials for private git repositories

---

lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt

Markdown document copied from http://contributor-covenant.org/version/1/2/0/code_of_conduct.md.

Update code of conduct to Contributor Covenant version 1.2.0

---

man/bundle-install.ronn

After using `standalone` for the first time, it took me some time to understand it was remembering the path and how I could revert the standard behavior.
So I think it's useful to make it clear that standlone changes path and path is a remembering option.

Clarify "--standalone" help message

---

lib/bundler/cli.rb
spec/commands/help_spec.rb

Bundler already delegates to executables of the form `bundler-<command>` when called as `bundle <command>` with an unknown command. Allow viewing help entries for such command plugins by
turning calls of the form `bundle help <command>` into `bundler-<command> --help`.

Add command plugin support to help command

---

lib/bundler/cli/exec.rb

Jruby 9k is ruby 2.2.2, but doesn't support processes. 
So running `bundle exec` leads to a warning `warning: unsupported exec option: close_others`.
This should fix that warning.

Fix for warning on jruby 9k

---

lib/bundler/source/git/git_proxy.rb
spec/commands/outdated_spec.rb

Tweaking the "Updating ..." output of the checkout method to reduce
confusion when running `outdated`. Opting instead for "Fetching" as it
does when doing a clone operation.

Tweaks git checkout UI output

---

spec/commands/lock_spec.rb

Gets rid of the following RSpec warning:
Using the `raise_error` matcher without providing a specific error or
message risks false positives, since `raise_error` will match when Ruby
raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially
allowing the expectation to pass without even executing the method you
are intending to call. Instead consider providing a specific error class
or message.

Specify the actual exception to test for

---

lib/bundler/settings.rb

An improvement over https://github.com/smlance/bundler/commit/426c36551823594f381b1fd136e9836a12f82d8e#diff-75219bd6bc0defc0e7f4ba322d92f950R157.
* The `install_path` variable isn't necessary, but I left it in for the sake of clarity
* The `if` branches at L155-167 can be shortened since three return values are the same, but I left it lengthened for clarity via the comments
Thoughts?

Add comment describing Bundler.settings.path

---

lib/bundler/cli.rb
lib/bundler/cli/install.rb
spec/cache/gems_spec.rb
spec/commands/install_spec.rb
spec/commands/package_spec.rb

Removes the --cache option and replaces it with an error that asks the user to run `bundle cache`.

Remove `bundle install --cache`

---

lib/bundler/source/rubygems.rb
spec/bundler/source/rubygems_spec.rb

Since `URI#parse` accepts URIs such as *http:rubygems.org* as per RFC 2396,
we reject such sources manually early in the process, in order to provide more
helpful error messages.
Fixes #3925.

Be stricter when accepting rubygems source URIs

---

.rubocop.yml
.rubocop_todo.yml

We don't agree with this rule. See discussion in <https://github.com/bundler/bundler/pull/3922>.

Disable Lint/UnusedMethodArgument

---

lib/bundler/cli/update.rb
lib/bundler/definition.rb
spec/commands/update_spec.rb
spec/update/git_spec.rb

Fixes #3759 and #3761.
And also another issue I found where if:
1. You have a Gemfile with a group,
2. That group contains a gem with the same name as a source
3. And you run `bundle update --group group_name`
4. Then all gems associated with the source will be updated.
The 3 cases fixed here are all pretty subtle. The specs should make it clearer, and the github issues above add more context.
Note that this PR removes the ability to use `bundle update --source gem_name` as a hacky way to update a gem 'conservatively'. This is detailed in #3759.

Fix `--source` option causing incorrect gem unlocking

---

lib/bundler/source/git/git_proxy.rb

Before:
$ bundle install
Fetching git://github.com/agis-/some_gem.git
fatal: ambiguous argument 'FOO': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git  [...] -- [...]'
Git error: command `git rev-parse WRONG` in directory /cache/path
has failed.
Ref 'foo' was not found. Perhaps you mispelled it?
If this error persists you could try removing the cache directory
After:
$ bundle install
Fetching git://github.com/agis-/some_gem.git
fatal: Needed a single revision
Git error: command `git rev-parse --verify WRONG` in directory /cache/path
has failed.
Ref 'foo' was not found. Perhaps you mispelled it?
If this error persists you could try removing the cache directory
Fixes #3879.

Show friendly errors when ref is not found

---

lib/bundler/gem_helper.rb

when you in your `.gemspec` specify
```
if spec.respond_to?(:metadata)
spec.metadata['allowed_push_host'] = 'https://gems.example.com'
end
```
you can't use the `bundler` rake tasks, as it can't specify the alternate host. This change picks up the `allowed_push_host` and uses it when pushing.

make it able to specify gem host with GEM_HOST env

---

lib/bundler/source/path.rb
spec/cache/path_spec.rb

When a gem has the same path prefix as the application that is being bundled,
the gem will not be added to vendor/cache.
For example: a gem with a path /home/test/src/bundled_gem and an application with a path
/home/test/src/bundled that references it.

make sure intersecting gem paths are cached

---

lib/bundler.rb
spec/commands/exec_spec.rb

Output gemspec validation errors on exec commands

---

lib/bundler/resolver.rb

Given this previous configuration:
```ruby
gem 'rails',      '~> 4.1.11'
gem 'sass-rails', '~> 4.0.3'
```
When changing both gem versions:
```ruby
gem 'rails',      '~> 4.2.4'
gem 'sass-rails', '~> 5.0.0'
```
And running `bundle update rails`, you see this error message:
```
You have requested:
sass-rails ~> 5.0.0
The bundle currently has sass-rails locked at 4.0.3.
Try running `bundle update sass-rails`
```
This commit adds a hint to run `bundle update rails sass-rails`:
```
You have requested:
sass-rails ~> 5.0.0
The bundle currently has sass-rails locked at 4.0.3.
Try running `bundle update sass-rails`
If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`
```

Improve hint on conflict error message

---

lib/bundler.rb
lib/bundler/settings.rb
lib/bundler/source/rubygems.rb
spec/commands/install_spec.rb
spec/install/gems/dependency_api_spec.rb
spec/install/gems/flex_spec.rb
spec/install/gems/sources_spec.rb
spec/lock/lockfile_spec.rb
spec/support/artifice/endpoint_no_gem.rb
spec/support/path.rb

@indirect wrote this in response to https://github.com/bundler/bundler/pull/3975

Add cross-application user cache [3975]

---

lib/bundler/dsl.rb
spec/bundler/dsl_spec.rb

Before this change, a gem inside a rubygems source block that also
defined a custom source, would cause subsequent gems inside that same
block to be fetched from rubygems.org.
For example:
source "https://rubygems.org"
source "https://foo.bar" do
gem "rails", git: "git@github.com/rails/rails.git"
gem "i18n"
end
In that case, i18n would be fetched from rubygems.org instead of
foo.bar.
Fixes #3974.
Backport of #3978

Dsl#with_source should restore the previous source

---

lib/bundler/cli/config.rb
spec/commands/config_spec.rb

Previously, if the user tried to set `path` when `system` was set (and viceversa), the conflicting option would be removed, but the passed option would not be saved.

Persist path to configuration when there are conflicts

---

lib/bundler.rb
lib/bundler/cli/check.rb
lib/bundler/cli/install.rb
spec/commands/config_spec.rb
spec/install/path_spec.rb
spec/runtime/executable_spec.rb
spec/runtime/setup_spec.rb

As [mentioned](http://git.io/vnqjO), this flag is a leftover from a previous implementation.

Remove `disable_shared_gems` flag

---

lib/bundler.rb
spec/runtime/with_clean_env_spec.rb

Clean RUBYLIB as well in `with_clean_env`

---

spec/commands/config_spec.rb

the current running process cannot reliably report the state of the
bundler config file when it's changed on disk (cfr. git.io/vnclk)
Closes #4003.

Revert to using sub-processes

---

CODE_OF_CONDUCT.md

@indirect Follow the PR.
Reference:
http://contributor-covenant.org/version/1/2/0/code_of_conduct.md

Integrate new wording from version 1.2.0 of Code of Covenant

---

lib/bundler/index.rb

Index#search is called many times so this change is worth it.
With a single gem in your Gemfile, this change drops the string
allocations by nearly 30,000.
Script:
```ruby
require 'allocation_tracer'
ObjectSpace::AllocationTracer.setup(%i{path line type})
result = ObjectSpace::AllocationTracer.trace do
begin
require 'bundler/inline'
rescue LoadError => e
$stderr.puts 'Bundler version 1.10 or later is required. Please update your Bundler'
raise e
end
gemfile(true) do
gem 'benchmark-ips'
end
end
result.sort_by{|k, v| k}.each{|k, v|
puts ([v[0]]+k).join("\t")
}
```
**String allocations before**:
```
$ruby benchmark_allocations.rb | grep T_STRING | sort -nr | head -n 10
65461 /Users/joerafaniello/.rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.r …
```

Allocate the "ruby" and "\0" Strings once.

---

man/bundle-config.ronn

Fixes some outdated information in `bundle config`'s man page:
* Avoids using invalid flags
* Tells users to pass options to `bundle config` instead of `bundle install`

Update config man for 2.0

---

lib/bundler/cli.rb
lib/bundler/cli/install.rb
man/bundle-config.ronn
man/bundle-install.ronn
spec/bundler/settings_spec.rb
spec/commands/clean_spec.rb
spec/commands/exec_spec.rb
spec/commands/install_spec.rb
spec/install/gems/sudo_spec.rb
spec/install/path_spec.rb
spec/other/platform_spec.rb

As [planned](https://github.com/bundler/bundler-features/issues/26#issuecomment-129487171), this PR removes the `--system` flag from `install`.
Users are expected to use `bundle config path.system true` instead.
Also fixes a bug introduced in ddafe06ab60c42943cc7c8d64973d4745d6a26ca where passing the `--system` option would set `Bundler.settings[:path]`, which in turn would be used to `disable_shared_gems` when doing a system install - which seems wrong.

Remove --system flag from install

---

man/bundle-install.ronn

The deployment mode section in `install`s man page still read as if installation to the system path were the default.

Update deployment mode explanation

---

lib/bundler.rb
lib/bundler/definition.rb
lib/bundler/gem_helper.rb
lib/bundler/installer.rb
lib/bundler/runtime.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
lib/bundler/source/git/git_proxy.rb
lib/bundler/source/path/installer.rb
lib/bundler/source/rubygems.rb
spec/commands/install_spec.rb

This introduces `SharedHelpers#filesystem_access` which can wrap any piece of code that makes a modification to the file system (eg. creating a directory). Doing so, results in user-friendly errors instead of the original ones (ie `Errno:EACCES`).
In the future we could (and probably should) handle more error types within `#filesystem_access`.
Closes #4009.
Closes #3988.
https://trello.com/c/OicgrmDd/102-improve-permissions-error-messages.

Friendly filesystem permission errors

---

lib/bundler/runtime.rb

When bundling gems via Git with native extensions with the `--clean` flag the `extensions/` directory should be left around.
Lacks a test, I'll follow up with that.
---
(optional debugging fairy tale for the record)
It all started an innocent Friday morning with a production Rails console taking a long time to boot (~2m). I started investigating why. `ps auxf` quickly surfaced that something fishy was going on:
```
8192     12831  0.3  0.0 196096 10696 pts/4    Ssl+ 15:48   0:00  \_ borginit:shopify/console/1
8192     12927  0.0  0.0   8316   668 pts/4    S+   15:48   0:00      \_ /sbin/ppidshim /bin/bash -c exec bin/rails console
8192     12929 48.0  0.3 853924 475960 pts/4   Sl+  15:48   0:10          \_ ruby /app/bin/rails console
8192     16762  0.0  0.0   8568   816 pts/4    S+ …
```

runtime: avoid cleaning up extensions directory

---

lib/bundler/cli.rb

The current long description or the `binstubs` command does not provide
any hint that it can accept multiple gems as arguments and generate
binstubs for all of them.
This PR enhances the description using similar phrasing for usage
with multiple gem arguments, to the `outdated` command.

Update binstubs command description for multiple gems

---

lib/bundler/dsl.rb
lib/bundler/env.rb
lib/bundler/friendly_errors.rb
spec/bundler/env_spec.rb

This change has the nice side-effect that `bundle env` will throw an error for Gemfiles with invalid DSLs.
Closes https://trello.com/c/QOX9jyYN.

Also print gemspecs in `bundle env`

---

spec/commands/clean_spec.rb

Unfortunately https://github.com/bundler/bundler/pull/4030 was merged before I had a chance to write a test. I confirmed that the test did not pass before my patch.
Any ETA of 1.10.7 which includes #4030? :heart: 
@indirect @segiddins @andremedeiros @skottler

clean: add test for not removing git extensions artifacts

---

lib/bundler/gem_helper.rb

Since across the codebase and documentation shell commands are displayed
wrapped in backticks, the command included in the error output of
Bundler::GemHelper#sh should also be displayed in the same format.

Add missing backtick in Bundler::GemHelper#sh

---

lib/bundler/cli/config.rb

My main goal was to show the structure of the run method:
1. Guard Clauses
2. Message to user
3. Save new settings
and to separate the message texts from the rest of the logic.
So the class and methods are easier to understand read.
While doing that I reduced the complexity of the run method by
extracting methods. This should improve the Code Climate rating of
Bundler::CLI::Config substantially.

Refactoring config.rb

---

lib/bundler.rb

This constant isn't defined anymore

Remove `autoload :Specification`

---

lib/bundler/dsl.rb

Apparently, a period is already added when interpolating those messages,
some lines below.

Remove excessive periods from DSL error messages

---

lib/bundler/definition.rb
lib/bundler/index.rb
lib/bundler/resolver.rb
lib/bundler/source/path.rb
spec/resolver/basic_spec.rb
spec/support/builders.rb
spec/update/path_spec.rb

Take the definition's ruby version into account when resolving, to try and avoid conflicts with incompatible `required_ruby_version`s. This will mostly help once the compact index is in use.

[Resolver] Resolve for a given ruby version

---

lib/bundler/dsl.rb

The deprecation warning tries to access `user_name` which is not yet
assigned and falls back to `method_missing` which raises an error.

Fix bitbucket source deprecation warning

---

UPGRADING.md
lib/bundler/cli.rb
lib/bundler/cli/binstubs.rb
spec/commands/binstubs_spec.rb

bundle install `--binstubs` option is to be removed from Bundler 2.0 and currently 
supports setting the shebang using the `--shebang` option.
See #1467 introducing the `--shebang` option, which with this commit
is ported to the binstubs command.

Add --shebang option to binstubs command

---

lib/bundler/source/git.rb
spec/install/deploy_spec.rb
spec/install/git_spec.rb
spec/update/git_spec.rb

This effectively changes the output of commands that use Source::Git#to_s
(ie. `bundle install`). For example:
Using rack 1.0.0 from git@github.com:rack/rack.git (at master@574b147)
Closes #3433.

Include revision hash in Source::Git#to_s

---

lib/bundler/settings.rb
spec/bundler/settings_spec.rb

Needed to turn off SSL verify mode, most the code seemed to be there but the setting was being cast to a string which caused it to fail. Added it to NUMBER_KEYS and it's ok now

Make SSL Verify Mode a number setting

---

lib/bundler/rubygems_integration.rb
spec/bundler/rubygems_integration_spec.rb

Previously, we would attempt to initialize `Gem::SystemExitException`
without an argument, which would result in an `ArgumentError` since the
argument is required (from Rubygems 1.3 all the way to 2.4).
I don't know how we missed this all this time. Maybe that path is not
even hit anymore.
Anyway, we don't even have to initialize a new exception, just re-raising the
one we've rescued is sufficient.

Fix Gem::SystemExitException initialization

---

lib/bundler/fetcher.rb
lib/bundler/fetcher/base.rb
lib/bundler/fetcher/index.rb
lib/bundler/rubygems_integration.rb
spec/bundler/fetcher/index_spec.rb
spec/bundler/rubygems_integration_spec.rb

This fixes #4090
I did a little refactoring that made sense to me along the way, but if I went too far or might be breaking something I'm not aware of, please let me know.
**Existing issue:** This doesn't fix bundling with full index when using Rubygems < 2.0, as that code path seemed a bit trickier to fix. I added a *TODO* comment at the relevant method. I thought of a couple possibilities:
* Subclass `Gem::SpecFetcher` like `Bundler::GemRemoteFetcher`, it seems like it might be as simple as calling the super constructor and then replace `@fetcher` with a `Bundler::GemRemoteFetcher` with the headers added ahead of time (see https://github.com/rubygems/rubygems/blob/v1.8.30/lib/rubygems/spec_fetcher.rb#L66). This may involve different solutions the further back in Rubygems you go.
* Use …

Send X-Gemfile-Source when bundling with --full-index

---

lib/bundler.rb
lib/bundler/gem_remote_fetcher.rb
lib/bundler/installer.rb
lib/bundler/installer/gem_installer.rb
lib/bundler/installer/parallel_installer.rb
lib/bundler/rubygems_gem_installer.rb
lib/bundler/source/path/installer.rb
lib/bundler/source/rubygems.rb

My goal was to reveal the main part of install_gem_from_spec. From my
perspective the main part is:
1. Install
2. Generate stubs
3. Print message to the user
(4. handle exceptions)
While working on it I found that Bundler::Installer's run method and
instance variables weren't used when installing gems with
install_gem_from_spec. The installer was (and still is) only used to
generate executable stubs.
So I inserted the new GemInstaller in ParallelInstaller; passing the
instantiated Bundler::Installer to the GemInstaller only to generate
the executable stubs.
Based on this I would continue by extracting two BinstubGenerator
classes and removing GemInstaller's dependency on Bundler::Installer,
possibly allowing for a more concise way to generate binstubs in other
parts of bundler.
I was a …

Extracting a new "GemInstaller" from installer.rb

---

lib/bundler/cli/console.rb
spec/commands/console_spec.rb
spec/support/builders.rb

The fallback to IRB for `bundle console` is currently broken, due to a missing `require 'irb'`:
```bash
bundle config console pry
bundle console
Couldn't load console pry
Could not find constant IRB
```
This fixes the fallback and also alters the error message to indicate the fallback to irb.
While investigating the fix I noticed that the `bundle console` specs were broken and only worked because the expected strings were both contained in the error message.
In order to test an alternate console and the fallback behavior, I added a fake pry gem that implements the minimum required api. I also replaced `__callee__` with `__method__` for ruby 1.8.7 compatibility.

Fix bundle console IRB fallback

---

lib/bundler/cli/install.rb
lib/bundler/settings.rb
spec/install/gems/sudo_spec.rb
spec/support/helpers.rb

Adds a new setting `silence_root_warning` (environment variable: `BUNDLE_SILENCE_ROOT_WARNING`) that skips the default warning when `install` is run as root.
The warning is useful but I think it should be able to be disabled if the user knows what he's doing, it's handy when run inside Docker containers (which by default run as root), or other environments where root is used.
Also adds a new `preserve_env` option to `bundle` helper in tests which allows running commands under sudo with the `-E` flag (preserve environment) as opposed to the default env_reset. Without this, the command would be run without our flag which makes it impossible to test. There might be cleaner ways to achieve this, though.

Check silence_root_warning option to skip warning on root install cmds

---

lib/bundler/cli/gem.rb
lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt

The code of conduct template also now inserts email address for contact purposes.

Updates Contributor Covenant to 1.3.0

---

lib/bundler/runtime.rb
spec/commands/exec_spec.rb

Looks like these got moved.
I'm having a hard time getting this to actually fail in the tests. Here's a gist of something that fails:
Gemfile
----------
```ruby
gem 'rake'
```
Rakefile
-----------
```ruby
desc "foo"
task :foo do
sh 'bundle -v'
end
```
> bundle install
> bundle install --deployment
> bundle exec rake foo
```
bundle -v
/Users/jmundrawala/.rbenv/versions/2.1.2/bin/bundle:23:in `load': cannot load such file -- /Users/jmundrawala/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bundler-1.10.6/bin/bundle (LoadError)
from /Users/jmundrawala/.rbenv/versions/2.1.2/bin/bundle:23:in `<main>'
rake aborted!
Command failed with status (1): [bundle -v...]
/Users/jmundrawala/workspace/bundler/foo/Rakefile:4:in `block in <top (required)>'
Tasks: TOP => foo
(See …
```

Use exe instead of bin for BUNDLE_BIN_PATH fallback

---

lib/bundler/fetcher.rb
lib/bundler/source/rubygems.rb

As mentioned in https://github.com/heroku/heroku-buildpack-ruby/pull/435, bundler failed at the step of fetching version metadata:
```
Fetching version metadata from https://rubygems.org/Net::HTTPInternalServerError: <?xml version=\"1.0\" encoding=\"UTF-8\"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error.
Please try
again.</Message><RequestId>E7402EA19C5D6803</RequestId><HostId>hzuvaA1JAZX6ST+OL4ARYeAqZ/tgkM2yOjZgBq6Panu10YzWtfNNozOg8N5qR3gxFE/sUfYGP48=</HostId></Error>
```
It turns out the retry logic doesn’t cover fetching source index, gem metadata, version metadata and dependency metadata. A new method `Fetcher#specs_with_retry` is added to wrap `Fetcher#specs` with `Bundler::Retry` which reties when bundler fails in the mentioned cases.
/cc @schneems

Retry `Fetcher#specs` with `Bundler::Retry`

---

lib/bundler/cli.rb
lib/bundler/cli/lock.rb
spec/commands/lock_spec.rb

This Pull Request adds the ability to specify gems in bundle lock command via command-line option,
so that this is allowed:
```
bundle lock --gems devise
```
or
```
bundle lock --gems devise ominiauth
```
In this way, we can use lock command for specific gems without downloading any gem.
Thanks!

[Lock] Add support for specify gems to `bundle lock` command

---

lib/bundler/dependency.rb
lib/bundler/dsl.rb
spec/bundler/dsl_spec.rb

When referencing a `gemspec` in the `Gemfile`, restrict what platforms to check against to just those defined by the `gemspec` itself.
This fixes #4102

Restrict platforms when using gemspec in DSL

---

lib/bundler/dsl.rb

There are frequent pull requests proposing this change, which has already been merged to 2-0-dev.
Hopefully, this will help avoid so much wasted time.

Explain why we don't use HTTPS for github sources

---

man/bundle-lock.ronn

Follow up of #4105. `UPDATING ALL GEMS` and `UPDATING A LIST OF GEMS` sections are based on [bundle-update manual](https://github.com/bundler/bundler/blob/master/man/bundle-update.ronn).

Documents lock command's `--update` option [ci skip].

---

lib/bundler/templates/newgem/.travis.yml.tt

Jobs running on container-based infrastructure start up faster and permit the
use of caches for public repositories. As a default it makes sense to enable
this setting for generated gems.

Use travis container-based infrastructure

---

lib/bundler/runtime.rb
spec/commands/package_spec.rb

- Only cache gem specs that are not bundler and not the gem specified by
the gemspec in the main directory the command is being executed from

Fix broken `bundle package --all` command and prevent endless recursive copy

---

lib/bundler/lazy_specification.rb

This is a fix for #4147, as well as a change in which Ruby version we use to resolve gems against.

Handle LazySpecifications and Ruby versions

---

lib/bundler/definition.rb
lib/bundler/dependency.rb
lib/bundler/dsl.rb
lib/bundler/gem_helpers.rb
spec/bundler/dsl_spec.rb
spec/commands/check_spec.rb
spec/install/gemfile/gemspec_spec.rb
spec/lock/lockfile_spec.rb
spec/runtime/setup_spec.rb
spec/support/hax.rb
spec/support/helpers.rb
spec/support/platforms.rb
spec/update/git_spec.rb

This keeps the fix for #4102 but also fixes #4150
I added a test which fails if #4102 is broken, but also fails if #4150 is broken.
I have run the specs in the following scenarios:
* With the original Bundler code: the JRuby spec breaks but the Windows one passes
* With my previous fix attempt: the JRuby spec passes but the Windows one breaks
* With this new fix: both pass

Restrict gemspec platforms without breaking windows

---

exe/bundle
lib/bundler/cli.rb
spec/commands/help_spec.rb

In response to: bundler/bundler-features#97

Redirects any usage of --help flag for a command to that command's man page

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

Previously running `bundle gem` with a global config containing
BUNDLE_GEM__TEST: 'minitest'
would incorrectly set the default task in the generated Rakefile to
task :default => :spec
whereas `bundle gem --test=minitest` worked as expected.  This happened because the test task was determined before checking the global config or asking for user input, making the test task and default task inconsistent.
This fix moves the decision to after the test framework has been properly determined.

Ensure `bundle gem` default task matches framework

---

lib/bundler/fetcher/downloader.rb

Addresses #4054. 
- `NoMethodError` for `use_ssl=` in the downloader should now throw a `LoadError` with `cannot load such file -- openssl` as the message which will be caught and logged by the `FriendlyErrors` module as an OpenSSL Ruby error.

Catch NoMethodError for `use_ssl=` and raise appropriate FriendlyErrors warning

---

lib/bundler/errors.rb
spec/runtime/require_spec.rb

Add original error context info to GemRequireError message

---

lib/bundler/errors.rb
lib/bundler/shared_helpers.rb
spec/bundler/definition_spec.rb

Addresses #4183
Creates a `TemporaryResourceError` that is raised when an `Errno::EAGAIN` occurs when trying to perform some file op. `Errno::EAGAIN`s can occur for a variety of scenarios when certain system resources (ex. memory, in which case a fork cannot occur) aren't available at a certain moment, so the error message suggests that the user rerun the operation, which worked in the case of #4183.

Create `TemporaryResourceError` that `SharedHelpers#filesystem_access` raises for `Errno::EAGAIN`

---

lib/bundler/errors.rb

Optional green to green refactor of the error classes. While implementing #4189, I would have found it much easier and logical for the error classes to be arranged by status code rather than whatever order or lack of order it seems to currently employ.

Reorder Bundler error classes by correlated status code

---

spec/cache/git_spec.rb
spec/commands/exec_spec.rb
spec/commands/install_spec.rb
spec/commands/update_spec.rb
spec/install/gemfile/git_spec.rb
spec/other/bundle_ruby_spec.rb
spec/runtime/setup_spec.rb
spec/update/git_spec.rb

These commits remove a series of extraneous warnings and output messages from the test suite.
These include:
```
/path/bundler/tmp/bundled_app/Gemfile:1: warning: already initialized constant RUBY_VERSION
/path/bundler/tmp/bundled_app/Gemfile:2: warning: already initialized constant RUBY_PATCHLEVEL
Warning: bundle_ruby will be deprecated in Bundler 2.0.0.
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub
rack_two` to work around a system/bundle conflict.
-e:4:in `require': cannot load such file -- rack (LoadError)
from -e:4:in `<main>'
fatal: Needed a single revision
Cloning into 'submodule-1.0'...
done.
```
None of these messages indicate a failure in the correlated specs.

Clean up various test suite warnings

---

lib/bundler/env.rb
spec/bundler/env_spec.rb

We don't use ":" anywhere else on `bundle env` output.

Make `bundle env` output consistent

---

lib/bundler/shared_helpers.rb

Update `SharedHelpers#filesystem_access` inline comment documentation with `Errno::EAGAIN` rescuing [ci skip]

---

lib/bundler/fetcher.rb
lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb

Continuation of #4154. Some errors in the ruby `Net` module that we might not want to retry on were added in later Ruby versions of the stdlib. This PR allows us to preserve backwards compatibility while adding new  errors.

Add `Net#HTTP--` errors safely (only if in version of ruby stdlib)

---

lib/bundler/mirror.rb
lib/bundler/settings.rb

I have no idea why this fixes things locally, but it does. ¯\\_(ツ)_/¯

Fix returning case-sensitive mirror URIs in Ruby 2.3

---

spec/bundler/shared_helpers_spec.rb

Backfilling some unit tests for the `Bundler::SharedHelpers` module. This PR doesn't add all the unit tests yet as I'd like some feedback on whether I'm on the right track regarding the level of mocking out and the interaction of some of the testee methods with private methods.
Related to discussion at #4195 regarding unit tests.

Start adding unit tests for SharedHelpers

---

lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb
spec/spec_helper.rb

- Splits the implementation details/sections of `Bundler::SharedHelpers#set_bundle_environment` into three more modular, singularly responsible methods: `set_path`, `set_rubyopt`, `set_rubylib`
- Adds unit tests for `set_bundle_environment` and the new methods

Separate concerns of `Bundler::SharedHelpers#set_bundle_environment`

---

spec/bundler/shared_helpers_spec.rb
spec/spec_helper.rb

If this PR and #4207 are accepted/merged, then the `Bundler::SharedHelpers` module will have all its public methods unit tested. The only thing that's missing coverage in the spec file for `Bundler::SharedHelpers` is `clean_load_path`, which is used in the `Bundler::Runtime` class. This'll be hopefully addressed/covered as I look more into increasing reasonable unit test coverage to near 100%.

Finish adding unit tests for `Bundler::SharedHelpers` module

---

spec/install/gemfile/ruby_spec.rb

See #4147 
this test fails when run against the tag v1.11.0, and passes when run against v1.11.2.

add spec verifying that #4147 is fixed

---

lib/bundler/cli.rb
lib/bundler/cli/gem.rb
man/bundle-gem.ronn
spec/commands/newgem_spec.rb

This furthers the v1.8 transition of conventionally using the `exe/` folder for bins, leaving the `bin/` folder for binstubs, by allowing the flag that auto-generates a starter file in the `exe/` folder to logically be referred to as `--exe`.
This is a follow-up on the discussion at bundler/bundler-features#105.

Use 'bundle gem --exe' as primary option name, in addition to '--bin'.

---

lib/bundler/fetcher/dependency.rb
spec/bundler/fetcher/dependency_spec.rb

- Extract some parts of `#dependency_specs` and `#specs` into more modular sub-methods
This class was considerably more difficult to unit test out than the previous ones I've dealt with so far, even after breaking up some of the more monolithic methods. Bit of a code smell? Although, it does seem that the complexity of this class puts it among the more complex classes (functionality-wise, not necessarily implementation-wise) in the Bundler codebase.

Refactor and add unit test coverage for `Bundler::Fetcher::Dependency`

---

lib/bundler/cli/exec.rb

Closes #4230 by forcing `Kernel.exec` to never use a shell

[Exec] Fix exec-ing with 0 args in a directory with spaces

---

.codeclimate.yml
spec/support/code_climate.rb

This PR configures file exclusions for Code Climate test coverage analysis (which files we don't care about "coverage" on) and code analysis.

Configure Code Climate exclusions

---

lib/bundler/templates/newgem/bin/console.tt

Effortlessly providing completion in the generated `bin/console` seems like a sane default.
Rails has followed this way, at least [since 2009](https://github.com/rails/rails/commit/f0dd77c#diff-cd8bfebc5a193c9a13a282e9be10e180R14) and 'irb/completion' is present in the standard library for all Ruby versions we support.
What do you think?

Require 'irb/completion' in bin/console template

---

lib/bundler/dsl.rb
lib/bundler/source/path.rb
spec/bundler/dsl_spec.rb

This is a continuation of https://github.com/bundler/bundler/pull/3349 Following up per: https://github.com/bundler/bundler/pull/3349#issuecomment-88307579
The issue here is that paths used with `Bundler::Dsl#gemspec` will only work when the Gemfile being evaluated is `Bundler.default_gemfile`. 
Passing a Gemfile other than `Bundler.default_gemfile` to `Bundler::Dsl.evaluate` will break uses of `path:` options in the Gemfile.
These changes update `Bundler::Dsl` to remember the Gemfile passed into `eval_gemfile` and use it to resolve relative paths.

Fix the path to the Gemfile during evaluation. 

---

lib/bundler/cli.rb
lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

This feature adds the ability to specify a outdated command to show only the gems with a major or minor updates.
I was looking for this feature and found the issue https://github.com/bundler/bundler/issues/3805
@indirect, how can I improve this PR?

Bundle outdated with major and minor options

---

lib/bundler.rb
lib/bundler/cli/install.rb
lib/bundler/friendly_errors.rb
spec/bundler/bundler_spec.rb
spec/commands/exec_spec.rb
spec/install/gemfile/path_spec.rb

Now, when a local gem's gemspec contains errors, an error is raised immediately and helpful message is provided. This message instructs the user to fix the gemspec before an attempt is made to fetch the local gem that has an incorrect gemspec.
- Addresses #4248

Change behavior and improve clarity of error messages when local gems have invalid gemspecs

---

lib/bundler/cli.rb
lib/bundler/cli/gem.rb
man/bundle-gem.ronn
spec/commands/newgem_spec.rb

This takes #4225 further to completely deprecate usage of the --bin and -b flags for bundle gem in favor of --exe, which mirrors the new terminology for the files the flag creates.
This is a follow-up on the discussion at bundler/bundler-features#105 and PR #4226, but with those commits applied to the `2-0-dev` branch.

Use 'bundle gem --exe' as primary option name, instead of '--bin'.

---

lib/bundler/inline.rb
spec/runtime/inline_spec.rb

Added an argument to the gemfile method to allow overriding the
UI object.  Useful to override the default output format and
send those log events to a logfile or decorate them (timestamps,
severity, etc) before emitting them.

Allow passing UI object into bundler/inline

---

lib/bundler/installer.rb
spec/install/gems/standalone_spec.rb

Make standalone bin load path relative to Bundler.root rather than CWD.

---

lib/bundler/templates/newgem/newgem.gemspec.tt

The comment feels a bit misleading. It sounds like this allows Rubygems pushes by default which it does not

Clarify comment in `bundle gem` gemspec

---

lib/bundler/installer/standalone.rb
spec/install/gems/standalone_spec.rb

- when a gem/dependency has an invalid gemspec
- addresses #4275
Output whould now be:
```
$ bundle install --standalone
Using mono_logger 1.1.0
Using multi_json 1.11.2
Using rack 1.6.4
Using redis 3.2.2
Using tilt 2.0.2
Using thread_safe 0.3.5
Using bundler 1.12.0.pre
Using rack-protection 1.5.3
Using vegas 0.1.11
Using redis-namespace 1.5.2
Using tzinfo 1.2.2
Using sinatra 1.4.7
Using rufus-scheduler 2.0.24
Using resque 1.24.1
Using resque-scheduler 2.2.0
You have one or more invalid gemspecs that need to be fixed.
resque-scheduler 2.2.0 has an invalid gemspec
```

Add helpful invalid gemspec error message for `bundle install --standalone`

---

lib/bundler/cli.rb
lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

- This flag changes the output of bundle outdated from:
```
* activesupport (newest 3.0, installed 2.3.5, requested = 2.3.5) in groups "development, test"
```
to
```
activesupport (newest 3.0, installed 2.3.5, requested = 2.3.5)"
```
and removes the extraneous output relating to fetching gem metadata,
version metadata, git updates, and resolving dependencies.
- Addresses bundler/bundler-features#85

Add --parseable (with --porcelain alias) to `bundle outdated` for minimal output

---

.travis.yml

That build entry is redundant  -- we test frozen string literals in all of the 2.3.0 builds now.

[Travis] Remove special frozen string literal build

---

lib/bundler/rubygems_integration.rb
lib/bundler/runtime.rb
spec/runtime/setup_spec.rb

Previously, gems were being placed at the front of the LOAD_PATH. This
meant you couldn't override a gem by setting -I or RUBYLIB.
This patch places -I and RUBYLIB in front of loaded gems and matches the
behavior in RubyGems.

Place bundler loaded gems after -I and RUBYLIB

---

lib/bundler/errors.rb
lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb

- Related to #4163, #3932, and #3581
Ideally, a custom error and/or error message would be returned in these cases rather than just error out because of the uncaught `Errno::EPROTO`.
I'd like some feedback on what the appropriate error message should be however. The caveat is that it seems like a wide range of errors (possibly any error?) that occur in the presence of virtualization will raise this `Errno::EPROTO` error.

Raise new `Bundler::VirtualProtocolError` in response to `Errno::EPROTO`

---

lib/bundler/cli/install.rb
spec/install/deploy_spec.rb
spec/install/path_spec.rb

Calling `bundle install --deployment --system` currently results in the following error message:
```
$ bundle install --deployment --system
You have specified both a path to install your gems to,
as well as --system. Please choose.
```
which is a little confusing.
This PR changes the behavior to:
```
$ bundle install --deployment --system
You have specified both --deployment as well as --system. Please choose. #<-- in red
```

Add alternative error message for when `--deployment` and `--system` flags are both used on `bundle install`

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

Adds a helpful error message for when you run `bundle outdated` after having run `bundle install --deployment`.
```
You are trying to check outdated gems in deployment mode. Run `bundle outdated` elsewhere.
If this is a development machine, remove the /path/to/Gemfile freeze
by running `bundle install --no-deployment`.
```
- closes #4287

Add error with message/explanation for `bundle outdated` in a frozen state

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

If a `Gemfile` is as follows: 
```
gem "activesupport", "2.3.5"
```
and the latest version of `activesupport` is `3.3.5`, running `bundle outdated --minor` should not report any potential updates, which it currently does/would. Users would be using the `--minor` flag potentially because they want to see what latest updates to their gems are available that aren't huge, possibly breaking version changes. With this PR, only if the latest version of `activesupport` is something like `2.5.5` would updates be reported for `activesupport` via `bundle outdated --minor`.
- Related to discussion at bundler/bundler-features#85

Fix `bundle outdated --minor` behavior

---

lib/bundler/cli.rb
lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

- `bundle outdated --patch` will only report updates in the patch
version (`v#.#.patch`)
- Related to discussion at bundler/bundler-features#85

Add `--patch` flag for `bundle outdated`

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

Related PR: #4309 
The commit about `bundle outdated` in a frozen context (from PR #4301) is also cherry-picked as the commits regarding `bundle outdated --minor` move around the specs from that frozen-related PR. 
Please let me know if only the `bundle outdated --minor` PR commits should be cherry-picked and the cherry-picked commits should just be edited/fixed before merge.

Cherry-pick behavior fix for `bundle outdated --minor` for `1-12-stable`

---

lib/bundler/cli/exec.rb
spec/commands/exec_spec.rb

Proof-of-concept to avoid `exec` where possible, instead just using `load` when we'd be launching the same interpreter anyways. About a .2 second gain in my limited testing. Over a second gain in jruby in my testing, somehow.
Not near ready for merging, but pretty cool for an hour of hacking.

[Exec] Load instead of exec-ing

---

lib/bundler/ruby_version.rb
spec/bundler/ruby_version_spec.rb

Fixes how the `matches?` method in `Bundler::RubyVersion` handles a `RUBY_PATCHLEVEL` of `-1`, which seems to be the case with ruby-head.
Closes #4317

Allow `Bundler::RubyVersion` to handle -1 for RUBY_PATCHLEVEL

---

lib/bundler/cli/exec.rb
lib/bundler/rubygems_integration.rb
spec/commands/exec_spec.rb

This ought to fix the build!
\c @indirect

[RubygemsIntegration] Add support for new activate_bin_path binstubs

---

lib/bundler/cli.rb
man/bundle-package.ronn

This fixes the doc package --all-platforms mentioning that only the platforms present in the lock files are cached. #4330

Corrected docs for package --all-platforms

---

DEVELOPMENT.md

Without installing graphviz groff-base packages many tests were failing.

instruction to install certain packages for dev setup

---

DEVELOPMENT.md

`however brew install graphviz groff` won't work and I tried `brew install graphviz homebrew/dupes/groff` as homebrew suggested, it worked.

Update documentation for OSX homebrew

---

lib/bundler.rb
lib/bundler/capistrano.rb
lib/bundler/cli.rb
lib/bundler/cli/exec.rb
lib/bundler/cli/install.rb
lib/bundler/cli/update.rb
lib/bundler/definition.rb
lib/bundler/dsl.rb
lib/bundler/fetcher/compact_index.rb
lib/bundler/fetcher/dependency.rb
lib/bundler/friendly_errors.rb
lib/bundler/installer.rb
lib/bundler/installer/gem_installer.rb
lib/bundler/mirror.rb
lib/bundler/psyched_yaml.rb
lib/bundler/source/git.rb
lib/bundler/source/rubygems.rb
lib/bundler/vlad.rb
man/bundle-install.ronn
man/bundle-package.ronn
man/bundle-platform.ronn
man/bundle-update.ronn
man/gemfile.5.ronn
spec/quality_spec.rb

close #4338 
Sample run:
```
1) The library itself maitains language quality of the documentation
Failure/Error: expect(error_messages.compact).to be_well_formed
bundle-install.ronn has 'actually' on line 210. Avoid using such words.
bundle-install.ronn has 'just' on line 269. Avoid using such words.
bundle-package.ronn has 'actually' on line 46. Avoid using such words.
...
```
cc: @RochesterinNYC

Add test for checking quality of documentation

---

spec/bundler/fetcher/downloader_spec.rb

Fixes the following warning in the test suite:
```
Bundler::Fetcher::Downloader
fetch
when the # requests counter is greater than the redirect limit
WARNING: An expectation of `:body` was set on `nil`. To allow
expectations on `nil` and suppress this message, set
`config.allow_expectations_on_nil` to `true`. To disallow
expectations on `nil`, set `config.allow_expectations_on_nil` to
`false`. Called from
/home/travis/build/bundler/bundler/spec/bundler/fetcher/downloader_spec.rb:19:in
`block (3 levels) in <top (required)>'.
```

Fix the `Bundler::Fetcher::Downloader` rspec warning in test suite

---

lib/bundler/fetcher/base.rb
spec/bundler/fetcher/base_spec.rb

@dwradcliffe @indirect by my understanding, this is what we need to do to get the new index behind fastly?

[Fetcher] Switch from bundler.rubygems.org to index.rubygems.org

---

lib/bundler/definition.rb
lib/bundler/installer.rb
spec/install/git_spec.rb

Fixes #3981.
As far as I investigated the problem is, being in `without` group, it is not marked in missing_spec and so it is not resolved while resolving specs at https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L183
and https://github.com/bundler/bundler/blob/master/lib/bundler/installer.rb#L195
but it is in the definition's index at
https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L209
leading to 
https://github.com/bundler/bundler/blob/master/lib/bundler/source/git.rb#L150
where it checks for the presence of the folder at 
https://github.com/bundler/bundler/blob/master/lib/bundler/source/path.rb#L135
Possible solutions are :
- add it to the list of missing_specs
- check while building the index in Definition class and don't add it.

Checking out missing git repos (but not being installed) - Fixing #3981

---

lib/bundler/source/git.rb
lib/bundler/source/git/git_proxy.rb
spec/install/gemfile/git_spec.rb

* Running `bundle install --local` without having the gems locally fails, because it can not checkout the git repo
* After running `bundle install` at least once
* following runs of `bundle install` complete successfully and do not checkout the git repositories
* following runs of `bundle install --local` complete successfully and do not checkout the git repositories

Git repos should not be updated when --local is passed

---

spec/install/gems/standalone_spec.rb
spec/realworld/edgecases_spec.rb

- Move invalid gemspec spec involving `resque-scheduler 2.2.0` created in
#4283 to realworld specs
- Related to [comments here](https://github.com/bundler/bundler/commit/a753d0182e6d4d91d7e401e40482c6cec5baadae#commitcomment-16716088)

Create invalid gemspec error message spec that runs locally

---

lib/bundler/installer/standalone.rb
spec/install/gems/standalone_spec.rb

While chasing a threading / chdir bug in #4264, I discovered `bundler/setup.rb` isn't written to a proper directory when run in a subdirectory and binstubs don't work (https://github.com/bundler/bundler/pull/4264#issuecomment-179506385).
This changes that so `bundler/setup.rb` is written relative to `Bundler.root` instead of `cwd` and expands test coverage a bit.

Create standalone bundler/setup.rb at a consistent path.

---

lib/bundler/cli/open.rb
spec/commands/open_spec.rb

Editors which have ruby embedded may be confused by bundler's environment, so strip it before launching the editor process.
Here's what happens when I try to `bundle open activesupport` within a rails app using homebrew-installed vim (which embeds ruby by default) but using a different version of ruby in my app:
```
$ bundle open activesupport
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
Referenced from: /usr/local/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/ext/parser.bundle
Expected in: flat namespace
dyld: Symbol not found: _rb_str_new_static
Referenced from: /usr/local/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib/json/ext/parser.bundle
Expected in: flat namespace
Vim: Caught deadly signal TRAP
Vim: Finished.
Could not run …
```

Open editor with clean env

---

lib/bundler/runtime.rb
spec/commands/package_spec.rb

- prevents endless recursive copy regardless of gemspec file name (and whether it matches the name of the gem)
- Fixes #4392

Prevent endless recursive copy for `bundle package --all`

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

- Allow `bundle outdated` to handle all combinations of `--major`, `--minor`, and `--patch` flags
- Related to discussion at #4249

Fix `bundle outdated` behavior with combinations of `--major`, `--minor`, and `--patch` flags

---

lib/bundler/runtime.rb
spec/commands/package_spec.rb

`root_gem_names` should contain the names of the gems that the gemspecs in the directory are correlated with. Gems are packaged unless they're called `bundler` or their names match with the gems specified in the gemspecs.
- Handles multiple gemspecs in directory
- Handles case where gemspec file name does not match with the gem name specified in the gemspec
- Fixes #4430

Handle recursive bundle package loop when multiple gemspecs present

---

lib/bundler/environment_preserver.rb
spec/bundler/environment_preserver_spec.rb
spec/runtime/with_clean_env_spec.rb

This allows a bundle exec after the path has been changed inside
a bundle exec'd program to access the changes
Fixes a regression in 1.12
\c @indirect @RochesterinNYC

[EnvironmentPreserver] Fix restoring environment

---

lib/bundler/fetcher/dependency.rb
spec/bundler/fetcher/dependency_spec.rb

- Closes #4384
\cc @indirect Could use some review on this as to if the appropriate error message has been changed.

Suggest usage of `--full-index` flag in case of Dependency API failure

---

lib/bundler.rb
lib/bundler/source/git/git_proxy.rb
lib/bundler/uri_credentials_filter.rb
spec/bundler/uri_credentials_filter_spec.rb
spec/install/gemfile/git_spec.rb

If your environment includes `user1:password1` for your `GITHUB_CREDENTIALS` and you have something like the following in your `Gemfile`:
```
git "https://#{ENV['GITHUB_CREDENTIALS']}:x-oauth-basic@github.com/company/private-repo" do
gem 'be_excellent', ref: '83623'
end
```
the output for `bundle install` is:
```
bundle
Using be_excellent 0.0.1 from https://user1:password1@github.com/company/private-repo (at master@53534b2)
```
This PR sanitizes this output and removes the credentials so the output would be:
```
bundle
Using be_excellent 0.0.1 from https://github.com/company/private-repo (at master@53534b2)
```
- Also handles oauth tokens (ex. `https://oauth_token:x-oauth-basic@github.com/company/private-repo`)
Related to: bundler/bundler-features#111

Print sanitized urls with removed credentials for git sources on `bundle install`

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb
spec/support/builders.rb

- Examples of non-semantic versions: "7.0", "8", [`gitlab_meta` versioning](https://rubygems.org/gems/gitlab_meta/versions/7.0)
- Closes #4438

Fix `bundle outdated` with `--patch` and/or `--minor` for non-semantically versioned gems

---

lib/bundler/templates/newgem/spec/newgem_spec.rb.tt
lib/bundler/templates/newgem/spec/spec_helper.rb.tt
spec/commands/newgem_spec.rb

I just noticed this when generating a new gem, and I thought it would nice to be consistent across the templates.

use double quotes in the newgem spec templates

---

lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb

`Digest::MD5.file(path)` uses `File.open(path) { |f| f.read }` which will inject `\r\n` style newlines on windows. Using `IO.read(path)` avoids the carriage returns and produces matching checksums on windows.
Closes #4472.

fixes checksums of rubygems index on windows

---

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb
lib/bundler/vendor/molinillo/lib/molinillo/errors.rb
lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb

Closes https://github.com/bundler/bundler/issues/4484.
See https://github.com/CocoaPods/Molinillo/releases/0.4.5.

Update vendored Molinillo to 0.4.5

---

lib/bundler/runtime.rb
spec/runtime/setup_spec.rb

It was previously getting reversed
closes #4482

[Runtime] Fix the ordering of the load path when there are dependencies

---

lib/bundler/cli.rb
spec/commands/exec_spec.rb

Fixes #4480, where `bundle exec foo --help` shows `bundle exec`'s man instead of `foo`'s man.
@RochesterinNYC

Show executable's man page when --help or -h is present

---

lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb
spec/support/builders.rb

This fixes the following behavior:
Say you're using a gem `laduradura` on platform `java` with version `v1.0.1`. The latest `java` platform version of this gem is `v1.0.1` but the latest `ruby` platform version of this gem is `v1.0.2`. Running `bundle outdated` will currently tell you that you can update `laduradura` to `v1.0.2`.
This is a bad user experience as the user is given the suggestion to update `laduradura` to `v1.0.2`, despite this version being on a completely different platform than the one that the user is currently using `laduradura` on.
With this PR, `bundle outdated` will only report potential version updates to gems for the same platforms those gems are being used on.
- Fixes #4450

Only show potential updates on same platform for `bundle outdated`

---

spec/quality_spec.rb

Example mechanisms that are screened for:
- `sleep`
- `binding.pry`
- `debugger`
- focused `rspec` tests via `fit`
- Related to discussion at https://github.com/bundler/bundler/pull/4439#issuecomment-210091297

Create quality check spec for leftover debugging/development mechanisms

---

.travis.yml
Rakefile

- Side note: this feels like something we might be able to automate if we had a CI pipeline that could do periodic resource checks (i.e. watch for new version of Rubygems or Ruby).

[Travis] Test against Rubygems `2.6.4` and Ruby `2.3.1`

---

lib/bundler/gem_helper.rb

only raise error asking user to set rubygem credentials during gem push
if `allowed_push_host` is not set.
Fixes https://github.com/bundler/bundler/issues/4437
Apologies if this is a half baked PR.
- I looked around to add tests for this, but there is little test coverage over this area I simply wasn't sure how to add a test around this particular change.
- I also wasn't sure where to put this in the `CHANGELOG` as the latest entry there is already released.

don't error on missing rubygem cred if custom host

---

lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb
spec/install/gems/compact_index_spec.rb
spec/support/artifice/compact_index.rb
spec/support/artifice/compact_index_concurrent_download.rb

When bundler is run concurrently using the same bundle dir in $HOME,
the versions file can be updated from two processes at once. The
download has been changed to a temporary file, which is securely moved
into place over the original.
If retrying the update operation, the original file is no longer
immediately deleted and instead a full download is performed, later
overwriting the original file if successful.
If two processes are updating in parallel, this should ensure the
original file isn't corrupted and that both processes succeed.
- Fixes #4519
---
This would be useful on 1.12.x if possible, since the new caching behaviour with a shared home directory is causing the errors described in #4519.

Safely store concurrent compact index downloads

---

lib/bundler/runtime.rb

Hi!
I was checking out things in the code and couldn't find any existent usage of this method. I might be missing something but opening the PR just in case.
The method seems to be publicly accessible if someone goes `Bundler.load.dependencies_for(...)` e.g., but i am assuming that's not something "officially supported" anyways?

Cleans up unused Runtime#dependencies_for method

---

lib/bundler/runtime.rb
spec/runtime/require_spec.rb

If you guard the installation of a gem with `env` or `install_if`, and that gem declaration has a `:require` option specified, it tried to require the gem even though it hadn't been installed. It looks like a spot was missed when the `env` command was added in the first place.

Fix the combination of gem :require and env or install_if

---

lib/bundler/fetcher/compact_index.rb
spec/bundler/fetcher/compact_index_spec.rb

Right now, the thread pools created by CompactIndex are not cleaned up once they are done. I assume that over time, they would be garbage collected, but in the meantime there could be 200+ threads running. Many shared hosts have fork bomb protection set up which kills Bundler.
This patch will clean up the threads as soon as they are done, keeping the total number of active threads at any one time to a minimum.
Fixes https://github.com/bundler/bundler/issues/4367

Clean up worker threads once done with them

---

lib/bundler/cli.rb
lib/bundler/cli/binstubs.rb
spec/commands/binstubs_spec.rb

Add `--standalone` flag to `binstubs`
Fix #4594 
@RochesterinNYC @segiddins

Add standalone flag to binstubs

---

lib/bundler/definition.rb
spec/install/yanked_spec.rb

Handle yanked gems

---

lib/bundler/inline.rb
lib/bundler/source/rubygems.rb
spec/runtime/inline_spec.rb

The RubyGems change just means setting remote! will always cause specs to be fetched remotely
\c @indirect

[Inline] Install when necessary

---

lib/bundler/resolver.rb
lib/bundler/ruby_version.rb
spec/bundler/ruby_version_spec.rb
spec/install/gemspecs_spec.rb

spec always passes on 2.2.0p0, probably because the patch version is 0

Fixes specifying ruby patch level in gemfile and gemspec

---

lib/bundler/definition.rb
lib/bundler/index.rb
spec/bundler/definition_spec.rb
spec/install/gemfile/path_spec.rb

* Use sets to compare dependencies
* Exclude dev dependencies when comparing indexes for equality
* Create an index from the Gemfile.lock's `@locked_specs` instead of from current gemspecs and use this for comparison to the current gemspecs.
More details...
Fixes an issue where we can mistakenly "think" the path gems have changed,
causing Bundler::Resolver.resolve to run again, merging in the prior lockfile
results.  We think the path gems have changed because the dependencies comparison cared about order using array == array.  We don't care about order so we can use set equality.  Additionally, we weren't properly detecting changes to path gems because we compared the current path gemspecs to themselves instead of the path specs from the lockfile.
**Before (with lockfile)**
time bundle …

[WIP] Properly detect path spec changes to avoid needless re-resolve

---

lib/bundler/errors.rb
lib/bundler/fetcher.rb
lib/bundler/fetcher/downloader.rb
spec/bundler/fetcher/downloader_spec.rb
spec/bundler/fetcher/index_spec.rb

Currently a network error results in the credentials being output in deploy logs, for example.
Not sure if there is a better approach or this needs to be changed in more locations.

do not log the credentials used to contact a gem server

---

lib/bundler.rb
spec/bundler/bundler_spec.rb

This should fix #4592, the tests all pass, but the line of code in
question goes back to 2010, so this sorta seems slightly dangerous, but
it's probable the circumstances of hitting this line in conjunction with
`bundle exec` is a combination that didn't exist prior to 1.12.x.
Issue #4592 has a full diagnosis, but the gist of it is this: if an
empty string is passed as the `GEM_PATH` to the subsequent process
launched by `bundle exec`, then if the `cmd` portion of `bundle exec` is
a ruby shebanged file, then if the current bundle install uses a local
path (`disable_shared_gems` is true) then it won't be able to find the
bundler gem at all because Bundler doesn't install itself into its own
Bundle, it's only installed in the system gems for the Ruby.
`nil` must be passed because the …

Unset GEM_PATH with nil not empty string.

---

exe/bundle_ruby
lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/deprecate.rb
lib/bundler/dsl.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
lib/bundler/ui/shell.rb
lib/bundler/ui/silent.rb
spec/other/bundle_ruby_spec.rb
spec/other/major_deprecation_spec.rb

First step towards handling all of #4695 
\c @RochesterinNYC @indirect

Add machinery for printing major deprecations

---

lib/bundler/cli/install.rb
spec/install/post_bundle_message_spec.rb

Given current working directory `/foo/app`, when you install with
`--path /foo/app_cache`, ensure that the messaging says:
Bundled gems are installed into /foo/app_cache
instead of the incorrect:
Bundled gems are installed into ._cache

Don't incorrectly relativize sibling `--path` with the same prefix

---

lib/bundler/cli/exec.rb
spec/commands/console_spec.rb
spec/commands/exec_spec.rb
spec/commands/newgem_spec.rb
spec/commands/open_spec.rb
spec/other/platform_spec.rb
spec/quality_spec.rb
spec/support/helpers.rb

Fixes INT signal for ruby executables

---

lib/bundler/definition.rb
lib/bundler/dsl.rb
lib/bundler/fetcher/downloader.rb
lib/bundler/index.rb
lib/bundler/lockfile_parser.rb
lib/bundler/resolver.rb
lib/bundler/rubygems_ext.rb
lib/bundler/source.rb
lib/bundler/source/rubygems.rb
lib/bundler/source_list.rb
lib/bundler/stub_specification.rb
spec/bundler/fetcher/downloader_spec.rb
spec/bundler/source_list_spec.rb
spec/cache/gems_spec.rb
spec/commands/exec_spec.rb
spec/commands/lock_spec.rb
spec/install/gemfile/git_spec.rb
spec/install/gemfile/path_spec.rb
spec/install/gemfile/sources_spec.rb
spec/install/gems/compact_index_spec.rb
spec/install/gems/resolving_spec.rb
spec/install/post_bundle_message_spec.rb
spec/lock/lockfile_spec.rb
spec/resolver/basic_spec.rb
spec/runtime/inline_spec.rb
spec/runtime/require_spec.rb
spec/runtime/setup_spec.rb
spec/support/indexes.rb
spec/update/git_spec.rb

Closes https://github.com/bundler/bundler/issues/3671.
Closes https://github.com/bundler/bundler/pull/3696.
Closes #4059.

[2.0] Remove RubyGems Aggregate & support transitive source pinning

---

spec/support/rubygems_ext.rb

- Rack 2.x requires Ruby version >= 2.2.2
- artifice doesn't support rack 2.x now.

Fix test failures due to Rack 2.x

---

spec/support/rubygems_ext.rb

`rake < 2` should be installed before `artifice`.
On `ruby 1.8.7` it fails randomly because of no specific order of hash traversal.
https://travis-ci.org/bundler/bundler/builds/141867428

Installing gems without version after the ones with version for tests

---

lib/bundler/cli/install.rb
lib/bundler/postit_trampoline.rb
spec/commands/install_spec.rb
spec/other/trampoline_spec.rb

@indirect @RochesterinNYC 
I'm a bit stumped.
The original issue on bundler/bundler#4707 mentions that this warning should only be printed once unless the user updates their version of Bundler, and that the warned version should be stored in `Bundler.settings[:warned_version]`.
The issue is that, AFAIK, this file, `postit_trampoline.rb` is the last place where I can access both the `installed_version` (system version) and the `running_version` (project's version) of Bundler before it completely switches over to the `running_version`.
Since `Bundler.settings` still hasn't been initialized at this point, I can't store the `running_version` in `Bundler.settings[:warned_version]`.
Right now, this warning is shown every time a `bundle` command is issued in a project directory where …

Print an outdated warning when a project is locked to an old version of Bundler

---

spec/support/helpers.rb

Fix RubyGems printing packaging messages during the specs

---

lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/cli/update.rb
lib/bundler/definition.rb
lib/bundler/gem_version_promoter.rb
lib/bundler/resolver.rb
lib/bundler/spec_set.rb
spec/bundler/definition_spec.rb
spec/bundler/gem_version_promoter_spec.rb
spec/commands/update_spec.rb
spec/plugins/install_spec.rb
spec/resolver/basic_spec.rb
spec/support/indexes.rb

A port of bundler-patch to bundler proper.
Core team questions:
---
Notes for issues to create that could be handled separately after this PR, esp. if we release undocumented/unsupported to begin with.
- Updating `outdated` to use the new flags and resolution
- adding some warnings when dependent updates go past --patch or --minor level (with an instruction to use --strict if they don’t want that)
- adding a warning when an unlocked gem doesn't move (possibly w/ a reason why?). the lack of feedback otherwise can be disconcerting, like "did I not do it right?"
- possibly adding a dry-run flag - though after looking at that today, that would make the most sense inside Installer, and make that flag an option for both install and update (drilling through all of the calls to push that option …

Conservative updates

---

Rakefile
lib/bundler/fetcher.rb
lib/bundler/resolver.rb
spec/commands/viz_spec.rb
spec/install/binstubs_spec.rb
spec/install/gems/resolving_spec.rb
spec/support/artifice/compact_index.rb
spec/support/artifice/endpoint.rb
spec/support/builders.rb

This is an extension of #4645, fixing the version check to actually work, testing that the correct versions get installed as a result, and showing the kind of error message that would actually be useful (as opposed to "couldn't find that gem").

Respect required ruby versions

---

lib/bundler.rb
lib/bundler/definition.rb
lib/bundler/dsl.rb
lib/bundler/environment.rb
lib/bundler/rubygems_ext.rb
lib/bundler/rubygems_integration.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
spec/bundler/dsl_spec.rb
spec/bundler/shared_helpers_spec.rb
spec/support/helpers.rb

This is a pre-req for being able to use bundler as the backend for RubyGems' Gemfile support, as RubyGems tests run in a single process and the hooks installed (particularly by `replace_entrypoints`) are rather destructive to those tests. More changes to come to get `Gem.use_gemdeps` using bundler (i.e. to get the RG suite green), but this is likely to be the grossest of them.

[RubygemsIntegration] Add support for reversing hooks

---

lib/bundler.rb
lib/bundler/definition.rb
lib/bundler/dsl.rb
lib/bundler/index.rb
lib/bundler/lazy_specification.rb
lib/bundler/lockfile_parser.rb
lib/bundler/source/gemspec.rb
lib/bundler/source/path.rb
spec/commands/package_spec.rb
spec/install/gemfile/gemspec_spec.rb
spec/install/gemfile/path_spec.rb
spec/support/builders.rb
spec/support/helpers.rb

Closes #4798 
This is necessary since `gemspec`  declares platforms for the dependency as the reverse platform map of the generic local platform, thus missing out on all those platforms that aren't currently being resolved for

[Definition] Ensure gemspec dependencies include all lockfile platforms

---

lib/bundler/fetcher/downloader.rb
spec/bundler/fetcher/downloader_spec.rb

Map request response to original URI when printing debug output for http responses for `bundler/fetcher/downloader`.
Overview
--------
I have recently been debugging some bundler stalling issues and found this addition to the debug output helpful when ruling out if a particular URL was timing out with the `CompactIndex` fetcher as it does it's requests over 25 threads and returns them asynchronously.  Getting a bunch of `HTTP 304 Not Modified` isn't as helpful if you are trying to determine how a thread is locking up.
Incidentally, this didn't end up helping solving some issues (further PRs will address this), but it seems like a simple debugging addition that could help rule out specific endpoint issues without requiring more [advanced debugging …

Add URI to http response output in debug mode

---

lib/bundler/env.rb
lib/bundler/source/git/git_proxy.rb
spec/bundler/env_spec.rb
spec/bundler/source/git/git_proxy_spec.rb
spec/spec_helper.rb

Overview
--------
When running the previous version of `Bundler::Source::Git::GitProxy#version` output through `Gem::Version.create` when the git version is something like
$ git --version
git version 1.2.3 (Apple Git-22)
Ruby blows up with the error:
ArgumentError:  Malformed version number string 1.2.3 (Apple Git-22)
The '(Apple Git-22)' and any additions that are added by `msysgit` (ex: `1.8.3.msysgit.0`) can be safely ignored as they are additions to the git version string for those specific versions, but should still line up with the core git version.
This regression was added in https://github.com/bundler/bundler/pull/4717, so this is not in a release of the gem yet, only in `1.13.0.rc1` installation.  This prevented:
* running tests on OSX or on any OS with a non-core git …

Removes OSX/msysgit strings from Bundler::Source::Git::GitProxy#version

---

lib/bundler/fetcher/base.rb
lib/bundler/fetcher/compact_index.rb
lib/bundler/fetcher/dependency.rb
lib/bundler/retry.rb
spec/bundler/fetcher/compact_index_spec.rb
spec/bundler/retry_spec.rb

Add dot output for CompactIndex fetcher
---------------------------------------
The `Bundler::Fetcher::CompactIndex`'s logging was missing the "dot logging" when not in debug mode, which is an assumed behavior based on the code in `lib/bundler/source/rubygems.rb`:
```ruby
api_fetchers.each do |f|
Bundler.ui.info "Fetching gem metadata from #{f.uri}", Bundler.ui.debug?
idx.use f.specs_with_retry(dependency_names, self)
Bundler.ui.info "" unless Bundler.ui.debug? # new line now that the dots are over
end
```
While this isn't critical for `bundler` function properly by any stretch of the imagination, it provides a small bit of user feedback that requests are still continuing to be processed and `bundler` hasn't stalled.  It also maintains logging consistency between the different fetcher …

Fix random string printing inconsistencies and formatting

---

lib/bundler/postit_trampoline.rb
spec/other/trampoline_spec.rb

Set ENV["BUNDLE_ENABLE_TRAMPOLINE"] to enable it
Closes #4821

Feature-flag the postit trampoline, disabled by default

---

lib/bundler/fetcher.rb

Overview
--------
When ruby makes an HTTP connection with the `Net::HTTP` library, by default, it has no timeout to setup that connection.
```ruby
def initialize(address, port = nil)
@address = address
@port    = (port || HTTP.default_port)
@local_host = nil
@local_port = nil
@curr_http_version = HTTPVersion
@keep_alive_timeout = 2
@last_communicated = nil
@close_on_empty_response = false
@socket  = nil
@started = false
@open_timeout = nil
@read_timeout = 60
end
def connect
if proxy? then
conn_address = proxy_address
conn_port    = proxy_port
else
conn_address = address
conn_port    = port
end
D "opening connection to #{conn_address}:#{conn_port}..."
s = Timeout.timeout(@open_timeout, Net::OpenTimeout) {
TCPSocket.open(conn_address, conn_port, @local_host, @local_port)
}
if use_ssl? …
```

Add an open_timeout to the fetcher connection

---

lib/bundler/cli/install.rb
spec/commands/install_spec.rb

Closes #4752 
@RochesterinNYC @indirect

Bundler version warning should not print when versions match

---

lib/bundler/postit_trampoline.rb
lib/bundler/vendor/postit/lib/postit/installer.rb
spec/other/trampoline_spec.rb

This is for #4753.
[This](https://github.com/bundler/bundler/issues/4753#issuecomment-233786976) always showed the installing message whether the locked Bundler version was installed or not, so I moved the line into `lib/bundler/vendor/postit/lib/postit/installer.rb`.
I've also added the appropriate specs for this.
@RochesterinNYC @segiddins @indirect

Display message showing locked Bundler version is being installed

---

spec/bundler/friendly_errors_spec.rb
spec/bundler/gem_helper_spec.rb
spec/cache/git_spec.rb
spec/commands/exec_spec.rb
spec/commands/help_spec.rb
spec/commands/install_spec.rb
spec/commands/package_spec.rb
spec/commands/update_spec.rb
spec/install/gemfile/gemspec_spec.rb
spec/install/gemfile/git_spec.rb
spec/install/gemfile/path_spec.rb
spec/install/gems/flex_spec.rb
spec/install/gems/resolving_spec.rb
spec/install/gems/standalone_spec.rb
spec/lock/lockfile_spec.rb
spec/other/bundle_ruby_spec.rb
spec/other/ext_spec.rb
spec/other/major_deprecation_spec.rb
spec/other/trampoline_spec.rb
spec/quality_spec.rb
spec/realworld/edgecases_spec.rb
spec/runtime/inline_spec.rb
spec/runtime/require_spec.rb
spec/runtime/setup_spec.rb
spec/runtime/with_clean_env_spec.rb
spec/spec_helper.rb
spec/support/helpers.rb
spec/update/git_spec.rb

This now also appends all executed commands to failed examples, meaning we don't have to scroll up to see the output from a failing test:
```
Failures:
1) The library itself does not contain any warnings
Failure/Error:
sys_exec!("ruby -w -I.") do |input, _, _|
lib_files.each do |f|
input.puts "require '#{f}'"
end
input.puts "abort 'fdsfds'"
end
RuntimeError:
Invoking sys_exec!("ruby -w -I.") failed:
fdsfds
Commands:
$ ruby -w -I.
fdsfds
```

Remove expect_err from the specs & print all output on a spec failure

---

lib/bundler/cli.rb
lib/bundler/cli/doctor.rb
man/bundle.ronn
spec/commands/doctor_spec.rb

This new command, linkage, checks for broken dynamic library links in C extensions.
I'd heard there was some interest in adding this functionality, so I thought I'd submit a preliminary PR for discussion. In my experience, broken dylib linkage is a common issue with C extensions, so I think having a good way to diagnose it would be valuable.
This command scans all of the specifications in the bundle for .bundle files in C extensions. If any of the dynamic libraries linked against no longer exist, bundler will report a message to the console and exit non-0.
TODOs:
* Add support for non-Darwin OSs
* Improve tests
A few questions:
* Is there a good way to mock functionality in the tests? Doing it in the standard rspec way isn't working since `bundle :command` runs in a subprocess. I'd like …

WIP: add command to check dynamic library linkage

---

lib/bundler/gem_helper.rb

Removing `--annotate` option does not change default behaviour
Since git 2.9.0 its possible to configure signed tag with
`tag.forceSignAnnotated` to true
Cheers

Allow signed tags on rake release

---

lib/bundler/mirror.rb
lib/bundler/settings.rb
spec/bundler/mirror_spec.rb
spec/bundler/settings_spec.rb

Proposed fix for issue #4843.
I would like to be able to do something like `BUNDLE_MIRROR__FOO__RUBYGEMS__ORG` and have it work the same way as `BUNDLE_MIRROR__HTTPS://FOO__RUBYGEMS__ORG/`
There was some discussion about it already [here](https://groups.google.com/forum/#!topic/ruby-bundler/QlhlTuxoDCc).
I'm sure there are currently some issues with my implementation as this was the first time I looked at the bundler code, but would you accept this change once they are resolved?

enables BUNDLE_MIRROR__HOSTNAME environment variables

---

lib/bundler.rb
lib/bundler/environment_preserver.rb
lib/bundler/runtime.rb
spec/bundler/environment_preserver_spec.rb
spec/runtime/with_clean_env_spec.rb
spec/support/helpers.rb

Any enviroment variable that starts with BUNDLE_ will be treated as a
configurationg setting, printed by `bundle config`, and made available
internally via `Bundler.settings`. The ORIG_* environment variables are
actually just internal housekeeping to enable us to provide clean
non-bundled environments, and so they shouldn't show up as settings.
This change to the environment variable names makes sure it is still
clear where they are coming from, but no longer surfaces them via
config/settings.

Rename all BUNDLE_ORIG_* env to BUNDLER_ORIG*

---

lib/bundler/rubygems_integration.rb

Fixes https://github.com/bundler/bundler/issues/4846

Retry gem downloads

---

lib/bundler/templates/Executable.standalone
spec/commands/binstubs_spec.rb
spec/install/gems/standalone_spec.rb

When an executable is the destination of a symlink `__FILE__` contains
the path to the symlink, rather than the actual path of the current
file.
`Pathname#realpath` resolves symlinks to get the actual location on disk.

fix standalone executable when dest of symlink

---

lib/bundler/lockfile_parser.rb
spec/commands/check_spec.rb
spec/lock/lockfile_spec.rb

Can make it easier to understand what's going on.

include version numbers involved with warn_for_outdated_bundler_version

---

lib/bundler/cli/exec.rb
lib/bundler/settings.rb
spec/commands/exec_spec.rb

Add a setting for disable_exec_load

---

.rubocop.yml
lib/bundler/definition.rb
lib/bundler/resolver.rb
lib/bundler/settings.rb
spec/commands/update_spec.rb

This is currently behind the only_update_to_newer_versions setting
Closes https://github.com/bundler/bundler/issues/4511.
See https://github.com/bundler/bundler/issues/4856 and https://github.com/bundler/bundler/issues/4871

Block resolving to older versions during an update

---

lib/bundler/shared_helpers.rb
spec/other/major_deprecation_spec.rb

[SharedHelpers] Always print major deprecations on .99 versions

---

lib/bundler/installer.rb
spec/install/path_spec.rb

If i'm attempting to install my gems into a folder that conflicts with a file that already exists, Bundler will raise the following error: 
```
Could not install to path `vendor` because of an invalid symlink. Remove the symlink so the directory can be created.
```
But this error will be raised even if its just a regular ol file and not a symlink. IMO its a better user experience to drop the symlink mention and ask the user to simply move or rename the file.
Example:
```
Could not install to path `vendor` because a file already exists at that path. Either remove or rename the file so the directory can be created.
```

update path already exists error message to not be specific to symlinks

---

lib/bundler/rubygems_gem_installer.rb
lib/bundler/settings.rb
lib/bundler/source/rubygems.rb
spec/install/gems/compact_index_spec.rb
spec/support/artifice/compact_index.rb
spec/support/artifice/compact_index_wrong_gem_checksum.rb

[RubyGemsGemInstaller] Validate checksums from the compact index

---

lib/bundler/remote_specification.rb
spec/bundler/remote_specification_spec.rb

Because we should overwrite this method when we overwrite
`method_missing`.
See http://ruby-doc.org/core-2.3.1/BasicObject.html#method-i-method_missing

Add missing definition of `respond_to_missing?`

---

lib/bundler/cli.rb

This flag was introduced in #4610, declared with the same code as the flag found in the `install` command.
In the case of the `install` command, it makes sense to be an `Array` option, since
one can specify groups.
This doesn't hold true for the `binstubs` cmd where `--standalone` just stands to signify
whether the generated stubs will require the Bundler runtime or not.
In the current implementation even passing groups with the flag doesn't have any affect.

Change standalone flag of binstubs cmd to boolean

---

lib/bundler/cli/gem.rb
lib/bundler/templates/newgem/README.md.tt
spec/commands/newgem_spec.rb

This Pull Request changes the GitHub URL in the Contributing section of README.md from generated gem (e.g. `bundle gem foo`).
Why:
I found myself change `[USERNAME]` to my git username so many times and I also help [some](https://github.com/suzuki86/rhymer/pull/1/files) [people](https://github.com/fastly/blockbuster/pull/12/files) [fix](https://github.com/abookyun/taiwan_validator/pull/2/files) [this](https://github.com/mkhairi/materialize-sass/pull/62/files).
So I think this should be filled when new gem is generated. When git username not set, falls back to `[USERNAME]`.
I don't really know how to make tests DRY, please advise, thank you.

Fill in git username to the generated gem's contributing section of README.md

---

lib/bundler/definition.rb
lib/bundler/resolver.rb
lib/bundler/ruby_version.rb
lib/bundler/rubygems_ext.rb
spec/install/gems/resolving_spec.rb
spec/install/gemspecs_spec.rb
spec/resolver/basic_spec.rb
spec/support/indexes.rb

*Proposal:* When a gem in the Gemfile requires a Ruby version different than the Gemfile's `ruby`, print a conflict error message that looks more or less exactly like any other resolution conflict error.
*Current behavior:* On `master` today, Bundler will ignore the gem's required_ruby_version until install-time, and raise an exception like "require_ruby-1.0 requires ruby version > 9000, which is incompatible with the current version`.
After #4650 has been merged, Bundler will correctly reject gems that require a different version of Ruby, and instead print the error "Could not find `required_ruby` in any of the sources in your Gemfile".
*Rationale for change:* I believe that error message is surprising and misleading. The source _does_ contain `required ruby`, and I think we'll get bug …

Add resolver-style error messages for required Ruby conflicts

---

lib/bundler.rb
lib/bundler/cli/binstubs.rb
lib/bundler/cli/cache.rb
lib/bundler/cli/check.rb
lib/bundler/cli/install.rb
lib/bundler/cli/outdated.rb
lib/bundler/cli/platform.rb
lib/bundler/cli/show.rb
lib/bundler/cli/update.rb
lib/bundler/definition.rb
lib/bundler/dependency.rb
lib/bundler/gem_helpers.rb
lib/bundler/inline.rb
lib/bundler/lazy_specification.rb
lib/bundler/lockfile_parser.rb
lib/bundler/match_platform.rb
lib/bundler/plugin.rb
lib/bundler/resolver.rb
lib/bundler/runtime.rb
lib/bundler/source.rb
lib/bundler/spec_set.rb
spec/bundler/source_spec.rb
spec/install/gemfile/specific_platform_spec.rb
spec/resolver/platform_spec.rb
spec/support/builders.rb
spec/support/platforms.rb
spec/support/the_bundle.rb

Closes #4295.
This will require adding a bunch of tests, as well as figuring out how to put this new behavior behind a feature flag (thus fixing all of the existing tests).

Resolve for specific platforms

---

spec/support/artifice/compact_index.rb
spec/support/artifice/compact_index_concurrent_download.rb
spec/support/artifice/compact_index_extra_api.rb
spec/support/rubygems_ext.rb

Also removed the penalty for adding requirements to dependencies!
\c @indirect

Update specs to use compact_index 0.11

---

spec/bundler/mirror_spec.rb

This PR adds a spec for `Mirror#==` method.

Add a spec for Bundler::Settings::Mirror#==

---

lib/bundler/definition.rb
lib/bundler/fetcher.rb
lib/bundler/index.rb
lib/bundler/source/rubygems.rb
spec/install/gems/compact_index_spec.rb
spec/support/artifice/compact_index.rb
spec/support/artifice/compact_index_extra_api.rb
spec/support/artifice/compact_index_extra_api_missing.rb
spec/support/rubygems_ext.rb

[RubyGems] Stop fetching all specs 😁

---

lib/bundler/definition.rb
lib/bundler/installer.rb
lib/bundler/source/path.rb
lib/bundler/source/rubygems.rb
lib/bundler/source_list.rb
lib/bundler/spec_set.rb
spec/install/gemfile/lockfile_spec.rb

Closes #3096. Closes #4417.
\c @indirect

[Installer] Skip eval’ing a Gemfile twice when there’s a lockfile

---

lib/bundler/rubygems_ext.rb

The change referenced below as released in 1.13.0.rc.2, may attempt to reference Gem::Source without it being loaded, resulting in:
~~~
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `elided.gemspec`: uninitialized constant Gem::Source. Bundler cannot continue.
~~~
Observed this on ruby 2.2.5 with stock rubygems 2.4.5 as well as upgraded rubygems 2.6.6. Add this require.
f9de70ee931ca4a8500916fa9480f6df6c062626  by @segiddins:
> [RubygemsExt] return Source::Installed from #source when appropriate

[RubygemsExt] Add missing require rubygems/source

---

lib/bundler/definition.rb
spec/bundler/definition_spec.rb

When Definition creates the GemVersionPromoter, it needs to do so
_after_ it's performed the eager_unlock so the GVP gets the correct list
of unlocked gems.
Prior to this fix, it had a stricter list of gems being updated with the
new `--patch` or `--minor` options used with `bundle update` and in some
cases would have inconsistent results when used without a conservative
switch or the `--major` option. See #4934 for details.

Fix #4934. Make GVP _after_ eager unlock.

---

spec/realworld/edgecases_spec.rb

This way, we don't have to update this expectation every time a new rails version comes out

Dynamically fetch expected rails version

---

lib/bundler/ruby_version.rb
spec/bundler/ruby_version_spec.rb
spec/install/gemfile_spec.rb

This fixes #4914.
Our test suite did not run with jruby but I have manually verified this patch works. Details can be seen below.
<details>
<summary>View manual verification details</summary>
The spec I added in this PR works with jruby:
```
$ chruby jruby-9.1.2.0
$ ruby -v
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.25-b02 on 1.8.0_25-b17 +jit [darwin-x86_64]
$ rspec spec/install/gemfile_spec.rb
Run options: exclude {:rubygems_master=>true, :git=>"=< 2.8.1", :rubygems=>"=< 2.6.4", :ruby=>"=< 2.3.0", :realworld=>true, :sudo=>true}
bundle install
with duplicated gems
will display a warning
with --gemfile
finds the gemfile
with gemfile set via config
uses the gemfile to install
uses the gemfile while in a subdirectory
with deprecated features
reports that …
```

Support specify engine by symbol in Gemfile

---

lib/bundler/endpoint_specification.rb
spec/bundler/endpoint_specification_spec.rb

Would make diagnosing a recent issue around this easier
\c @indirect  would love to get this into 1.13.1

[EndpointSpecification] Raise a helpful error when parsing metadata fails

---

lib/bundler/source.rb
spec/bundler/source_spec.rb

Hello!
Using Bundler version 1.13.1 i noticed a small graphic inconsistency on parentheses color:
This commit resets the opening parenthesis color:
Is this the expected behaviour? The spec was only checking the closing parenthesis color.
p.s:
Imho green parentheses look better here.

fix message parenthesis color

---

lib/bundler/settings.rb
spec/bundler/settings_spec.rb

When the Settings object is initialized with no root directory it cannot read the local_config. This used to not be a problem due to the fact that the `#load_config` method did not try to exit early. Since now it does it returns nil when the config is not present setting the @local_config instance variable to nil. The fix is to return an empty hash the same way the `#load_config` method would return if it encountered a problem later on.
The attached test proves that there is a problem and the fix makes the problem go away.

fixing NoMethodError on settings

---

DEVELOPMENT.md

When I wanted to contribute something, the link to the "small issues" was broken. So why not contribute by fixing this?

Fix broken link in DEVELOPMENT.md to "small" issues

---

lib/bundler.rb
lib/bundler/rubygems_integration.rb
spec/bundler/bundler_spec.rb
spec/commands/exec_spec.rb
spec/support/helpers.rb

_nth time is a charm ... here's the latest latest latest commit message_:
Fix disable_shared_gems bug & keep nested exec
tl;dr `--deployment` will copy _all_ gems to the `--path` now and a
proper fix is in place for nested bundle execs when `--path` is set and
RubyGems >=2.6.2 is being used.
Fixes #4974.
There's two problems blended in here. Let's trace the events here from
the beginning, shall we?
First off, from probably the first versions of Bundler, when
`disable_shared_gems` is true, the `GEM_PATH` gets internally overridden
and initialized to an empty string. This is done to make sure that later
in the `Bundler.setup` process it's expanded to ONLY the Bundler `--path`
setting, otherwise it expands to include the system path.
In 1.12, `bundle exec` was changed to use `Kernel.load` in …

Fix GEM_PATH regression in 1.13.

---

lib/bundler/lazy_specification.rb
spec/install/gemfile/gemspec_spec.rb

Closes #5006 
This was not fun to track down >.<

[LazySpecification] Select the best platform match when materializing

---

ISSUES.md
README.md

This PR is for #4986. It adds documentation into ISSUES for when the user gets permission denied when installing bundler and a typical solution.
This will benefit users who are unfamiliar with unix and how to handle installing a system gem with elevated privileges.

added documentation for gem install bundler permission denied

---

lib/bundler/templates/newgem/bin/console.tt

`IRB.start` expects an argument with the name of the script being executed. When this argument is omitted, IRB does not search the filesystem for `.irbrc` files. That means that developers who have customized their IRB settings with an `~/.irbrc` will not benefit from those customizations when using Bundler's default `bin/console` script.
Fix this by editing the `bin/console` template to pass `__FILE__` to `IRB.start`.
This makes `bin/console` consistent with Ruby's builtin `bin/irb` command.
https://github.com/ruby/ruby/blob/9f9add3eb5006473dfabac3e994e904b5c1979fe/bin/irb#L11

Improve IRB behavior in generated bin/console

---

lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/fetcher/compact_index.rb
lib/bundler/gem_helper.rb
lib/bundler/shared_helpers.rb
lib/bundler/ui/shell.rb
lib/bundler/ui/silent.rb
spec/bundler/shared_helpers_spec.rb
spec/runtime/inline_spec.rb

Closes https://github.com/bundler/bundler/issues/4778
This is an alternative to https://github.com/bundler/bundler/pull/4886
\c @allenzhao @indirect

Fallback to a temp dir when the home directory is not usable

---

spec/spec_helper.rb

Fail fast in the specs when running from a path with special characters

---

lib/bundler/cli/install.rb
lib/bundler/cli/update.rb
lib/bundler/installer.rb
lib/bundler/rubygems_integration.rb

[Installer] Load gem plugins when installing

---

lib/bundler/plugin.rb
lib/bundler/plugin/api.rb

Please read https://github.com/bundler/bundler/pull/4981#issuecomment-248674155.
> But it's elusive reproduction (and lack of test case) makes me think that the problem is a bit deeper and may recur.
I think so. This Pull Request is just *workaround*.

[workaround] Use `require` instead of `autoload` for bundler/plugin/api

---

.travis.yml

In retrospect, once this build started always failing, we should have just removed it rather than moved it to allowed failures. I guess I was hoping it would get better. :/

Remove build that always fails

---

lib/bundler/cli.rb
lib/bundler/cli/common.rb
lib/bundler/cli/lock.rb
lib/bundler/cli/update.rb
spec/commands/lock_spec.rb

Fix #4912.
The bundle lock command produces a lockfile same as bundle update but
won't install all the gems. If the `--update` option is fed to `bundle
lock` you can also specify the `--patch`, `--minor`, `--major` and
`--strict` options added to `bundle update` in 1.13.

Add conservative update options to bundle lock

---

lib/bundler/compact_index_client/updater.rb
spec/install/gems/compact_index_spec.rb

As we noticed in #4519, we need to use a temporary directory to hold
compact index downloads so that multiple processes don't write to the
same files at the same time and break everything.
The fix for that was #4561, which added temporary directories to hold
all files as they download, and then uses the (atomic) `FileUtils.cp` to
move the completed downloads into place, so there is never a point where
multiple processes are trying to write into the file at once.
Unfortunately, using `Dir.mktmpdir` requires that the parent directory
be _either_ world writable or sticky, but not both. Based on #4599, it
looks like it's common for home directories to be both world writable
and sticky. While that's a security problem by itself, it's not a big
concern for Bundler and the compact index. So we …

use /tmp for mktmpdir

---

lib/bundler/cli.rb
lib/bundler/cli/outdated.rb
spec/commands/outdated_spec.rb

Hi,
the current version of bundler is listing all gems with the group, I improve these list grouping the gems by group and not repeat the group every line.
Current:
```
Outdated gems included in the bundle:
* aasm (newest 4.11.0, installed 3.4.0, requested = 3.4.0) in group "default"
* activerecord-import (newest 0.15.0, installed 0.13.0) in group "default"
* annotate (newest 2.7.1, installed 2.7.0) in group "development"
* authority (newest 3.2.0, installed 3.0.0, requested ~> 3.0.0) in group "default"
* awesome_print (newest 1.7.0, installed 1.2.0, requested ~> 1.2.0) in groups "development, test"
* aws-sdk (newest 2.5.1, installed 1.60.2, requested ~> 1.60.2) in group "default"
* bootstrap-sass (newest 3.3.7, installed 3.3.5.1, requested ~> 3.3.5.1) in group "default"
* capybara …
```

Better gem outdated list

---

lib/bundler/compact_index_client/updater.rb
lib/bundler/fetcher/compact_index.rb

This was super helpful when the server was continuously returning bad
checksums, but it’s a scary warning to see anytime we update the 
versions file. And we’re going to need to update the versions file at
least twice a year, so it seems like a good idea to head off users
worrying about a message that is actually things working as intended.

change checksum warning to debug print

---

lib/bundler/cli/clean.rb
spec/commands/clean_spec.rb

Changed the behavior of 'bundle clean --dry-run' to output the list of gems bundle without having the local path set or providing the '--force' option. This change does not affect the actual behavior of 'bundle clean' which requires either the path being set or use of '--force'.
Closes #5027.

Changed the behavior of 'bundle clean --dry-run' to output the list regardless of path set or force option

---

lib/bundler/cli.rb
lib/bundler/cli/lock.rb
lib/bundler/cli/update.rb
lib/bundler/definition.rb
spec/bundler/definition_spec.rb
spec/commands/update_spec.rb

In the discussion on new 1.13 [Conservative Bundle
Updates](https://github.com/bundler/bundler-features/issues/122), some
users would like to have the same [Conservative
Updating](http://bundler.io/v1.12/man/bundle-install.1.html#CONSERVATIVE-UPDATING)
behavior available in `bundle install` when a declared dependency is
altered in the Gemfile, also available in the `bundle update` command.

replicate cons. bundle install in update cmd

---

lib/bundler/cli.rb
lib/bundler/cli/common.rb
lib/bundler/cli/lock.rb
lib/bundler/cli/outdated.rb
lib/bundler/cli/update.rb
spec/commands/outdated_spec.rb

Add conservative resolving behavior to outdated command.
The flags as passed to the GemVersionPromoter _change_ resolution. <=1.13.2 of bundle outdated, those flags merely filter the output, with no influence on resolution.
If the lockfile is set to foo 1.0.0, and all of the following exist: 1.0.1, 1.1.0, 2.0.0, then <=1.13.2 bundle outdated currently will show:
`foo (newest 2.0.0, installed 1.0.0)`
<=1.13.2 `bundle outdated --minor` simply filters away that line and won't show it. 
With these changes, `bundle outdated --minor` would be fed to the GemVersionPromoter and actually only resolve `foo` up to `1.1.0`. 
This gist shows how it currently works, filtering the output: https://gist.github.com/chrismo/0bc6cfa00f539787101a9a2c900616d3
It's unfortunate timing. They were only added in …

Conservative updates on outdated

---

lib/bundler/deployment.rb

This reverts commit c5a889ce865cc0314597e9de11e2bee366e797ac.

Revert "::Rake::CommandFailedError doesn't exist."

---

man/bundle.ronn

Hi, I noticed on the main man page for bundler that some of the listed categories where not being formatted correctly with the rest of the document. This change adds some backticks to add the highlights. The before image is on the right and the after image is on the left.
I'm not sure if those categories were missing their highlights on purpose but let me know if they were.
Thanks!

add missing highlights to bundler's bundle man page

---

lib/bundler/cli/doctor.rb

Hi, there is some weird behaviour in `bundler doctor`. Bundler is checking for the existence of the `ldd` and `otool` commands but is not correctly redirecting the output of `otool`. Example being on the latest version of bundler:
```
› bundle doctor
llvm-otool(1): Apple Inc. version cctools-895
llvm-otool(1): Apple Inc. version cctools-895
llvm-otool(1): Apple Inc. version cctools-895
llvm-otool(1): Apple Inc. version cctools-895
llvm-otool(1): Apple Inc. version cctools-895
llvm-otool(1): Apple Inc. version cctools-895
```
This is happening on Mac OS (10.12). I have refactored the check of these tool using the built in `command` function, this lets us check for the existence of these commands without actually having to execute them.
Thanks.

use Bundler.which to check for otool and ldd

---

bundler.gemspec

for compatibility with license_finder gem, allowing automatic license checks.
Bundler already proposes the same format in it's newgem.gemspec template:
https://github.com/bundler/bundler/blob/master/lib/bundler/templates/newgem/newgem.gemspec.tt#L16
Let use it for bundler itself too.

change license specification in gemspec

---

lib/bundler/lockfile_parser.rb

Introduced and seemingly never used by https://github.com/bundler/bundler/commit/ba579f4a3e525fdd78d89531291450b26a009b07

[LockfileParser] Stop requiring strscan

---

.gitignore
Rakefile
bundler.gemspec
lib/bundler/cli.rb
spec/commands/exec_spec.rb
spec/commands/help_spec.rb

The [gem-man](https://github.com/defunkt/gem-man) gem searches for the man pages in the man folder. Sadly bundler right now uses `lib/bundler/man` for the man pages.
This pr fixes this and also creates correct names for the man pages. A man page always needs the section number in the filename.
After this is merged, I will create a PR that changes the [bundler-site](https://github.com/bundler/bundler-site) repo to search in this new folder for the documentation.

Move man pages to man folder

---

README.md

Add Ruby Together CTA

---

lib/bundler/cli/outdated.rb
lib/bundler/definition.rb
lib/bundler/spec_set.rb
spec/bundler/definition_spec.rb
spec/commands/outdated_spec.rb

Refactoring of @lucasmazza fix w/ specs.
The only existing spec coverage was essentially integration level and
there was no way either @lucasmazza or myself could find a way to
simulate the bug context.
I extracted some of the code out of outdated into Definition and
SpecSet and added unit specs to those extracted bits.
Fixes #4979

Fix outdated regression from cc355865

---

lib/bundler/cli/install.rb
man/bundle.ronn
spec/install/deploy_spec.rb
spec/install/path_spec.rb
spec/other/major_deprecation_spec.rb

This PR is just making a few small improvements to error messages, documentation and code indentation.
Let me know what you think.
Thanks!

Documentation and error improvements

---

lib/bundler/cli/outdated.rb

Hi, 
I separate these part from this PR https://github.com/bundler/bundler/pull/5058.
Regards.

Improve and fixed guide style code from outdated cmd

---

lib/bundler/rubygems_gem_installer.rb
spec/install/gems/compact_index_spec.rb

Improve gem checksum mismatch error message by telling users how to resolve it.
Old message:
```
The checksum for the downloaded `rack-1.0.0.gem` did not match the checksum given by the API. This means that the contents of the gem appear to be different from what was uploaded, and could be an indicator of a security issue.
(The expected SHA256 checksum was "abababababababababababababababababababababab", but the checksum for the downloaded gem was "BR6Oc6Gqnq93u1aIVX4m6DvTHaFgFxdYaLUfa4ekJKI=".)
Bundler cannot continue installing rack (1.0.0).
```
New message:
```
Bundler cannot continue installing rack (1.0.0).
The checksum for the downloaded `rack-1.0.0.gem` does not match the checksum given by the server. This means the contents of the downloaded gem is different from what was uploaded …
```

Improve gem checksum mismatch error message

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

[CLI::Gem] Fail gracefully on an invalid constant name

---

lib/bundler/inline.rb
lib/bundler/installer.rb
spec/runtime/inline_spec.rb

This fixes #5117 
I am passing an option to `Installer` to not build a definition when resolving gems via inline gemfile.
Also, i notice: `Bundler.default_lockfile.exist? && !options["update"]...`. Is "update" suppose to be a string? I ask because i noticed that other options are being passed as symbols, so I'm not which i'm suppose to be using.
Thanks.
PS. Hopefully i have the bundler terminology correct 😄

Dont build defintion with Gemfile.lock (if present) when resolving gems via inline gemfile

---

lib/bundler/templates/newgem/spec/newgem_spec.rb.tt

This little pull request, juste for use actual new syntax for begin an spec file.
```ruby
RSpec.describe "MyAwesomeSpec" do
end
```
instead
```ruby
describe "MyOldAwesomeSpec" do
end
```
link: https://github.com/rspec/rspec-rails/commit/ca0d249858903949052e06884e8e7f9d596cdc79

Use new RSpec syntax in spec template

---

lib/bundler/rubygems_integration.rb
lib/bundler/source/rubygems.rb
spec/install/gemfile/git_spec.rb
spec/install/path_spec.rb

Closes #5210 but I'm not entirely convinced that this is necessary

[RubyGems] Ignore specs missing extensions

---

lib/bundler/errors.rb
lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb

[SharedHelpers] Handle generic SystemCallErrors in #filesystem_access

---

lib/bundler/fetcher/compact_index.rb
spec/bundler/fetcher/compact_index_spec.rb

[CompactIndex] Disable when openssl is in fips mode

---

lib/bundler/cli/lock.rb
spec/commands/lock_spec.rb

Necessary since the ruby platform is a string instead of a platform object
Closes #5230

[Lock] Fix --add-platform ruby

---

lib/bundler/cli/common.rb
lib/bundler/cli/install.rb
lib/bundler/cli/update.rb
spec/update/gems/post_install_spec.rb

Currently post install messages are only displayed for `bundle install` not for `bundle update`.  This PR fixes that so they're displayed for both, and includes a small refactor of some duplicated functionality between `install` and `update`

`bundle update` post install messages

---

lib/bundler/retry.rb
spec/bundler/retry_spec.rb
spec/realworld/mirror_probe_spec.rb

This PR is fixing a problem where the warnings and errors on a `bundle install` using an invalid source are not being put on a newline correctly.
```
› bundle install
Fetching source index from https://www.google.com/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://www.google.com/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://www.google.com/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://www.google.com/Could not fetch specs from https://www.google.com/
``` 
This is happening because the new lines for the warnings are being printed before the error itself. This behaviour is happening due to another UI problem, see …

Add a new line for before priring BundlerError errors

---

spec/commands/outdated_spec.rb

This supersedes PR #4734, which fixed a bug but didn't have proper spec
coverage. Since that PR was submitted, a different commit (291a807c in
PR #5176) fixed a similar bug at the same time. That caused a merge
conflict in #4734. It was unknown if the same fix fixed both bugs,
since there were no successfully implemented specs. These specs show
that the bug was properly fixed.
These specs were mostly already implemented by @b-ggs, just needed a
little additional guidance.

Specs for multiple platform bug fix in outdated.

---

lib/bundler/plugin/api/source.rb

I checked `Bundler::Source::Path::Installer#post_install` - it's definitely `pre_install` and not `post_install` twice though I wasn't sure given the method name 😄

Use correct hook name in comment

---

lib/bundler/installer/parallel_installer.rb
spec/bundler/installer/parallel_installer_spec.rb
spec/bundler/installer/spec_installation_spec.rb

[ParallelInstaller] Allow installing with corrupted lockfiles

---

lib/bundler/cli.rb
spec/commands/newgem_spec.rb

Should fix #5296 
Since `Kernel#require` calls into `Kernel#gem` as an instance method on `self`, overriding the `gem` method can lead to bad things happening

[CLI] Dont override Kernel#gem for bundle gem

---

bundler.gemspec

@segiddins we can ship pre2 with this. 👍

update link, appeal to better natures

---

Rakefile
task/release.rake

This adds some scripts that I've developed to make releasing easier to the repo, so that way they're not just sitting around in random gists. It also mitigates the risk of me accidentally `git clean -dfx`-ing an uncommitted script in `bin`, which I've totally done before.

[Rakefile] Add release-related tasks

---

lib/bundler/cli/viz.rb

Homebrew capitalises its name — see http://brew.sh.

viz: fix capitalisation of Homebrew

---

lib/bundler/resolver.rb
spec/realworld/edgecases_spec.rb

Closes https://github.com/bundler/bundler/issues/5031
Closes #5095 
\c @marcandre @indirect

[Resolver] Consider locked dependencies first

---

man/gemfile.5.ronn

closes https://github.com/bundler/bundler-site/issues/260
Per @lynnco's suggestion, this cleans up the formatting for platform version specifications. I added the platform list first, then specified the platforms that don't have versions, and then provided the full version list.
I'm not sure how to check the formatting of man pages locally - if you let me know how to do this I can update `CONTRIBUTING` and add this to other guidelines 💯

clean up platform docs for versions

---

lib/bundler/definition.rb
lib/bundler/installer/parallel_installer.rb
spec/install/deploy_spec.rb
spec/install/gemfile/gemspec_spec.rb

Fixes #5340 
Improves handling of gemspec sources by ensuring they're converged before anything else, and also converging the locked dependency sources so that `dependencies_for_source_changed?` doesn't get tripped up

[Definition] Converge sources before anything else

---

lib/bundler/current_ruby.rb
spec/runtime/platform_spec.rb

Closes #5344 
fixes the problem since `Bundler.local_platform` can now be `"ruby"` on Windows, instead of a full-blown `Gem::Platform` object, when `force_ruby_platform` is set

[CurrentRuby] Ensure the local platform isnt ruby before checking os/cpu

---

lib/bundler/definition.rb
spec/install/gemfile/gemspec_spec.rb

Inspired by #5349.
Since dev deps are added with `type: :development`, they are `!=` to the deps retrieved from the lockfile, which have no type. This compares the deps ignoring type completely

[Definition] Avoid re-resolving when a gemspec has dev deps

---

lib/bundler/definition.rb
lib/bundler/resolver.rb
spec/install/gemfile/gemspec_spec.rb

This ensures that deps that come from the lockfile, which might only have the "ruby" platform, dont cause us to attempt to activate/resolve all "ruby" platform gems
Closes #5349

[Resolver] Restrict activated platforms to those in the Gemfile

---

lib/bundler/friendly_errors.rb

This URL no longer exists after the docs reorganization
\c @feministy 
I'd like to release this as 1.14.x so people aren't frustrated when opening new issues

[FriendlyErrors] Update ISSUES.md URL

---

lib/bundler/cli/show.rb
spec/commands/show_spec.rb

This PR is for #5375. I have added a spec (currently failing) of the desired behavior for `bundle show --outdated`
I'm currently looking into a fix for this but welcome anyone else to come in as well.

Bundle show --outdated shouldn't be updating versions 

---

lib/bundler/cli.rb
lib/bundler/cli/inject.rb
spec/commands/inject_spec.rb

Closes #5384
Now it shows the error : 
```
$ bundle inject "gem_name" 1 "v"
ERROR: "bundle inject" was called with arguments ["gem_name", "1", "v"]
Usage: "bundle inject GEM VERSION"
$ bundle inject "gem_name" "v" 1
ERROR: "bundle inject" was called with arguments ["gem_name", "v", "1"]
Usage: "bundle inject GEM VERSION"
```

Show inject usage when args are passed incorrectly

---

.travis.yml

Ruby 2.1.10 was released.
https://www.ruby-lang.org/en/news/2016/04/01/ruby-2-1-10-released

CI against Ruby 2.1.10

---

lib/bundler/definition.rb
spec/install/gemfile/platform_spec.rb

The current warning message for a dep with empty platform is misleading/confusing. You see a sort of the below warning when you `bundle install`,
```
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform mingw, mswin, x64_mingw, jruby`.
```
However, there two issues exist in this message "run `bundle lock --add-platform mingw, mswin, x64_mingw, jruby`":
- You must not have comma (,) for separators
- these commas will be considered as comma itself. see [here](https://github.com/bundler/bundler/blob/242fcbcb2d15d39c63e3441756b77fbfcc1b73b2/lib/bundler/cli/lock.rb#L34-L41) …

Fix misleading warning message when a dependency is unused on any platform

---

doc/contributing/README.md
doc/development/README.md
doc/documentation/README.md

In doc/contributing/README.md, doc/documentation/README.md, and
doc/development/README.md, there were links that referenced files in the
same doc directory but prepended the directory name. This lead to urls
that were broken due to having the directory name stated twice.
I didn't want to clog the issues section with this since it isn't actually an issue with bundler. But I can create an issue of that would be better. Just noticed as I was trying to figure out how to get started. This will be my first OS contribution, so even though it is minor, please let me know if I did anything wrong. Thanks.

Fix links in READMEs causing 404 errors in Github

---

lib/bundler.rb
spec/bundler/bundler_spec.rb
spec/spec_helper.rb

We're deploying to a server with several Ruby applications each with it's own user. However, the home directory of these users is *not* writable by the users.
Since Bundler 1.14.x, a temporary home directoy in the `tmpdir` is used as a fallback. This works well for only one user, but will fail with more than one:
1. user1 execs `bundle`
2. `/tmp/bundler/home/user1` is created usually with 0755 modes
3. user2 execs `bundle`
4. `/tmp/bundler/home/user2` cannot be created since user2 can't write to `home`
This PR adds a `chmod` to apply mode 0777 to `home`. It rescues to nil in order to silently fail on step 4 (user2 cannot chmod `home` since it's owned by user1) as well as in case of any other problem performing chmod. Since we're in a fallback here, I guess it's okay to do this. However, …

Permissive temporary home directory

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

`bundle gem` command fails with an exception when creating a gem having
the same name of a file in the specified path.
For instance:
> touch hello
> bundle gem hello
This bug is due to Thor gem. At the moment, Thor does not handle
conflicts between files and directories. This commit mitigates the
problem by rescuing the exception from Thor and gracefully exit with an
error message.
Fixes https://github.com/bundler/bundler/issues/5358

[Fix #5358] Handle files conflicts when using `bundle gem`

---

lib/bundler/definition.rb
lib/bundler/index.rb
lib/bundler/source/path.rb
lib/bundler/spec_set.rb
spec/install/deploy_spec.rb
spec/install/gemfile/gemspec_spec.rb
spec/lock/lockfile_spec.rb
spec/support/helpers.rb

[Definition] Fail when installing in frozen mode & gemspec deps have changed

---

lib/bundler/lazy_specification.rb
lib/bundler/remote_specification.rb
lib/bundler/rubygems_integration.rb
lib/bundler/source/rubygems.rb
spec/runtime/setup_spec.rb

Avoid conflict between two versions of openssl gem on 'bundle exec' if
a newer and non-default version of openssl gem is installed to the
system. rubygems/spec_fetcher loads openssl through resolv and
securerandom when running with Ruby <= 2.4.
This is not a proper fix for #5235 as other standard libraries that
Bundler currently loads will be gemified as well in Ruby >= 2.5,
however, this will fix openssl's case.
Reference: https://github.com/bundler/bundler/issues/5235
Fixes: https://github.com/ruby/openssl/issues/103
---
Reproduce:
1. Install Ruby 2.4.0 (comes with openssl 2.0.2)
2. Run `gem install openssl` to install openssl 2.0.3
3. Create a Gemfile and run `bundle install`
4. Run `bundle exec ruby -e'require "openssl"'

Defer requiring rubygems/spec_fetcher until it becomes necessary

---

bundler.gemspec

as demonstrated on twitter[1], this message was unfortunately convincing people that Ruby Together pays for the rubygems.org servers. let's remove it and come up with something clearer later.
[1]: https://twitter.com/MelissaKaulfuss/status/829504864229023744

remove post-install on account of confusion

---

doc/contributing/BUG_TRIAGE.md

\cc @indirect What we were discussing earlier
This PR consists of several changes like:
* Update references to guides (troubleshooting.md & issues.md specifically)
* Adding references to existing guides (pull_request.md)
* General cleanup, adding clarity etc

improvements to the BUG_TRIAGE guide

---

lib/bundler/cli/gem.rb
lib/bundler/templates/newgem/README.md.tt
spec/commands/newgem_spec.rb

This fixes #5438 where the wrong git config variable was being
retrieved.
This was using `git config user.name` rather than `git config github.user` in URL in `README.md`

Fix Github username for README.md contrib URL

---

man/bundle-config.ronn

As suggested in https://github.com/bundler/bundler/pull/5403#issuecomment-278384552 instead of changing parsing `mirror.fallback_timeout` I added documentation for it.
Pull request https://github.com/bundler/bundler/pull/5403 can be closed.

Add documentation for mirror.fallback_timeout option.

---

lib/bundler/fetcher/compact_index.rb
spec/bundler/fetcher/compact_index_spec.rb

Fixes #5433. Since there is no easy accessor in Ruby to detect whether or not FIPS mode is currently active, the best approach I could come up with is to `fork` a separate process and attempt to generate a build MD5 object as a test of whether MD5 module is currently available.
Because `fork` approach won't work on some platforms (JRuby, Windows etc), `md5_supported?` returns `false` on any platforms where FIPS mode is enabled and `Process.respond_to?(:fork)` is `false`.
I've added a spec that simulates behavior when OpenSSL FIPS mode is active - an error message is output to STDERR and the process is killed with the `ABRT` signal.

Enable compact index when OpenSSL FIPS mode is enabled but not active

---

lib/bundler/resolver.rb
spec/install/bundler_spec.rb

As the added comment says, this will force all dependencies where there are only 0 or 1 total specs with that name to be resolved first. Right now, they sort ~last, which leads to poor performance.
(This was one way of fixing some recent resolver issues, even though we've done the proper fixes in Molinillo for them)

[Resolver] Improve sorting of deps with 0 or 1 possibility

---

lib/bundler/stub_specification.rb
spec/runtime/setup_spec.rb

Call through to the stub instead of materializing the full remote_spec since all gems added to the local index are asked whether they are missing extensions or not

[StubSpecification] Avoid loading all installed gemspecs

---

doc/contributing/BUG_TRIAGE.md

I messed up the path to the PR review guide from an earlier PR. Sorry.

fix broken link to PULL_REQUESTS.md in BUG_TRIAGE.md

---

lib/bundler/installer/gem_installer.rb
spec/bundler/installer/gem_installer_spec.rb

If use bundler 1.14.4 with rubygems 2.6.8 and
`Bundler.settings["build.#{spec.name}"]` returns `nil` then we get
error "can't modify frozen literal string" from [rubygems](https://github.com/rubygems/rubygems/blob/v2.6.8/lib/rubygems/ext/rake_builder.rb#L13).
RubyGems 2.6.8 is the default version for Ruby2.4.0.
See also https://github.com/sickill/rainbow/issues/48

Use empty array when `spec_settings` returns `nil`

---

lib/bundler/cli.rb
lib/bundler/cli/info.rb
lib/bundler/cli/install.rb
lib/bundler/cli/show.rb
spec/commands/info_spec.rb
spec/install/post_bundle_message_spec.rb

This PR refers to #4754. 
It introduces the command `bundle info GEM` that takes some responsabilities out of `bundle show`. 
`bundle info rake` will output information of a single gem, different from `bundle show --outdated` that outputs informataion of all gems:
```
* rake (11.3.0)
Summary:  Rake is a Make-like program implemented in Ruby
Homepage: https://github.com/ruby/rake
Status:   Up to date
```
**Options:**
`--path` will output only gem's installation path:
```
$ bundle info rake --path 
/home/fredrb/.rvm/gems/ruby-2.3.1/gems/rake-11.3.0
```
---
As for now, the `GEM` parameter is not optional. I think this makes sense if there will be a `bundle list` command (or something similar) that will output the full list of gems. What do you guys think?
I also added a _deprecated warning_ …

bundle info command

---

lib/bundler/plugin/api/source.rb
lib/bundler/rubygems_ext.rb
spec/install/gemfile/gemspec_spec.rb

Avoid undefined Bundler::Plugin::API::Source exception

---

lib/bundler/lazy_specification.rb

Because a nil platform is the same as RUBY

[LazySpecification] Handle when platform is nil in __materialize__

---

exe/bundle
lib/bundler/worker.rb

I found this helpful when trying to figure out why bundler was going so slowly

Print a backtrace on SIGINT in debug mode

---

man/gemfile.5.ronn

These two links don't go anywhere in the browser, most likely because 01fc34bebd128d758733261f16d9e9a8523d81d4 changed the text of those (and other) headers.
As far as I know (based on a quick search with `/\w+-)/`), these are the only two links with this problem.

Update `Gemfile` docs' link targets for `:source`

---

lib/bundler/compact_index_client/updater.rb
spec/bundler/compact_index_client/updater_spec.rb

This code in Compact Index Client expected there to _be_ an ETag header in the response:
```ruby
response_etag = response["ETag"].gsub(%r{\AW/}, "")
```
This PR handles that case when an ETag header may not be available in the `response`. If so, we won't try to update any cache.
~**Questions**: Would it be better with a non-empty string default? Something along the lines of "No ETag header found in response"?~
Closes #5463 
---
Continuation of this work: Use artifice to imitate Net::HTTP interactions -
see https://github.com/bundler/bundler/commit/fb8d40c3462751e5853f76e2cd342b8b9a4b4430 for details

Updater.rb: Avoid using String method on nil

---

lib/bundler/source/rubygems.rb
spec/runtime/inline_spec.rb

This is super helpful when you're on slow cafe wifi and downloading an 8MB gem such as nokogiri

[Source::RubyGems] Print that we are fetching a gem

---

lib/bundler/templates/newgem/README.md.tt
spec/commands/newgem_spec.rb

Adds feature discussed in #5512 
When the --coc flag is set or otherwise enabled when generating a new
gem, a Code of Conduct is generated. This adds an additional link to
that Code of Conduct in the README, and adds default text for the
Code of Conduct based on language used in other popular ruby open
source libraries (bundler, rails).

Add Code of Conduct content to README template

---

lib/bundler/version.rb

Once RubyGems ships with Bundler as a default spec, if using bundler via
-I, it will still be registered as an activated spec (even if the loaded
features are loaded from the load path and not the default gem). This
hack ensures the versions will always match.
This works around https://github.com/rubygems/rubygems/issues/1866, and is a substitute for https://github.com/rubygems/rubygems/pull/1868, allowing the bundler tests to pass if RubyGems master (which will be released as 2.7), which ships with bundler as a default gem, is installed (vs. just being used via `-I`)

Ensure Gem.loaded_specs["bundler"].version returns bundler's version

---

lib/bundler.rb
lib/bundler/cli.rb
spec/commands/exec_spec.rb
spec/support/helpers.rb

[CLI] Dont reset every time the CLI is initialized

---

lib/bundler/gem_helper.rb
man/bundle-config.ronn

In order to use the `rake release` command with a private gemstash server, I'd need the `--key` option described here:
https://github.com/bundler/gemstash/blob/master/docs/gemstash-private-gems.7.md#pushing
I added a quite unobtrusive method to check for an ENV variable and - if it's present - add the `--key` param.
Final command would be:
`GEM_KEY=test_key bundle exec rake release`

Adding the --key option for releasing private gems with gemstash

---

lib/bundler/templates/newgem/README.md.tt

This PR fixes a tiny cosmetic issue in the READMEs that are generated with the `bundle gem` command. Currently when ERB is parsing the `<% if ...` blocks the new lines are not being omitted so you end up with:
```
Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/testapp. This project is intended to be a safe, welcoming space for collaboration, and contributors are expected to adhere to the [Contributor Covenant](http://contributor-covenant.org) code of conduct.
The gem is available as open source under the terms of the [MIT License](http://opensource.org/licenses/MIT).
Everyone interacting in the Testapp project’s codebases, issue trackers, chat rooms and mailing lists is expected to follow the [code of …
```

fix spacing between paragraphs in generated READMEs for new gems

---

lib/bundler/plugin.rb
lib/bundler/plugin/index.rb
spec/plugins/install_spec.rb

Previously, when encountering any kind of exception when installing or
registering a plugin, we would uninstall _everything_ in `specs`, which included
not just every installed plugin but Bundler itself 😱  
This patch prevents this from happening, by only attempting to delete code 
that is a) part of the installation attempt and b) NOT a currently registered
command. This second restriction is to avoid a broken state,  in the case
where we attempt to install the same plugin twice. In that case, if we uninstall
the code for the plugin, but leave the command registered, this causes
attempts to reinstall the plugin to fail, as the command is still in the
registry, and attempts to USE the command will fail because the code behind
it has been destroyed.
Paired with @roseaboveit

Only uninstall plugins that we attempted to install

---

lib/bundler/cli/gem.rb
spec/commands/newgem_spec.rb

So the `gem` command is still breaking on master if `git` is not installed on the machine. This is because we're not checking if git is installed before we init a new git repo.
The test for #5466 is also not actually testing if git is not installed, it's only removing the git config which we already have tests for as well.
@segiddins Do you know a way i can stub `Bundler.git_present?` in the sub-process or have `git` appear to not be present in rspec?

Fix `bundle gem` command without having git

---

lib/bundler/mirror.rb

Require socket in the file that needs it

---

doc/contributing/ISSUES.md

Rails 2.3 has been EOL since 2013 and i have not seen any issue currently in Bundler's open issues or recently closed that is dealing with it. So i propose we remove it as it no longer has any value.

remove Rails 2.3 from ISSUES.md guide

---

lib/bundler/source.rb
spec/bundler/source_spec.rb

This is very much intended as a work in progress (no tests!) and proof-of-concept .
Closes #5506.
In cases where the _dependencies_ change, it is not always possible to tell if they are going forwards or backwards -- for instance a change from `> 2.0` to `< 2.8` is neither obviously a forward or a backward change.
Hence the behavior here is to always default to the green color unless there are two specific version numbers and the new one is strictly less than the old one, in which case we use the yellow color.
I’d love any code review and any suggestions for the right place to add some tests for this. I think the tests should end up being quite simple -- we can check for `\e[32m` (green) versus `e[33m` (yellow) in the strings sent to the shell, and that’s easy enough -- but I’m simply not …

use yellow color when version appears to be moving backwards

---

lib/bundler/definition.rb
lib/bundler/lockfile_parser.rb

What this addresses
---
The LockFileParser dependenies class variable is used throughout definition
using a series of select and find statements. While measuring Bundler performance, it was
noticed that pieces that interacted with @locked_deps took a fair chunk of time.
This chart shows some timings for `Definition.new` which is called during `require 'bundler/setup'`
** Note: The time scale is a little off because `TracePoint` slows it down, but this does show us a slow point we can optimize.
Diving into that a bit more, we can see the following timings
Again, despite the timings being off due to TracePoint, we can see that `locked_source = @locked_deps.select {|d| d.name == dep.name }.last (run 112812 times) :a1, 0.001, 0.182` was run upwards of 113K times for the Shopify application. …

Change LockFileParse dependencies class variable from an array to a hash

---

lib/bundler.rb
lib/bundler/resolver.rb
lib/bundler/version_ranges.rb
spec/bundler/version_ranges_spec.rb
spec/resolver/basic_spec.rb

This implements a feature that @indirect thought up last week.
Previously, when a resolver conflict occurred, bundler would print _all_ the "conflicting" dependencies, even if some of them were not an issue! No longer. Now, we'll compute the minimal set of conflicting dependencies and only print out the requirement trees for those, which should hopefully make conflict messages less confusing and more actionable for users.
I have some tests for the `VersionRanges` module that I'll push up in a few minutes, but a test for the feature itself is already included.

[Resolver] Only include minimal set of conflicting deps in conflict message

---

lib/bundler/source/git.rb
lib/bundler/source/path.rb

Instead of validating every time we setup, only do so when we re-serialize the spec
\c @jules2689

[Source::Git] Only validate specs once (on download)

---

man/bundle.ronn

Fixes #5560. Hope I understood correctly, I only added a reference because the full man page was already there.

Add bundle binstubs to the main man page

---

lib/bundler/cli.rb
lib/bundler/cli/issue.rb
spec/commands/issue_spec.rb

This is my stab at adding a `bundle issue` command, as listed in the list of tasks anyone can claim (#4871).  This is also my first contribution (of what I hope will be many) to Bundler!  
I hope that this is useful, and please let me know how to improve it!

Add `bundle issue` command that prints instructions for reporting issues

---

lib/bundler/rubygems_integration.rb
spec/runtime/setup_spec.rb

This is failing on ruby 2.5, since more of the stdlib is being gemified (fileutils in particular)
We can wait to merge until it passes if you'd like, @indirect, but this will likely also require changes in RubyGems

Add a spec for not activating any gems during Bundler.setup

---

lib/bundler/cli.rb
lib/bundler/cli/inject.rb
lib/bundler/injector.rb
spec/commands/inject_spec.rb

Fixes https://github.com/bundler/bundler/issues/5452
Eg
```
$ bundle inject "bootstrap" ">0" --source=https://rubygems.org --group=development
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Fetching dependency metadata from https://rubygems.org/.
Added to Gemfile:
bootstrap (> 0), group => [:development], :source => 'https://rubygems.org'
```
In GemFile 
```
gem 'bootstrap', '> 0', :group => [:development], :source => 'https://rubygems.org'
```
```
$ dbundle inject "bootstrap" ">0" --source=https://rubygems.org --group=development,production
Fetching …
```

`bundle inject` with source and group options

---

lib/bundler/dsl.rb
spec/bundler/dsl_spec.rb

When the user supplies the `branch` option to a non-git gem an error message should be printed.
Relates to #5530.

print an error message when a non-git gem is given a `branch` option

---

lib/bundler/lazy_specification.rb
lib/bundler/remote_specification.rb
lib/bundler/rubygems_integration.rb
lib/bundler/source/git.rb
lib/bundler/source/path.rb
lib/bundler/stub_specification.rb
spec/bundler/plugin/installer_spec.rb
spec/runtime/require_spec.rb

This should save us the hit of needing to `eval` all the gemspecs we use when the user has a modern (>= 2.3) RubyGems

[StubSpecification] Avoid loading the full spec when possible

---

lib/bundler/shared_helpers.rb
lib/bundler/worker.rb

This means that SIGINT during, say, dependency resolution will still cleanly exit the process.

[Worker] Allow interrups to exit the process even after the threads are disposed

---

lib/bundler/cli/pristine.rb
lib/bundler/source/rubygems.rb
spec/commands/pristine_spec.rb

Since Source::Rubygems will never re-install it
Closes #5578

[Pristine] Skip the bundler gem

---

lib/bundler/fetcher/downloader.rb
spec/bundler/fetcher/downloader_spec.rb

[Downloader] Print underlying error in HTTPError

---

lib/bundler/cli.rb
lib/bundler/cli/config.rb
spec/commands/config_spec.rb

This Pull Request implements #4913:
```
$ bundle config gem.coc --parseable
=> true
```
Related: #4871
<details>
<summary>
Feedback for development of Bundler</summary>
Cannot use byebug / pry to dive into the code. 😢 
Cannot use puts / p to print something for debugging. 😢 
Currently use `Bundler.ui.info` to print something for debugging. 😅 
</details>

Feature: Add parseable option to bundle config command

---

lib/bundler/cli.rb
lib/bundler/cli/issue.rb
lib/bundler/env.rb
lib/bundler/friendly_errors.rb
spec/bundler/env_spec.rb

This is to a comment i made in #5589 
Currently to print the Bundler env report you need to need to invoke it
via:
Bundler::Env.new.report
This change removes the need to instantiate an instance and just call
a class method of the same name:
Bundler::Env.report

move implementation of Bundler::Env to class methods

---

lib/bundler/stub_specification.rb
spec/install/gemfile/git_spec.rb

Fixes https://github.com/bundler/bundler/issues/5594
`stub_specification` doesn't know what `full_name` should be because we don't have a record of the source, so it resolves to `cityhash-0.6.0` rather than `cityhash-3cfc7d01f333`
This makes `StubSpecification` aware of the source to we can still avoid loading the full spec when needed. This is done by bringing remote_specs `attr_accessor :source` to `stub_spec`, and assigning source to the `stub`.
I am probably missing some edge cases to check for though 🙈  Need to write specs.
cc @segiddins

Apply source and git_version to stub spec extension

---

lib/bundler/lazy_specification.rb
spec/install/gems/compact_index_spec.rb

Closes https://github.com/bundler/bundler/issues/5599
I decided to not compare using `full_name` in `SpecSet#merge` for the sake of performance, since `#full_name` is uncached

Avoid duplicating specs in the lockfile after updating w/ the gem uninstalled

---

lib/bundler/source/git.rb
spec/cache/git_spec.rb

This will be my first contribution to Bundler. Thanks for the amazing dev setup guides!
This fixes issue #5423 where Git sources would not be updated if they were already cached in `vendor/cache`.
When we build a Git source from Gemfile.lock, we store the revision listed in the lockfile. However, when unlocking the source for an update, we don't clear that revision, and the update proceeds to grab the stale version from `vendor/cache`. Interestingly, this behaviour only occurs when updating a specific gem, i.e. `bundle update timecop`. This bug isn't present when doing a global `bundle update`, possibly because of the differences in how we build up the Definition between the two methods.
Closes #5423.

Ensure pre-existing Git caches are updated from remote sources

---

lib/bundler/templates/newgem/README.md.tt

if value of `config[:coc]` is not `true` when executing `bundle gem <gemname>`, redundant blank lines are created in README.md.
This patch will not create these redundant blank lines.
```diff
Bug reports and pull requests are welcome on GitHub at https://github.com/[USERNAME]/foo.
-
The gem is available as open source under the terms of the [MIT License]
(http://opensource.org/licenses/MIT).
-
```
Related PR: #5523

Tweak a template of newgem

---

CODE_OF_CONDUCT.md
doc/contributing/COMMUNITY.md
doc/development/PULL_REQUESTS.md
lib/bundler/dsl.rb

As far as I know, I think that "GitHub" and "RuboCop" become more precise names.   This PR unifies the name in that way.

Unify the names of GitHub and RuboCop

---

lib/bundler/mirror.rb
lib/bundler/settings.rb
spec/bundler/settings_spec.rb

[Settings] Allow configuring a mirror fallback timeout without a trailing slash

---

lib/bundler/source/git.rb
spec/install/git_spec.rb
spec/support/builders.rb

[Git] Only shorten refs if they are SHAs

---

lib/bundler/settings.rb
spec/cache/cache_path_spec.rb

Removes check on leading `/` from `cache_path` and updates tests.
Fixes #5627

Permit absolute paths in cache_path setting

---

Rakefile
doc/TROUBLESHOOTING.md
doc/contributing/COMMUNITY.md
doc/contributing/ISSUES.md
lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/cli/binstubs.rb
lib/bundler/cli/install.rb
lib/bundler/definition.rb
lib/bundler/env.rb
lib/bundler/gem_helper.rb
lib/bundler/installer.rb
lib/bundler/rubygems_ext.rb
lib/bundler/rubygems_integration.rb
lib/bundler/source/path.rb
lib/bundler/templates/newgem/newgem.gemspec.tt
spec/bundler/fetcher/dependency_spec.rb
spec/commands/binstubs_spec.rb
spec/commands/help_spec.rb
spec/commands/pristine_spec.rb
spec/install/gems/compact_index_spec.rb
spec/install/gems/dependency_api_spec.rb
spec/install/gems/sudo_spec.rb
spec/install/security_policy_spec.rb
spec/runtime/setup_spec.rb
spec/support/builders.rb

This PR is mainly replacing Rubygems with RubyGems. 
`Rubygems` is a Ruby module name (e.g. `Bundler::Source::Rubygems`) , whereas RubyGems is the proper notation as below.
https://github.com/rubygems/rubygems/blob/master/README.md
In this PR, it changed the notation mainly used in console output and documentation  (and some source code comments) .

Unify the notation of RubyGems

---

lib/bundler/stub_specification.rb
spec/bundler/stub_specification_spec.rb

Supersedes https://github.com/bundler/bundler/pull/5593
Fixes https://github.com/bundler/bundler/issues/5592
Explanation
---
In some cases the `Gem::Specification.stubs` call in [this method](https://github.com/bundler/bundler/blob/master/lib/bundler/rubygems_integration.rb#L773-L778) in the rubygems integration returns a mixed bag of `Bundler::StubSpecification` and `Gem::StubSpecification` objects. We then instantiate `Bundler::StubSpecification` objects and set the `stub` to be both `Gem::StubSpecification` and `Bundler::StubSpecification` objects.
This happens after we tell rubygems to use our overrides [here](https://github.com/bundler/bundler/blob/master/lib/bundler/runtime.rb#L21-L24).
A `Bundler::StubSpecification` does not define `to_spec` where `Gem::StubSpecification` does. In …

Return Bundler::StubSpec if stub is a Bundler::StubSpec

---

lib/bundler/rubygems_integration.rb
spec/install/gemfile/gemspec_spec.rb

Fixes https://github.com/rubygems/rubygems/issues/1911
Small novel:
In RubyGems 2.6.11, I changed `Gem.finish_resolve` to respect all of the currently resolved (i.e. `Gem.loaded_specs`) gems. This fixed some bugs that would lead `Gem.finish_resolve` to incorrectly raise gem incompatibility exceptions. That's great, except Bundler's resolver doesn't always resolve the same thing as RG's. In particular, `Source::Gemspec` gems that come from the `gemspec` DSL method are allowed to have conflicts. It appears projects, such as rails, were taking advantage of that fact. Since `stub_entrypoints` is called whenever `Bundler.setup` is run, this is essentially us 'activating' all of the gems in the bundle. Since everything is eagerly activated, it should be impossible for there to ever be any …

[RubygemsIntegration] Stub out Gem.finish_resolve

---

spec/support/rubygems_ext.rb

See https://github.com/rack/rack/issues/1168
The above issue broke rack on 1.9.3
\c @colby-swandale

Avoid Rack 1.6.7 in specs for now

---

lib/bundler/source/git/git_proxy.rb

Fixes  the following test under newer git versions
```
bundle update
git sources
with submodules
unlocks the source when submodules are removed from git source
```

[GitProxy] Force deinitializing submodules

---

lib/bundler/templates/newgem/rspec.tt
lib/bundler/templates/newgem/spec/newgem_spec.rb.tt

`--require spec_helper` is contained in .rspec by default when running `rspec --init` on RSpec 3.
```sh
% rspec --version
3.5.4
% rspec --init
create   .rspec
create   spec/spec_helper.rb
% cat .rspec
--color
--require spec_helper
```
It seems that the code of template premise the RSpec 3, so I think that it was reasonable to adjust to it.
Related PR #5634

Tweak a newgem template for RSpec

---

doc/contributing/HOW_YOU_CAN_HELP.md

fixed broken link within the HOW_YOU_CAN_HELP.md file in the docs. The link is located at the bottom of the file. It is on the second to last item in the unordered list. The words to the link are: "these instructions".

Fixed broken link in docs

---

doc/documentation/README.md

Fixed "Writing" heading and converted "here" into links for clarity

Minor links refactoring in README.md

---

lib/bundler/gem_helper.rb

When using the `allowed_push_host` metadata in a gems gemspec along with `bundler/gem_tasks` `rake release` shows that the gem will be pushed to rubygems.org rather then showing the configured `allowed_push_host` if that has been set.  This resolves that confusion by showing the correct host that `rake release` will attempt to push to.

List the remote host correctly in rake task desc.

---

doc/development/README.md

GH now requires a space between `#` and the header

Fix markdown headers in doc/development/readme

---

lib/bundler/installer.rb
lib/bundler/source/git/git_proxy.rb
spec/install/force_spec.rb

This allows `bundle install --force` to work when the gemfile includes a git spec, previously it would error nonsensically. This happened because sources needed to be `remote!`ed for installation to succeed, and this wouldn't happen when `--force` was called with no other changes to the gemfile.
Closes #5678

Allow bundle install --force to work with git specs

---

lib/bundler/cli/init.rb
spec/commands/init_spec.rb

Also added some specs to init what wasn't being tested.

Fix `bundle init --gemspec` breaking when gemspec is invalid

---

lib/bundler/cli/common.rb
lib/bundler/cli/lock.rb
lib/bundler/cli/update.rb
spec/commands/lock_spec.rb

Closes #5693 by behaving the same way `bundle update` handles gems that aren't in the lockfile

[CLI::Lock] Fail gracefully when updating a missing gem

---

lib/bundler/spec_set.rb
spec/runtime/setup_spec.rb

Closes #5696
This is required for backwards compatibility, see
issue #5696  for an example. The issue is that previous versions of bundler would have the load path in one (correct) order, and master has them in another (correct) order. So some projects depend on the load path ordering when multiple gems have the same requirable file.

[SpecSet] Sort by name in #tsort

---

lib/bundler/cli/viz.rb
spec/commands/viz_spec.rb
spec/support/helpers.rb

Closes #5706 by ensuring we always have the correct gem that contains a requirable `graphviz` file loaded (`ruby-graphviz` is the one we test against and suggest installing)

[Viz] Work correctly when another gem with a graphviz file is present

---

lib/bundler/env.rb

Closes #5616.
Prints out `Gem.ruby` and the `bundle` binstub shebang when they don't match, which should help us pinpoint when ruby installation shenanigans are the root cause of an issue

[Env] Print shebang when it doesnt match Gem.ruby

---

lib/bundler.rb
lib/bundler/cli.rb
lib/bundler/cli/install.rb
lib/bundler/environment_preserver.rb
lib/bundler/inline.rb
lib/bundler/runtime.rb
lib/bundler/shared_helpers.rb
spec/bundler/environment_preserver_spec.rb
spec/runtime/with_clean_env_spec.rb
spec/spec_helper.rb

Closes #5700.
Attempts to make sure we properly preserve missing env variables such as `RUBYOPT` across `bundle exec` invocations so that `Bundler.original_env` is accurate

Ensure Bundler.original_env preserves _all_ keys bundler sets

---

doc/contributing/README.md

Some headers in contributing/README.md aren't displaying properly.
Also, I promised @indirect that I'd start contributing to bundler last night.
The markdown was missing some spaces.
I added some spaces. TADA!
Adding spaces seemed like the most reasonable choice to transition from a state of non-spaces to a spaceful state.

Fix headers in contributing README

---

README.md

make it clear that everyone's contributions are welcome, and make it clear that Ruby Together funds contributors, but does not maintain the project directly

clearer, more specific wording about sponsorship and contributing

---

lib/bundler/installer.rb
lib/bundler/rubygems_integration.rb
spec/install/gemfile/path_spec.rb
spec/spec_helper.rb

Closes #5429 .
Because RubyGems doesn't know about path gems before we install, we need to manually load the plugin files for the path gems we're installing. This is basically copying the logic RG uses, but scoped only to those gems that we're entirely responsible for.

[Installer] Load plugin files from path gems

---

.gitignore
Rakefile
lib/bundler.rb
lib/bundler/build_metadata.rb
lib/bundler/cli.rb
lib/bundler/env.rb
lib/bundler/generated/build_metadata.rb
spec/commands/version_spec.rb
spec/install/gemfile/git_spec.rb
task/build_metadata.rake
task/git_hooks.rake
task/release.rake

Closes #5049.
Will get all the build metadata into `bundle env` once https://github.com/bundler/bundler/pull/5703 lands, since I don't want conflicts and want to use that code for generating the "tables"

Print build metadata when running `bundle version`

---

lib/bundler.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
man/bundle-config.ronn
spec/bundler/definition_spec.rb
spec/install/gemfile_spec.rb

With `prefer_gems_rb` set (by default on 2.0), Bundler will prefer a `gems.rb` that is in the same directory as a `Gemfile`

[2.0] Add a feature flag to prefer gems.rb to Gemfile

---

lib/bundler/templates/Gemfile
lib/bundler/templates/gems.rb
lib/bundler/templates/newgem/Gemfile.tt

The problem was that people are creating new Gemfiles that use the built-in `github` git source, which is being removed in 2.0. Additionally, it does _not_ use an encrypted connection to GitHub.
My diagnosis was that we can't change the default because of backwards compatibility, but we can encourage _new_ Gemfiles to "do the right thing".
My fix is to add our new, recommended definition of the shortcut to all bundler-generated gemfiles.
I chose this fix because it will only affect new Gemfiles.

Create Gemfiles with an HTTPS github source defined

---

lib/bundler/definition.rb
lib/bundler/installer.rb
lib/bundler/source/path.rb
lib/bundler/source/rubygems.rb
spec/install/gemfile/lockfile_spec.rb
spec/spec_helper.rb

This is just a straight port of https://github.com/bundler/bundler/pull/4952 to master from `2-0-dev`.
Unfortunately, the Gemfile is still eval'ed twice when plugins are enabled.

Eval Gemfiles one fewer time when running `bundle install`

---

lib/bundler/environment_preserver.rb
spec/runtime/setup_spec.rb

The problem was Bundler could throw an exception during setup when a gem contained manpages we were adding to `$MANPATH`.
Fixes #5730.
My diagnosis was that `$MANPATH` wasn't whitelisted as a key we preserved / were 'allowed' to override via `SharedHelpers.set_env`.
My fix is to add `$MANPATH` to that list of keys, as @jules2689 suggested. I also added some test coverage around us setting the proper man path.
I chose this fix because it treats that env var in the same way as others bundler sets.

[EnvironmentPreserver] Allow preserving MANPATH

---

lib/bundler/cli/install.rb

There is a typo in the error message that is printed to users when a user specifies a set of conflicting groups when running bundle install. There is a missing space after the first sentence. 
```
› bundle install --with foo --without foo
You can't list a group in both, --with and --without.The offending groups are: foo.
```
execute `bundle install --with foo --without foo`

fix a missing space in the group conflict error message

---

lib/bundler/definition.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
man/bundle-config.ronn
spec/commands/update_spec.rb

The problem is that `bundle update --source NAME` will unlock a _gem_ with that name, in addition to the source.
My diagnosis was that we unlocked based on `spec.name` instead of `spec.source.name`.
My fix is to put this backwards-compatibility hack behind a feature flag that will turn off on 2.0.
I chose this fix because it allows the current behavior to continue for those who depend upon it, but the hack will be disabled by default on 2.0, or when `unlock_source_unlocks_spec` is set to true.

Add a feature flag for `bundle update —source NAME` not unlocking a gem with that name

---

lib/bundler/cli.rb
spec/bundler/cli_spec.rb

The problem was that running `bundle lock --verbose`  would print 
Running `bundle lock    --add-platform  --remove-platform  --verbose` with bundler 1.15.1
even though the platform flags were never specified. This was surfaced by https://github.com/bundler/bundler/pull/5724, which will be fixed by this PR.
My diagnosis was that default values of options were being printed.
My fix is to filter out the default values before getting Thor 
I chose this fix because there is no way, within the `CLI` instance, to tell which flags the user has explicitly given, so I felt that filtering out those options that had default values was the next-best thing.

[CLI] Dont print defaults in the command printed with --verbose

---

bundler.gemspec
spec/spec_helper.rb

The problem was the specs had method redefinition warnings on 1.8.7.
My diagnosis was the `mkpath` hack was causing some, as well as us requiring support files by their absolute paths.
My fix requires support files by relative paths and updates rspec to 3.6, where the `mkpath` hack is unnecessary.
I chose this fix because it works on 1.8.7 without any adverse effects on modern rubies.

Avoid warnings in the specs on Ruby 1.8.7

---

spec/bundler/stub_specification_spec.rb
spec/bundler/ui/shell_spec.rb
spec/install/gemfile/install_if.rb

Follow up of #5634.
Since `--require spec_helper` is specified in the .rspec file, This PR will remove redundancy.

Remove `require "spec_helper"` from spec files

---

lib/bundler/definition.rb
lib/bundler/feature_flag.rb
lib/bundler/installer.rb
lib/bundler/resolver.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
man/bundle-config.ronn
spec/install/bundler_spec.rb

The problem will occur once 2.0 is released -- there are many gems that declare a `s.dependency "bundler", "~> 1.x"` dependency on bundler. This would essentially make them inoperable with Bundler 2. We want to make adopting 2.0 as pain-free as possible, so hard conflicts are a no-go.
My diagnosis was that we need a way to allow conflicts on the bundler dependency once 2.0 comes out, so people can use 2.0.
My fix introduces a feature flag for allowing these conflicts (enabled on 2.0), which when enabled will ignore bundler dependencies during resolution, and warn in the installer when a conflict would've occurred.
I chose this fix because it has the minimal performance penalty with the feature flag enabled. This is mostly a port of https://github.com/bundler/bundler/pull/3871 to master.

[2.0] Allow conflicts between bundler dependencies and the current bundler version

---

lib/bundler/cli.rb
lib/bundler/feature_flag.rb
spec/quality_spec.rb

The problem was that users unfamiliar with Bundler would run `bundle` and either install gems (if in a directory with a gemfile), or else get the error `Could not locate Gemfile`. You'd need to know to run `bundle help` or `bundle -h` to get the man page, and even that could be overwhelming (not to mention turfing you into a pager).
My diagnosis was that we ought to print some form of help when the bare `bundle` command is run, rather than defaulting to running `bundle install`.
This work was prompted by https://trello.com/c/OpuOdTZl/112-print-help-when-bundle-is-run-without-arguments, and is an improvement (rather than a straight port) on https://github.com/bundler/bundler/pull/3831.
My fix was to print the following help output when the CLI is invoked without arguments, contingent upon …

Default to printing a help message when `bundle` is run without arguments on 2.0

---

lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb
spec/bundler/fetcher_spec.rb

When the `no_proxy` environment variable is configured it is not being honored and requests for hosts that are present in the list will be sent through the proxy defined via `http_proxy` and `https_proxy`.
Ultimately this means that a user utilizing the `http_proxy`, `https_proxy`, and `no_proxy` environment variables will unable to access an internal RubyGems source.
The underlying `net-http-persistent` gem currently does not explicitly pass in nil arguments when a host matches a value within `no_proxy`, so when `Net::HTTP.new()` is called, it will fall back an utilize the values defined in `http_proxy` and `https_proxy`.
https://github.com/drbrain/net-http-persistent/pull/88 has been submitted to add the explicit nil argument to be defined.
Adding explicit nil arguments for the proxy …

Add explicit nil proxy arguments - Fixes no_proxy support

---

lib/bundler/definition.rb
lib/bundler/installer.rb
lib/bundler/spec_set.rb
spec/install/deploy_spec.rb
spec/install/gemfile/groups_spec.rb
spec/install/git_spec.rb
spec/quality_spec.rb

The problem was we would attempt to fetch dependency info from a RubyGems remote even when it was only needed for gems whose groups were excluded.
My diagnosis was that the test we had for this case was insufficient, since it checked only that `stderr` was empty, and since Bundler 1 prints errors to `stdout`... it went undetected for a year.
My fix is to only report that deps are missing when they are either requested or are path/git/gemspec-sourced.
I chose this fix because it keeps the behavior of always ensuring all git repos are checked out.

Avoid hitting RubyGems remotes when all missing gems are in --without groups

---

lib/bundler/settings.rb
spec/bundler/settings_spec.rb

The problem was `bundle config` would print bool keys as strings (i.e. `true` was printed as `"true"`)
My diagnosis was we needed to convert the values before formatting them
My fix extracts the conversion method, and calls it in `pretty_values_for`

[Settings] Print pretty values for settings as their converted values, rather than strings

---

lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb
spec/runtime/setup_spec.rb

Hello - I was stalking the open issues and had time to implement this quick PR for your review. This is a direct fix to https://github.com/bundler/bundler/issues/5712.
I implemented the fix that @segiddins suggested in the comments, just added a test scenario. Please let me know if anything else is needed!
---
The problem was that starting with Bundler 1.15.0, `Bundler.setup` fails with an `ArgumentError` raised from `Pathname#relative_path_from` when the following conditions are met:
- Bundler is in deployment mode; and
- A Gemfile is explicitly specified via the `BUNDLE_GEMFILE` environment variable; and
- That Gemfile is not an absolute path (e.g. `BUNDLE_GEMFILE=Gemfile`)
My diagnosis was that in `Bundler::SharedHelpers#default_gemfile`, the `Pathname` object being instantiated was …

Allow BUNDLE_GEMFILE to not be an absolute path

---

lib/bundler.rb
lib/bundler/feature_flag.rb
lib/bundler/fetcher/compact_index.rb
lib/bundler/settings.rb
lib/bundler/shared_helpers.rb
lib/bundler/source/rubygems.rb
lib/bundler/source/rubygems/remote.rb
man/bundle-config.ronn
spec/bundler/fetcher/compact_index_spec.rb
spec/install/global_cache_spec.rb
spec/support/artifice/compact_index_no_gem.rb

The problem was that bundler would need to download `foo-1.0.gem` files from a RubyGems server for each different ruby version installed on a user's machine. It also meant that people installing into a per-app path would need to re-download every gem for that bundle an additional time. This adds up, and makes `bundle install` slower than it needs to be.
My diagnosis was that Bundler could keep a (per-source) cache of these `.gem` files, and pull from that cache instead of hitting the network whenever possible.
My fix implements said cache, in a very similar way to the compact index cache (same cache slug per remote strategy, etc). This largely comes from https://github.com/bundler/bundler/pull/3983.
I chose this fix because it is safe when used from multi-source gemfiles, it is easy to …

[2.0] Add a global cache for downloaded .gem files

---

lib/bundler/dsl.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
man/bundle-config.ronn
spec/bundler/dsl_spec.rb

The problem was the default git source shortcuts have been deprecated, but still existed in 2.0.
My diagnosis was we needed to avoid adding them in 2.0.
My fix is to introduce a feature flag, which when enabled will stop adding the sources to the DSL, and additionally will disable the `github` DSL method.

[2.0] [DSL] Remove default git sources on 2.0

---

bin/bundle
doc/development/SETUP.md
lib/bundler/version.rb

The problem was that developing bundler can be difficult, and letting users use the in-development bundler locally should be as easy as possible.
My diagnosis was we could use a binstub that handles setting up the load path for bundler, ensures the gem spec is activated, and loads the local bundler code.
My fix adds such a binstub.

Add a bin/bundle binstub

---

lib/bundler/cli.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
spec/commands/console_spec.rb
spec/other/platform_spec.rb
spec/quality_spec.rb

> The console command has gotten many, many pull requests for different kinds of customization and so we eventually realized that an editable bin/console is the only way to provide that level of customization. The gem command already creates bin/console, so all that's left is to remove the console command.
From https://github.com/bundler/bundler/issues/4025.
My diagnosis was `bundle console` needed to go.
My fix removes the console command behind a feature flag, enabled by default on 2.0.
See https://github.com/bundler/bundler/pull/4034.
I chose this fix because it didn't require touching any of the console logic and would give the proper missing command error on 2.0.

[2.0] Remove the console command

---

lib/bundler/feature_flag.rb
lib/bundler/settings.rb
lib/bundler/source.rb
lib/bundler/source/git.rb
lib/bundler/source/metadata.rb
lib/bundler/source/path.rb
lib/bundler/source/rubygems.rb
man/bundle-config.ronn
spec/commands/pristine_spec.rb
spec/commands/update_spec.rb
spec/install/deploy_spec.rb
spec/install/force_spec.rb
spec/install/gemfile/eval_gemfile_spec.rb
spec/install/gemfile/git_spec.rb
spec/install/gems/native_extensions_spec.rb
spec/install/git_spec.rb
spec/runtime/setup_spec.rb
spec/update/git_spec.rb

The problem was that `bundle install` output can get very verbose, even when Bundler is not doing anything.
See https://github.com/bundler/bundler-features/issues/33.
My diagnosis was that bundler was printing a bunch of `Using name (version)` messages, even when we were already using that gem at the same version.
My fix is to introduce a feature flag (enabled by default on 2.0), that will only print those extra `Using` messages when `--verbose` is passed, and will continue to print them when there was an old version we can tell users about. Note that we still print a message when installing a gem for the first time.
I chose this fix because it was essentially what had been done in https://github.com/bundler/bundler/pull/3872, and allows for easy feature-flagging.

[2.0] Suppress `Using …` messages during installation when a version has not changed

---

lib/bundler/cli.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
spec/other/cli_dispatch_spec.rb
spec/quality_spec.rb

The problem was the current `bundle cache` is obsolete.
My diagnosis was we want `bundle package` to be `bundle cache`, but can't change the `cache` behavior due to backwards compatibility.
My fix is to redirect `bundle cache` to `bundle package` on Bundler 2.
I chose this fix because it implements https://github.com/bundler/bundler/pull/4008 without breaking the current `bundle cache` command on master.

Use the Package command for `bundle cache` on Bundler 2

---

lib/bundler/remote_specification.rb
spec/commands/install_spec.rb

Instead of containing Gem::Dependency objects
The problem was some gems have invalid gemspecs served by RubyGems.org. See https://github.com/bundler/bundler/issues/5797.
My diagnosis was (very old) some gemspecs can have `s.dependencies = [["name", "req"]]` instead of `s.dependencies = [Gem::Dependency.new("name", "req")]`.
My fix coerces the invalid dependencies to an array of dependency objects so we can fail more gracefully during installation, without spitting out the error template.
Closes #5797.
I chose this fix because it allows resolution to finish, and falls back upon existing error messages.

[RemoteSpecification] Fail gracefully when deps is an array of array of string

---

lib/bundler/definition.rb
lib/bundler/dependency.rb
lib/bundler/feature_flag.rb
lib/bundler/lazy_specification.rb
lib/bundler/resolver.rb
lib/bundler/settings.rb
spec/bundler/definition_spec.rb
spec/commands/check_spec.rb
spec/commands/install_spec.rb
spec/commands/lock_spec.rb
spec/commands/update_spec.rb
spec/install/gemfile/platform_spec.rb
spec/install/gems/flex_spec.rb
spec/lock/lockfile_bundler_1_spec.rb
spec/lock/lockfile_spec.rb
spec/other/platform_spec.rb
spec/plugins/source/example_spec.rb
spec/runtime/setup_spec.rb
spec/support/command_execution.rb
spec/support/platforms.rb
spec/update/git_spec.rb

The problem was that Bundler has somewhat suspect handling of multi-platform gems. We'd assume that different platform versions of gems were generally interchangeable, so if Bundler resolved to the "ruby" platform gem we'd just blindly try to swap in the gem for the local platform, which could lead to issues (say if the sets of dependencies were different).
My diagnosis was that we needed to stop only working with the notion of "generic" platforms, which mapped everything to (basically) either java, pure ruby, and windows, and instead keep track of the actual platforms a bundle was being used on, and resolve for those specific platforms.
My fix enables the changes made in https://github.com/bundler/bundler/pull/4836 by default on Bundler 2.
I chose this fix because it means Bundler will …

[2.0] Enable specific_platform by default on 2.0

---

lib/bundler/source/path.rb
spec/bundler/source/path_spec.rb
spec/install/gemfile/eval_gemfile_spec.rb

Given a setup where:
1. A project's Gemfile makes use of another project's Gemfile and the `eval_gemfile` method to share the dependencies.  Something like:
```ruby
eval_gemfile(File.expand_path("../../main_project/Gemfile", __FILE__))
```
2. The main project includes a path gem in it that is nested in the main project:
```ruby
gem "foo_gem", :path => "vendor/foo_gem"
```
3. A `bundle install` is followed by a `bundle install --deployment`, the second of which triggers a comparison of the `lockfile.sources` and the `Bundler.definition`
A error will occur when comparing the specs, saying the the "foo_gem" source has been deleted:
```console
$ bundle install
...
$ bundle install --deployment
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` …
```

Compare sources using source's root

---

man/bundle-config.ronn
spec/quality_spec.rb
spec/support/matchers.rb

The problem was we kept on adding new settings to the end of the list, making it completely unordered.
My diagnosis was we should order the list.
My fix orders the list and tests that it is indeed ordered.
I chose this fix because I could write a little script to do it.

Sort all documented settings in the bundle-config man page

---

lib/bundler/cli.rb

This PR is a small patch.
I made the following changes locally to the code of the master branch and tried Bundler 2.0.
```diff
% git diff
diff --git a/lib/bundler/version.rb b/lib/bundler/version.rb
index dad4a88a2..386782023 100644
--- a/lib/bundler/version.rb
+++ b/lib/bundler/version.rb
@@ -7,7 +7,7 @@ module Bundler
-  VERSION = "1.15.1" unless defined?(::Bundler::VERSION)
+  VERSION = "2.0.0.dev" unless defined?(::Bundler::VERSION)
def self.overwrite_loaded_gem_version
begin
```
Here is the result of running the `bundle` command.
```console
% bundle
Bundler version 2.0.0.dev
Commands:
bundle add GEM VERSION            # Add gem to Gemfile and run bundle install
bundle binstubs GEM [OPTIONS]     # Install the binstubs of the listed gem
bundle cache [OPTIONS]            # Locks and …
```

Capitalize the description lines in Bundler 2

---

lib/bundler/templates/newgem/newgem.gemspec.tt

There are unnecessary magic comment for currently maintained Ruby 2.2, 2.3, and 2.4.
The default script encoding from Ruby 2.0 is UTF-8.
https://bugs.ruby-lang.org/issues/6679
Ruby 1.9 is EOL, so I think that there is not much Gem to start developed using it. 
This PR removes magic comment when starting Gem development (i.e. `bundle gem`) with Ruby 2.0 or higher version.

Tweak gemspec template when using Ruby 2.x

---

lib/bundler/inline.rb
lib/bundler/installer.rb
lib/bundler/installer/gem_installer.rb
spec/bundler/installer/gem_installer_spec.rb
spec/quality_spec.rb
spec/runtime/inline_spec.rb

The problem was that `bundler/inline` would fail when `$BUNDLE_BIN` was set.
Closes #5847.
My diagnosis was we needed to skip installing binstubs when doing an inline install.
My fix sets a temporary setting for `:inline` and skips installing binstubs when that's true.
I chose this fix because it was minimally intrusive.

[Inline] Work when BUNDLE_BIN is set

---

lib/bundler/compact_index_client/updater.rb
spec/install/gems/compact_index_spec.rb
spec/support/artifice/compact_index_partial_update.rb

Previously, Bundler was requesting partial response ranges for the Rubygems compact index that could be empty. Since Rubygems was [ignoring the `ETag` header](https://github.com/rubygems/rubygems.org/pull/1652) for these requests, empty ranges would occur whenever the versions index (for instance) hadn't been modified since the version Bundler currently had cached. When this happened, Rubygems would respond with a 416 (Range Not Satisfiable). Bundler would treat this as a `Bundler::HTTPError`, and fall back to using `Fetcher::Dependency` for dependency info. Sadly, that meant metadata about what Ruby version each dependency required was no-longer checked, and updates for gems which should be limited by the system Ruby version were failing.
Closes #5373.
See above
This PR updates the range …

Avoid Range Not Satisfiable errors during normal request flow

---

lib/bundler/feature_flag.rb
lib/bundler/rubygems_integration.rb
lib/bundler/settings.rb
spec/runtime/setup_spec.rb

The problem was Bundler 1 accidentally made `Kernel#gem` public, even though RubyGems declares it as private. Oops. We tried to make it private in 1.13, it broke stuff, so we added in a hack to keep it public.
My diagnosis was we could delete that hack in 2.0.
My fix implements a feature flag that skips making `Kernel#gem` public, and adds regression tests for `gem` or `require` accidentally being made public.

Make Bundler.setup not make Kernel#gem public in Bundler 2

---

spec/support/rubygems_ext.rb

The problem was the specs were broken by the release of `rack-test 0.7.0`.
My diagnosis was `rack-test` has intentionally dropped 1.8.7 support, though we didn't catch that immediately because they didn't put a `required_ruby_version` in their gemspec.
My fix pins us to older versions of the gem.

Limit specs to rack-test < 0.7.0 for Ruby 1.8.7 compatibility

---

lib/bundler/installer/parallel_installer.rb

The problem was that when installation failed due to a corrupted lockfile or checksum mis-match, we wouldn't show the reason that gem was being installed in the first place, as we would when other errors happened.
See https://github.com/bundler/bundler/issues/5846
My diagnosis was we needed to show that requirement tree whenever installation fails, regardless of the reason for the failure.
My fix rescues hard installation errors and re-raises with the tree appended.

[ParallelInstaller] Show require tree when a gem fails to install due to corrupted lockfile

---

lib/bundler.rb
lib/bundler/cli/check.rb
lib/bundler/cli/install.rb
lib/bundler/cli/outdated.rb
lib/bundler/definition.rb
lib/bundler/feature_flag.rb
lib/bundler/injector.rb
lib/bundler/installer.rb
lib/bundler/runtime.rb
lib/bundler/settings.rb
man/bundle-config.ronn
spec/bundler/settings_spec.rb
spec/commands/add_spec.rb
spec/commands/check_spec.rb
spec/commands/inject_spec.rb
spec/commands/outdated_spec.rb
spec/commands/package_spec.rb
spec/commands/update_spec.rb
spec/install/deploy_spec.rb
spec/quality_spec.rb

The problem was bundler had a `--deployment` flag, a `--frozen` flag and a `frozen` setting. All frozen meant was the lockfile couldn't change, whereas `--deployment` meant the full "deployment experience". This was confusing.
Closes https://github.com/bundler/bundler/issues/4619.
My diagnosis was  we want to get rid of the `--frozen` setting and add a new `deployment` setting that will be used by default on Bundler 2.
My fix adds the deployment setting, and updates the myriad places we use `Bundler.settings[:frozen]` to take it into account, along with fixing the behavior when `bundle config deployment true` is used instead of the command line switches.

[2.0] Use deployment instead of frozen as a setting on Bundler 2

---

lib/bundler/cli.rb
man/bundle.ronn
spec/other/major_deprecation_spec.rb

I understand that `bundle show` will be removed in Bundler 2.0, not `bundle list`. 
https://github.com/bundler/rfcs/pull/6/files#r125875779
In the current message, there is a possibility of misleading the command which will be removed in Bundler 2.0.
I think that it is better to display `bundle show` instead of `bundle list` in the deprecated warning.
Change the deprecated warning from `bundle list` to `bundle show`.
I thought that changing the console message was a simple and effective change to the end user.

Change deprecation from `bundle list` to `bundle show`

---

lib/bundler.rb
lib/bundler/installer.rb
lib/bundler/process_lock.rb
spec/install/process_lock_spec.rb

As per #5851 multiple concurrent bundle installs would cause failures when compiling
As described in #5851 a sample project was created demonstrating the issue when running a docker-compose solution of 2 containers using a gem cache volume
The fix is to implement an installation process lock so that only one process can execute an install at one time
I chose this fix because it was discussed in #5851 as a possible solution

Adding process lock for bundle install operations

---

task/release.rake

The problem was changes to the versions file on the `master` branch would cause checkout to fail

[Rakefile] In a patch release, change version after checkout

---

spec/bundler/cli_spec.rb

The problem was I merged in a change necessary to keep the 1.15.x specs passing accidentally, even though it broke the 2.0 spec. Oops.

Fix spec on 2.0 broken with the v1.15.2 merge

---

lib/bundler/endpoint_specification.rb
spec/bundler/endpoint_specification_spec.rb

Attempting to compare endpoint specifications that didn't have any extensions was causing a `NoMethodError: undefined method `empty?' for nil:NilClass` error.
The `extensions` method on `EndpointSpecification` was incorrectly returning `nil` when there were no extensions.
~~Return an empty array in that case, instead~~ Fall back to the base class implementation in that case, instead.
~~Alternative would be to call `super`. I presumed there was a reason that wasn't being done already, but it would also work.~~ Alternative would be to explicitly return an empty array, but all other methods call `super`, which feels more robust.

Return an empty array if no extensions are found

---

lib/bundler/inline.rb
lib/bundler/installer.rb
lib/bundler/installer/parallel_installer.rb
spec/commands/install_spec.rb

The problem was that a "no-op `bundle install`", defined as a user running `bundle install` when `bundle check` would have succeeded was taking roughly 4 times as long as `bundle check`.
Closes #5842.
My diagnosis was that there were a few different bottlenecks:
- loading plugins
- using `Bundler::Worker` when the work done in that workers block would finish nearly instantly
- some unoptimized code in the parallel installer
My fix avoids the bottlenecks by checking if the `install` is guaranteed to be a no-op and short-circuiting all but the core `install` method, which in turn will now avoid the `Bundler::Worker` overhead and quickly cache gems when needed.
I chose this fix because it succeeded in speeding up no-op installs by a _huge_ margin.
This _should_ make `install` nearly as fast …

Speed up no-op installs

---

lib/bundler/templates/newgem/gitignore.tt

This will be followed up with a documentation PR on some best practices to keep gems tested against up to date dependencies. 
The problem was that sometimes open source contributors get discouraged because they can't setup the project they want to contribute to easily. 
My diagnosis was that a lot of projects gitignore `Gemfile.lock` just because it's gitignored by default in the new gem template. This causes `bundle install` to no longer be guaranteed to work. And `bundle install` is usually the first step towards a contribution.
My fix was to remove the `Gemfile.lock` entry from the gitignore template.
I chose this fix because to prevent a file from being gitignored, removing it from the `.gitignore` file usually does the trick :)

Stop gitignoring Gemfile.lock in default template

---

lib/bundler/cli.rb
spec/bundler/cli_spec.rb

The problem was the outdated bundler version warning could be printed when running a command whose output should be parseable.
@schneems pointed this out on twitter
My diagnosis was parsable commands needed to have such extraneous output suppressed.
My fix was to use the blacklist from printing the running command to bail out on the outdated bundler version warning as well.
I chose this fix because it means we can have a single list of parseable command.

[CLI] Dont print an outdated version warning when running a parseable command

---

lib/bundler/yaml_serializer.rb
spec/bundler/yaml_serializer_spec.rb

The problem was that empty strings in YAML were being read in as empty hashes.
Closes https://github.com/bundler/bundler/issues/5881.
My diagnosis was we needed to fix the YAML Serializer to understand `""` as an empty string.
My fix ensures that a hash isn't created when the parser encounters `""`.

[YAMLSerializer] Handle empty strings properly

---

lib/bundler/rubygems_integration.rb

The problem was `Bundler.rubygems.use_gemdeps` would raise a missing constant error.
My diagnosis was we needed to require the gemdeps file
My fix requires the gemdeps file.
I chose this fix because watching autocorrect struggle to understand that `gemdeps` is not the same as `genders` is priceless.

[RubyGemsIntegration] Require bundler/gemdeps before using it

---

README.md

- I haven't seen anywhere in Bundler's documentation any instructions on how to uninstall bundler.
- I added instructions to `gem uninstall bundler` in the README 👌🏼
My fix...
- I know it's unlikely for someone to want to uninstall bundler, but I still think it's worthwhile to have instructions for this somewhere in the docs.
- I made a new section in the README and put it underneath the _Installation and usage_ section, because I thought it made the most logical sense to place it there. I didn't place it anywhere in the [bundler.io](http://bundler.io/docs.html) site. Please let me know if I …

Add uninstallation instructions to Readme

---

man/bundle-binstubs.ronn

Added a paragraph that explains what binstubs is and how it works, per feedback from @arbonap.
The problem was...without an explanation of what binstubs is and what it does, it's difficult for 
users to understand where to apply the binstubs command. Shout out to @arbonap for calling this out!
My diagnosis was...to take a wonderful explanation given by @indirect about what binstubs are and turn it into a paragraph! 😄 
My fix...is two intro paragraphs in the "DESCRIPTION" section, before going into what the command does.
I chose this fix because...explanations help users 👍

Adding graphs explaining binstubs

---

man/bundle-config.ronn

Added a sentence in line 291 re: CGI escaping passwords and usernames. Resolves issue: https://github.com/bundler/bundler/issues/5643
The problem was needing to make it clear that users had to CGI escape usernames and passwords before pushing to remote. Referenced here: https://github.com/bundler/bundler/issues/5643
My diagnosis was to add a sentence to the man page as a reminder.
My fix was to add a sentence to the man page :)
I chose this fix because it would make things clearer for users.

Add line re: CGI escape

---

man/bundle-exec.ronn

Hey team,
I've added a graph to the documentation that explains why bundle exec makes changes to Gemfile.lock. It was originally referenced in this issue: https://github.com/bundler/bundler/issues/5245
The problem was lack of clarity around why the `bundle exec` command modified the lock file. A user brought it up here: https://github.com/bundler/bundler/issues/5245 and the determination was to add it to the man page.
My diagnosis was to add a graph in the "Environmental Modifications" section to explain the issue.
My fix was to update the docs! \o/
I chose this fix because enough users referenced it as a problem that needed to be addressed.

Add graph re: bundle exec modifying lockfile

---

spec/resolver/basic_spec.rb
spec/support/indexes.rb

Bundler-specific version of https://github.com/CocoaPods/Resolver-Integration-Specs/pull/12. We didn't have any specs for resolving pre-release versions before, and I'm nervous about https://github.com/CocoaPods/Molinillo/pull/69 breaking this when introduced.

Add spec for prerelease dependency resolution

---

man/bundle-install.ronn

- I noticed the flag options for the `bundle install` docs weren't alphabetized.
- Also, at the end of the `bundle install` page, I created links to the RubyGems docs regarding the `gem install` command.
- I asked around and found out the flags weren't ordered by importance or anything like that, so I decided to alphabetize them. 
My fix...
- I alphabetized the flags on the `bundle install` page ✨
- Hopefully this can help users more quickly find the `bundle install` flag they want to read up on. 🙌🏽

Alphabetize install flags; add links to Rubygems docs

---

.rubocop_todo.yml
lib/bundler/dsl.rb
spec/bundler/dsl_spec.rb

Users are allowed to add a gem to the Gemfile with an empty string as the name but Bundler won't find a gem with an empty and does not make this clear as possible to the end user. Using a Gemfile like:
```
gem '', git: 'https://github.com/rack/rack'
```
Bundler will print the following:
```
› dbundler install
Fetching https://github.com/rack/rack
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.org/...
Could not find gem '' in https://github.com/rack/rack (at master@8693330).
The source does not contain any versions of ''
```
Check the name of the gem in the DSL. If the name is empty print a clear message to the user that using an empty name is not allowed …

Add clear error message when using a gem in the Gemfile with an empty name

---

man/gemfile.5.ronn

- I thought the `bundle-install` and `gemfile` docs could have more background explanations.  
- Given more clarifying background information regarding some Ruby-specific domain knowledge, this can help those newer to the Ruby community. ♦️
My fix...
- I gave a general overview of various Ruby implementations, and explained what git submodules and gemspecs are.
- @rubymorillo and @indirect gave me the go-ahead to give more background information about these topics 👍🏽 
- please let me know what y'all think, I'm happy to incorporate edits

Add more background explanations to bundle-install and gemfile docs

---

lib/bundler.rb
lib/bundler/source/git.rb
spec/commands/clean_spec.rb
spec/install/gemfile/git_spec.rb

Closes https://github.com/bundler/bundler/issues/5895.
The problem was:
> Now that we have a "global" user-wide cache of gems, it would be great to also have a user-wide place to keep git repos. In 1.x, the default system path provided that user-wide cache, and losing it because of the default 2.0 path will slow down installs with git repos by a lot.
My diagnosis was we needed to change the git cache location to something global
My fix uses the global "~/.bundle/cache" directory to cache git gems
I chose this fix because it means the cache (which only contains _downloaded_ information, nothing evaluated at runtime) can be shared across every app and every ruby version

[Source::Git] Cache repos globally

---

bin/bundle2
task/bundler_2.rake

The problem was it was too difficult to run Bundler in 2.0 mode.
My diagnosis was we needed a way to install a dev version of 2.0, and also to run commands as bundler 2.
My fix adds a `bin/bundle2` bin stub that runs bundler as 2.0.0.dev, and a `bundle_2:install` rake task that will install `bundler-2.0.0.dev`

Add tasks to make running in 2.0 mode easier

---

man/bundle-gem.ronn
man/bundle-install.ronn
man/bundle-outdated.ronn
man/bundle-update.ronn
man/bundle-viz.ronn
man/bundle.ronn

- I noticed in the documentation that a lot of aliases for flags were missing.
- I added missing aliases for flags into the documentation. 
My fix...
- I added the missing flag aliases into the docs, so that users can more easily access this information. 💖
- I also added in a line describing how RSpec is the default testing framework 
- more bundler knowledge for bundler users is helpful 🍒

Add missing flag aliases to docs 🌟

---

lib/bundler/cli.rb

- I was looking at the `bundle outdated` command in `cli.rb`, and noticed some flag aliases were the same as the original flags.
- I thought these aliases weren't necessary
My fix...
- I deleted two aliases from `bundle outdated`.
- I ran `rake spec:deps && bin/rspec spec/commands/outdated_spec.rb` locally and all tests passed.
- to DRY up `cli.rb` 👌🏼

Delete redundant aliases from bundle outdated command 💫

---

lib/bundler/templates/newgem/newgem.gemspec.tt

When using `bundle gem` to create a new gem, the created gemspec file starts with 
```
lib = File.expand_path('../lib', __FILE__)
```
Rubocop recommends having a blank line after magic comments (like `# coding: utf-8`).
The rubocop style guide recommends having a blank line after "magic comments" ([see link](https://github.com/bbatsov/ruby-style-guide#separate-magic-comments-from-code)).   The main bundler.gemspec follows this recommendation, but the .gemspec, that is created for new gems, does not.
Update the template file to have a blank line after the magic comment.
It's what rubocop wants.

Add new line after newgem gemspec template

---

lib/bundler/definition.rb
lib/bundler/dsl.rb
lib/bundler/env.rb
spec/bundler/dsl_spec.rb
spec/bundler/env_spec.rb
spec/install/gemfile/eval_gemfile_spec.rb

The problem was we'd get error reports like https://github.com/bundler/bundler/issues/5381 where the env output was insufficient to reproduce the issue because `eval_gemfile` had been used.
My diagnosis was we needed to print out all gem files that had gone through `eval_gemfile`
My fix keeps track of all eval'ed gem files and prints them all out in the env report.

[Env] Print all gemfiles that have been evaled

---

lib/bundler/cli.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
man/bundle-config.ronn
spec/bundler/cli_spec.rb
spec/commands/version_spec.rb

(Fix #4706)
The behavior was different from [Bundler 2 RFC](https://github.com/bundler/rfcs/pull/6/files#diff-0579edc0374571613cd01f0a42c19bdaR38).
When it is `bundler_2_mode`, it behaves as written in RFC.
This PR will switch `Bundler.feature_flag` using `bundler_2_mode`.
Since #4708 does not use `Bundler.feature_flag`, then compatibility with Bundler 1 will be lost.
In addition, this PR adds specs for Bundler 2.

[2.0] Print only version number from `bundler --version`

---

doc/development/SETUP.md

- I was looking through `SETUP.md` and I didn't understand why I had to set the `RUBYOPT` env variable to `-rpry dbundle`. I was wondering why I couldn't just normally use `require 'pry'; binding.pry` to debug Bundler's codebase.
- To add more explanations to the Setup documentation.
My fix...
- I asked @indirect and @jules2689 all about `RUBYOPT`, and why we have to set `RUBYOPT` to require pry and require this path to Bundler. I used their wonderful explanations and tried synthesizing their knowledge in a way that made sense to those who aren't familiar with `RUBYOPT`. I also included background context as to why Bundler …

Explain RUBYOPT in Debugging section of Setup docs

---

doc/documentation/WRITING.md

- I was updating documentation in a `.ronn` file. I struggled a bit when I tried testing my doc changes. When I tried running `rspec ./spec/commands/help_spec.rb` and `rspec ./spec/quality_spec.rb`, I kept getting this error: 
```
uninitialized constant Bundler::EnvironmentPreserver::BUNDLER_PREFIX (NameError)
Did you mean?  Bundler::BundlerError
```
- @colby-swandale told me that I should run`bin/rspec` instead of `rspec`. It worked 🎈
My fix...
- To add in `bin/rspec` to the ["Writing docs for man pages" documentation](https://github.com/bundler/bundler/blob/master/doc/documentation/WRITING.md) …

Include `bin/rspec` in directions to test doc changes

---

lib/bundler/templates/gems.rb

Building from source using `rake bundler_2:install`. (#5901)
```console
% bundle version
2.0.0.dev (2017-08-02 commit f184adfc1)% cd /tmp
% bundle init
Writing new gems.rb to /private/tmp/gems.rb
% cat gems.rb
source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
```
Editing the comment out of `# gems "rails"` and executing it resulted in an error.
```console
% bundle install
[!] There was an error parsing `gems.rb`: Undefined local variable or method `gems' for Gemfile. Bundler cannot continue.
#
>  gems "rails"
```
[Like the Gemfile](https://github.com/bundler/bundler/blob/c4ae85f01edca72d48c617be07440c2cd600ab4f/lib/bundler/templates/Gemfile#L7), use `gem` method.
Use `gem` method instead of `gems` method.

Fix the tempalte of gems.rb

---

man/bundle-gem.ronn

- This resolves [Issue#296](https://github.com/bundler/bundler-site/issues/296) on bundler/bundler-site. 
- @olleolleolle came across a broken link in the `bundle gem` docs. Specifically, the `bundle-config` link in the "See Also" section was broken.
My fix...
- I fixed the broken link 🍒
- To make navigating around the bundler docs a pleasant experience.

Update broken link in bundle-gem man page

---

doc/TROUBLESHOOTING.md
doc/contributing/BUG_TRIAGE.md

- I asked about how to go about triaging bugs in bundler. To what extent should contributor's env try to match the user's env?
- To include more strategies of how to triage bugs
My fix...
- I added some documentation to synthesize the response's that I got from the Bundler Slack group on how people go about triaging. Specifically, I asked how contributors go about incorporating the user's environment into their own when debugging. 
- Hopefully this additional documentation can help squash more bugs 🕷
- Let me know what y'all think, always happy to incorporate changes.

Add Bug Triage Strategies 🐞

---

man/bundle-config.ronn

I documented the env var for the init new gem file feature flag incorrectly
› BUNDLE_NEW_GEMFILE_NAME=1 dbundler init
Writing new Gemfile to /Users/c/Desktop/Projects/testapp/Gemfile
does not generate the gems.rb as expected
Use the correct env name to generate gems.rb

fix documented init gems rb config env var

---

man/bundle-pristine.ronn

- I didn't know in what situations it was practical to use `bundle pristine`.
- To write more docs for [bundler.io](bundler.io) and the man pages
My fix...
- To add more documentation regarding what practical situations a developer can use `bundle pristine`. 
- Also, I added some explanation between the differences between `bundle pristine` and `gem pristine --all`
- Added a note that `pristine` doesn't work for local gems
- Hopefully with a practical example of when to use `bundle pristine`, bundler's users can use this command more ✨

Add more explanations to `bundle pristine`

---

lib/bundler/cli.rb
lib/bundler/cli/list.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
man/bundle-config.ronn
man/bundle-list.ronn
spec/commands/list_spec.rb

We're removing the `bundle show` command (which has been replaced with `bundle info`) but we should probably still have a command to list the gems in the bundle.
`bundle show` has been marked as deprecated but a replacement for listing gems does not yet exist
Add a new `bundle list` (including `ls` alias) that prints the gems in the bundle, this was taken from #4754

implement new list command

---

lib/bundler/rubygems_integration.rb
spec/bundler/rubygems_integration_spec.rb

`Gem::RemoteFetcher::FetchError` failures were not being retried when downloading gems. Retrying downloading of gems for network blips is very ideal and helpful in CI environment.
- The retry logic that existed (using `Bundler::Retry`) for `Bundler::RubygemsIntegration#download_gem` was not getting called, becase `Bundler.rubygems` defaulted to a sub class of `Bundler::RubygemsIntegration::MoreFuture`, which inherited from `Bundler::RubygemsIntegration::Future` and `#download_gem` in there didn't perform download with retry logic.
- Sending `Gem::RemoteFetcher::FetchError` as an argument to `Bundler::Retry` meant, `Bundler::Retry` would fail first thing,[ if exception being raised was the one being supplied](https://github.com/bundler/bundler/blob/5a61b65ad5ec1df1539ecf8bc5d124f2b254ba14/l …

Retry downloading gems consistently across all versions of RubyGems

---

lib/bundler.rb

(Follow up of #2884)
It seems that [the PR](#2884) written in [Bundler 2 RFC](https://github.com/bundler/rfcs/pull/6/files#diff-0579edc0374571613cd01f0a42c19bdaR30) is not included in master.
It applies to master branch based on the PR implementation written in RFC.
This PR will switch `Bundler.feature_flag` using `bundler_2_mode`.
Since #2884 does not use `Bundler.feature_flag`, then compatibility with Bundler 1 will be lost.

[2.0] Don't create gem home before setting it

---

doc/documentation/README.md
doc/documentation/WRITING.md

- When trying to add documentation for [bundler.io](bundler.io), I was confused as to what files I should exactly add my changes.
- I asked around in Bundler's slack what file I should edit to make doc changes for bundler.io. 
My fix...
-  I added documentation that explains how editing `.ronn` files from `bundler/bundler` is all you need to update documentation about primary commands and utilities on the [bundler.io](bundler.io) site. I explained how it's not necessary to touch files from `bundler/bundler-site`. 
- Hopefully this will alleviate some confusion surrounding how to contribute to …

Explain how to write docs for bundler.io

---

.rubocop.yml
lib/bundler/definition.rb
lib/bundler/settings.rb
lib/bundler/source.rb
lib/bundler/source/path.rb
lib/bundler/source/rubygems.rb
lib/bundler/source_list.rb
man/bundle-config.ronn
spec/install/deploy_spec.rb

This is my first PR to bundler, so if something is out of place let me know and I'll do my best to correct it.
The issue I'm trying to fix is allowing to change a remote on a frozen bundler for the same remote adding username and password.
In our dev boxes we have configured bundle to store the username and password for a given domain, but on our qa boxes we don't want to do that for various reasons.
As far as I can tell this should not have any negative side effects as we are keeping the same remote but only adding some auth to it

Allow to add username and password to a remote during a deployment

---

lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb

fixes #5485
Bundler does not work with paths that contain the path separator.
The ```bundle_bin``` path can't contain a path separator.
We can validate the ```bundle_path``` to make sure that it does not contain the
current ```File::PATH_SEPARATOR```. If we find the path separator, we exit with a non-zero
code and give the user an error message. 
I chose this fix because it was recommended by @colby-swandale.

exit if bundle bin path contains a path separator

---

lib/bundler/cli/update.rb
spec/commands/update_spec.rb

The problem was you could run `bundle update foo bar` and it would be possible that either `foo` or `bar` not move to a newer version.
My diagnosis was we should tell users when this happens!
My fix warns when a locked bundle has `bundle update` called with an explicit list of gems and one of those gems could not actually be _updated_.
I chose this fix because it didn't require mucking around with the resolved.

[Update] Warn when an explicitly updated spec does not get a newer version

---

lib/bundler/cli.rb
spec/bundler/cli_spec.rb

The problem is once users start using our new `bin/bundle` binstub or the RubyGems that helps lock to the bundler version in the lockfile, the outdated bundler version warning was outdated.
My diagnosis was we needed to tell people to `bundle update --bundler`, and restrict the `gem install` suggestion to when the latest version indeed wasn't installed.
My fix takes into account the actual installed bundler versions.
@indirect I think this addresses your concern on the RG PR?

[CLI] Suggest bundle update --bundler when a newer version is installed

---

bundler.gemspec

What was the end-user problem that led to this PR?
--------------------------------------------------
I noticed while doing a `bundle open bundler` (inception!) that we have included the `bin/` directory in the packaged gem.  While this is not hurting anything, it provides a bunch of scripts that won't function properly in any capacity when installed through ruby gems.
While doing that, I noticed that the dotfiles for CI were also packaged up in the gem, so I made sure to only include specific files from there that seemed to provide value when being shipped as a gem.
What is your fix for the problem, implemented in this PR?
---------------------------------------------------------
Change the reduction of the results from `git ls-files` to be a whitelist instead of a blacklist.  This was …

Remove uneeded files packaged into bunder's gem build on rubygems

---

lib/bundler/fetcher.rb
spec/bundler/fetcher_spec.rb

The problem was having to configure ssl client cert and ca cert in bundler and gem.
My fix makes bundler check the gem configuration for these settings.
I chose this fix because it makes sense for the user to only configure these once.
Couldn't find existing coverage for this in the tests so haven't added any...
Also assume a changelog entry is needed but can't see a unreleased changes section so not sure how this is handled.

Use ssl client cert and ca cert settings from gem configuration as fallbacks

---

lib/bundler/cli/pristine.rb
spec/commands/pristine_spec.rb
spec/support/builders.rb

Fixes bundler pristine to respect the `bundle config` options for particular gems.  In my particular case, on OSX I have a keg version of `pg` and a bundle config with the following entry:
```console
$ bundle config
...
build.pg
Set for the current user (/Users/nicklamuro/.bundle/config): "--with-pg-config=/usr/local/Cellar/postgresql@9.5/9.5.6/bin/pg_config"
```
This would not be respected
What was the end-user problem that led to this PR?
--------------------------------------------------
See above, but steps to reproduce (requires `bundler` >= 1.15):
1. Install postgres on your machine if it is not already there (OS dependent)
2. Add the following bundler build arg for `pg`:
```console
$ bundle config build.pg -- --with-pg-config=$(which pg_config)
```
2. Make sure `pg_config` is not …

Use Bundler::Installer for bundle pristine

---

Rakefile

What was the end-user problem that led to this PR?
--------------------------------------------------
When following the [setup documentation](https://github.com/bundler/bundler/blob/master/doc/development/SETUP.md) for bundler, it suggests to run `bin/rake spec:deps` to install the development dependencies for bundler.
Doing this with ruby 1.9.3 (and not upgrading rubygems) will cause this to fail.
What was your diagnosis of the problem?
---------------------------------------
Ruby 1.9.3 ships with a version of rubygems that is less than 2.0, and doesn't include the mechanisms for installing multiple gems (with specific versions) using colon delimited strings (which is the mechanism used to do so in `spec:deps`).
What is your fix for the problem, implemented in this PR? …

Use universal rubygems method for installing gems

---

lib/bundler/rubygems_gem_installer.rb
lib/bundler/rubygems_integration.rb
lib/bundler/source.rb
lib/bundler/source/git.rb
lib/bundler/source/path.rb
lib/bundler/source/path/installer.rb
lib/bundler/source/rubygems.rb
spec/install/global_cache_spec.rb
spec/support/builders.rb

The problem was with the switch to defaulting the install path to `./.bundle`, you'd need to rebuild extensions for each app you use a gem in.
Closes #5905 
My diagnosis was we could globally cache built extensions in a per-ruby, per-source directory, similar to how 2.0 global `.gem` caching and the git cache works.
My fix implements that cache.

[2.0] Globally cache built extensions for RG & Git sources

---

bundler.gemspec
lib/bundler.rb
lib/bundler/compatibility_guard.rb
lib/bundler/inline.rb
lib/bundler/shared_helpers.rb
spec/install/bundler_spec.rb
spec/lock/lockfile_bundler_1_spec.rb
spec/lock/lockfile_spec.rb
spec/other/compatibility_guard_spec.rb
spec/runtime/with_clean_env_spec.rb
spec/support/hax.rb
spec/support/helpers.rb

This way, if someone manages to get bundler 2 installed on a system we don't support, they'll get a very obvious message saying so

[2.0] Add a compatibility guard that prints friendly errors on bundler 2+

---

lib/bundler.rb
spec/bundler/bundler_spec.rb

fixes #5958.
The problem was that local variables are magically introduced into the global toplevel, when there is a local gemspec that has such local variables.
My diagnosis was that `TOPLEVEL_BINDING` is used with `eval`
My fix is to duplicate that binding.
I chose this fix because it is clean and concise.  Other possible options are like reinventions of wheel.

Avoid namespace pollution

---

lib/bundler/cli/update.rb
lib/bundler/definition.rb
lib/bundler/installer.rb
spec/commands/update_spec.rb

The problem was `bundle update --bundler` went through the full update/resolution path when really we just want to pin to a different bundler version.
My diagnosis was we should just update the lockfile, without threading the rest of the process like an update.
This implements what @indirect requested in https://github.com/rubygems/rubygems/pull/1977#issuecomment-322852799.

[Update] Avoid a normal update when running with only --bundler

---

lib/bundler/templates/Executable.bundler
spec/commands/binstubs_spec.rb
spec/support/rubygems_ext.rb

The problem was the bin stub would lock to a specific version even for a 1.x version, which was an incompatible change.
See @indirect's comment in https://github.com/rubygems/rubygems/pull/1977#issuecomment-322852799
My diagnosis was we needed to only pin to a specific version for 2.0+.
My fix transforms any 1.x bundler version to a "< 2" constraint.

When the locked bundler is under 2.0, allow any version < 2

---

lib/bundler/cli/binstubs.rb
man/bundle-binstubs.ronn
spec/commands/binstubs_spec.rb
spec/commands/install_spec.rb

Currently, specifying the `--standalone` flag breaks `bundler binstubs` unless you have the `path` setting set in your bundle config. This is breaking in different ways but mostly for the same reason.
Bundler Master:
```
RuntimeError: Can't standalone without an explicit path set
/Users/c/Desktop/Projects/bundler/lib/bundler/installer.rb:158:in `generate_standalone_bundler_executable_stubs'
/Users/c/Desktop/Projects/bundler/lib/bundler/cli/binstubs.rb:36:in `block in run'
/Users/c/Desktop/Projects/bundler/lib/bundler/cli/binstubs.rb:26:in `each'
```
Bundler 1.15.4:
```
TypeError: no implicit conversion of nil into String
/Users/c/.rubies/ruby-2.4.1/lib/ruby/2.4.0/pathname.rb:409:in `initialize'
/Users/c/.rubies/ruby-2.4.1/lib/ruby/2.4.0/pathname.rb:409:in `new' …
```

Fix bundle binstubs stanadlone flag

---

lib/bundler/fetcher.rb
lib/bundler/vendored_persistent.rb
spec/bundler/vendored_persistent_spec.rb

Right now, output looks like
```
Your Ruby version does not support TLSv1.1 or newer, which will be required to connect to https://index.rubygems.org by June 2018.
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 11.3.0
Using automatiek 0.1.2 from source at `.`
Using rspec-support 3.5.0
Using diff-lcs 1.3
Using bundler 1.15.0.pre.3
Using rspec-core 3.5.4
Using rspec-expectations 3.5.0
Using rspec-mocks 3.5.0
Using rspec 3.5.0
Bundle updated!
```
Obviously this requires tests, and also backing out forcing the TLS version (which I did to make testing easier). The message could also use improvement, but I figured I'd ask for input from @indirect and @dwradcliffe

Warn when making an outdated TLS connection to rubygems.org

---

lib/bundler/cli.rb

What was the end-user problem that led to this PR?
--------------------------------------------------
When taking a look at the output that was shown when doing `bundle cli_help`, half of the output for describing the `bundle pristine` command is truncated.
What was your diagnosis of the problem?
---------------------------------------
My diagnosis was that we had to long of a "basic description" (`desc`) for the `bundle pristine` command.
What is your fix for the problem, implemented in this PR?
---------------------------------------------------------
Convert the existing `desc` to a `long_desc`, and provide a shorter one for `desc`.
Why did you choose this fix out of the possible options?
--------------------------------------------------------
I chose this fix because it retained the …

Convert pristine command desc to long_desc

---

lib/bundler/cli.rb
lib/bundler/cli/add.rb
lib/bundler/cli/binstubs.rb
lib/bundler/cli/common.rb
lib/bundler/cli/info.rb
lib/bundler/cli/install.rb
lib/bundler/cli/lock.rb
lib/bundler/cli/open.rb
lib/bundler/cli/outdated.rb
lib/bundler/cli/pristine.rb
lib/bundler/cli/show.rb
lib/bundler/cli/update.rb
lib/bundler/feature_flag.rb
lib/bundler/index.rb
lib/bundler/settings.rb
man/bundle-config.ronn
spec/commands/clean_spec.rb
spec/commands/exec_spec.rb
spec/commands/outdated_spec.rb
spec/commands/update_spec.rb
spec/install/allow_offline_install_spec.rb
spec/plugins/source/example_spec.rb
spec/support/command_execution.rb
spec/update/git_spec.rb

The problem was with the switch to defaulting to a local install in 2.0, we're concerned about taking up too much disk space.
My diagnosis was we'd like to run `bundle clean` when possible.
Closes https://github.com/bundler/bundler/issues/5875.
My fix runs `clean` automatically on 2.0 when a `path` has _not_ been set.
I chose this fix because it avoids the possibility of accidentally cleaning a shared location.

[2.0] Automatically bundle clean without a path set

---

lib/bundler/cli.rb
spec/bundler/cli_spec.rb
spec/commands/newgem_spec.rb

The problem was the new help output for `bundle` was very verbose and unorganized, making it look a bit like work vomit.
My diagnosis was we should 
Closes https://github.com/bundler/bundler/issues/5963.
My fix prints the full version info, as well as grouping the commands into `primary` and `utility` as done in the man pages.
I chose this fix because it makes the output pleasing to visually parse.
```
$ bundle
Bundler version 1.15.4 (2017-08-25 commit 3203fdd2a)
Bundler commands:
Primary commands:
bundle install [OPTIONS]    # Install the current environment to the system
bundle update [OPTIONS]     # Update the current environment
bundle package [OPTIONS]    # Locks and then caches all of the gems into vendor/cache
bundle exec [OPTIONS]       # Run the command in context of the bundle …
```

[CLI] Prettify the output in cli_help

---

lib/bundler/rubygems_integration.rb
lib/bundler/shared_helpers.rb
spec/bundler/shared_helpers_spec.rb

Closes #5975. The problem was that recent code to detect a bad bundle_path by looking for the PATH_SEPARATOR character broke when running from a war file generated by jruby's warbler.
My diagnosis was that the path separator used was not appropriate in this circumstance.
My fix implements the suggestion from @segiddins to use the same path splitting logic used by RubyGems under jruby to determine if the bad path is present.
I chose this fix because it provides a way to detect the original problem that is consistent with the handling within RubyGems.

Support bundle_path used by war files generated with jruby's warbler

---

man/bundle-package.ronn

I need to package gems for deployment but don't want to install them on the local system. 
The behaviour is a part of bundler but it is not documented anywhere in man pages or the bundler site. To find the answer, one has to look at issues that were closed a few years ago.
I've updated the man page for the `bundle package` command. Hopefully, this will trickle down to bundler site pages for package command whenever CI publishes it. 
Followed the doc [here](https://github.com/bundler/bundler/blob/master/doc/documentation/WRITING.md) to run tests.
It felt appropriate to document a flag available on a CLI in its help pages.

Add documentation for packaging with --no-install

---

lib/bundler/vendored_persistent.rb
spec/bundler/vendored_persistent_spec.rb

Stubbing Rubygems requests with WebMock was causing `undefined method 'io' for nil:NilClass` errors when using Bundler 1.16.0.pre.1
My diagnosis was that the new warning text about old OpenSSL versions didn't consider the case that a connection might not have an `@socket` variable set.
Guard against this by returning early in that case.
I chose this fix because it works, and because `Net::HTTP` itself has some guards in it around `nil` values for `@socket` ([example](https://github.com/ruby/ruby/blob/trunk/lib/net/http.rb#L858-L860)). This isn't my area, though, so it could be that a fix is needed in WebMock, not here...

Handle missing socket when warning about OpenSSL version

---

lib/bundler/definition.rb
lib/bundler/feature_flag.rb
lib/bundler/gem_version_promoter.rb
lib/bundler/resolver.rb
lib/bundler/settings.rb
spec/quality_spec.rb

The problem was @chrismo wants to start delegating all sorting to the GVP.
My diagnosis was to start doing that in 2.0.
Closes https://github.com/bundler/bundler/issues/5993
My fix adds a feature flag.

[2.0] [Resolver] Use the GVP for major updates in 2.0

---

lib/bundler/cli.rb
lib/bundler/cli/config.rb
spec/commands/config_spec.rb

The problem was the current `bundle config` mega-command is hacky and confusing.
My diagnosis was we should add subcommands for `list`, `get`, `set`, and `unset` to make the CLI clearer.
Closes #4600.
My fix implements those subcommands while preserving the current bare `bundle config` command.
I chose this fix because, as opposed to https://github.com/bundler/bundler/pull/5507, we can keep the existing command in for a little while to help ease the transition.
@denniss how do you feel about this compared to your PR?

[2.0] Implement config subcommands

---

lib/bundler/gem_helper.rb
spec/bundler/gem_helper_spec.rb

When running the `release` task, bundler didn't know anything
about the RUBYGEMS_HOST environment variable that rubygems respects when
doing a gem push.  This resulted in incorrect messaging, as environments
where this was set without an `allowed_push_host` configured would
message that the gem had been pushed to rubygems.org, when in fact it
was pushed elsewhere.
Bundler was hardcoding `rubygems.org` in the event that an `allowed_push_host` setting was not specified, and didn't know anything about the `RUBYGEMS_HOST` env var.
Added a check for that variable and used it before the hardcoded `rubygems.org` if it exists.
I chose this fix because it seemed the most straightforward way to solve the problem.

Respect RUBYGEMS_HOST env var in release messaging

---

lib/bundler/cli.rb
lib/bundler/feature_flag.rb
lib/bundler/settings.rb
spec/commands/viz_spec.rb
spec/quality_spec.rb

The `bundle viz` command is to been removed from bundler 2 and extracted into a plugin
Closes #5180 
Deprecate the `bundle viz` command with an error explaining that a new gem will replace it's functionality.

deprecate the bundle viz command

---

lib/bundler/feature_flag.rb
lib/bundler/installer.rb
lib/bundler/installer/parallel_installer.rb
lib/bundler/settings.rb
spec/quality_spec.rb

Closes https://github.com/bundler/bundler/pull/5808.
The description of that issue, copied verbatim:
This argument comes in two parts, but luckily, the first one is both easier to understand and hopefully to agree with.
Background: Bundler 1.4.0 added support for parallel installation via the `--jobs` param.  Soon after, [this blog post](http://archlever.blogspot.com/2013/09/lies-damned-lies-and-truths-backed-by.html) (probably greatly amplified by [this Thoughtbot blog post](https://robots.thoughtbot.com/parallel-gem-installing-using-bundler)) popularized the recommendation "set `--jobs` to `nproc - 1`".
Not long after, probably also inspired by the popularity of this tip, this "n - 1 jobs" advice got codified into Bundler itself: …

[2.0] Auto-configure job count

---

.travis.yml
Rakefile
lib/bundler/version.rb
task/build_metadata.rake
task/release.rake

Now that we've branched `1-16-stable` and the [2.0 milestone](https://github.com/bundler/bundler/milestone/13) is nearly done, it's time that we target `master` to be Bundler 2.
Until Bundler 2 final is released, I'd like us to keep testing rudimentary 1.x support, to make backporting things to `1-16-stable` easier, but I've severely cut down the matrix. I'm willing to take it upon myself that 1.x stable maintains esoteric Ruby/RubyGems version compatibility now, rather than requiring it from all those who try to contribute to the project (in reality, this just means fixing up `1-16-stable` after back porting and before a release).
@bundler/core: 2.0 is finally happening!

Bump to a Bundler 2 version

---

spec/commands/exec_spec.rb
spec/commands/newgem_spec.rb
spec/commands/show_spec.rb
spec/runtime/with_clean_env_spec.rb
spec/spec_helper.rb
spec/support/artifice/endpoint.rb
spec/support/helpers.rb
spec/support/path.rb

Ruby core needs to change `Spec::Path.root` and gemspec, bin, spec directories structure.
1. I changed spec directory from `spec` to `spec/bundler` because ruby core has rubyspec files under the `spec/rubyspec`.
2. I changed gemspec location to `bundler.gemspec` to `lib/bundler.gemspec`.
ref. https://bugs.ruby-lang.org/issues/12733#note-15
This pull request make we can modify root, gemspec path to flexible locations. After merging this pull request, I will add directory structure of ruby core repository to only `spec/support/path.rb`

Use helper methods for relative path references in the specs

---

spec/quality_es_spec.rb
spec/quality_spec.rb

- Now that Spanish localization is under-way, there are no specs that test the localized documentation.
- To write a test that filters out gender-specific pronouns and "_Well, actually..._"'s and the like in Spanish
My fix...
- I looked at `quality_spec.rb` and took the format from that spec and localized it to be Spanish-specific.
- testing documentation quality should also exist for other languages

Create quality spec for docs in spanish

---

lib/bundler/environment_preserver.rb

This PR adds the environment variable `RB_USER_INSTALL` to the list of preserved keys. That variable is used on FreeBSD.
- see #6013 
Without this change, Bundler's usage of it with the shared helpers to set a preserved env would raise this:
> ArgumentError: new key RB_USER_INSTALL
(This seems to be the only env var which is used but not listed in the preserved keys list.)

Add RB_USER_INSTALL to preserved ENV keys
