rubygems/bundler

CHANGELOG.md
I noticed it wasn't in the changelog from #3270.
Hope this helps.
=> add to changelog

lib/bundler/settings.rb, spec/bundler/settings_spec.rb
HTTParty users can party hard once again.
Fixes #3398
=> Tighten the check for URLs in config keys

lib/bundler/cli/gem.rb
This is an attempt at rebasing #3123 and integrating the recommended changes mentioned in that PR’s comments.
=> prevent naming mistake

lib/bundler/definition.rb, spec/install/gems/sources_spec.rb
Sometimes, it's disappointing to compare the amount of time it took to track down a problem with the amount of code it took to fix it :smile:
=> Fix multi source unlocking

lib/bundler/source/path.rb, spec/install/gemfile/path_spec.rb
Attempts to close https://github.com/bundler/bundler/issues/3286, https://trello.com/c/DQx0OKJl/82-search-for-gemspecs-near-the-root-of-a-git-repo-first
\c @TimMoore
=> [Source::Path] Sort gemspecs by relative depth

spec/resolver/basic_spec.rb, spec/support/indexes.rb
Pull request to add tests issue for https://github.com/bundler/bundler/issues/3459
=> Pull request to add tests for issue #3459

lib/bundler/dsl.rb, spec/bundler/dsl_spec.rb
[Fixes https://github.com/bundler/bundler/issues/3457 and https://github.com/bundler/bundler/issues/3187]
review @segiddins @indirect @andremedeiros 
For more context on the error see my spec, and both issues.
(not sure where the Changelog entry should go, if to 1.8.x or 1.9.x, let me know)
=> Catch and report RuntimeError on Gemfile eval

lib/bundler/dsl.rb, lib/bundler/friendly_errors.rb, spec/bundler/dsl_spec.rb, spec/install/gems/simple_case_spec.rb
Goes hand in hand with https://github.com/CocoaPods/Core/pull/226.
=> [DSL] Add prettier DSL error

lib/bundler/cli.rb, lib/bundler/cli/lock.rb, man/bundle.ronn, spec/commands/lock_spec.rb
Closes https://github.com/bundler/bundler/issues/3437.
This is obviously missing specs, and I doubt I defined all the stuff correctly in `cli.rb`, but it's a start!
=> [Lock] Add lock command

lib/bundler/cli/gem.rb, spec/commands/newgem_spec.rb
=> Apply test framework when install with asks

bundler.gemspec, spec/runtime/gem_tasks_spec.rb
=> [GemTasks] Add a basic spec that the relevant tasks are installed

spec/update/gems_spec.rb
Proves that https://github.com/bundler/bundler/issues/3128 is already addressed :)
=> Add a test that shows that bundle update fails loudly in a frozen bundle

man/bundle-config.ronn
Addresses https://github.com/bundler/bundler/issues/3503.
=> Disable multisource doc

bin/bundle_ruby, spec/other/bundle_ruby_spec.rb
Addresses https://github.com/bundler/bundler/pull/3491.
=> Send bundle_ruby deprecation error to STDERR

lib/bundler/cli/outdated.rb, spec/commands/outdated_spec.rb
Addresses https://github.com/bundler/bundler-features/issues/63. I know the spec is a bit sparse, so let me know if you have suggestions for more specs or parts of specs.
=> Make `outdated` output more "grepable"

lib/bundler/source/git/git_proxy.rb
Attempts to close https://github.com/bundler/bundler/issues/2663.
I have no idea if this is right, I just implemented what @cyphactor suggested.
=> [GitProxy] Try and preserve the umask on git gems

lib/bundler/source/git/git_proxy.rb
=> Revert "[GitProxy] Try and preserve the umask on git gems"

lib/bundler/definition.rb, lib/bundler/lockfile_parser.rb, spec/install/gems/flex_spec.rb, spec/lock/lockfile_spec.rb
Squashed version of https://github.com/bundler/bundler/pull/3485.
=> Track Bundler version in lockfile

lib/bundler/cli.rb, lib/bundler/installer.rb, lib/bundler/source/git.rb, lib/bundler/source/path.rb, lib/bundler/source/rubygems.rb, spec/install/force_spec.rb
Closes https://trello.com/c/baZN0BmP/78-add-bundle-install-force-option.
=> [Installer] Add option to force installation

lib/bundler/installer.rb, lib/bundler/installer/parallel_installer.rb, spec/install/parallel/spec_installation_spec.rb
=> refactor parallel installer

lib/bundler/cli.rb, lib/bundler/fetcher.rb, lib/bundler/retry.rb, lib/bundler/settings.rb, spec/bundler/retry_spec.rb, spec/bundler/settings_spec.rb
Fixes #3583
Works just like you’d expect it to like all settings and is easily config’d with `bundle config`
=> Configurable timeout/retries/redirects

man/bundle-config.ronn
=> add ignore messages documentation

lib/bundler/cli/install.rb, lib/bundler/installer/parallel_installer.rb, lib/bundler/settings.rb, spec/bundler/settings_spec.rb, spec/install/gems/post_install_spec.rb
=> Fix ignore messages

lib/bundler/dependency.rb, lib/bundler/dsl.rb, spec/install/gems/install_if.rb
Closes https://github.com/bundler/bundler-features/issues/77
Closes https://trello.com/c/Sh1xnJSi/76-add-install-if-dsl
=> [DSL] Add install_if method / option

lib/bundler/source/path/installer.rb
these conditionals would always evaluate to `true`, so just directly set
them to true without checking the option value
=> set `@wrappers` and `@env_shebang` to true

spec/support/helpers.rb
Probably closes https://github.com/bundler/bundler/issues/3607.
=> [SpecHelper] Reset settings

bin/bundle, bin/bundler
Closes https://trello.com/c/NXXTLLau/105-get-rid-of-executable-check-for-0-9.
\c @indirect
=> Clean up invocation of Bundler CLI

lib/bundler/endpoint_specification.rb, lib/bundler/inline.rb, lib/bundler/rubygems_integration.rb, spec/bundler/rubygems_integration_spec.rb, spec/install/gemfile/path_spec.rb, spec/runtime/inline_spec.rb
Needed for when inline has installed from this spec
Closes #3693.
=> [EndpointSpecification] Return local load paths

lib/bundler/rubygems_integration.rb
Closes https://github.com/bundler/bundler/issues/3698.
Closes https://github.com/bundler/bundler/issues/3686.
\c @indirect
=> Allow missing files when validating a spec

lib/bundler.rb, lib/bundler/cli/exec.rb, lib/bundler/setup.rb
closes a few issues
closes #3710.
\c @indirect
=> Unset UI when yielding to other programs

lib/bundler/installer.rb
Code climate points it as complexity 384.
This build should fail because the master build is failing. I ran the
specs against ruby 2.2.2 only, so don't merge without pass on travis.
=> Extract two methods from Installer#run

man/bundle-install.ronn
Adding some documentation for the `--force` option of `install`. Based on issue #3625.
Could not think of more stuff to write about this option. Lemme know if this is enough. :) Thanks!
=> Add man docs for bundle install --force option

README.md
=> missing period at end of README

lib/bundler/cli/check.rb, spec/commands/check_spec.rb
Run ``` bundle check ``` with ``` disable_shared_gems ``` set to '1' if --path option is specified
=> Run ``` bundle check ``` with ``` disable_shared_gems ``` set to '1' 

spec/realworld/edgecases_spec.rb
https://github.com/rails/rails/releases/tag/v3.2.22
=> update rails version in specs

lib/bundler/resolver.rb
Closes https://github.com/bundler/bundler/issues/3732.
=> [Resolver] Add optimization for deps where theres a path/gemspec source

CODE_OF_CONDUCT.md
See also: http://contributor-covenant.org/version/1/1/0/code_of_conduct.md
=> Integrate Code of Covenant 1.1.0 changes

lib/bundler/definition.rb, spec/lock/lockfile_spec.rb
=> [Definition] Preserve BUNDLED WITH section in #to_lock

lib/bundler/definition.rb, spec/lock/lockfile_spec.rb
=> [Definition] Dont updated bundled with when 100% unnecessary

lib/bundler/source/git/git_proxy.rb, spec/install/gemfile/git_spec.rb
=> Friendly error for EEXIST on git gem install.

lib/bundler/shared_helpers.rb
More readable, faster and more fun
=> Change if statement condition and syntax

lib/bundler/cli.rb, lib/bundler/settings.rb, lib/bundler/shared_helpers.rb, spec/deprecation_spec.rb, spec/support/matchers.rb
It'd be better if I squashed these commits...
=> Add deprecation warning for not autoremembering flags

lib/bundler/installer/parallel_installer.rb, spec/install/parallel/spec_installation_spec.rb
Fixes #3799 
Reject is clearly not the right method to use here, now I’m trying to figure out what state of mind I was in when I wrote something that is so obviously wrong.
=> switch reject to select

lib/bundler/cli/config.rb, lib/bundler/cli/install.rb, lib/bundler/settings.rb, lib/bundler/source/rubygems.rb, spec/commands/clean_spec.rb, spec/commands/config_spec.rb, spec/commands/exec_spec.rb, spec/commands/show_spec.rb, spec/install/gemfile/path_spec.rb, spec/install/gems/sudo_spec.rb, spec/install/path_spec.rb, spec/install/post_bundle_message_spec.rb, spec/other/platform_spec.rb, spec/support/path.rb
Opening this PR from a branch in the bundler repo, so we can all collaborate on it... /cc @smlance
=> Change default install path to ./.bundle/gems

lib/bundler/settings.rb, lib/bundler/source/rubygems.rb, spec/install/path_spec.rb
Fixes this failing spec: https://github.com/bundler/bundler/pull/3784#discussion-diff-34627198L94
The path code looks a bit scattered now, and it probably deserves some explanation.
=> Ensure configured relative paths are expanded from the Gemfile directory

spec/commands/config_spec.rb
Confirms that https://github.com/bundler/bundler/issues/3552 is implemented in 2-0-dev.
=> Check that `ruby_scope` is concatenated to globally configured install paths

.rubocop.yml, .rubocop_todo.yml, lib/bundler/cli.rb, lib/bundler/cli/gem.rb, lib/bundler/cli/show.rb, lib/bundler/dsl.rb, lib/bundler/gem_helper.rb, lib/bundler/graph.rb, lib/bundler/resolver.rb, lib/bundler/source/git.rb
=> Fix Style/AccessModifierIndentation

lib/bundler.rb, lib/bundler/settings.rb
=> Raise permission error when config file isn't readable

Rakefile
This fails faster on style issues.
=> Run Rubocop before specs

lib/bundler/installer.rb, spec/install/gems/standalone_spec.rb
https://github.com/bundler/bundler/issues/3813
=> Fixes #3813 : --standalone generates incorrect paths for native extensions

lib/bundler/source/rubygems.rb, spec/cache/gems_spec.rb
I still need to create a test, but I am not entirely sure where to write it.
=> Print a warning when a gem can't be cached due to a missing source

Rakefile, bundler.gemspec
This uses my new gem to manage vendoring.
\c @indirect
=> [Rakefile] Use automatiek to manage vendoring

lib/bundler/fetcher/index.rb, spec/bundler/fetcher/index_spec.rb
=> Rescue Net::HTTPFatalError, too

lib/bundler/graph.rb
=> align the hash that rubocop made wonky

bin/rake
=> rescue gem load errors so setup can run

lib/bundler/fetcher.rb, spec/bundler/fetcher_spec.rb, spec/support/helpers.rb
Rebases #3833 onto the latest master, allowing it to be merged.
=> Rebase #3833

lib/bundler/settings.rb
See https://github.com/bundler/bundler/pull/3941.
=> Refactor and add comments describing Bundler.settings.path

lib/bundler.rb
=> Wrap sudo access prompts in a mutex

.rubocop.yml, spec/support/builders.rb
(this seems to be the current leading reason for CI job failures)
=> maybe we can install missing system gems?

lib/bundler.rb, lib/bundler/friendly_errors.rb, lib/bundler/runtime.rb, lib/bundler/ui/shell.rb, spec/runtime/require_spec.rb
=> Handle errors gracefully when requiring gems

exe/bundle_ruby, lib/bundler.rb, lib/bundler/dsl.rb, lib/bundler/ruby_dsl.rb, spec/bundler/dsl_spec.rb
=> Distinguish Gemfile syntax and evaluation errors

lib/bundler/dsl.rb, spec/bundler/dsl_spec.rb
=> Dsl#with_source should restore the previous source

lib/bundler/cli.rb, lib/bundler/cli/binstubs.rb, lib/bundler/cli/config.rb, lib/bundler/cli/install.rb, lib/bundler/installer.rb, lib/bundler/settings.rb, man/bundle-config.ronn, man/bundle-install.ronn, spec/bundler/settings_spec.rb, spec/cache/git_spec.rb, spec/cache/path_spec.rb, spec/commands/binstubs_spec.rb, spec/commands/check_spec.rb, spec/commands/clean_spec.rb, spec/commands/config_spec.rb, spec/commands/install_spec.rb, spec/commands/package_spec.rb, spec/commands/update_spec.rb, spec/install/deploy_spec.rb, spec/install/gems/standalone_spec.rb, spec/install/path_spec.rb, spec/other/platform_spec.rb, spec/realworld/parallel_spec.rb, spec/runtime/executable_spec.rb, spec/runtime/setup_spec.rb, spec/support/builders.rb, spec/support/helpers.rb
Based on https://github.com/bundler/bundler/pull/3744.
=> Don't autoremember flags

lib/bundler/cli/gem.rb, lib/bundler/fetcher.rb
because shell can find urls and make it clickable if it begins with http://
=> add http://

lib/bundler/cli.rb, spec/bundler/cli_spec.rb
=> Ignore ENV["BUNDLE_GEMFILE"] if it's empty

lib/bundler/runtime.rb
I was not feeling inspired, but I do like to delete code! Here's a small simplification as reported [in Code Climate](https://codeclimate.com/github/bundler/bundler/Bundler::Runtime).
=> Removes duplication from bundle clean command

lib/bundler/gem_tasks.rb, spec/runtime/gem_tasks_spec.rb
=> include 'pkg/' in rake/clean's CLOBBER array

lib/bundler/installer.rb, lib/bundler/installer/standalone.rb
=> Show ruby engine and version

lib/bundler/index.rb, spec/install/gemfile/path_spec.rb
=> [Index] Handle when comparing against an index with no gemspec

lib/bundler/cli.rb, spec/bundler/cli_spec.rb
=> Warn if RUBYGEMS_GEMDEPS env. variable is set

lib/bundler/dsl.rb, lib/bundler/injector.rb, spec/other/platform_spec.rb
See https://github.com/bundler/bundler/pull/3441 for discussion.
Closes https://github.com/bundler/bundler-features/issues/79.
=> [DSL] Infer ruby from .ruby-version

lib/bundler/friendly_errors.rb, lib/bundler/rubygems_integration.rb, spec/bundler/friendly_errors_spec.rb
=> Handle invalid RubyGems config files

lib/bundler/cli.rb, man/bundle.ronn, spec/deprecation_spec.rb
=> Deprecate `bundle list`

lib/bundler/dsl.rb, spec/deprecation_spec.rb
Also fix the respective test failures which were around for a while.
=> Fix bitbucket/gist deprecation warnings

lib/bundler/fetcher.rb
=> Retry Fetch operation on Zlib error.

spec/bundler/friendly_errors_spec.rb
=> [FriendlyErrors] Update specs for the release of 2.5.0

ISSUES.md
=> Remove outdated advice

man/bundle-lock.ronn
This Pull Request adds a skelton of `bundle lock` man page.
=> Add a basic bundle lock manual [ci skip]

spec/realworld/edgecases_spec.rb
=> Fix edgecases spec for new gxapi_rails version

lib/bundler/cli/exec.rb
@segiddins is this enough for #4081 ?
=> Deal with ENOEXEC

lib/bundler/gem_helper.rb
=> [GemHelper] Fix crash when pushing gem

lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb
=> [CompactIndex] Handle yanked versions

lib/bundler/fetcher.rb
=> Add more exception classes not to retry on to the Fetcher

lib/bundler/cli.rb, lib/bundler/cli/lock.rb
=> [Lock] Add --full-index option

lib/bundler/templates/newgem/lib/newgem/version.rb.tt
Pet peeve of mine
\c @indirect
=> [newgem] freeze version constant

lib/bundler/source/git/git_proxy.rb, spec/install/gemfile/git_spec.rb
=>  Disable colorized git output in GitProxy#branch

.rubocop.yml, .travis.yml, lib/bundler/definition.rb, lib/bundler/env.rb, lib/bundler/gem_helper.rb, lib/bundler/lazy_specification.rb, lib/bundler/resolver.rb, lib/bundler/rubygems_ext.rb, lib/bundler/source/path.rb, lib/bundler/source/rubygems.rb
This commit prevents several bugs with `RuntimeError: can't modify frozen String` with enabled string frozen literal in Ruby 2.3
=> [WIP] Better support of Ruby 2.3 with enabled frozen string literal

man/bundle-config.ronn
Updating the man pages for the new redirect/timeout configs. Also added retry, it's currently under the install page though. See #4205
I just placed items these at the bottom of the list, but let me know if you'd prefer a different order or description. Thanks!
=> Add docs for retry, redirect, and timeout configs.

lib/bundler/cli/check.rb, lib/bundler/cli/install.rb, lib/bundler/settings.rb
Hi 👻
I thought that the last value in the config looks a bit strange:
```
$ cat .bundle/config
---
BUNDLE_PATH: vendor/bundle
BUNDLE_JOBS: 4
BUNDLE_CLEAN: true
BUNDLE_DISABLE_SHARED_GEMS: '1'
```
So I have booleanized it.
=> Booleanize the disable_shared_gems option

.travis.yml, Rakefile, spec/spec_helper.rb, spec/support/code_climate.rb, spec/support/rubygems_ext.rb
Let's see if this works!
\c @RochesterinNYC
=> Setup CodeClimate

spec/bundler/gem_helper_spec.rb, spec/support/hax.rb
=> [Hax] Support simulating jruby on MRI 2.3

lib/bundler/vendor/molinillo/lib/molinillo.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/errors.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/modules/ui.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb, lib/bundler/vendor/molinillo/lib/molinillo/state.rb
Closes https://github.com/bundler/bundler/issues/4198.
Closes https://github.com/bundler/bundler/issues/4101.
=> [Resolver] Update Molinillo to 0.4.2

.travis.yml, Rakefile
=> [Travis] Test against Ruby 2.3.0

lib/bundler/resolver.rb
=> [Resolver] Determine debug mode once

bin/rake, bin/rspec, bin/rubocop, lib/bundler/fetcher/compact_index.rb, lib/bundler/installer/parallel_installer.rb, lib/bundler/worker.rb
Also helps with https://github.com/bundler/bundler/issues/4246.
@indirect r?
=> [Worker] Add a worker name to ease debugging

spec/bundler/path_preserver_spec.rb
=> Add unit tests for `Bundler::PathPreserver` module

.rubocop.yml, lib/bundler/cli/platform.rb, lib/bundler/fetcher.rb, lib/bundler/ruby_dsl.rb, lib/bundler/ruby_version.rb, spec/bundler/ruby_dsl_spec.rb, spec/bundler/ruby_version_spec.rb, spec/other/platform_spec.rb
I believe these bugs should be blockers for 1.12, but I don't have it in me to write specs yet.
\c @indirect
=> Ruby version fixes

lib/bundler/current_ruby.rb
=> [CurrentRuby] Refactor

lib/bundler.rb, lib/bundler/cli/exec.rb, lib/bundler/runtime.rb, lib/bundler/shared_helpers.rb
Closes #2951, #2952.
@indirect it feels like I'm missing something?
=> [Exec] Avoid loading the definition before exec-ing

lib/bundler/fetcher.rb, spec/bundler/fetcher_spec.rb
=> [Fetcher] Support setting http_proxy to :no_proxy

lib/bundler/source/rubygems/remote.rb, spec/commands/install_spec.rb
=> Add helpful message and error handling for non-CGI-escaped authentication

lib/bundler/vendor/molinillo/lib/molinillo.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/errors.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/modules/specification_provider.rb, lib/bundler/vendor/molinillo/lib/molinillo/modules/ui.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb, lib/bundler/vendor/molinillo/lib/molinillo/state.rb
See https://github.com/CocoaPods/Molinillo/releases/0.4.3.
Closes https://github.com/bundler/bundler/issues/4276.
=> [Resolver] Update Molinillo to 0.4.3

lib/bundler/cli.rb, spec/commands/package_spec.rb
=> Add `--frozen` flag support for `bundle package`

lib/bundler/resolver.rb, spec/install/gemfile/git_spec.rb, spec/support/builders.rb
=> Add platform info to error message for different platform in gemspec than Gemfile.lock

lib/bundler/cli.rb, lib/bundler/settings.rb, spec/commands/package_spec.rb
=> [CLI] Ensure `bundle install` will always install

bin/rake, bin/rspec, bin/rubocop, bin/with_rubygems
=> Add helper script for running with particular rubygems versions

.travis.yml, Rakefile
=> [Travis] Test against RubyGems 2.6.0

.travis.yml, Rakefile
=> [Travis] Test against RubyGems 2.6.1

lib/bundler.rb, spec/bundler/bundler_spec.rb, spec/realworld/edgecases_spec.rb
=> Handle quotes in PATH

man/bundle-install.ronn, man/bundle.ronn, man/gemfile.5.ronn
Sorry about cosmetic PR. I just wanted to contributing something. :smile:
=> Small fixes in man pages

CONTRIBUTING.md, DEVELOPMENT.md, ISSUES.md
Small improvements in `DEVELOPMENT.md`, `CONTRIBUTING.md`, and `ISSUES.md` relating to clarity, grammar, additional links, additional content.
=> Improvements to Bundler repo docs

CHANGELOG.md
=> Document change in --without behavior

lib/bundler/source.rb, lib/bundler/source/rubygems.rb, lib/bundler/ui/shell.rb, lib/bundler/ui/silent.rb, spec/bundler/source_spec.rb
closes https://github.com/bundler/bundler/issues/4334
=> Colorize gem updates

lib/bundler/spec_set.rb, spec/bundler/spec_set_spec.rb
=> Add alias `Bundler::SpecSet#size` for `Bundler::SpecSet#length`

lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt
=> Upgrade template Code of Conduct to Contributor Covenant 1.4

spec/bundler/cli_spec.rb
=> Fix typo in bundler/cli_spec.rb

spec/cache/platform_spec.rb
=> Fix typo in cache/platform_spec.rb

lib/bundler/ssl_certs/certificate_manager.rb, spec/bundler/ssl_certs/certificate_manager_spec.rb
- Related to #4407
/cc @indirect
=> Have `CertificateManager` use new `ssl_certs` dir structure for `#certificates_in`

lib/bundler/templates/newgem/newgem.gemspec.tt
80 column is not respected on newgem created, this have to be changed every new gem for those respecting this convention.
Cheers
=> Fix 80 column on newgem gemspec

lib/bundler/errors.rb, lib/bundler/shared_helpers.rb, spec/bundler/shared_helpers_spec.rb
Closes #4394.
\c @RochesterinNYC
=> [SharedHelpers] Handle Errno::ENOTSUP in .filesystem_access

lib/bundler/spec_set.rb
This exception message contains duplication of "depend".
=> Fix exception message in spec_set.rb

lib/bundler/source/path.rb
Closes #2846, I presume.
\c @indirect
=> [Path] Speed up bin generation when there are many files

spec/support/builders.rb
This should speed up the specs slightly
\c @indirect
=> [Builders] Dont rebuild gem index when unnecessary

lib/bundler/cli/exec.rb, spec/commands/exec_spec.rb
@indirect this is a pretty bad bug :(
=> [Exec] Allow executables to exit non-zero via at_exit

lib/bundler/settings.rb, spec/bundler/settings_spec.rb
=> Improve loading config files

lib/bundler/settings.rb, spec/commands/config_spec.rb
¯\\\_(ツ)\_/¯ seems like a good idea
\c @RochesterinNYC @indirect
=> [Settings] Use a custom serializer instead of relying upon the YAML module

man/bundle-install.ronn
This option has existed since v1.1 and we're currently on v1.11!
=> Update bundle install man page with --frozen option

lib/bundler/cli/check.rb, lib/bundler/definition.rb, lib/bundler/environment.rb, lib/bundler/lockfile_parser.rb, lib/bundler/runtime.rb, spec/bundler/lockfile_parser_spec.rb, spec/runtime/setup_spec.rb, spec/support/helpers.rb
WIP, this needs tests
@indirect
=> Generically preserve new attributes in lockfile

lib/bundler/fetcher/compact_index.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client/version.rb, spec/install/gems/compact_index_spec.rb, spec/support/artifice/compact_index_checksum_mismatch.rb
@indirect this will make diagnosing https://github.com/bundler/bundler/issues/4472 much easier.
=> [Updater] Raise a more helpful error on checksum mismatch

lib/bundler/definition.rb, spec/install/deploy_spec.rb
=> Fixes frozen string exception when checking equivalent gemfile and lockfile

lib/bundler/source/git.rb, spec/commands/show_spec.rb
=> [Git] Fix checking for equality when a version includes a -

lib/bundler/index.rb, spec/bundler/index_spec.rb
Fixes #4557.
@indirect @RochesterinNYC ideas on how to test this?
=> [Index] Ensure nil and "ruby" platforms are treated identically

lib/bundler/dsl.rb, spec/install/gemfile/eval_gemfile_spec.rb
=> Use the full expanded path of passed `Gemfile` during `eval_gemfile`

lib/bundler/cli.rb, lib/bundler/friendly_errors.rb, spec/commands/exec_spec.rb, spec/support/helpers.rb
Closes #4596.
\c @RochesterinNYC @b-ggs
=> [CLI] Only redirect to help when first two args are help and exec

spec/quality_spec.rb
=> Add quality check for unresolved merge conflicts

lib/bundler/dsl.rb, lib/bundler/env.rb, lib/bundler/index.rb, lib/bundler/resolver.rb, lib/bundler/runtime.rb, lib/bundler/source.rb, lib/bundler/source/gemspec.rb, lib/bundler/source/path.rb, lib/bundler/source_list.rb, man/gemfile.5.ronn, spec/install/gemfile/gemspec_spec.rb
Needs to be cleaned up, but this demonstrates the general idea
=> Allow conflicts for gems resolved via `gemspec`

lib/bundler/cli.rb, lib/bundler/cli/lock.rb, lib/bundler/definition.rb, spec/commands/lock_spec.rb
=> [Lock] Add --add-platform

lib/bundler/definition.rb, lib/bundler/source/path.rb, spec/install/deploy_spec.rb
=> Add logic to check if the issue is path source related

lib/bundler/definition.rb, lib/bundler/endpoint_specification.rb, lib/bundler/fetcher.rb, lib/bundler/fetcher/compact_index.rb, lib/bundler/fetcher/dependency.rb, lib/bundler/index.rb, lib/bundler/remote_specification.rb, lib/bundler/resolver.rb, lib/bundler/rubygems_integration.rb, spec/bundler/endpoint_specification_spec.rb, spec/bundler/remote_specification_spec.rb, spec/install/bundler_spec.rb
Some not insignificant improvements found while developing https://github.com/CocoaPods/Molinillo/pull/40, which I absolutely cannot wait to 🚢 
\c @indirect
=> Improve resolver performance

lib/bundler/installer.rb, spec/install/gems/resolving_spec.rb
Let's finally put these to use!
=> [Installer] Fail fast when required_ruby(gems)?_version doesn't match

lib/bundler/fetcher.rb, spec/bundler/fetcher/downloader_spec.rb
=> Fail gracefully on Errno::EHOSTUNREACH

lib/bundler/definition.rb, lib/bundler/ruby_version.rb, spec/bundler/ruby_version_spec.rb, spec/commands/install_spec.rb, spec/install/gemfile/ruby_spec.rb, spec/other/platform_spec.rb, spec/runtime/setup_spec.rb, spec/support/hax.rb, spec/support/helpers.rb
Closes #4595. Closes #4627.
\c @RochesterinNYC
=> [Definition] Allow unlocking when removing the ruby version requirement

Rakefile, bundler.gemspec, exe/bundle, lib/bundler/cli.rb, lib/bundler/cli/update.rb, lib/bundler/postit_trampoline.rb, lib/bundler/setup.rb, lib/bundler/shared_helpers.rb, lib/bundler/vendor/postit/lib/postit.rb, lib/bundler/vendor/postit/lib/postit/environment.rb, lib/bundler/vendor/postit/lib/postit/installer.rb, lib/bundler/vendor/postit/lib/postit/parser.rb, lib/bundler/vendor/postit/lib/postit/setup.rb, lib/bundler/vendor/postit/lib/postit/version.rb, spec/bundler/shared_helpers_spec.rb, spec/other/trampoline_spec.rb, spec/support/helpers.rb, spec/support/rubygems_ext.rb
~~Except on bundle exec, since that would be too slow~~
~~If you want, I guess we could vendor postit and manually setup the `LOAD_PATH` and `-r` the full path to the vendored postit exe. Your call.~~ Done this
\c @indirect
=> [bundle] Automatically trampoline to postit

lib/bundler/resolver.rb, lib/bundler/vendor/molinillo/lib/molinillo/delegates/resolution_state.rb, lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/action.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/log.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/set_payload.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/tag.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb, lib/bundler/vendor/molinillo/lib/molinillo/state.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.0
Closes #4376.
=> Update vendored Molinillo to 0.5.0

man/bundle-update.ronn
=> [Docs] Add update --bundler

lib/bundler/lockfile_parser.rb
=> [LockfileParser] Support for old RG on Ruby 2.3+

lib/bundler/cli.rb
=> Print only version number from `bundler --version`

lib/bundler/definition.rb, lib/bundler/dsl.rb, lib/bundler/lockfile_parser.rb, lib/bundler/resolver.rb, lib/bundler/rubygems_ext.rb, lib/bundler/source_list.rb, lib/bundler/stub_specification.rb, spec/bundler/fetcher/downloader_spec.rb, spec/bundler/source_list_spec.rb, spec/commands/exec_spec.rb, spec/commands/lock_spec.rb, spec/install/gemfile/git_spec.rb, spec/install/gemfile/path_spec.rb, spec/install/gemfile/sources_spec.rb, spec/install/post_bundle_message_spec.rb, spec/lock/lockfile_spec.rb, spec/resolver/basic_spec.rb, spec/runtime/inline_spec.rb, spec/runtime/require_spec.rb, spec/support/indexes.rb, spec/update/git_spec.rb
This is a total hack but appears to work!
\c @indirect @TimMoore
=> [Resolver] Pin transitive deps to relevant sources

lib/bundler/definition.rb, lib/bundler/spec_set.rb
@indirect this might make your debugging a bit easier?
=> [Definition] Add a #change_reason printed in debug

lib/bundler/rubygems_integration.rb, spec/commands/exec_spec.rb, spec/install/binstubs_spec.rb
=> Prefer spec name matches when searching for an exe

lib/bundler/definition.rb, spec/install/gemfile/sources_spec.rb
=> [Definition] Just search for changed specs in an exactly matching source

DEVELOPMENT.md
=> disable trampoline in dbundle

lib/bundler/dsl.rb, spec/install/gemfile/gemspec_spec.rb, spec/support/helpers.rb
=> [DSL] Set ruby version when using the gemspec method

lib/bundler/ui/silent.rb, spec/bundler/source_spec.rb, spec/support/helpers.rb
Was leaking through the GemHelper unit tests
=> Fix spurious spec failures due to leaking Bundler.ui

exe/bundler, spec/bundler/cli_spec.rb, spec/support/helpers.rb
=> Make `bundler` and `bundle` executables have the same functionality

DEVELOPMENT.md
I noticed the label name was updated.
=> fix feature request link

lib/bundler/gem_version_promoter.rb
I've been changing bundler-patch to work with the code portions that
have been moved into Bundler, and the tap block at the end of
sort_dep_specs couldn't be overridden, so that's been moved into its own
method.
Another refactoring was to move local vars into instance vars to stop
passing them around. Going all the way to push that into a class seemed
a bit much at this stage.
=> GemVersionPromoter refactorings

spec/commands/update_spec.rb
@indirect @RochesterinNYC 
---
Closes #4631
=> Add spec for only updating from pinned source

lib/bundler/cli/exec.rb, spec/install/gemfile/git_spec.rb, spec/install/gemfile/path_spec.rb, spec/spec_helper.rb, spec/support/builders.rb
Unfortunately I can't get testsuite running locally, hope that travis will tell that changes are OK.
Fixes https://github.com/bundler/bundler/issues/4586.
I don't really know if test should be added for the last commit, please advise.
=> Improve exec on JRuby

lib/bundler/cli.rb, spec/bundler/cli_spec.rb, spec/other/trampoline_spec.rb
This also has the nice side-effect of printing the bundler version ;)
=> [CLI] Print running command

spec/install/gemfile/sources_spec.rb, spec/install/git_spec.rb, spec/support/builders.rb, spec/support/matchers.rb
I was on a ✈️. I got bored. This got written. EOS
=> Add support for checking source in should_be_installed

lib/bundler/cli.rb, spec/commands/help_spec.rb
Fixes the issue mentioned in https://github.com/bundler/bundler/issues/4801
=> Fix bundle --help

lib/bundler/fetcher/compact_index.rb
Overview
--------
One of the main benefits of the `Net::HTTP::Persistent` library is that it maintains the HTTP connections so that multiple requests to the same host don't need to re-instantiate the http tcp socket to make a request, and also allows this to be done across threads.  But when used with the `CompactIndex` client, the each iteration of the `remaining_gems?` loop throws away the `Bundle::Worker` and initiates new Threads with new connections.
Since the resulting work on these threads only returns to the caller the result, and can be collected cleanly, it is safe to reuse these threads by other repeated `gem_name` iterations and gain a bit of a performance boost in the process.
While in this code change, we do run `@bundle_worker.stop`, we could simple skip this now as we will …
=> Allow for Thread reuse for CompactIndex fetcher

lib/bundler/friendly_errors.rb, spec/bundler/friendly_errors_spec.rb
Fixes #4771 
/c @RochesterinNYC @segiddins
=> Add message filter to generate better search URL

man/bundle-binstubs.ronn
This PR is intended to resolve https://github.com/bundler/bundler/issues/4000.
=> Add manpage for bundle-binstubs

lib/bundler/cli/install.rb, lib/bundler/inline.rb, lib/bundler/installer.rb, lib/bundler/installer/gem_installer.rb, lib/bundler/installer/parallel_installer.rb, lib/bundler/ui/shell.rb
=> [Install] Print errors at the end of installation instead of inline

lib/bundler/definition.rb, lib/bundler/installer/parallel_installer.rb, spec/install/gemfile/git_spec.rb
=> Unlock sources when a local override leads to changes

lib/bundler/fetcher/compact_index.rb, lib/bundler/settings.rb, lib/bundler/source/git.rb, lib/bundler/source/git/git_proxy.rb, lib/bundler/ui/shell.rb, spec/install/allow_offline_install_spec.rb, spec/support/artifice/fail.rb, spec/support/builders.rb
This should ideally have some tests, but right now it's behind a feature flag
=> Allow installing / updating when everything necessary is available locally

lib/bundler/postit_trampoline.rb, lib/bundler/setup.rb
@indirect this should fix the stack overflow bug!
=> [Setup] Only add bundler to the load path if we havent trampolined

lib/bundler/cli/exec.rb, spec/commands/exec_spec.rb
Closes #4589.
See https://github.com/bundler/bundler/issues/4852.
=> Manually set a process title when using load

lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client/cache.rb, spec/install/gems/compact_index_spec.rb
=> Add resiliency against case conflicts on a case-insensitive FS

lib/bundler/gem_helper.rb
=> Allow users to sign the version tag

lib/bundler/templates/Gemfile
Taken from https://github.com/bundler/bundler/pull/4746
=> Simplify Gemfile template

lib/bundler.rb, spec/bundler/bundler_spec.rb
Ref #4726 
Might need to add a spec?
/c @indirect @RochesterinNYC
=> Rescue ArgumentError and explain the security vulnerability. Fixes #4726

lib/bundler.rb, lib/bundler/plugin.rb, lib/bundler/plugin/index.rb, spec/bundler/plugin/index_spec.rb, spec/bundler/plugin/installer_spec.rb, spec/bundler/plugin_spec.rb, spec/plugins/install_spec.rb, spec/plugins/source_spec.rb, spec/support/helpers.rb, spec/support/path.rb
If the user is in an app directory the plugin is installed in `.bundle/` inside the app root.
If the user is in not in any app directory the plugin is installed in the `.bundle/` in the user's home.
=> Project local plugins

lib/bundler/cli.rb, lib/bundler/cli/lock.rb, lib/bundler/definition.rb, spec/commands/lock_spec.rb
=> [Lock] Allow removing platforms

lib/bundler/source/git/git_proxy.rb, spec/install/gemfile/git_spec.rb
=> Filter out credentials in stderr message 

lib/bundler.rb, lib/bundler/cli.rb, lib/bundler/cli/install.rb, lib/bundler/cli/update.rb, lib/bundler/feature_flag.rb, lib/bundler/fetcher/compact_index.rb, lib/bundler/inline.rb, lib/bundler/plugin.rb, lib/bundler/source/git.rb
Main use will be code showing what is true setting vs what is flagged
Also can be used to develop for future major versions without needing a separate dev branch
=> Add FeatureFlag class

lib/bundler/cli/doctor.rb, lib/bundler/cli/update.rb, spec/commands/doctor_spec.rb
\c @mistydemeo who implemented the Doctor command
=> Have `doctor` call through to `check`

exe/bundle, lib/bundler/postit_trampoline.rb, lib/bundler/setup.rb, spec/other/trampoline_spec.rb
See https://github.com/bundler/bundler/issues/4853
=> [PostitTrampoline] Automatically enable when target version is >= 2

lib/bundler/yaml_serializer.rb, spec/bundler/yaml_serializer_spec.rb
Closes #4435.
\c @asutoshpalai
=> [YAMLSerializer] Allow loading with CRLF line endings

lib/bundler/source/git/git_proxy.rb
Ref: https://github.com/bundler/bundler/pull/4704#discussion_r74819953
=> Add todo for #capture_and_filter_stderr

lib/bundler/definition.rb, lib/bundler/resolver.rb, spec/commands/lock_spec.rb, spec/support/matchers.rb
=> [Resolver] Ensure all platforms are activated for the activated spec group

spec/commands/exec_spec.rb
=> [Exec] Add specs for $0 and __FILE__ when loaded

.travis.yml, Rakefile, bundler.gemspec, exe/bundle, lib/bundler.rb, lib/bundler/compatibility_guard.rb, lib/bundler/inline.rb, lib/bundler/rubygems_ext.rb, lib/bundler/shared_helpers.rb, spec/bundler/shared_helpers_spec.rb, spec/other/platform_spec.rb, spec/realworld/edgecases_spec.rb, spec/runtime/with_clean_env_spec.rb, spec/support/rubygems_ext.rb
Closes https://github.com/bundler/bundler/issues/4719
\c @indirect
=> Get 2-0-dev green again

DEVELOPMENT.md
Follow up of https://github.com/bundler/bundler/pull/4919#issuecomment-242706463.
[Preview DEVELOPMENT.md](https://github.com/JuanitoFatas/bundler/blob/6667a9d9a1fd7f83b4d262ff00b933f8574a974f/DEVELOPMENT.md#development-setup)
=> Doc: Add a note on how to dive into the code with Pry

lib/bundler/settings.rb, spec/bundler/settings_spec.rb
This PR adds a spec and moved an alias in Settings class.
followup of #4917.
=> Add some specs for Bundler::Settings#temporary

lib/bundler/dsl.rb, spec/other/platform_spec.rb
See https://github.com/bundler/bundler/issues/4856.
Reverts most of https://github.com/bundler/bundler/pull/4036
=> Revert inferring from .ruby-version

lib/bundler/dsl.rb
See https://github.com/bundler/bundler/issues/4856 & https://github.com/bundler/bundler/pull/4918
=> [DSL] Suggest updating bundler on invalid options

man/bundle-config.ronn
Closes #4947.
Default taken from https://github.com/bundler/bundler/blob/96bdba7686ca39b41eebde7533148f92aee2260a/lib/bundler/settings.rb#L210
=> Document the default value for the cache_path setting

lib/bundler/vendor/compact_index_client/lib/compact_index_client.rb, lib/bundler/vendor/compact_index_client/lib/compact_index_client/updater.rb
=> Add debug logging to the compact index client

lib/bundler/fetcher/downloader.rb, spec/install/gems/compact_index_spec.rb
=> Fail gracefully when attempting to request from an unknown URI scheme

lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.1
I'd love this to be a 1.13.1
=> Update vendored Molinillo to 0.5.1

lib/bundler/rubygems_integration.rb
Closes #4975 
\c @indirect @headius 
I'd love to get this out as 1.13.2 asap, if it works
=> [RubygemsIntegration] Ensure redefined methods have the same visibility

lib/bundler/source/path.rb, spec/install/gemfile/eval_gemfile_spec.rb
Closes https://github.com/bundler/bundler/issues/4966, but i'm wondering if this will break anything else?
=> [Path] Store lockfile paths relative to the root, not the gemfile path

lib/bundler/definition.rb
=> [Definition] Avoid parsing lockfile twice on init

lib/bundler/cli.rb, lib/bundler/cli/lock.rb, spec/commands/lock_spec.rb, spec/support/helpers.rb
Closes https://github.com/bundler/bundler/issues/4957
=> [Lock] Default to not updating

man/bundle-exec.ronn
See https://github.com/bundler/bundler/issues/4852 @indirect
=> Update bundle-exec docs for exec loading

lib/bundler.rb, lib/bundler/errors.rb
I think this should close #3006 ?
This is an alternate to https://github.com/bundler/bundler/issues/4905.
\c @b-ggs
=> Always prompt once for sudo

lib/bundler/definition.rb, lib/bundler/feature_flag.rb
=> Enable feature flags by default on 2.0

lib/bundler.rb, lib/bundler/current_ruby.rb, lib/bundler/definition.rb, lib/bundler/dsl.rb, lib/bundler/gem_helpers.rb, lib/bundler/lazy_specification.rb, lib/bundler/rubygems_integration.rb, lib/bundler/settings.rb, spec/cache/gems_spec.rb, spec/commands/install_spec.rb, spec/runtime/platform_spec.rb, spec/support/builders.rb
See https://github.com/bundler/bundler/pull/4895.
Closes https://github.com/bundler/bundler/issues/4813.
=> Add a setting for forcing only the ruby platform

lib/bundler/cli.rb, lib/bundler/cli/outdated.rb, spec/commands/outdated_spec.rb
This is a branch from #4841 which is still in the final stages of review. At one point that PR contained the conservative update stuff, too, and there were some code review comments pertaining to breaking behavior that I wanted to copy over here, so I"m making this PR to capture that stuff so I can close out the review of the prior PR.
Once #4841 is merged, I'll rebase this PR.
=> PLACEHOLDER - Conservative updates on outdated

lib/bundler/env.rb
Closes https://github.com/bundler/bundler/issues/5069
=> Add platform information to env

lib/bundler/fetcher/dependency.rb, spec/bundler/fetcher/dependency_spec.rb
This might slightly help the fastly hit rate?
\c @indirect @dwradcliffe
=> [Fetcher::Dependency] Sort gem names in query string

lib/bundler/index.rb, spec/install/gemfile/sources_spec.rb, spec/support/artifice/compact_index.rb, spec/support/artifice/endpoint.rb
=> [Index] Allow pre-release versions in search when the base is pre-release

lib/bundler/definition.rb, spec/install/yanked_spec.rb
=> Fixed bundler incorrectly printing "the gem may have been yanked" in local installs

lib/bundler/gemdeps.rb, lib/bundler/rubygems_integration.rb
=> [RubyGemsIntegration] Add a single method for #use_gemdeps

lib/bundler/rubygems_integration.rb, spec/runtime/setup_spec.rb
Closes #5102 
\c @indirect @schneems
=> [RubygemsIntegration] Temporarily make #gem public again

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/action.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/delete_edge.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/log.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/set_payload.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/tag.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.3
=> Update vendored Molinillo to 0.5.3

lib/bundler/cli/exec.rb, spec/commands/exec_spec.rb
closes https://github.com/bundler/bundler/issues/5084
=> Warn if executable in bundle exec is empty

lib/bundler/cli.rb, man/bundle-lock.ronn, man/bundle-outdated.ronn, man/bundle-update.ronn, spec/commands/update_spec.rb, spec/resolver/basic_spec.rb
=> [WIP] New patch level and conservative options documented.

Rakefile
Should fix our current CI failures
=> [Rakefile] Pin CodeClimate reporter to pre-1.0

lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.4
=> Update vendored Molinillo to 0.5.4

lib/bundler/compact_index_client.rb, lib/bundler/fetcher/compact_index.rb, spec/bundler/bundler_spec.rb
=> [CompactIndexClient] Synchronize access to the list of fetched endpoints

lib/bundler/env.rb, lib/bundler/friendly_errors.rb, spec/bundler/env_spec.rb
I don't know if this is a good idea, but it might help increase the proportion of new issues we get that are properly formatted?
=> [Env] Print as GFM

lib/bundler/templates/newgem/gitignore.tt, lib/bundler/templates/newgem/spec/spec_helper.rb.tt
aka make my life easier when working with new gems.
=> [CLI::Gem] When using rspec, configure persistence file

lib/bundler/source.rb, spec/commands/install_spec.rb, spec/support/artifice/fail.rb, spec/support/helpers.rb
Called "sam has a flight and forgot to run `rake spec:deps`"
=> Random spec improvements

.travis.yml
=> [Travis] Test against Ruby 2.4

lib/bundler/index.rb, spec/bundler/index_spec.rb, spec/runtime/load_spec.rb, spec/support/builders.rb
=> Don't include dev deps in Index#dependency_names

lib/bundler/installer/gem_installer.rb, lib/bundler/rubygems_integration.rb, lib/bundler/source/rubygems.rb
I believe this closes #4684
\c @lynnco
=> [GemInstaller] Allow installing extensions in parallel

DEVELOPMENT.md, lib/bundler/postit_trampoline.rb, lib/bundler/settings.rb, man/bundle-config.ronn, man/bundle-lock.ronn, man/bundle.ronn, spec/bundler/settings_spec.rb, spec/other/trampoline_spec.rb, spec/quality_spec.rb, spec/support/helpers.rb
See https://github.com/bundler/bundler/issues/4853
@indirect feel free to add any other docs you think might be helpful to this branch
=> Document 1.14 platform changes

lib/bundler/definition.rb, lib/bundler/match_platform.rb, lib/bundler/rubygems_integration.rb
=> [RubyGemsIntegration] Restore 1.3.6 compatibility when installing

lib/bundler/cli/open.rb, spec/commands/open_spec.rb
Closes https://github.com/bundler/bundler/issues/5301
=> [CLI::Open] Support exiting when selecting gem

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.5
=> Update vendored Molinillo to 0.5.5

lib/bundler/cli.rb, lib/bundler/settings.rb, man/bundle-config.ronn, spec/bundler/cli_spec.rb, spec/support/hax.rb
Closes https://github.com/bundler/bundler/issues/4683.
The `send`s are super hacky but ¯\_(ツ)_/¯
=> [CLI] Warn when running an outdated bundler version

lib/bundler.rb, lib/bundler/cli/check.rb, lib/bundler/inline.rb, lib/bundler/installer.rb, spec/runtime/inline_spec.rb
=> [Inline] Support running when BUNDLE_GEMFILE=""

lib/bundler.rb, lib/bundler/settings.rb
=> [Settings] Autoload Mirror under Settings namespace

lib/bundler/settings.rb, man/bundle-config.ronn, spec/quality_spec.rb
=> Document all Bundler settings

bundler.gemspec
=> marketing-ify the post-install message

lib/bundler/ui/silent.rb, spec/bundler/friendly_errors_spec.rb
Hi,
This is my first contribution to bundler, so I started by covering bundler/friendly_errors.rb with unit tests.
After covering it, I spotted a bug in lib/bundler/ui/silent.rb, trace method interface, so I fix it in this PR.
Waiting for feedback!
=> Fix silent.rb method interface

lib/bundler/ruby_version.rb, spec/install/gemfile/ruby_spec.rb
=> [RubyVersion] Ensure passed-in versions are valid during init

lib/bundler/ui/silent.rb, spec/bundler/ui_spec.rb
=> [UI::Silent] Ensure all the same methods as Shell are implemented

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/modules/ui.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.6
closes #5359 
closes #5362
=> Update vendored Molinillo to 0.5.6

lib/bundler/source/git.rb, lib/bundler/source/path.rb, spec/install/gems/native_extensions_spec.rb
Closes https://github.com/bundler/bundler/pull/5399
Closes https://github.com/bundler/bundler/issues/5401
=> Properly set native extension build args for git gems

task/release.rake
Implement pagination
Account for the fact that only issues can be filtered by milestone, not PRs
=> [Release] Fix pulling PRs from milestone

task/release.rake
Today in 'testing release code is hard'...
=> [Release] Coerce PR numbers to strings for the regexp matching

lib/bundler/cli.rb, lib/bundler/vendor/thor/lib/thor.rb, lib/bundler/vendor/thor/lib/thor/actions.rb, lib/bundler/vendor/thor/lib/thor/actions/create_file.rb, lib/bundler/vendor/thor/lib/thor/actions/create_link.rb, lib/bundler/vendor/thor/lib/thor/actions/directory.rb, lib/bundler/vendor/thor/lib/thor/actions/empty_directory.rb, lib/bundler/vendor/thor/lib/thor/actions/file_manipulation.rb, lib/bundler/vendor/thor/lib/thor/actions/inject_into_file.rb, lib/bundler/vendor/thor/lib/thor/base.rb, lib/bundler/vendor/thor/lib/thor/command.rb, lib/bundler/vendor/thor/lib/thor/core_ext/hash_with_indifferent_access.rb, lib/bundler/vendor/thor/lib/thor/core_ext/io_binary_read.rb, lib/bundler/vendor/thor/lib/thor/core_ext/ordered_hash.rb, lib/bundler/vendor/thor/lib/thor/error.rb, lib/bundler/vendor/thor/lib/thor/group.rb, lib/bundler/vendor/thor/lib/thor/invocation.rb, lib/bundler/vendor/thor/lib/thor/parser/argument.rb, lib/bundler/vendor/thor/lib/thor/parser/arguments.rb, lib/bundler/vendor/thor/lib/thor/parser/option.rb, lib/bundler/vendor/thor/lib/thor/parser/options.rb, lib/bundler/vendor/thor/lib/thor/runner.rb, lib/bundler/vendor/thor/lib/thor/shell.rb, lib/bundler/vendor/thor/lib/thor/shell/basic.rb, lib/bundler/vendor/thor/lib/thor/shell/color.rb, lib/bundler/vendor/thor/lib/thor/shell/html.rb, lib/bundler/vendor/thor/lib/thor/util.rb, lib/bundler/vendor/thor/lib/thor/version.rb
=> [Thor] Update to v0.19.4

lib/bundler.rb, lib/bundler/settings.rb, spec/bundler/settings_spec.rb, spec/support/helpers.rb, spec/support/path.rb, spec/support/rubygems_ext.rb
Closes https://github.com/bundler/bundler/issues/5371
This is an alternative to https://github.com/bundler/bundler/pull/5385
=> Don't read global settings on a read-only FS with no $HOME

lib/bundler/plugin/api/source.rb
=> fixing small typo in comments

lib/bundler/endpoint_specification.rb, lib/bundler/errors.rb, lib/bundler/installer/gem_installer.rb, lib/bundler/lazy_specification.rb, lib/bundler/remote_specification.rb, lib/bundler/source/rubygems/remote.rb, spec/bundler/remote_specification_spec.rb, spec/install/gemfile/platform_spec.rb, spec/install/gemfile/specific_platform_spec.rb, spec/install/gems/compact_index_spec.rb, spec/support/artifice/compact_index_wrong_dependencies.rb
Fixes https://github.com/bundler/bundler/issues/5426
Closes https://github.com/bundler/bundler/issues/5339
=> Fail gracefully when installing a spec where the API is missing deps

lib/bundler/rubygems_gem_installer.rb, spec/install/gems/compact_index_spec.rb
Fix https://github.com/bundler/bundler/issues/5369
=> Fix disable.checksum_validation to disable_checksum_validation

lib/bundler/friendly_errors.rb
This way, we don't continuously have to ask for them
=> [FriendlyErrors] Include Gemfile in error report

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb, lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.5.7
=> Update vendored Molinillo to 0.5.7

lib/bundler/cli/gem.rb, spec/commands/newgem_spec.rb
Fixes https://github.com/bundler/bundler/issues/5458
=> `bundle gem` check if git is installed

lib/bundler/definition.rb, spec/commands/update_spec.rb
Fixes: https://github.com/bundler/bundler/issues/5009
=> Suggest different command depending on where 'frozen' config is set

man/bundle-update.ronn
Also makes the --jobs doc a little closer to the copy from install.
=> Document that --retry works for update.

man/bundle-config.ronn
This matches my experimental results at least.
=> Correct the config option name corresponding to --binstubs

lib/bundler/definition.rb
What this addresses
---
Follow up for #5539 
Previously, a proc was used to extract name and requirements from dependencies. This was
done twice, `2*O(n)`, and compared as `Set` objects.
This was identified as slow:
** Again, note that tracepoint slows the results in the chart down.
Without `TracePoint`, we run at about 13-15ms.
How this fixes it
---
Now that we use a hash for `@locked_deps`, we can
iterate one of the arrays (`@dependencies`) and compare against entries in `@locked_deps` with `O(1)`
access. This results in `O(n)` access.
The result is that `converge_dependencies`, which used to take 15ms, now takes about 2-3ms.
** Again, note that tracepoint slows the results in the chart down.
Considerations
---
Equality between 2 dependencies, as defined [here for …
=> Change `definition#converge_dependencies` comparison to an iterator for performance

lib/bundler/cli/outdated.rb, lib/bundler/lazy_specification.rb, lib/bundler/ui/shell.rb, spec/bundler/ui_spec.rb, spec/commands/outdated_spec.rb
=> [Outdated] Support running when gems are not yet installed

lib/bundler/rubygems_integration.rb, spec/commands/exec_spec.rb, spec/runtime/setup_spec.rb
=> Friendly error when exec'ing to gem outside the bundle

lib/bundler/cli.rb, lib/bundler/cli/add.rb, lib/bundler/injector.rb, spec/commands/add_spec.rb, spec/commands/inject_spec.rb
@indirect  @segiddins Starting out with implementation of add command. Not very sure of what the differences are with `inject` other than this will have no ui and run install
=> Add command implementation

lib/bundler/cli.rb, lib/bundler/cli/pristine.rb, lib/bundler/source/git.rb, spec/commands/pristine_spec.rb
Initial implementation of bundle pristine
Addressing:
https://github.com/bundler/bundler/issues/4509
https://github.com/bundler/bundler-features/issues/5
=> Implementation of `bundle pristine`

lib/bundler/definition.rb, lib/bundler/index.rb, lib/bundler/rubygems_ext.rb, lib/bundler/spec_set.rb, spec/support/builders.rb
Nothing major, but why not ¯\_(ツ)_/¯
Closes #5057
=> Speed up spec sets

lib/bundler/cli/issue.rb, lib/bundler/env.rb
This will save a lot of time spent asking for them, and is something I thought we'd already done
=> [Env] Default to always printing gemfile & gemspecs

bundler.gemspec
=> add metadata to gemspec

.rubocop.yml, lib/bundler/rubygems_integration.rb, lib/bundler/runtime.rb, spec/runtime/setup_spec.rb
This is currently failing on ruby trunk
=> Test that default gem substitutes are properly activated

lib/bundler/settings.rb, lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb, lib/bundler/vendor/thor/lib/thor/base.rb, lib/bundler/vendor/thor/lib/thor/util.rb, man/bundle-config.ronn, man/bundle-install.ronn, spec/bundler/dsl_spec.rb, spec/bundler/plugin/api_spec.rb, spec/commands/config_spec.rb, spec/commands/newgem_spec.rb, spec/commands/update_spec.rb, spec/install/gemfile/git_spec.rb, spec/runtime/platform_spec.rb
I picked up a typical typos using [misspell](https://github.com/client9/misspell) and applied it.
=> Fix a typos

spec/bundler/spec_set_spec.rb
As the title says, this PR just adds a few specs that i noticed were missing in SpecSet.
=> Add specs for #find_by_name_and_platform and #merge in SpecSet

lib/bundler/installer.rb
This PR just updates some comments/documentation that was written ~6 years ago that is a fair bit out of date.
Let me know if any information is incorrect.
=> Update comments in installer that was a bit out of date

task/release.rake
=> [Rakefile] Allow making a patch release with no changes

spec/runtime/setup_spec.rb
=> Make the setup specs resilient agains ruby shims setting RUBYLIB

lib/bundler/env.rb
=> [Env] Print well-formed markdown when there are no settings

lib/bundler/cli/init.rb, lib/bundler/feature_flag.rb, lib/bundler/settings.rb, lib/bundler/templates/gems.rb, man/bundle-config.ronn, spec/commands/init_spec.rb, spec/quality_spec.rb
This PR adds a feature flag to generate a new `gems.rb` with `bundle init`.
=> generate gems.rb in bundle init with feature flag

lib/bundler/cli.rb, lib/bundler/cli/pristine.rb, spec/commands/pristine_spec.rb
In the process of testing this, I discovered and fixed a bug that had pristine git gems not get added files removed.
=> [Pristine] Allow passing a list of gems to pristine

lib/bundler/dsl.rb, spec/other/major_deprecation_spec.rb
Closes #5699.
Closes #5698.
@indirect is this what you wanted?
=> [DSL] Deprecate the github source for 2.0

.github/welcome_message.md
This PR is adding the welcome message that will serve as the auto reply for Bundlerbot when a new PR is opened.
=> add welcome message for PR auto replies

CONTRIBUTING.md, doc/TROUBLESHOOTING.md, doc/contributing/BUG_TRIAGE.md, doc/contributing/ISSUES.md, doc/contributing/README.md
Hi - I had some time and ran through all the docs looking for small typos and grammatical mistakes. Please let me know if I need to fill out the CHANGELOG and/or anything else.
=> Small documentation fixes for spelling and grammar

lib/bundler/definition.rb, lib/bundler/lockfile_generator.rb
The problem was that eventually we might want to add more stuff to the lockfile.
My diagnosis was that lockfile generation should probably exist outside of a single method.
My fix is to create a `LockfileGenerator` class.
=> Extract lockfile generation into a new class

spec/runtime/setup_spec.rb
The problem was those specs were failing on CI and I couldn't figure out why.
My diagnosis was we needed the hack loaded before all bundler code.
My fix gets the hack loaded in via an `-r` switch set in `RUBYOPT`
I chose this fix because it will make spec failures more informative.
=> Improve logging in default gem activation specs

spec/bundler/lockfile_parser_spec.rb
The problem was the lockfile parser was missing some robustness unit tests.
My fix was to add test coverage!
=> Add some unit tests for lockfile parsing

doc/development/SETUP.md
Hey @indirect @segiddins,
I've implemented the suggested updates that @arbonap provided. Specifically, adding a new step 1 (how to fork a repo), and adding instructions for creating aliases in bash.
=> Updated Development setup page

lib/bundler/cli.rb, lib/bundler/cli/gem.rb, lib/bundler/vendor/thor/lib/thor.rb, lib/bundler/vendor/thor/lib/thor/actions.rb, lib/bundler/vendor/thor/lib/thor/actions/create_file.rb, lib/bundler/vendor/thor/lib/thor/actions/create_link.rb, lib/bundler/vendor/thor/lib/thor/actions/empty_directory.rb, lib/bundler/vendor/thor/lib/thor/actions/file_manipulation.rb, lib/bundler/vendor/thor/lib/thor/actions/inject_into_file.rb, lib/bundler/vendor/thor/lib/thor/base.rb, lib/bundler/vendor/thor/lib/thor/command.rb, lib/bundler/vendor/thor/lib/thor/core_ext/hash_with_indifferent_access.rb, lib/bundler/vendor/thor/lib/thor/group.rb, lib/bundler/vendor/thor/lib/thor/line_editor/basic.rb, lib/bundler/vendor/thor/lib/thor/parser/option.rb, lib/bundler/vendor/thor/lib/thor/parser/options.rb, lib/bundler/vendor/thor/lib/thor/runner.rb, lib/bundler/vendor/thor/lib/thor/shell/basic.rb, lib/bundler/vendor/thor/lib/thor/util.rb, lib/bundler/vendor/thor/lib/thor/version.rb, spec/commands/newgem_spec.rb
Thor 0.20.0 was released so I'm upgrading bundler to the newest version.
=> Upgrade thor to 0.20.0

lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
The problem was Molinillo 0.6.2 fixes a potential problem.
My fix is to update to Molinillo 0.6.2.
=> Update Molinillo to 0.6.2

lib/bundler/cli.rb, lib/bundler/cli/cache.rb, lib/bundler/cli/package.rb, lib/bundler/feature_flag.rb, lib/bundler/source/git.rb, lib/bundler/source/path.rb, spec/cache/git_spec.rb, spec/cache/path_spec.rb, spec/commands/package_spec.rb, spec/install/deploy_spec.rb, spec/install/gemfile/git_spec.rb, spec/lock/lockfile_bundler_1_spec.rb, spec/lock/lockfile_spec.rb, spec/plugins/source/example_spec.rb
This is going to be the last set of changes to defaults in Bundler 2.
@colby-swandale @indirect are there other changes I should be making here?
=> Default to packaging all on 2.0

task/release.rake
The problem was we spend all this time writing up an awesome changelog, yet don't have proper GitHub releases.
Closes https://github.com/bundler/bundler/issues/4904.
My diagnosis was we needed to automate creating new GH releases, and tie that into the existing `rake release` process.
I've already taken the liberty of backfilling existing releases, see https://github.com/bundler/bundler/releases/tag/v1.14.5 for an example
=> [Rakefile] Add a task to generate GitHub releases

lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
See https://github.com/CocoaPods/Molinillo/releases/0.6.3.
=> Update vendored Molinillo to 0.6.3

.travis.yml
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/
https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-4-2-released/
=> update ruby version to v2.3.4 to v2.3.5, v2.4.1 to v2.4.2

lib/bundler/rubygems_gem_installer.rb, spec/support/artifice/compact_index.rb
Currently in travis CI specs are failing intermittantly and makes merging code into master difficult. See: 
* https://github.com/bundler/bundler/pull/6080
* https://github.com/bundler/bundler/pull/6059
=> Fix flaky tests

lib/bundler/deprecate.rb, lib/bundler/psyched_yaml.rb
This, along with https://github.com/rubygems/rubygems/pull/2034, should get tests passing again 🙌
=> Avoid RubyGems psych warning breaking the tests

CHANGELOG.md
When reviewing the CHANGELOG, it is difficult to navigate to the issue
or pull request that is relevant to the CHANGELOG item.
The CHANGELOG should link to the referenced pull request/issue.
I added links to all of the issues referenced via BSD `sed`:
```
sed -i'' -Ee "s/#([0-9]+)/[#\1](https:\/\/github.com\/bundler\/bundler\/issues\/\1)/g" CHANGELOG.md
```
=> Link Issues and Pull Requests in the CHANGELOG

lib/bundler/cli/plugin.rb, lib/bundler/plugin.rb, lib/bundler/plugin/index.rb, spec/bundler/plugin_spec.rb
Hi guys, can someone do an early review in this PR? It is a work in progress to implement the `bundle plugin list` command. I'll commend some parts of the code where I specifically need help. Thanks!
=> add `bundle plugin list` command

lib/bundler/cli/plugin.rb, lib/bundler/plugin.rb, lib/bundler/plugin/index.rb, spec/bundler/plugin_spec.rb, spec/plugins/list_spec.rb
This is a continuation of PR #5672  which was originally created to fix Issue #5467 
Fixes a typo from the last PR, and add additional test files to check Bundler::Plugin#list
=> Add plugin list command

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb, lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
The problem was uncovered in #6114.
My fix updates molinillo to 0.6.4.
See https://github.com/CocoaPods/Molinillo/releases/tag/0.6.4 for release notes.
=> Update vendored Molinillo to 0.6.4

spec/resolver/basic_spec.rb
=> Fix typo in spec name

.travis.yml, Rakefile
Since I just released 2.7.0, we now have to test against it!
=> [Travis] Test against RubyGems 2.7.0

spec/bundler/fetcher_spec.rb, spec/spec_helper.rb, spec/support/builders.rb, spec/support/rubygems_ext.rb
In Dec 2017, 1-16-stable branch of Travis was broken caused outside condition. I try to fix it.
=> Fix broken status on Travis CI

spec/commands/exec_spec.rb, spec/commands/newgem_spec.rb, spec/commands/pristine_spec.rb, spec/install/gemfile/sources_spec.rb, spec/runtime/gem_tasks_spec.rb, spec/runtime/require_spec.rb, spec/runtime/setup_spec.rb, spec/runtime/with_clean_env_spec.rb, spec/spec_helper.rb, spec/support/hax.rb
This pull-request and branch are only investigation for Travis.
=> Fix test failure with new bundler version and default gems of bundler

spec/support/rubygems_ext.rb
Fixes https://travis-ci.org/bundler/bundler/jobs/320785817
=> Re-order gem dependency for Ruby 1.8 build matrix.

README.md
Old badge shows status unknown, so replace it with new maintainability badge
=> Fix codeclimate badge

spec/bundler/definition_spec.rb, spec/commands/binstubs_spec.rb, spec/install/gemfile/sources_spec.rb, spec/install/gems/flex_spec.rb, spec/install/post_bundle_message_spec.rb, spec/lock/lockfile_spec.rb
Followed up https://github.com/bundler/bundler/pull/6226
=> Fix failing examples with Ruby 2.5

man/bundle-binstubs.ronn, man/bundle-check.ronn, man/bundle-config.ronn, man/bundle-exec.ronn, man/bundle-gem.ronn, man/bundle-init.ronn, man/bundle-inject.ronn, man/bundle-install.ronn, man/bundle-lock.ronn, man/bundle-outdated.ronn, man/bundle-package.ronn, man/bundle-show.ronn, man/bundle-update.ronn, man/bundle-viz.ronn, man/bundle.ronn, man/gemfile.5.ronn
The problem was links to many of our man pages were broken.
Closes https://github.com/bundler/bundler-site/issues/355.
My diagnosis was we were omitting the section in the link ID.
My fix manually updates the link IDs to be correct.
=> [Man] Audit links to other manpages

lib/bundler/cli/gem.rb
To avoid human-in-the-middle attacks
=> Update unencrypted http links to https

bundler.gemspec
Just adding myself and Hiroshi-san to the list of authors in the Bundler gemspec
\cc @indirect
=> add the new team members of the bundler core team to the author list in the Bundler gemspec

CODE_OF_CONDUCT.md
package.community has done a terrific job with their clear explanation
of what enforcing a CoC looks like. Bundler is a better place when
everyone knows what kind of behavior is expected, and what will happen
if those expectations are not met, for whatever reason.
=> Add enforcement steps and examples to the CoC.

doc/contributing/README.md
...the contributor guide was is too long and too confusing. It was difficult to determine what information needed to be reviewed in what sequence. We wanted to make the guidelines easy to read and easy to follow.
...to condense the information 
My fix...
to condense the information presented and truncate the number of sections. See changes:
...it's a quick win!
=> Update Bundler Contributor Guidelines README

doc/POLICIES.md, doc/README.md
This isn't intended to be authoritative, but it's a start!
=> Add a POLICIES document

.github/welcome_message.md
Broken link to contributing doc in bot response
Corrected the link
Fixes #6332
=> Fix link to contributing doc

lib/bundler/definition.rb, spec/commands/update_spec.rb
Fixes https://github.com/bundler/bundler/issues/6350.
Kudos to @segiddins for the test.
=> Handle updating a specific gem for a non-local platform

lib/bundler/resolver/spec_group.rb
The problem was this ivar was unused.
My diagnosis was we should remove it. For performance, you know.
=> [SpecGroup] Remove unused ivar

man/bundle.ronn
I did a cursory review of the `bundle help` doc to make sure the language still made sense. Everything still made sense, but I wanted to remove redundant phrases that could confuse users, and just tightened up punctuation.
My fix...
...was to make some small tweaks in capitalization, punctuation, and remove redundant phrasing that could confuse users.
...simple to implement :)
=> Made small copy tweaks, removed redundant phrasing

.travis.yml, Rakefile
My local tests don't match Travis environment, since I use ruby 2.5.1 but travis doesn't.
My diagnosis was that we should be testing against the latest patch level releases.
My fix is to update versions.
I chose this fix because I can't think of another fix.
=> Ci against latest versions

lib/bundler/cli/update.rb
This pr updates the messaging for bundle update. Fix for #6584 .
=> Reword bundle update regression message

lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb, lib/bundler/vendor/molinillo/lib/molinillo/errors.rb, lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
See https://github.com/CocoaPods/Molinillo/releases/0.6.6
=> Update vendored Molinillo to 0.6.6

spec/runtime/setup_spec.rb
The problem was that some specs could be more readable and clean.
My diagnosis was that some stuff could be more explicit, some TODO's could be removed because they're already fixed, and there should not be typos.
My fix is to make the obvious changes to fix what I diagnosed.
I chose this fix because it makes the specs clear, in my opinion.
=> Clean up some specs

task/release.rake
The problem was andre updated @bundlerbot and it makes merges with a new message now
My diagnosis was the merge message had changed
My fix update a regexp or two
=> Update for new bors merge commit message

.github/bors.toml
Use a fancy new Bors feature to delete merged branches automatically, hooray.
=> delete merged branches automatically

spec/commands/show_spec.rb, spec/spec_helper.rb
#6743 was failed with ruby core repository and ignored working example.
I fixed them.
=> Followed up #6743

spec/spec_helper.rb
I found the missing commits in 1-17-stable branch. 
I picked 110f841537f96649983b24b3ad002989e7143f26 from master branch.
=> Merge #6741 for 1-17-stable.

.travis.yml
The problem was that CI in #6938 is failing, and I'm not sure why.
My diagnosis was that I should split the two changes made in that PR to find out the culprit.
My fix is to split the TravisCI update to xenial, because my guess is that this is not the culprit, so if the build is green, we can merge this and upgrade :tada: 
I chose this fix because it means no work for me, just delegate to TravisCI. :)
=> Bump TravisCI build to Xenial

.travis.yml, Rakefile
The problem was that I have some spec failures locally, and they don't seem to be reproduced in TravisCI.
My diagnosis was that either my environment is messed up or there's some issues with the latest rubygems + ruby combination.
My fix is to use latest rubygems and ruby in Travis, so I can double check whether the problem is just my environment or a real problem.
I chose this fix because it's always good practice to test against the latest versions of your dependencies.
=> Bump rubygems to 3.0.2 and ruby to 2.6.1 in TravisCI

spec/support/rubygems_ext.rb
The problem was that we were using some outdated test dependencies.
My diagnosis was that we can upgrade them, since the comments justifying them being pinned are no longer relevant.
My fix is to unpin the dependencies, and remove the comments no longer applying.
I chose this fix because it was the only fix I could think of.
=> Dependency review

spec/bundler/bundler_spec.rb, spec/support/rubygems_ext.rb
The problem was that we have some really legacy code in our specs.
My diagnosis was that we forgot to remove/update these bits when dropping support.
My fix is to remove the legacy code.
I chose this fix because it's the only fix, really.
=> Remove old 1.8.7 remanents

.travis.yml, Rakefile
The problem was not testing against the latest and greatest rubygems.
My diagnosis was rubygems is outdated since the latest security releases.
My fix is to update the tested rubygems.
I chose this fix because it's the only fix.
=> Bump rubygems in CI

bundler.gemspec
The problem is that I just can't find where this development dependency is used. Furthermore, I can't find where it was used in the past :S
My diagnosis was that maybe it's never been used?
My fix is to remove the dependency.
I chose this fix because the less dependency, the better.
=> Remove mustache dep

spec/commands/exec_spec.rb
The problem was that I discovered by chance that one of the skipped specs seems to be passing.
My diagnosis was that something has changed for the better that made this spec green.
My fix is to remove the skip.
I chose this fix because it's good :)
=> Unskip passing spec

doc/contributing/BUG_TRIAGE.md, lib/bundler/compact_index_client/updater.rb, lib/bundler/rubygems_ext.rb, lib/bundler/settings.rb, lib/bundler/shared_helpers.rb, lib/bundler/version.rb, lib/bundler/yaml_serializer.rb, spec/install/gemfile/git_spec.rb, spec/install/gemfile/platform_spec.rb, spec/support/artifice/compact_index.rb
The problem was that there was still some code specific for old rubies in our code base.
My fix is to remove that code.
=> Cleanup old rubies stuff

.travis.yml
The problem was that new rubies have been released, and we're not yet testing against them,
My fix is to update our CI matrix.
=> Bump CI rubies to latest patch levels

man/bundle.ronn
Hi there! I skipped all the questions the template asked, since this is a kinda silly PR. 🌻
=> Fix typo in file extension

bundler.gemspec, lib/bundler/rubygems_ext.rb, lib/bundler/rubygems_integration.rb, lib/bundler/shared_helpers.rb, lib/bundler/stub_specification.rb
The problem was we still have unnecessary code for compatiblity with rubygems versions we no longer support.
My diagnosis was that we can remove this code.
My fix is to remove it.
=> More compatibility cleanup

bundler.gemspec
There was not a problem, just some housekeeping.
I wanted to see if bumping the latest Rubocop version would bring in any new fixes or updates. It did not but I figured it didn't hurt to bump the version in case new PRs are affected by the new cops.
I bumped the patch version of RubCop by 1.
I chose this fix because it was the only logical thing to do.
=> Bump Rubocop version

lib/bundler/cli/add.rb
The problem was no problem just code refactors.
My diagnosis was the possibility to reorganize the code to make clean and more readable.
My fix reorganize the code, good usage of the attributes.
=> Refactors to `bundle add`

spec/install/gemfile/sources_spec.rb
The problem was that some specs had harcoded paths from @indirect's file system. :sweat_smile:. These lockfiles are clearly incorrect but specs are not failing.
My diagnosis is that these lockfiles are unnecessary for these tests and don't affect what these tests are testing.
My fix is to remove the lockfiles.
As a consequence of the change, the "comment numbering" got messed up. So I removed the numbering while keeping the comments to avoid that problem from happening again in the future.
=> Minor spec improvements

.azure-pipelines/steps.yml
The problem was that Azure CI is now failing.
My diagnosis was that the ruby version was upgraded, and as a consequence, a hardcoded path in our configuration no longer exists.
My fix is to update the path and to be more explicit about the ruby version we want to use, so that this doesn't happen again.
I chose this fix because it fixes the problem, and prevents it from happening in the future.
=> Fix azure CI issue

spec/bundler/dsl_spec.rb, spec/bundler/shared_helpers_spec.rb, spec/commands/exec_spec.rb
I merged the current master branch into ruby/ruby repository. Some of the tests are failing because the current code is not working with ruby core repository.
The failing examples specified the bundler/bundler repository structure and not worked with a recent version of Ruby.
Added the condition of the structure of ruby core repository and better handles the exception.
There are no other options.
=> Backport the commits from ruby/ruby

lib/bundler/dependency.rb, spec/bundler/dsl_spec.rb
=> Added Ruby 2.6 to dsl.

lib/bundler/source/git/git_proxy.rb
The problem was that git proxy helpers had a few pending TODOs.
My diagnosis was that we should get the TODOs done, because now they can be done.
My fix is to fix the TODOs by migrating git proxy helpers to use `Open3` instead of backticks.
I chose this fix because it works.
=> Migrate git proxy helpers to use Open3

.travis.yml, Rakefile
The problem was that we should make sure everything is ok with the most recent rubygems releases.
My fix is to upgrade the rubygems versions in our CI.
=> Bump rubygems in CI to 3.0.4 and 2.7.10

Rakefile, spec/bundler/plugin/installer_spec.rb, spec/commands/clean_spec.rb, spec/commands/config_spec.rb, spec/commands/exec_spec.rb, spec/install/gemfile/git_spec.rb, spec/runtime/setup_spec.rb, spec/spec_helper.rb
This is a bunch of miscelaneous commits that fix and improve some stuff in our test suite. I could open separate PRs for them but they are so small that I figured I could compile them all on a single PR.
=> Spec improvements

README.md, doc/POLICIES.md, doc/contributing/BUG_TRIAGE.md, doc/contributing/COMMUNITY.md, doc/contributing/GETTING_HELP.md, doc/contributing/HOW_YOU_CAN_HELP.md, doc/contributing/README.md, doc/development/NEW_FEATURES.md, doc/documentation/README.md, lib/bundler/templates/newgem/README.md.tt, spec/quality_spec.rb
I'm not really sure of the exact context when I made these changes, but I recall I was getting some invalid encoding errors somehow, and they turned out to be an estraneous `’` quote in one of the documentation files.
My diagnosis was that we should not include this character anywhere, but instead use regular quotes.
My fix is to add a quality spec for this, and while I was at it, I added some improvements to quality specs in general.
=> Improve quality specs

lib/bundler/cli/outdated.rb, spec/commands/outdated_spec.rb
Code in `bundle outdated` code be simpler and more readable.
My fix is to refactor the command.
=> Refactors to `bundle outdated`

spec/support/artifice/endpoint.rb, spec/support/artifice/endpoint_500.rb, spec/support/artifice/windows.rb, spec/support/rubygems_ext.rb
The problem was that some test dependencies, sinatra and rack in particular, were outdated.
My diagnosis was that we should use the latest versions.
My fix is to upgrade them. Both of them seem 100% compatible with respect to our test suite because there seems to be now failures, even though there was a note suggesting the opposite.
=> Bump test deps

spec/commands/exec_spec.rb, spec/support/helpers.rb, spec/support/path.rb
The problem was that this particular spec is like a nightmare that keeps on failing whenever we make changes to bundler, and we keep adding workarounds to it.
My diagnosis was that I should investigate closer what's going on with this spec, and fix it in a better way.
My fix is to fix several issues with the spec, and to essentially revert it back to the way it looked before https://github.com/bundler/bundler/commit/e63e844bc7444c6a489fcde0dc7011c6c4807edd. See each commit for more details.
I chose this fix because it should make it less painful to keep CI green as we make changes to bundler.
=> Fix spec working by chance

doc/playbooks/RELEASING.md, task/release.rake
The problem was that I'm not sure how to release bundler.
My diagnosis was that the part about how to handle the changelog is the most unclear step.
My fix is to _guess_ how we are currently managing that, and document that.
I chose this fix because it improves our docs, while starting a PR at the same time where I can incorporate feedback if this is not the right way.
While I read the release scripts, I also added a couple of improvements to the `rake release:open_unreleased_prs` task.
=> Document changelog handling for releases

spec/commands/clean_spec.rb, spec/support/path.rb
The problem was typos.
My fix is to correct typos.
=> Fix a couple of typos

.rspec_parallel, Rakefile, bin/parallel_rspec, spec/bundler/source_spec.rb, spec/runtime/load_spec.rb, spec/support/parallel.rb, spec/support/path.rb, spec/support/rubygems_ext.rb
This branch reduced test time of bundler.
#7232 has a conflict with the current master branch.
I picked a commit for parallelized tests from #7232 
Fixed https://github.com/bundler/bundler/pull/7232
=> Parallelize test suite (Take 2)

spec/bundler/ruby_version_spec.rb, spec/runtime/with_unbundled_env_spec.rb
The problem was that our specs print some warnings to screen.
My diagnosis was that specs should have a clean output.
My fix is to remove the warnings.
=> Fix spec warnings

lib/bundler/version.rb
The problem was that I forgot to merge the version increase back to master after release.
My fix is to bump it.
=> Bump version to latest pre-release

spec/commands/newgem_spec.rb, spec/spec_helper.rb
The problem was that I rebased #6455 and I had trouble getting the specs to pass.
My diagnosis was that the new gemspecs could use a refactor.
My fix is to refactor these specs so that they are easier to read and modify.
=> Refactor new gem specs

lib/bundler/rubygems_integration.rb
The problem was that I found some dead code.
My fix is to remove it because it's dead.
=> Remove rubygems integration dead code

lib/bundler/cli/pristine.rb, lib/bundler/source/git.rb, spec/commands/pristine_spec.rb
=> Ignore local overrides for bundle pristine

spec/commands/version_spec.rb, spec/support/path.rb
The problem was that we haven't incorporated recent fixes for integration in ruby-core.
My fix is to cherry-pick the fixes.
=> Backport ruby-core changes

azure-pipelines.yml, spec/bundler/env_spec.rb, spec/install/gems/resolving_spec.rb, spec/install/redownload_spec.rb, spec/runtime/setup_spec.rb, spec/support/artifice/compact_index.rb, spec/support/artifice/compact_index_api_missing.rb, spec/support/artifice/compact_index_extra_api_missing.rb, spec/support/artifice/compact_index_extra_missing.rb, spec/support/artifice/endpoint.rb, spec/support/artifice/endpoint_api_missing.rb, spec/support/artifice/endpoint_extra_missing.rb, spec/support/artifice/windows.rb, spec/support/builders.rb, spec/support/rubygems_ext.rb
The problem was that we have a bunch of spec failures on Windows (~315).
My fix is to improve some stuff to be more OS-independent. This should bring the failures down to ~305.
=> Windows spec fixes

.rubocop.yml, spec/bundler/fetcher_spec.rb, spec/support/rubygems_ext.rb
The problem was not really a problem, but it's good to keep our dependencies up to date.
My fix is to bump rubocop and rubocop-performance.
=> Bump rubocop and rubocop-performance

CHANGELOG.md, lib/bundler/version.rb
The problem was that version and changelog need to be cherry-picked from the stable branch.
My fix is to do just that.
=> Merge changelog and version bump back to master

.travis.yml, CHANGELOG.md, Rakefile, lib/bundler/cli/exec.rb, lib/bundler/rubygems_integration.rb, lib/bundler/setup.rb, lib/bundler/version.rb, spec/commands/exec_spec.rb
The problem was I want to get regression fixed as soon as possible to reduce impact.
My fix is to release what we have already fixed as soon as possible.
=> Release 2.1.1

CHANGELOG.md, lib/bundler/version.rb
The problem was changelog and version bump not yet in master.
My fix is to merge back changelog and version bump after the release from the stable branch.
=> Bump version and changelog after release

.travis.yml, CHANGELOG.md, Rakefile, lib/bundler/rubygems_integration.rb, lib/bundler/version.rb, spec/runtime/setup_spec.rb, task/release.rake
The problem was that I want to ship [a small regression fix](https://github.com/bundler/bundler/pull/7505), and also so tweaks to the development environment (#7506) that I want to use in the rubygems side to fix the CI errors in https://github.com/rubygems/rubygems/pull/3043.
My fix is to release 2.1.2
=> Release 2.1.2

CHANGELOG.md, lib/bundler/version.rb
The problem was master branch doesn't yet include the version bump and changelog from 2.1.2.
My fix is to include those.
=> Bump version and changelog

CHANGELOG.md, lib/bundler/inline.rb, lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb, lib/bundler/version.rb, spec/commands/pristine_spec.rb, spec/install/gemfile/gemspec_spec.rb, spec/plugins/source/example_spec.rb, spec/runtime/inline_spec.rb, spec/runtime/require_spec.rb, spec/runtime/setup_spec.rb, spec/support/builders.rb, spec/support/matchers.rb
This PR gets out there two more bug fixes in the 2.1 line. Specifically #7529 and #7537.
=> Release 2.1.4

.github/workflows/windows.yml, .travis.yml, Rakefile, spec/spec_helper.rb, spec/support/rubygems_ext.rb
The problem was that specs are slow.
My fix is to run them in parallel.
We enabled this a while ago, but run into some issues. I want to try again.
=> Enable parallel specs again

.github/bors.toml, .github/workflows/windows.yml, spec/bundler/cli_spec.rb, spec/bundler/env_spec.rb, spec/bundler/mirror_spec.rb, spec/commands/binstubs_spec.rb, spec/commands/cache_spec.rb, spec/commands/exec_spec.rb, spec/commands/help_spec.rb, spec/commands/install_spec.rb, spec/install/allow_offline_install_spec.rb, spec/install/deploy_spec.rb, spec/install/gemfile/gemspec_spec.rb, spec/install/gemfile/git_spec.rb, spec/install/gemfile/path_spec.rb, spec/install/gemfile/platform_spec.rb, spec/install/gems/compact_index_spec.rb, spec/install/gems/dependency_api_spec.rb, spec/install/gems/resolving_spec.rb, spec/install/gems/standalone_spec.rb, spec/install/gemspecs_spec.rb, spec/install/git_spec.rb, spec/install/global_cache_spec.rb, spec/lock/lockfile_spec.rb, spec/runtime/executable_spec.rb, spec/runtime/inline_spec.rb, spec/runtime/require_spec.rb, spec/runtime/setup_spec.rb, spec/runtime/with_unbundled_env_spec.rb, spec/support/helpers.rb
The problem was that, although we have a Windows CI, errors are ignored, so whenever we break something on Windows, we don't notice, and having a CI become useless.
My diagnosis was that we should make the Windows CI required.
My fix is to actually go ahead and fix some issues, and skip the rest.
=> Enforce Windows CI

UPGRADING.md
Fixed some issues in UPGRADING.md. I am not sure the link https://github.com/bundler/bundle-viz should be removed or not, but it could make readers confused (like me), so I removed it. It should be reverted when the link is available.
=> Tweak UPGRADING.md

README.md
n/a
repository was transferred and url changed. 
update badge url for travis-ci in README.md
n/a
=> Fix travis-ci badge status

man/bundle-config.1, man/bundle-config.1.txt, man/bundle-config.ronn
Fixes #7085
The problem was missing documentation.
N/A
Provided some documentation.
N/A
=> Adds documentation for BUNDLE_APP_CONFIG env var

lib/bundler/cli/issue.rb, lib/bundler/friendly_errors.rb, lib/bundler/source/git/git_proxy.rb, spec/bundler/friendly_errors_spec.rb
This PR updates URLs pointing to the old repo in various error messages.
=> Update GitHub URLs in error messages.

doc/contributing/HOW_YOU_CAN_HELP.md
This PR updates the CodeClimate link in `doc/contributing/HOW_YOU_CAN_HELP.md`, now that #7581 ("Update CodeClimate to use correct repository") is resolved.
=> [docs] Update CodeClimate link.
