rubygems/bundler

- lib/bundler/resolver.rb
- spec/install/gemfile/sources_spec.rb
The problem was the "source priority" in ambiguous source situations was ... ambiguous.
My diagnosis was we should error and require a user explicitly pin the dependency to a source in those situations, rather than leaving the source used up to an implementation detail.
My fix attempts to implement the priority described in the conversation in https://github.com/bundler/bundler/issues/4629.
I chose this fix because it still allows using the default source as a backup, while only taking the "relevant" sources into account, so that the error/warning is not overzealous.
> [2.0] [Resolver] Error when it is ambigous which transitive source a gem should come from

- lib/bundler/resolver.rb
- spec/resolver/basic_spec.rb
- spec/support/indexes.rb
The problem was that a pre-release version was being installed when the user hadn't asked for one, and a non-prerelease install was possible.
My diagnosis was that this was caused by the change to the way pre-releases get selected for resolution when we moved to Molinillo 0.6.0. See the change to `lib/bundler/index.rb` in https://github.com/bundler/bundler/pull/5902.
My fix... isn't present yet. Basically we want to replicate the `wants_prerelease || only_prerelease` behaviour in `Bundler::Resolver#requirement_satisfied_by?`, but it's late and I haven't thought about how to do that yet. Instead, here's a failing spec.
I chose this fix because it's late and I haven't thought about how to fix this yet, but I at least wanted it flagged.
> Add spec that pre-release versions aren't selected when not in the Gemfile

- lib/bundler/compact_index_client/updater.rb
- spec/bundler/compact_index_client/updater_spec.rb
Fixes #5518
A user had issues installing gems due to a permissions issue on the temp dir, because
Bundler was not checking for proper permissions on the temp directory or $HOME.
After discussing the issue with @colby-swandale, the solution was to check permissions on $HOME and the ```tmpdir```.
The creation of the [temp dir](https://github.com/bundler/bundler/blob/master/lib/bundler/compact_index_client/updater.rb#L31) is now wrapped in the block passed to ```filesystem_access```, so ```filesystem_access``` will rescue the ```Errno::EACCES``` exception which is thrown if the effective user of the bundler process doesn't have sufficient permissions to create the temp dir.
I chose this fix because it's what was discussed in the original issue thread.
> ensure $HOME and Dir.tmpdir are writable

- spec/bundler/vendored_persistent_spec.rb
since we now test what happens if `socket` is `nil`, and `rspec-mocks` warns when we do that
> Avoid warning for stubbing `nil`

- lib/bundler/env.rb
- spec/bundler/env_spec.rb
We've been printing the version of OpenSSL that Ruby was compiled against, but not the version that was dynamically linked at runtime, which is a huge potential issue. While I was there, I added a few more things that seemed helpful.
> Expand `env` output

- bin/bundle1
- lib/bundler/definition.rb
- lib/bundler/fetcher/dependency.rb
- lib/bundler/index.rb
- lib/bundler/resolver.rb
- lib/bundler/source.rb
- lib/bundler/source/rubygems.rb
- lib/bundler/spec_set.rb
- spec/install/gems/compact_index_spec.rb
- spec/install/gems/dependency_api_spec.rb
- spec/support/artifice/endpoint.rb
The problem was installing `source "https://rubygems.org"; gem "rack"` could cause bundler to make requests for _hundreds_ of specs, drastically slowing down installation. This was a regression in 1.16 caused by the new source pinning logic.
My diagnosis was the "double checking" step of creating the definition's index was accidentally saying Bundler needed to download specs for _every gem installed_, along with their dependencies _for every version in existence_.
My fix narrows down the set of names that need to be double-checked for to (a) only those that could possibly be needed for resolution (b) and only those specs that could possibly come from many sources (i.e. are "unpinned")
I chose this fix because it takes that `rack` gemfile back down to __2__ requests: `/versions` and …
> Avoid making unnecessary network requests fetching specs

- lib/bundler/settings.rb
- spec/bundler/cli_spec.rb
The problem was people were getting confused by the terseness and bluntness of the current outdated bundler version warning.
My diagnosis was we need to spend time fine-tuning the message, including when it is displayed. But given the lack of time to do so immediately, I thought it best to disable the warning for now, until someone can make a PR that addresses the comments and concerns raised in #6004.
> [CLI] For now, disable the new version warning by default

- lib/bundler/cli.rb
- lib/bundler/cli/common.rb
- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
The problem was
> outdated would be more consistent to change --strict to --filter-strict and --update-strict to --strict
My diagnosis was
> let's rename --strict to --filter-strict and rename the current --update-strict to --strict. In another ticket, later, we can expand the way outdated works to not need as many flags to show the relevant info
My fix switches around the options, by just making `--strict` an alias that means something different on 2.0 than on 1.0
I chose this fix because it allowed keeping temporary 1.x compatibility, versus wholesale renaming of the option.
> [CLI] Switch around the --strict option for bundle outdated

- lib/bundler/source/rubygems.rb
- spec/install/failure_spec.rb
The problem was the user could (once) have downloaded a `.gem` file that isn't actually a `.gem`, and that package would poison their cache.
Closes https://github.com/bundler/bundler/issues/5941.
My diagnosis was we should remove the `.gem` right after downloading it if we can't open it.
My fix `rm_rf`'s the `.gem` on failure.
I chose this fix because it won't accidentally nuke existing cache entries for a user, but it should help prevent Bundler propagating an issue.
> [Source::Rubygems] Remove .gem if downloaded package is invalid

- lib/bundler.rb
- lib/bundler/plugin.rb
- lib/bundler/settings.rb
- spec/bundler/bundler_spec.rb
As in #4333, users wanted a way to make Bundler respect the XDG specification.
The directory `~/.bundle` was hard-coded and could not be configured.
Allow users to configure `~/.bundle` and its relevant sub-directories by setting environment variables. The environment variables and their fallbacks are as follows:
| variable | fallback if unset |
|---|---|
| `BUNDLE_USER_HOME` | `$HOME/.bundle` |
| `BUNDLE_USER_CACHE`  | `$BUNDLE_USER_HOME/cache` |
| `BUNDLE_USER_CONFIG` | `$BUNDLE_USER_HOME/config` |
| `BUNDLE_USER_PLUGIN` | `$BUNDLE_USER_HOME/plugin` |
Unlike https://github.com/bundler/bundler/pull/5787, This solution is not specific to the XDG specification. Users have all kinds of setups, and this is a very general system for allowing them to configure their development machines …
> Allow user to override ~/.bundle with environment variables

- Rakefile
rubygems v2.6.12 has important security issues.
So, It's better to update v2.6.13 to rubygems.
http://blog.rubygems.org/2017/08/27/2.6.13-released.html
> update rubygems to v2.6.13

- lib/bundler/templates/newgem/README.md.tt
`bundle` command has been changed to display list of commands with Bundle 2.
```console
% bundle
Bundler version 2.0.0.dev (2017-09-29 commit 5e9c40aa1)
Bundler commands:
Primary commands:
bundle install [OPTIONS]    # Install the current environment to the system
bundle update [OPTIONS]     # Update the current environment
bundle cache [OPTIONS]      # Locks and then caches all of the gems into vendor/cache
bundle exec [OPTIONS]       # Run the command in context of the bundle
bundle config NAME [VALUE]  # Retrieve or set a configuration value
bundle help [COMMAND]       # Describe available commands or one specific command
(snip)
```
Therefore, it can not be installed with `bundle` command written in README.md created by `bundle gem`.
It is the same as above.
I think that it is better …
> Update newgem README.md template for Bundler 2

- Rakefile
No
My fix enable rubocop's parallel option.
This may improve rubocop's test time.
> use rubocop --parallel option

- man/bundle-install.ronn
Per feedback from @arbonap, we've added a sentence that briefly explains what binstubs is to the binstubs section.
The problem was...no understanding of what binstubs is. Added a quick two sentences!
My diagnosis was...we needed some language there. @arbonap and @indirect pointed this out and offered the explanations.
My fix...was to turn their explanations into simple language!
I chose this fix because...it'll help users understand binstubs better
> Added a sentence to `binstubs`

- lib/bundler/env.rb
`bundle env` uses the constant `Gem::ConfigFile::SYSTEM_CONFIG_PATH` which is not defined in early versions of RubyGems.
See: https://travis-ci.org/bundler/bundler/builds/276981165
While `SYSTEM_CONFIG_PATH` is not defined for earlier versions of RubyGems, a constant called `Gem::ConfigFile::SYSTEM_WIDE_CONFIG_FILE` does appear to be both in current and early versions of RubyGems which contains the path (plus the ruby config file) we want.
This fix is compatible with all the tested versions of RubyGems in CI and is not overly complex.
> Fix uninitialised constant Gem::ConfigFile::SYSTEM_CONFIG_PATH

- bundler.gemspec
- This WIP PR tries to solve Issue #6029 
- When running commands like `dbundle -v` as described in [SETUP.md](https://github.com/bundler/bundler/blob/master/doc/development/SETUP.md#development-setup), commands give us a git error.
- Like stated in Issue #6029, the git option `-C` should be used to pass the directory containing the gemspec file to the git command.
- to give git the correct directory path where the gemspec file is
My fix...
- I'm wondering if I'm on the right track with this? 
- So, I ran `bin/rspec /spec/install/gemfile/gemspec_spec` and the specs passed. I then run the entire test suite and the `gemspec_spec` and a few other specs fail throughout the test suite. 
Then, I re-ran the failing specs files individually-- both as a …
> Pass gemspec directory path to Git

- lib/bundler/gem_helper.rb
IO.popen with the command in an array doesn't need command line
quotes, and is safer.
Back-ticks with command line quoting is dangerous.
Back-ticks is not for complex purpose.
Use `IO.popen` and redirection option instead.
`IO.popen` and options of `spawn` have been introduced for such purpose.
> Call IO.popen instead of backticks

- doc/TROUBLESHOOTING.md
Doing the previous command from the TROUBLESHOOTING guide returns an error:
```sh
$ `gem update bundler`
zsh: command not found: Updating
```
Removing both ``` ` ``` in the documentation.
> Fix bundler update instructions in TROUBLESHOOTING

- spec/support/helpers.rb
It only needs with Ruby 1.8 and Ruby 2.5 will remove it.
This commit picked r60125 from ruby/ruby: https://github.com/ruby/ruby/commit/9de6c712b66aad77df40661c1fc6d37e9a5c251a
> Rename `-rubygems` option.

- lib/bundler/compact_index_client/cache.rb
- lib/bundler/compact_index_client/updater.rb
- lib/bundler/definition.rb
- lib/bundler/plugin/api/source.rb
- lib/bundler/runtime.rb
- lib/bundler/source/git.rb
- lib/bundler/source/rubygems/remote.rb
- lib/bundler/vendor/thor/lib/thor/runner.rb
- spec/bundler/plugin/api/source_spec.rb
- spec/bundler/source/rubygems/remote_spec.rb
- spec/commands/clean_spec.rb
- spec/plugins/source/example_spec.rb
- spec/spec_helper.rb
- spec/support/artifice/compact_index.rb
The problem was `digest` files would sometimes be loaded twice.
My diagnosis was we needed to load the `digest` files using the `::Digest` method, which is explicitly thread-safe.
> Load digest subclasses in a thread-safe manner

- lib/bundler/installer.rb
We're seeing several "assigned but unused variable" warnings when we run `bundle` in Ruby 2.5 with `RUBYOPT=-w`.
This is because Ruby 2.5's unused variable check has been improved since https://github.com/ruby/ruby/commit/37b04894f20a5d3701309a2055bfa03b9d760090, and [previous double-assignment technique](https://github.com/bundler/bundler/blob/fea177f61df71121c6f9422a74b093e42c504388/lib/bundler/installer.rb#L116) no longer works as an anti-warning workaround.
For example, here's a short reproducible code that doesn't warn in 2.4 but warns in 2.5:
```ruby
`def a() x = x = 1; end`
```
So here are updated workarounds against this warning, which are valid for both Ruby < 2.5 and >= 2.5.
> Fix "assigned but unused variable" warning in Ruby 2.5

- man/bundle-binstubs.ronn
There are some non-ascii characters in `man/bundle-binstubs.ronn` that is causing a build failure when `ronn` is compiling the man pages on linux
```
...
/usr/local/bin/ruby -S ronn --roff --pipe man/bundle-binstubs.ronn > man/bundle-binstubs.1
/usr/local/bundle/gems/ronn-0.7.3/lib/ronn/document.rb:192:in `split': invalid byte sequence in US-ASCII (ArgumentError)
from /usr/local/bundle/gems/ronn-0.7.3/lib/ronn/document.rb:192:in `sniff'
from /usr/local/bundle/gems/ronn-0.7.3/lib/ronn/document.rb:76:in `initialize'
from /usr/local/bundle/gems/ronn-0.7.3/bin/ronn:166:in `new'
from /usr/local/bundle/gems/ronn-0.7.3/bin/ronn:166:in `block in <top (required)>'
from /usr/local/bundle/gems/ronn-0.7.3/bin/ronn:166:in `map'
from /usr/local/bundle/gems/ronn-0.7.3/bin/ronn:166:in `<top (required)>' …
```
> remove non-ascii chars from binstubs man page

- lib/bundler/definition.rb
- spec/install/gemfile/gemspec_spec.rb
The problem was doubled informative message in verbose mode (#6028)
`Bundler::Definition#missing_specs?` clears the `@resolve` ivar due to
the fact that `ensure` clause evaluates regardless whether exception
occurred. That results in repeated resolution, and, therefore, in
repeated debug messages.
This change moves ivars clearing into the `rescue` clause, so
`@resolve` will be cleared only in case when `BundlerError` occurs
I chose this fix because running deps resolution twice is a bad idea anyway and it needs to be prevented.
> Fix doubled message in verbose mode

- lib/bundler/cli/exec.rb
- lib/bundler/friendly_errors.rb
- spec/commands/exec_spec.rb
Avoid rescue of SignalException in kernel_load and with_friendly_errors This allows SignalException to be handled gracefully by the ruby interpreter.
This supersedes #6091.
Fixes #6090
CLI::Exec#kernel_load should not rescue the SignalException. Neither should with_friendly_errors, so it unwinds all the way to the ruby interpreter. 
Two rescue and re-raises specific to SignalException.
My first naive attempt was #6091, where I had missed the outer rescue in with_friendly_errors, all of the other special friendly error behavior, and the spec dependencies. While I still suspect that kernel_load and friendly_errors might be rescuing/handling more than they should (for comparison: binstub doesn't do this) this is a much more minimal, safer, and easier fix to #6090.
> Avoid bundle exec rescue of SignalException

- task/release.rake
None, I just happened to find this misspelling.
My diagnosis was that it was a simple typo.
My fix is a local variable rename.
> release.rake: Fix typo in variable name

- doc/development/SETUP.md
Some distrobutions of linux do not ship with the `col` command which `ronn` requires. And there are also some code blocks that don't need to quoted.
Update the developer docs to include instruction to install the package that has the `col` command and remove the code block quotes that don't need to be there.
> improve development setup docs and remove redundant quotes

- bundler.gemspec
- lib/bundler/compact_index_client/cache.rb
- lib/bundler/compact_index_client/updater.rb
- lib/bundler/definition.rb
- lib/bundler/plugin/api/source.rb
- lib/bundler/rubygems_gem_installer.rb
- lib/bundler/runtime.rb
- lib/bundler/shared_helpers.rb
- lib/bundler/source/git.rb
- lib/bundler/source/rubygems/remote.rb
The problem was, under ruby 2.5, Bundler would activate digest, which is now a stdlib gem, preventing users from choosing a different version.
With this change, the travis build against trunk should go green, hopefully.
My diagnosis was we needed to lazy-load digest.
My fix removes all `require "digest"` top-level statements from the Bundler codebase, and replaces the top-level `Digest` method with one that will `require "digest"`.
I chose this fix because it would keep the use of digest classes thread-safe.
\c @hsbt
>  Avoid activating stdlib digest under Ruby 2.5

- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
The problem was `bundle outdated --group NAME` wouldn't work if it was the second group for the dependency.
Closes #6115.
My diagnosis was we were joining with `, ` and splitting on `,`, so subsequent groups had an additional space.
> [Outdated] Support --group with the second group for a dependency

- spec/plugins/list_spec.rb
The problem was failure of Travis CI build. (refs: [build for #6123](https://travis-ci.org/bundler/bundler/builds/292436821?utm_source=github_status&utm_medium=notification))
Bundler::Plugin::Index#installed_plugins is keys of Hash,
and Hash is not ordered in prior to Ruby 1.9.
`foo` and `bar` plugins defined in spec are not always listed in specified order.
My fix is to separate tests into for Ruby < 1.9 or not.
I chose this fix because this makes code easy to remove if we stop building Ruby < 1.9 in Travis CI.
> Fix failing spec for `bundle plugin list`

- lib/bundler/templates/newgem/newgem.gemspec.tt
Need to remove a leading blank line of generated gemspec.
```erb
<%- if RUBY_VERSION < "2.0.0" -%>
<%- end -%>
lib = File.expand_path("../lib", __FILE__)
...
```
When executing `bundle gem xxx` with ruby (< 2.0), the leading blank line is appeared.
Move a blank line into the `if` block.
😃
> Remove a blank line in generated gemspec for RUBY_VERSION >= "2.0.0"

- lib/bundler/installer.rb
- lib/bundler/resolver.rb
- spec/resolver/basic_spec.rb
- spec/support/indexes.rb
Calling `bundle update github-pages` on https://github.com/Floppy/cv was causing a downgrade in the `github-pages` version.
The `Bundler::Resolver#sort_dependencies` method didn't have any logic to prioritise explicitly requested gems. Therefore, where two rival resolutions were possible (in this case one with `activesupport` at 5.1.4 and `github-pages` at 24, and one with `github-pages` at 166 and `activesupport` at 4.2.9), Bundler didn't always correct the most desirable resolution.
My fix is to explicitly prioritise requested gems in the dependency sort order during resolution.
I chose this fix because it's intuitive.
> Prioritise explicitly requested gems in dependency resolution sort order

- lib/bundler/source/git/git_proxy.rb
Fixes an issue on 2.5.0-dev where using local git overrides would cause an exception because the default bundler had been loaded
The problem was Bundler was failing 8 specs against ruby trunk.
My diagnosis was when the autoload for `URICredentialsFilter` fired in a `chdir` block, the default bundler gem was getting activated.
My fix eagerly trips that auto-load in the git proxy.
I chose this fix because it's a one-liner.
> Ensure that autoloads are resolved in the real working directory

- lib/bundler/resolver.rb
The problem is described in #6114 - An unusually large set of conflicting dependencies leads to bundler get stuck and lead to very unhealthy amounts of memory and CPU time be consumed. 
This happens because because a too large array is fed into Array#combination in the "reduce_trees" lambda in `version_conflict_message`. 
By simply bailing out when the conflict set is bigger than a certain size,
we'll get a result that is similar to what happened in earlier bundler versions
but skip a ton of CPU cycles and memory allocations.
I've chosen the limit rather unscientifically by playing around with the result
set sizes. 15 seems to be a good compromise but really anything larger than 10
should work (and with work I mean "should not usually not have to be invoked").
Reducing the conflict trees …
> Bail out of reducing depency trees on huge dependency conflict sets

- man/bundle-gem.ronn
In the `man/bundle-gem.ronn`, we are using a hard-coded version number to link the `bundle-config` doc, which is `v1.14` in this case. Ref: https://bundler.io/v1.16/man/bundle-gem.1.html
<del>This commit updates the link and uses a relative path so it will always point to the recent version.</del>
Edit: This commit updates the link to the current stable version.
> Update `config` page link to the recent version

- lib/bundler/cli/update.rb
- spec/commands/update_spec.rb
#6156: NoMethodError: undefined method `version' for nil:NilClass 
The `bundler` gem does not participate in the lockfile, but it can still be included in the list of dependencies that are being updated by `bundle update` if `--group` is specified.
For example, if a Gemfile contains `bundler-audit` (which depends on `bundler`) in the `:development` group, then updating with the option `--group=development` will naturally include `bundler` in the list of gems to evaluate for updating.
The trouble is that since `bundler` is excluded from the lockfile, searching the locked gems for a gemspec for bundler will return `nil`. This caused the following error during `bundle update`:
NoMethodError: undefined method `version' for nil:NilClass
This PR solves this bug by skipping over gems (i.e …
> Fix NoMethodError during `bundle update --group`

- doc/development/PULL_REQUESTS.md
We added this requirement before the changelog was automated. Now that the changelog generated by a script, it's not helpful for PRs to update the changelog anymore, so we shouldn't expect it anymore.
We had to [ask a PR to remove a changelog entry](https://github.com/bundler/bundler/pull/6157#discussion_r149701953), even though the PR was following [the docs](https://github.com/bundler/bundler/blob/374caf6ede2cf4de7d2196aa2e2adef782bea5bd/doc/development/PULL_REQUESTS.md#changelogmd).
It looks like we failed to update the docs when we automated generating the changelog.
Removing the changelog requirement from the docs hopefully means that future PRs will not include changelog entries, and we can generate future changelogs automatically.
I chose this fix because it seemed like the …
> Stop requesting changelogs in PRs

- lib/bundler/resolver.rb
- spec/resolver/basic_spec.rb
- spec/support/indexes.rb
Fixes https://github.com/bundler/bundler/issues/6181.
In Bundler 1.15.4, the way we checked for pre-releases meant that dependencies with a lot of them sorted as more constrained than those with few/none. When we moved to our updated resolution strategy in 1.16.0 we accidentally lost that behaviour.
I'm not wild about this PR, but it fixes the resolver regression. It's unsatisfying because it would be nice to believe the resolver will always resolve performantly, regardless of the sort order thrown at it, but clearly that isn't the case.
Conceptually, this can be justified as "when two resolutions are possible, we prefer the one that does not require one dependency to be at a pre-release version".
If others are happy with this I can write a test for it.
> Resolver: treat dependencies with prerelease versions as slightly constrained

- bundler.gemspec
f06405 caused a regression with warbler, described in #6165 and jruby/warbler#421
If the fix is ok, it should probably be cherry-picked to 1-16-stable. 
Upgrading from bundler v1.15.x to v1.16.0 causes warbler to break/abort with error.
1. error message from warbler: missing file
2. see why file is missing
3. google to see if it's just me 😄 
Put the missing (from warblers point of view at least) back.
Seems easier than to fix warbler.
> Include bundler.gemspec in the gem because warbler breaks w/o it

- spec/commands/update_spec.rb
Lets say the current Bundler version is 1.16.0. If the test suite is, by a chance, executed in directory which contains such version string, this path is stored in Gemfile.lock file. Later, the test tries to replace
the version of Bundler in the lock file, but instead, it replaces the version in path. Be more careful what should be actually replaced.
This is related to #6185 although it does not resolve the original concern.
> Be more precise when replacing Bundler version in lock file.

- lib/bundler/templates/newgem/newgem.gemspec.tt
Executables from bundled gems weren't available. 
```
Gem::Exception: can't find executable <EXEC-FILENAME> for gem <GEM-NAME>
/Users/elia/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/bundler/rubygems_integration.rb:458:in `block in replace_bin_path'
/Users/elia/.rvm/rubies/ruby-2.3.4/lib/ruby/site_ruby/2.3.0/bundler/rubygems_integration.rb:478:in `block in replace_bin_path'
…
```
When a Gemfile was pointing to a local gem using git to list its files the git command
was executed from within the wrong dir.
Initially I added `-C #{__dir__}` to the `git ls-files -z` command.
Realized `-C` wasn't safe and opted for stuff already available in the corelib, i.e. `Dir.chrid` instead of, say, escaping with `shellwords`.
---
I know the line is long-ish, happy to fix it in the way you want
> Ensure git is executed inside the gemspec dir

- spec/spec_helper.rb
PR #5036 added restriction on what characters can be contained in path,
from where the specs are executed. But they dissallows even dash, which
is hopefully handled just fine on all systems.
This patch fixes #6185 by relaxing the restriction a bit and allowing
path to contain dash.
> Allow test execution in paths containing dash.

- lib/bundler/templates/Executable
- spec/runtime/executable_spec.rb
While you have several gemfiles: `Gemfile` and `Gemfile.tools`.
and generates binstubs for gems from second gemfile: `BUNDLE_GEMFILE=Gemfile.tools bundle binstubs rubocop`
when you invoke those bin `bin/rubocop`
then you see error like:
```bash
/usr/local/opt/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:458:in `block in replace_bin_path': can't find executable rubocop for gem rubocop. rubocop is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
from /usr/local/opt/rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/rubygems_integration.rb:489:in `block in replace_bin_path'
from bin/rubocop:21:in `<main>'
```
When you have generated `bin/bundler` by rails or by …
> Setup custom Gemfile path before loading bundler for binstubs

- lib/bundler/templates/.document
When users invoke `rdoc -o rdoc lib`, it generates documentation contains template files under the `lib/bundler/template` like `rdoc/lib/bundler/templates/newgem/bin/setup_tt.html`
These files are not useful for users.
I added `.document` file to its directory.
> Ignore to generate documentation of templates.

- spec/support/helpers.rb
Followup #6080 for 1-16-stable branch.
> Rename `-rubygerms` option.

- spec/bundler/definition_spec.rb
- spec/commands/lock_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/install/gems/flex_spec.rb
- spec/install/gems/mirror_spec.rb
- spec/lock/lockfile_bundler_1_spec.rb
- spec/plugins/source/example_spec.rb
- spec/runtime/setup_spec.rb
- spec/update/git_spec.rb
(It targets 1-16-stable branch. I will create another pull request for master)
It's introduced by `URI::Generic` changes.
see  https://github.com/ruby/ruby/commit/ed48bfa5e8770a345424abd7f24f94ea9bbf5973
I added a hostname to examples that expect `file:` string in result messages.
> Fixed failing examples with Ruby 2.5.

- lib/bundler/cli/init.rb
- spec/commands/init_spec.rb
Users are unable to generate a new Gemfile with `bundle init` if there is a Gemfile in any
parent folder.
Closes #6205 
Don't use `SharedHelpers.default_gemfile` as that searches up the paths for a Gemfile. Instead only check the current directory.
> Let users generate gemfiles inside paths whos parent contains a Gemfile

- task/release.rake
I rake `rake release`, and successfully released version 1.16.1, but I also saw an exception backtrace:
```
bundler 1.16.1 built to pkg/bundler-1.16.1.gem.
Tagged v1.16.1.
Pushed git commits and tags.
Pushed bundler 1.16.1 to rubygems.org
rake aborted!
https://api.github.com/user?access_token=
#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>
{"message"=>"Bad credentials", "documentation_url"=>"https://developer.github.com/v3"}
task/release.rake:35:in `gh_api_post'
task/release.rake:46:in `block (2 levels) in <top (required)>'
/Users/andre/src/bundler/bundler/Rakefile:30:in `block in invoke'
/Users/andre/src/bundler/bundler/Rakefile:29:in `invoke'
Tasks: TOP => release => release:verify_github
(See full trace by running task with --trace)
```
As far as I can tell, we were intending …
> Verify buildable manpages and GitHub token before release

- man/bundle-binstubs.ronn
correct typo in binstubs man page: `s/--sheband/--shebang/`
> correct typo in binstubs man page

- .travis.yml
- Rakefile
- lib/bundler/current_ruby.rb
The problem was Ruby 2.5 was released yesterday! So this updates Bundler to test against it on CI, as well as acknowledging 2.6 as a new minor.
>  [Travis] Test against Ruby 2.5

- lib/bundler/rubygems_integration.rb
Testing with trunk & rubygems, many warnings of:
`rubygems/lib/rubygems.rb:940: warning: __FILE__ in eval may not return location in binding; use Binding#source_location instead`
Updates for warnings & 'security' in trunk are showing issues that should be addressed.
It's one line...
Unaware of other options...
Not sure if this will work with all ruby versions.  Did not test my fork...
> Fix warning in rubygems testing re __FILE__

- lib/bundler/cli.rb
- lib/bundler/cli/list.rb
- man/bundle-list.ronn
- spec/commands/list_spec.rb
See #6172 
This option mimics the `--paths` options in `bundle show` which is
being removed in Bundler 2.
Example Usage:
```
$ bundle list --paths
/Users/c/Desktop/Projects/testapp/.bundle/ruby/2.4.0/gems/actioncable-5.1.4
/Users/c/Desktop/Projects/testapp/.bundle/ruby/2.4.0/gems/actionmailer-5.1.4
/Users/c/Desktop/Projects/testapp/.bundle/ruby/2.4.0/gems/actionpack-5.1.4
/Users/c/Desktop/Projects/testapp/.bundle/ruby/2.4.0/gems/actionview-5.1.4
```
> add `--paths` option to `bundle list` command.

- lib/bundler/runtime.rb
- spec/commands/clean_spec.rb
- spec/support/builders.rb
The problem was that `bundle clean` command doesn't remove gem extensions (#5596)
I've looked into `Bundler::Runtime#clean` and realized that extension dirs are not removed
My fix is to tweak `Bundler::Runtime#clean` to remove extensions dirs
as well.
I chose this fix because I didn't see any other option.
> Make `bundle clean` clean extension directories

- lib/bundler/cli.rb
The problem was Bundler would try to do the outdated version check on FIPS systems, leading to an exception.
Closes #6032.
My diagnosis was we needed to skip the check when MD5 is unavailable.
I chose this fix because using `#available?` would make network requests, which is not acceptable.
> [CLI] Skip the outdated bundler check when MD5 is not available

- lib/bundler/source/rubygems.rb
The problem was occasional failures on CI w/ ruby 2.5
My diagnosis was that there was a race condition in the rubygems installer, see https://github.com/rubygems/rubygems/pull/2148 for the fix there.
My fix will ensure that directory is created before we get into that rubygems code path
> [Source::RubyGems] Ensure the bindir exists before installing

- lib/bundler.rb
- lib/bundler/cli/check.rb
- lib/bundler/cli/install.rb
- lib/bundler/cli/outdated.rb
- lib/bundler/definition.rb
- lib/bundler/injector.rb
- lib/bundler/installer.rb
- lib/bundler/runtime.rb
The problem was `Bundler` overrode the `Object#frozen?` method to mean something else, breaking anything that checks that method to determine if an object is frozen.
Closes #6252.
My diagnosis was the method name had to be changed.
> Rename Bundler.frozen? to avoid Object method conflict

- man/bundle-binstubs.ronn
Typo found while i was packaging 1.16.1 for Debian
> [man] fix typo on bundle-binstubs

- lib/bundler/friendly_errors.rb
This would have made diagnosing https://github.com/bundler/bundler/issues/6220 much easier
My diagnosis was we do a lot in our error handler, so it needs a fallback
My fix falls back to just re-raising the original error
> [FriendlyErrors] Fallback to the original error if the friendly message raises

- lib/bundler/compact_index_client/updater.rb
- spec/bundler/compact_index_client/updater_spec.rb
Bundler will raise an exception and crash if the Gzip that the Compact Client Index downloaded was corrupt.
See #6261 
Handle the exception and allow Bundler to continue without crashing
> handle gzip corruption errors in the compact index client

- doc/contributing/HOW_YOU_CAN_HELP.md
Github has defined a couple of tags to use for classifying issues that are suitable for new contributors to fix/contribute towards. We have started using these tags in Github so we should start linking to them in our documentation as well.
> Update contributing documentation to use new tags

- spec/commands/exec_spec.rb
There is an issue where a spec was failing because it was activating the version of Bundler inside of RubyGems and not the development version that we're working on.
This would cause the Lockfile to raise an error because we were generating a Bundler 2 lockfile in our tests but Bundler 1 was being activated making it complain.
Add the Bundler development dir in the Ruby include argument.
This error is raising in CI and is preventing PRs from being merged.
See https://travis-ci.org/bundler/bundler/jobs/333434747
> Fix failing spec in the bundle exec system gem spec

- lib/bundler/cli/init.rb
- spec/commands/init_spec.rb
The problem was that when running `bundle init` inside a directory which is not writable by the current user (e.g. `/` as demonstrated in #6219) Bundler prints out an `EACCES` error with a huge backtrace.  In the mentioned PR @segiddins suggested to print out a better error message.  This PR addresses that.
See [this comment on said PR](https://github.com/bundler/bundler/issues/6219#issuecomment-359002919).
My fix is simple: adding a check whether the current directory is writeable before trying to create `gems.rb`/`Gemfile`.  If that's not the case, print out an error and exit.
I chose this fix because... it was really simple to implement.
> [Init] Check if the current directory is writeable

- lib/bundler/cli.rb
- spec/commands/update_spec.rb
- spec/install/gemfile_spec.rb
- spec/update/gemfile_spec.rb
The problem was that `BUNDLE_GEMFILE` is not respected when `.bundle/config` specifies an alternate Gemfile. However, my specific issue is that `bundle install --gemfile Gemfile2` is an option, but `bundle update` won't let me specify an alternate Gemfile.
My diagnosis was that Bundler copies `BUNDLE_GEMFILE` environment variable to `BUNDLE_ORIG_GEMFILE` and always uses `.bundle/config`. Simplest solution was to add parity to `bundle update` rather than diagnose why environment variables don't override `.bundle/config` settings across the board.
My fix is to add the `--gemfile` option to `bundle update` for parity with `bundle install`.
I chose this fix because …
> Added `--gemfile` option to `bundle update`

- lib/bundler/cli/doctor.rb
- spec/commands/doctor_spec.rb
#5786 
> We should have a check in bundle doctor for the file/folder permissions in the Bundler home directory.
>We should print a warning if there are any files/folders that is owned by another user but is readable/writable but prints an error when a file cannot be read or written to.
Created private method ```check_home_permissions``` that will print a warning if there are any files/folders that are owned by another user but are readable/writable, and print an error when the 
bundler home dir contains a file cannot be read or written to 
I chose this fix because it's what was requested in the open issue.
> check permissions in doctor command

- lib/bundler/installer/gem_installer.rb
- spec/commands/install_spec.rb
- spec/install/failure_spec.rb
My bundling failed and the command that `bundler` output was wrong-ish, in the sense that my gem was suppose to come from a different source.
The error message was not explicit.
Bundler now explicitly print the source when there's just one. I think it's a good case just to print it when there's one. If there are more it's ambiguous, so we fallback to the old way. Maybe we could have a warning there that the command might not be exactly what the user wants.
See previous answer. I didn't find any easier ways of getting the source url.
Let me know if there are better implementations :)
> Add explicit source when available in the error msg upon failure

- man/bundle-doctor.ronn
The `bundle doctor` command was missing a man page (see https://github.com/bundler/bundler/issues/6243).
Running `bundle help doctor` from the command line showed [the description from `cli.rb`](https://github.com/bundler/bundler/blob/723608f45866cee0f1b315551a8dde6a99efebc6/lib/bundler/cli.rb#L611-L620), but it wasn't displayed in the same format as commands with man pages. Documentation for `bundle doctor` was also missing from http://bundler.io/docs.
I added a man page for `bundle doctor`.
I chose this fix because the ["Writing docs for man pages" documentation](https://github.com/bundler/bundler/blob/master/doc/documentation/WRITING.md#what-goes-in-man-pages) says...
> Our goal is to have a man page for every command.
> Add man page for `bundle doctor`

- lib/bundler.rb
- spec/install/gemspecs_spec.rb
The problem was that if a gemspec had a non ascii character on it, and the external encoding is not utf-8, bundler would fail with a very cryptic error. CircleCI is very likely to reproduce this bug since its base images default to `LANG=C`. See [here](https://circleci.com/gh/deivid-rodriguez/pry-byebug/12) for an example.
In bundler's master, `bundle install` seems to hang in this same situation. I have no idea why but CPU usage goes crazy (100%) when running something like `LANG=C bundle install` with such a gemspec.
Note that adding a utf-8 magic encoding comment seems to fix the problem, but I think `bundler` should just work in this situation, or at least give the user a more helpful error message. And of course never hang either.
My diagnosis was that bundler was reading an …
> Fix hang when gemspec has incompatible encoding

- lib/bundler/cli/exec.rb
- spec/commands/exec_spec.rb
- spec/support/helpers.rb
The problem was commands like `nohup bundler exec {program}` wouldn't work as intended. For  example, if a `HUP` signal were to be sent to the process running the `bundle exec ..`, it should in theory not terminate. Because, `nohup` would `IGNORE` that signal. But, that is not what the case is case is currently.
My diagnosis was, if a process/bundler execution already had a `SIGNAL` set to it, example `HUP`, then performing `bundle exec {program}`, would mean that bundler resets any prior `SIGNAL`s on that process and sets them to `DEFAULT`.
My fix to the problem is to only trap `SIGNAL`s that we think should be set to `DEFAULT`, in this case, `INT`. 
I chose this fix because its lot less aggressive than setting every signal to `DEFAULT`, and gives us the work with a smaller set of …
> Only trap INT signal and set to DEFAULT

- lib/bundler/definition.rb
- lib/bundler/spec_set.rb
- spec/runtime/platform_spec.rb
- spec/support/builders.rb
- spec/support/helpers.rb
The problem was users could get `Unable to find a spec satisfying ... perhaps the lockfile is corrupted?` error messages, particularly when they use multiple platforms.
Fixes #6079.
My diagnosis was the lockfile _was_ indeed corrupted, because it was missing `spec_name (version)` entries, but resolution could still be skipped (preventing those gems from being added back in).
My fix checks whether all specs are present _in the lockfile_ (e.g. not locally) for the current platform, and considers that a "change" that forces the resolver to run, allowing those missing specs to be added back to the bundle.
I chose this fix because it was a way to force re-resolution in a way that ties into our existing `#change_reason` infrastructure. Additionally, it shouldn't have much of a performance …
> Gracefully handle when the lockfile is missing spec entries for the current platform

- man/bundle-install.ronn
- man/gemfile.5.ronn
- Bundler stopped gitignoring gem locks. The change was merged in but we need to reflect that change in documentation.
- To add in documentation explaining why Bunder now does _not_ gitignore gem locks.
My fix...
- Update the `gemfile.lock` section of `bundle install` man pages as well as the `gemfile` man page.
- This addresses open issue https://github.com/bundler/bundler/issues/5879
> Update docs to reflect revised guidance to check in locks for gems

- spec/commands/binstubs_spec.rb
- spec/commands/licenses_spec.rb
- spec/commands/pristine_spec.rb
- spec/commands/show_spec.rb
- spec/runtime/setup_spec.rb
I fixed test fails with bundler-1.16.1 as default gems.
https://travis-ci.org/rubygems/rubygems/jobs/339325369
When the system has a same version of bundler as default gems(Currently it's 1.16.1), It conflicts on command invocation in bundler's examples. I added two workarounds.
1. Bump virtual version of bundler in `binstubs_spec.rb`
2. In other examples, I modified expected variables when it was installed bundler as default gems.
> To use dynamic expectation with same versioned bundler installed as default gems

- lib/bundler/injector.rb
As discussed on #6193 this PR simply removes the comment timestamp when adding a gem via command line.
> Remove comment with timestamp on `bundle add`

- lib/bundler/templates/newgem/lib/newgem.rb.tt
- spec/commands/newgem_spec.rb
The problem was that the main file in a gem generated by `bundle gem` can't be inspected via `rubocop`.
My diagnosis was `bundler` was generating unparsable ruby in the generated gem.
My fix was to change the offending template to generate valid ruby code.
I chose this fix because it's the only one, really.
> Fix `bundle gem` generating unparsable ruby

- spec/bundler/gem_helper_spec.rb
- spec/support/builders.rb
Running `bin/rake spec` in the Bundler repository causes a bunch of failures if `commit.gpgsign` is set in the global Git configuration.
Bundler's tests were making Git commits and trying to GPG sign them.
Set `commit.gpgsign` to `false` when initializing a Git repository in the tests.
I chose this fix because the alternative would be to pass `--no-gpg-sign` every time a commit is made in the tests, which would have a bigger maintenance impact.
> Don't GPG-sign test setup commits

- lib/bundler/fetcher.rb
- lib/bundler/fetcher/index.rb
- lib/bundler/rubygems_integration.rb
- spec/install/gems/resolving_spec.rb
- spec/support/artifice/compact_index.rb
- spec/support/artifice/endpoint.rb
When  I released RubyGems 3.0, users can not use bundler with it.
bundler still uses deprecated methods with https://github.com/rubygems/rubygems/pull/2214
Replace `Gem.inflate` to `Gem::Util.inflate`
> Use Gem::Util.inflate instead of Gem.inflate

- lib/bundler/definition.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/install/gemfile/platform_spec.rb
The user needed a way to turn off platform warnings.
Creating a config variable to solve the above problem.
Added a key `disable_platform_warnings` in settings and placed check at the relevant place to disable warnings.
We will by default show warnings but the user might want to disable them, so using a config variable looked a good option.
Fixes #6124
> Add config variable and check for platform warnings

- README.md
Hey team,
The "Contributing" section confusingly sends contributors over to the "Documentation" README, and from there, contributors have to click on "Overview" to actually get to the guidelines. Since it's easier to cut out those two steps, I've rephrased a sentence and provide the direct link to the contributor guidelines here.
...that it wasn't clear why contributors had to complete two steps to get to the contributor guidelines. And because it isn't clear once they get to "Documentation" which link is the actual guideline, it's much simpler to link out to it directly from the Bundler README.
....to cut out the middle …
> Link out directly to contributor guidelines

- man/bundle-init.ronn
An enhancement request to bundle-init docu as per - issue 6140 
n/a
Updated the man/bundle-init.ronn file to include brief description of frozen string literal, and added a SEE ALSO section with link to Gemfile(5) webpage
File edited to try and reflect the previous discussion regarding what was required.
> Document `# frozen_string_literal` in `bundle init` Gemfile

- lib/bundler/definition.rb
The problem was that the error message for a yanked Gem told the user to:
> update your bundle to a different version of foo (1.0)
This is slightly misleading because in this example, foo 1.0 is the version that has been yanked. They should use any verion of foo **other** than 1.0.
My diagnosis was that the error message interpolated the gem specification (which converts to a string as "NAME (VERSION)") rather than just the name of the gem in this instance.
My fix was to change that occurrence of the gem specification to just the gem name.
I chose this fix because it was the only way that occurred to me to do it.
> Improve yanked gem error message

- lib/bundler/installer.rb
The interface of `ERB.new` will change from Ruby 2.6.
> 2nd, 3rd and 4th arguments of ERB.new are deprecated. 2nd
> argument (safe_level) will be dropped in the future and
>  some of those arguments (trim_mode, eoutvar) are changed to
> keyword arguments. [Feature #14256]
https://github.com/ruby/ruby/blob/v2_6_0_preview1/NEWS#stdlib-updates-outstanding-ones-only
The following addresses are related commits.
- ruby/ruby@cc777d0
- ruby/ruby@8b9a3ea
This change will cause the users to see a warning as described below.
In Ruby 2.6, a warning is displayed when using the interface of Ruby 2.5 or lower.
This warning can also be confirmed in Travis CI.
```console
/home/travis/.rvm/gems/ruby-head/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:171:
warning: Passing safe_level with the …
```
> Deprecate safe_level of `ERB.new` in Ruby 2.6

- lib/bundler/rubygems_integration.rb
Thanks to @nobu for pointing out the error (which was mine).  `source_location` returns an array, not a string.
> Fix source_location call in PR 6237 and commit fbb1ff7

- spec/commands/lock_spec.rb
The problem was we were unsure (in https://github.com/bundler/bundler/issues/6312) whether lock had this behavior.
My diagnosis was it did, and I came to that conclusion via this test!
> Add a spec for bundle lock not downloading gems

- spec/spec_helper.rb
The problem was we could accidentally set an expectation on `nil`, leading to an RSpec warning
My diagnosis was we should just error when we do so
> Raise an error when attempting to set an expectation on nil

- lib/bundler/fetcher.rb
- lib/bundler/fetcher/index.rb
- spec/install/gems/resolving_spec.rb
- spec/support/artifice/compact_index.rb
- spec/support/artifice/endpoint.rb
The problem was Bundler was using RubyGems methods directly that may change their interface over time.
My diagnosis was  we should use `Bundler.rubygems` to encapsulate those method calls.
> Use Bundler.rubygems.inflate instead of the Gem::Util method directly

- lib/bundler/source/git/git_proxy.rb
- spec/bundler/source/git/git_proxy_spec.rb
See https://github.com/bundler/bundler/issues/6324 for context.
The problem was when a git gem referenced a branch, and you tried to install on a machine without the revision in the lockfile cached, Bundler would print the following error:
```
Git error: command `git reset --hard cb70aded58b9215a495f0509e49daef930eec478` in directory
/home/deivid/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/bundler/gems/decidim-cb70aded58b9 has failed.
If this error persists you could try removing the cache directory
'/home/deivid/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/cache/bundler/git/decidim-9495d3039168996748af12c0fdb04debdea10392'
```
The problem was that removing the cache directory doesn't help.
My diagnosis was we needed to print a `RevisionNotFound` error when that `git reset --hard` failed.
My …
> [GitProxy] Fail gracefully when resetting to the given revision fails

- doc/development/SETUP.md
[dupes](https://github.com/Homebrew/homebrew-dupes) tap is deprecated, `groff` is now in [hombrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/groff.rb).
Also fixed a missing single quote while I was at it :)
> Update brew install for groff

- lib/bundler/compact_index_client/updater.rb
The problem was users could see the error template when they do not have write permissions to their temporary directory.
Closes https://github.com/bundler/bundler/issues/6289
My diagnosis was we need to use `SharedHelpers.filesystem_access` when writing files.
My fix wraps usage of `cp`
> [CompactIndexClient::Updater] Use filesystem_access when copying files

- lib/bundler/cli/exec.rb
- spec/commands/exec_spec.rb
Resolves #6342 
Instead of throwing a readable error, Bundler failed and generated an issue report template (see details in #6342).
My diagnosis was that nil safety is hard in Ruby.
To check whether backtrace is nil before sending it a `take_while` method.
I chose this fix because I see no other solutions.
> Fix failure when exception backtrace is nil

- lib/bundler/ui/shell.rb
- spec/bundler/ui/shell_spec.rb
- spec/support/streams.rb
See https://github.com/bundler/bundler/issues/6190
The error is happening because we're not checking if stderr is closed prior to writing to it.
My fix is to add a check to determine if stderr was closed.
I chose to fix it here for a start and discuss with others if more checks were needed. Maybe we need to check if stderr is closed for all references of `$stderr.puts` and replace `abort` with `$stderr.puts` and `exit(1)`?
> Fix to check if stderr was closed before writing to it

- lib/bundler/cli/gem.rb
- lib/bundler/templates/newgem/newgem.gemspec.tt
Resolves #6246 
1. There is no helpful comment about `spec.files` method in a new gem's gemspec.
2. `$ bundle gem gem_name` is missing link to further reading about developing, testing and releasing the newly created gem.
1. Add a comment in the `newgem.gemspec.tt`
2. Add a message after new gem generation with link to [bundler.io guides](https://bundler.io/guides/creating_gem.html)
Example: 
```bash
๛  ~/code/oss/tmp $  ../bundler/bin/bundle gem new_gem
Creating gem 'new_gem'...
create  new_gem/Gemfile
create  new_gem/lib/new_gem.rb
create  new_gem/lib/new_gem/version.rb
create  new_gem/new_gem.gemspec
create  new_gem/Rakefile
create  new_gem/README.md
create  new_gem/bin/console
create  new_gem/bin/setup
create  new_gem/.gitignore
Initializing git repo in …
```
> Explain spec files and output a link to bundler.io guides

- lib/bundler.rb
- lib/bundler/cli.rb
- lib/bundler/endpoint_specification.rb
- lib/bundler/env.rb
- lib/bundler/fetcher.rb
- lib/bundler/gem_helper.rb
- lib/bundler/installer.rb
- lib/bundler/installer/gem_installer.rb
- lib/bundler/installer/parallel_installer.rb
- lib/bundler/mirror.rb
- lib/bundler/plugin.rb
- lib/bundler/plugin/index.rb
- lib/bundler/runtime.rb
- task/release.rake
The problem I noticed was in style, several instances of `rescue` clauses that do not specify an exception type. This is noted in in the Ruby Style Guide as [Avoid rescuing the Exception class](https://github.com/bbatsov/ruby-style-guide#no-blind-rescues).
My diagnosis was that at least some of those are leftover style. They are noted in `.rubocop_todo.yml`. To make sure, I asked on Slack.
My fix is to make as many of them more specific, specifying at least `StandardError`, and trying to be more specific.
No other ways of addressing this came to mind. I'd be happy to consider.
> Fix some rescue calls that do not specifiy error type.

- lib/bundler/cli/pristine.rb
- lib/bundler/source.rb
- spec/commands/pristine_spec.rb
I have a gem with a native extension that is installed via git. I had to recompile it due to some needed build arguments.
Running `bundle pristine` would not recompile it as expected.
After digging into the source, I discovered that the built extension lived in a different location than the cloned git repo. `bundle pristine` was only removing the git repo so the built extension was not getting rebuilt.
Update `bundle pristine` to also remove the built extension. For 2.0, this also required removing the built extension cache. Without doing that, the built extension directory would just be recreated from the cache.
As far as I know, it's the only solution.
Resolves #6294
> Correctly re-install extensions when running `pristine` for a git source

- man/bundle-config.ronn
Parsed out the information in the first graph in order to help users understand the order of priority Bundler follows when loading config settings.
...[confusion from end users](https://github.com/bundler/bundler/issues/6270) about the order that Bundler loads settings in. 
Before:
```
This command allows you to interact with bundler's configuration system.
Bundler retrieves its configuration from the local application (`app/.bundle/config`),
environment variables, and the user's home directory (`~/.bundle/config`),
in that order of priority.
```
...[Colby pointed out how the bundle-config …
> Document the order Bundler loads settings

- spec/commands/add_spec.rb
- spec/install/gems/resolving_spec.rb
The problem was the specs on master are broken running against RubyGems master
My diagnosis was This was broken by RubyGems changing how requirements are sorted.
My fix uses `Gem::Requirement` to get the same sorting rubygems has
I chose this fix because the sorting is different between rubygems versions
> Fix specs against RubyGems master

- lib/bundler/definition.rb
- spec/commands/lock_spec.rb
The problem was on running `bundle lock --lockfile=AlternativeGemfile.lock` if a default lockfile already exists then `AlternativeGemfile.lock` is not created.
My diagnosis was that the [lock](https://github.com/bundler/bundler/blob/master/lib/bundler/definition.rb#L340) function does not check the file but for contents, so a new file is not created in case of an existing lockfile.
My fix was to check for the file existence.
Closes #6460
> Fix bundle lock when default gemfile is present

- lib/bundler/source/rubygems.rb
- spec/install/path_spec.rb
The problem was `bundle install` would fail when the path was configured to be the current working directory.
Fixes #6475.
My diagnosis was `Gem::RemoteFetcher` caches `.gem` files differently when `Dir.pwd == download_dir`
My fix moves the file rubygems has downloaded to the cache directory we expect.
I chose this fix because it does not re-implement logic in rubygems, and it keeps the directory structure bundler generates consistent.
> [Source::RubyGems] Allow installing when the path is `.`

- spec/commands/exec_spec.rb
There is a test that is [failing in travis](https://travis-ci.org/bundler/bundler/builds/365371973) which is preventing v1.16.2 from being released. The spec in question is checking the `BUNDLER_SPEC_SUB_VERSION` env var and changes the assertion of the test depending on the stubbed version. The issue is that the 1-16-stable branch does not really use `BUNDLER_SPEC_SUB_VERSION` and the spec is assuming it's testing Bundler 2.
Checking for `BUNDLER_SPEC_SUB_VERSION` is not really necessary in the first place because the test is already scoped for Bundler 1 & 2 (using rspec tags). This PR removes the checking for `BUNDLER_SPEC_SUB_VERSION﻿`.
> Fix failing exec spec that is blocking 1.16.2

- lib/bundler/cli.rb
- lib/bundler/cli/binstubs.rb
- spec/commands/binstubs_spec.rb
The problem was we have removed the `--binstubs` argument to `bundle install`, so saying "oh well, lets install all the bin stubs" became more tedious, requiring multiple calls to `bundle binstubs` and probably some swearing since you forgot what gem contains what binstub.
My diagnosis was we need a one-liner to generate bin stubs for all gems.
My fix adds such an option to `bundle binstubs`!
I chose this fix because it keeps binstub generation in its own command, rather than continuing to piggy-back off of `install`
> [Binstubs] Add --all options

- lib/bundler/injector.rb
Summary: Use File.open instead of Kernel.open to avoid private method call when using Bundler::Injector in Ruby script.
My app should allow users to install extensions at runtime. When using `Bundler::Injector`'s `inject` in a Ruby script, the internal method `append_to` fails with the error below.
Calling system('bundle inject GEM VERSION') is not feasible in my use case, since I want to inject the gem in a secondary Gemfile.
The error that occurs when trying to inject a dependency through a call to `Bundler::Injector.inject`:
`bundler-1.16.1/lib/bundler/injector.rb:85:in 'append_to': private method `open' called for "Gemfile.local":String (NoMethodError)`
My fix replaces Kernel.open with File.open to open the Gemfile.
I chose this fix because it does not break current `bundle inject GEM …
> Document parameters and return value of Injector#inject

- lib/bundler.rb
- spec/bundler/bundler_spec.rb
Bundler was attempting to use `sudo`, despite having permissions to create `bundle_path` (which didn't yet exist).
For some reason this became an issue in recent versions of bundler, where it wasn't one before. I'm not sure what change caused this problem to be exposed since `requires_sudo?` has not changed in a while.
`requires_sudo?` checks that bundle_path, and directories that bundler may need to write within it are writable. If bundle_path itself does not exist, we instead find the nearest existent parent directory, and check that that exists.
Unfortunately, when these two rules were applied together, we got the wrong result. If `bundle_path` did not exist, bundler would check that the nearest parent directory **and everything within that parent directory** were writable. This could …
> Check correct paths are writable in requires_sudo?

- lib/bundler/templates/newgem/newgem.gemspec.tt
- lib/bundler/templates/newgem/test/test_helper.rb.tt
Since Ruby 2.0 we've had `__dir__` as well as `__FILE__`.
The initial gem codes written with `bundle gem` using Ruby 2.0 or higher is an old description using `__FILE__`.
Ruby 1.9 is EOL, so I think that there is not much Gem to start developed using it.
This PR uses `__dir__` when starting Gem development (i.e. `bundle gem`) using Ruby 2.0 or higher version.
> Use `__dir__` instead of `__FILE__` in newgem.gemspec template

- lib/bundler/cli.rb
- lib/bundler/cli/add.rb
- man/bundle-add.ronn
- spec/commands/add_spec.rb
Usage
```bash
bundle add rack --skip-install
```
This flag would not install the gem, only add it to the gemfile.
Closes #6511
> Add --skip-install flag to bundle add

- man/bundle-binstubs.ronn
- man/bundle-config.ronn
- man/bundle-exec.ronn
- man/bundle-gem.ronn
- man/bundle-install.ronn
- man/bundle-lock.ronn
- man/bundle-outdated.ronn
- man/bundle-package.ronn
- man/bundle-update.ronn
- man/bundle-viz.ronn
- man/bundle.ronn
- man/gemfile.5.ronn
With a markup
[`bundle platform(1)`][bundle-platform(1)]
ronn creates this HTML fragment
<a href="bundle-platform.html"><code>bundle platform(1)</code></a>
At the same time, it generates HTML file `bundle-platform.1.html` based on the
man page section, and this results in certain inter-man-page links 404.
We resolve this inconsistency by spelling out the href attributes.
-----
404's on https://bundler.io.
For example, https://bundler.io/v1.16/man/bundle.1.html has the link to `bundle platform(1)`:
This points to https://bundler.io/v1.16/man/bundle-platform.html, but it is 404. The correct link is https://bundler.io/v1.16/man/bundle-platform.1.html.
My diagnosis …
> Fix man page links

- lib/bundler.rb
The problem was users would see an issue template when their `Gemfile` did not have read permissions
Fixes https://github.com/bundler/bundler/issues/6541
My fix is to use `SharedHelpers.filesystem_access` when reading the Gemfile
> Use filesystem_access when reading a Gemfile

- lib/bundler/installer.rb
- lib/bundler/plugin.rb
- lib/bundler/plugin/events.rb
- spec/bundler/plugin/events_spec.rb
- spec/bundler/plugin_spec.rb
Every event in #hook and #add_hook will check if the event is registered in
Bundler::Plugin::Events. This allows for easy tracking of what's calling events,
and allow documentation to easily point to a single location.
It also makes testing easier as events are predicatable and accessible via constants
---
There wasn't really a problem, but this makes adding events easier
Events are not tracked or documented well, this makes them documented well
Add an Events registration that hooks test for
Constants make things easily accessible via code, the hash makes it easy to check (with `O(1)` access!) for an event based on value as well.
> Make all plugin events registered to make documenting them easier

- lib/bundler/templates/newgem/travis.yml.tt
Whenever I create a gem using `bundle gem`, I always have to manually specify that I would like travis to cache bundler.
Specify `cache: bundler` in the generated .travis.yml.
> Enable bundler caching for generated travis config

- lib/bundler/cli.rb
- lib/bundler/cli/add.rb
- lib/bundler/injector.rb
- man/bundle-add.ronn
- spec/commands/add_spec.rb
By default, on `bundle add` we use "pessimistic" way (~>) of versions. According to this [comment](https://github.com/bundler/bundler/issues/6553#issue-326023952) some users face problems.
Adding flags to provide flexibility to change this declaration namely `optimistic` and `strict`
Adding flags to opt for other declarations.
Currently, its an experiment and I have added it to only `bundle add` but still the version locked in lockfile are "pessimistic". Need suggestions on this and on how to proceed.
Addresses #6553
> [bundle add] Add version prefix flexibility

- lib/bundler.rb
- lib/bundler/source/rubygems.rb
- spec/bundler/bundler_spec.rb
There is a bug for functionality that was added in #6258.  In certain scenarios, Bundler will create a folder for a temporary gem install with `root:root` permissions. This is happening because [Bundler#mkdir_p](https://github.com/bundler/bundler/blob/master/lib/bundler.rb#L377) checks for `requires_sudo?` which is creating a folder owned by `root:root` when it should be creating the folder with the current user.
See #6535
I can see that Bundler is creating the `bin` folder with `root:root` permissions
```
[vagrant@localhost ~]$ ls -la /tmp/bundler20180519-24861-1y67io7rake-12.3.1/
total 4
drwx------. 3 vagrant vagrant   17 May 19 07:36 .
drwxrwxrwt. 9 root    root    4096 May 19 07:36 ..
drwxr-xr-x. 2 root    root       6 May 19 07:36 bin
```
Add an option for `Bundler#mkdir_p` to …
> add option to Bundler#mkdir_p to force Bundler to not use sudo

- lib/bundler.rb
- spec/bundler/bundler_spec.rb
When running Omnibus packaged software with updated bundler, a warning is displayed because the home folder is not owned by the user:
```
`/var/opt/gitlab` is not writable.
Bundler will use `/tmp/bundler/home/root' as your home directory temporarily.
```
There are valid reasons why this is desired, and I don't have control over it. What I can do is create the required folders used by bundler and provide them with the right permissions.
See https://github.com/bundler/bundler/issues/6546
In practice instead of asking for permission on a higher level, if required folders are present and they have the right permissions, we shouldn't fallback to warning + temp directory, we should just use what is provided.
When home directory is not writable, but the required .gem and .bundle
are, we should …
> Don't fallback to tempdir when required directories exist.

- lib/bundler/installer/gem_installer.rb
- spec/install/failure_spec.rb
There is a bug that was introduced in #6211 that prints an error message during `bundle install` if a gem failed to be installed. The error message attempts to call the `#remotes` method on `Bundler::Source::Git` which it does not implement.
See #6563
Check if the `source` responds to `#remotes` before and return early
This seems to be the most simplest fix without having to refactor a lot of code.
> Check if source responds to `#remotes` before printing gem install error message

- lib/bundler/process_lock.rb
- spec/install/process_lock_spec.rb
Bundler is trying to perform an operation on an NFS that is raising an exception (Errno::ENOTSUP)
See #6566 
Catch the exception and allow Bundler to continue
This conforms with the existing pattern in regards to handling these types of errors in the Bundler process lock logic.
> handle Errno::ENOTSUP in the Bundler process lock

- lib/bundler/cli.rb
- lib/bundler/cli/outdated.rb
- man/bundle-outdated.ronn
- spec/commands/outdated_spec.rb
Resolves #5366 by adding a new option '--filter-dependencies' to `bundle outdated`. When present, `outdated` will only check the `gemfile_specs` and skip the `dependency_specs`.
> Add option to filter gem-dependencies from output of 'bundle outdated'

- lib/bundler/cli.rb
- lib/bundler/cli/add.rb
- lib/bundler/injector.rb
- spec/commands/add_spec.rb
Add support for mutiple gems by names only
```bash
bundle add rack rails
```
Concerns:
- All the options/switches used would be applied to the all gems specified and a warning is displayed for the time being.
Closes #6543
> Add mutiple gems by names

- lib/bundler/installer.rb
- lib/bundler/installer/parallel_installer.rb
- lib/bundler/plugin/events.rb
- spec/plugins/hook_spec.rb
Depends on #6548
We only had one plugin hook, which limited the plugin's capabilities a lot.
This adds more
We need more plugin hooks for gem stuff
Add more hooks in after-all (including dependencies) and before/after (including install spec)
These seemed like the obvious spots to put the hooks, but I could be wrong. The passed objects also seem to include all the info we need to action on the installations (errors, etc)
> Add registered plugin events for before-all, before, and after gem install

- lib/bundler/source/rubygems.rb
- lib/bundler/source/rubygems/remote.rb
- spec/commands/exec_spec.rb
- spec/commands/install_spec.rb
- spec/commands/lock_spec.rb
- spec/install/failure_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/install/gems/mirror_spec.rb
- spec/install/post_bundle_message_spec.rb
- spec/lock/lockfile_bundler_1_spec.rb
- spec/lock/lockfile_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
- spec/support/matchers.rb
When users use file protocol with bundler, URI of Ruby 2.6 will raise auth info assignment and normalize host parameter given localhost variable with its case.
URI behavior of Ruby 2.6 is reasonable for me. Because I will fix this problem on bundler side.
> Support URI::File of Ruby 2.6

- lib/bundler/resolver.rb
- spec/resolver/basic_spec.rb
The problem was #6449
Closes #6449 
My diagnosis was that Bundler didn't select a pre-release even if one of the dependencies of a gem was specified with a pre-release version in the Gemfile.
My fix is to change `Bundler::Resolver#requirement_satisfied_by?` so that it does not reject a pre-release if at least one of the dependencies is pre-released.
> select a pre-release if it's specified in the Gemfile

- lib/bundler/shared_helpers.rb
The problem was, actually I'm not sure. @indirect ?
Addresses the first bullet point in https://github.com/bundler/bundler/issues/6582.
My diagnosis was we should only hard error on deprecations in the major version _after_ we stop supporting them.
> [SharedHelpers] Only hard-error on major deprecations in the following version

- lib/bundler.rb
- spec/install/gemspecs_spec.rb
This PR fixes #6598. Thanks @eregon for the help and the explanation that helped me understand the issue :)!
On gems using UTF-8 symbols defined in other files in their gemspecs, `bundle install` would crash.
The problem was that since #6279 gemspecs are read binarily. However, files required from them as read as text. That means that the constants defined on those files and used in the gemspec are interpreted different and thus don't match.
My fix is to go back to reading gemspec as text again. Explictly passing the encoding when reading them still fixes the problem that the PR introducing the regression was meant to fix. 
I chose this fix because it fixes the problem, and keeps the situation that the PR introducing the regression fixed also working.
> Respect encodings when reading gemspecs

- spec/support/builders.rb
My problem is that I can't get https://github.com/rubygems/rubygems/pull/2332 CI passing.
My diagnosis was that current bundler test don't support my changes in that PR, because previously the `validate` method in `rubygems` would be called without arguments, and now it's called with two arguments.
My fix is to make the specification stub more flexible so it supports any number of arguments.
I chose this fix because it supports my changes and doesn't break the previous version either.
> More flexible stub

- lib/bundler/cli.rb
- lib/bundler/cli/list.rb
- man/bundle-list.ronn
- spec/commands/list_spec.rb
Listing gems according to groups, either excluding a particular or from a specific group.
Usage:
```bash
bundle list --without-group dev
```
```bash
bundle list --only-group dev
```
Addresses #6564
> [bundle list] add `--without-group` and `--only-group`

- README.md
There's a new command `bundle add` which is almost unknown
We are promoting to use a simple append to the Gemfile when there's a `bundle add` command available
My fix is just a little readme change :sweat_smile: 
Because it's a simple fix and provides more exposure to the command
> Updated 'bundle add' to rspec install guide

- man/gemfile.5.ronn
See https://github.com/bundler/bundler/issues/6280 for more context.
This PR adds a warning to the Gemfile documentation to more clearly indicate that specifying an explicit source on a per-gem or block basis also makes that scoped source a global source. Also adds a recommendation that users ensure that all gems in the Gemfile are using explicit sources whenever they introduce any explicit source blocks or source directives on individual gems.
If the root cause cannot be fixed until v2, I think this gotcha should be documented in all existing bundler versions which have this behavior, which as far as I can tell is all versions supporting explicit sources via blocks/per-gem directives. I believe it merits a warning because the behavior is non-intuitive, and represents a potential security …
> add warning to docs for explicit source gotcha

- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/vertex.rb
- lib/bundler/vendor/molinillo/lib/molinillo/gem_metadata.rb
The problem was bundler was using an outdated version of Molinillo.
My fix was to bump the version.
I chose this fix because it includes resolver performance improvements when using `recursive_predecessors` / `recursive_successors`
> Update vendored molinillo to 0.6.5

- lib/bundler/cli.rb
- lib/bundler/cli/remove.rb
- lib/bundler/dependency.rb
- lib/bundler/dsl.rb
- lib/bundler/injector.rb
- lib/bundler/shared_helpers.rb
- man/bundle-remove.ronn
- spec/commands/remove_spec.rb
- spec/support/matchers.rb
Features of the command implemented:
- Multiple gems support
```bash
$ bundle remove rack rails
```
- Remove any empty block that might occur after removing the gem or otherwise present
Things yet to implement:
- Add `rm` alias. _Optional_
Closes #6506
> Add `bundle remove`

- lib/bundler/dsl.rb
- lib/bundler/injector.rb
- spec/commands/add_spec.rb
- spec/commands/install_spec.rb
If the user tries to add a gem giving version requirement then bundler throws an error if the gem is already present.
The error displayed is very descriptive but if the user is specifying a gem version maybe he wants to update the gem.
Added an instructive message to inform the user that gem can also be updated.
This seemed to be the best informative message.
Closes #6341
> Update error message on bundle add in case of duplication

- doc/contributing/README.md
We're trying to publicize the new RFC process more, and one of the ways to do this is to make it prominent in the Bundler contributing guidelines.
> Added RFC to contributing guidelines

- .travis.yml
- lib/bundler/shared_helpers.rb
- spec/runtime/setup_spec.rb
- spec/spec_helper.rb
see #6465, basically we're not rejecting `bundler_lib` because we have symlink there and real path in `$LOAD_PATH`
```
$ irb
2.5.1 :001 > require 'bundler/setup'
From: /real_path/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.2/lib/bundler/shared_helpers.rb @ line 339 Bundler::SharedHelpers#clean_load_path:
330: def clean_load_path
331:   # handle 1.9 where system gems are always on the load path
332:   return unless defined?(::Gem)
333:
334:   bundler_lib = bundler_ruby_lib
335:
336:   loaded_gem_paths = Bundler.rubygems.loaded_gem_paths
337:
338:   binding.pry
=> 339:   $LOAD_PATH.reject! do |p|
340:     path = File.expand_path(p)
341:     path = File.realpath(path) if File.exist?(path)
342:     next if path.start_with?(bundler_lib)
343:     loaded_gem_paths.delete(p)
344:   end
345: …
```
> Use realpath in clean_load_path

- Rakefile
- spec/support/helpers.rb
- spec/support/rubygems_ext.rb
RubyGems will remove `--no-ri` and `--no-rdoc` options at RubyGems 3.0. But bundler spec is also broken when removing them.
* https://github.com/rubygems/rubygems/pull/2354
* https://travis-ci.org/rubygems/rubygems/jobs/402911887
To use --no-document option after RubyGems 2.0.
> Prefer to use `--no-document` option in spec

- lib/bundler/definition.rb
- lib/bundler/resolver/spec_group.rb
- spec/install/gemfile/platform_spec.rb
The problem was the lockfile would contain platform-specific gems that it didn't need
Closes https://github.com/bundler/bundler/issues/6491
My diagnosis was the resolver sometimes activates platforms it doesn't need, since it can't know it won't need them
My fix is to use `SpecSet#for` to filter out gems that won't ever be used
I chose this fix because it isn't re-inventing the wheel!
> [Definition] Filter out unneeded gem platforms after resolving

- lib/bundler/injector.rb
- spec/commands/add_spec.rb
- spec/commands/inject_spec.rb
The problem was that on adding a gem to a group via
```bash
bundle add rack --group=dev
```
It gets added as 
```ruby
gem "rack", :group => [:dev]
```
It should rather be 
```ruby
gem "rack", :group => :dev
```
My diagnosis was to not add single groups in the array.
My fix was to pick the element from the array of groups and append using
```ruby
":group => :#{d.groups.first}"
```
I chose this fix because it seemed to most appropriate.
> Fix singular groups on injecting gem

- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/install/bundler_spec.rb
- spec/install/gems/sudo_spec.rb
- spec/install/path_spec.rb
The problem was `bundle config path` behaving differently depending on whether the config is local or global was... confusing.
Closes https://github.com/bundler/bundler/issues/6619#issuecomment-405460114.
My diagnosis was setting the `path` setting should be consistent, regardless of the level of configuration it is set at.
My fix appends the "ruby scope" to the path when set globally on Bundler 2.
I chose this fix because it means users won't have to re-install gems when switching rubies with a global `BUNDLE_PATH` set.
> [Settings] Append the ruby scope on Bundler 2 with a global path setting

- doc/development/RELEASING.md
- lib/bundler/vendor/thor/lib/thor/base.rb
- lib/bundler/vendor/thor/lib/thor/util.rb
- spec/runtime/setup_spec.rb
Fixing typos is sometimes very hard. It's not so easy to visually review them. Recently, I discovered a very useful tool for it, [misspell](https://github.com/client9/misspell). 
This pull request fixes minor typos detected by [misspell](https://github.com/client9/misspell). 
I've ignored the past changelogs and false positives. If you would like me to work on other files as well, let me know. 
```
$ misspell .
bundler.gemspec:38:32: "automatiek" is a misspelling of "automate"
Rakefile:324:11: "automatiek" is a misspelling of "automate"
Rakefile:326:2: "Automatiek" is a misspelling of "Automate"
Rakefile:333:2: "Automatiek" is a misspelling of "Automate"
Rakefile:340:2: "Automatiek" is a misspelling of "Automate"
Rakefile:347:2: "Automatiek" is a misspelling of "Automate"
Rakefile:365:42: …
```
> Fix typos detected by github.com/client9/misspell

- lib/bundler.rb
- lib/bundler/env.rb
- spec/install/gemfile_spec.rb
See #6660 and https://github.com/oracle/truffleruby/issues/1410.
The above issue details the problem.
To read the Gemfile and other files in Bundler with the default source encoding of Ruby, UTF-8, instead of the binary encoding which cannot interpret non-US-ASCII characters.
Because it's what Ruby does for other source files.
Fixes #6660.
> Use UTF-8 for reading files including Gemfile

- lib/bundler/resolver.rb
*I know I'm messing with private APIs here, so have no right to expect this PR merged!*
Currently, when Bundler generates its error message for a version conflict, it mutates the `requirement_trees` array on the underlying `Molinillo::VersionConflict` error.
I would really like it if it didn't. Dependabot taps into that error to understand what went wrong with resolution and unlock any dependencies that are blocking resolution. The code where we do so is [here](https://github.com/dependabot/dependabot-core/blob/9abcb85ba69b408b11b56572dd13ab89d0c55b8c/lib/dependabot/file_updaters/ruby/bundler/lockfile_updater.rb#L142-L167).
I don't think that there's any downside to not mutating here. Resolution has finished (and failed) at this stage, so trying to reduce memory usage doesn't really …
> Don't mutate original error trees when determining version_conflict_message

- lib/bundler/gem_helper.rb
Hello. I found a method which raises SystemStackError by chance.
The method always calls itself recursively like as follows:
```
irb(main):006:0> require './lib/bundler/gem_helper'
=> true
irb(main):007:0> Bundler::GemHelper.new.send(:sh_with_code, 'ls')
Traceback (most recent call last):
16: from /home/hibariya/src/github.com/bundler/bundler/lib/bundler/gem_helper.rb:191:in `sh_with_code'
15: from /home/hibariya/src/github.com/bundler/bundler/lib/bundler/gem_helper.rb:191:in `sh_with_code'
14: from /home/hibariya/src/github.com/bundler/bundler/lib/bundler/gem_helper.rb:191:in `sh_with_code'
13: from /home/hibariya/src/github.com/bundler/bundler/lib/bundler/gem_helper.rb:191:in `sh_with_code'
12: from /home/hibariya/src/github.com/bundler/bundler/lib/bundler/gem_helper.rb:191:in …
```
> Fix SystemStackError (stack level too deep) in GemHelper#sh_with_code

- spec/install/gemfile_spec.rb
* String#b is Ruby 2.0+.
The CI is failing on the `1-16-stable` branch.
The CI on master doesn't run against MRI 1.9.3, so this failure slipped in in #6661.
Probably testing against MRI 1.9.3 should be done on `master` too?
Make the spec work on 1.9.3.
cc @hsbt
> Fix encoding spec from #6661 to also work 1.9.3

- lib/bundler/build_metadata.rb
The problem was https://github.com/bundler/bundler/issues/6453.
A use had a version of Bundler packaged with Ruby 2.5.0 in RVM, but this version didn't include Bundler's git repo or any of the ivars which should have been set. As a result, Bundler was shelling out to git even though it wasn't in a git repo.
My fix is to show a nicer result in this case (just say that the SHA is unknown)
I chose this fix because ensuring Bundler is always packaged correctly by others isn't possible (although it seems weird and unlikely that a version without instance variables set would be used). Falling back to a cleaner error message is marginally nicer than what we currently have, and not much work.
Fixes #6453.
> Avoid printing git error when checking version on badly packaged version

- lib/bundler/dep_proxy.rb
- spec/bundler/dep_proxy_spec.rb
After implementing a new hash table strategy in JRuby, bundle is broken for JRuby. The problem is caused that the ``==`` method in bundler does not check the class of the ``other`` object. This causes problems now when calling ``==`` on object other than DepProxy or nil.
jruby/jruby#5280 travis-ci/travis-ci#9994
The code crashes for anything other than DepProxy class or nil.
Checking now also that other class is the same as self.
> Fix DepProxy == method

- doc/playbooks/TEAM_CHANGES.md
The "adding a team member" was missing adding the person to bundlerbot
> Add adding a team member to bundlerbot

- lib/bundler/fetcher/downloader.rb
- spec/install/gems/compact_index_spec.rb
- spec/support/artifice/compact_index_range_not_satisfiable.rb
On ruby 2.1, bundler would try to install the latest version of psych, which is not compatible with it, instead of using an older version.
This is the error message i would get:
`Gem::RuntimeRequirementNotMetError: psych requires Ruby version >= 2.2.2. The current ruby version is 2.1.0.`
Looking online, i managed to discover that there are 2 API in use, and if bundler can't use the compact index, it will not be able to detect ruby version requirements. (It might be a good idea to have a message that explain that more clearly somewhere, I found that in a random thread somewhere)
Using `bundle install --verbose`, I found out that a RangeNotSatisfiable was being returned by the `info/psych` call and it stopped the usage of the compact index. I figured out that this was because the local …
> Handle RangeNotSatisfiable for compact index

- lib/bundler/env.rb
- spec/bundler/env_spec.rb
When reporting my `bundle env` for https://github.com/bundler/bundler/issues/6677, I noticed an extra blank line between the `rbenv` and the `chruby` lines. Not really a big problem, other than people like me getting distracted by those little inconsistencies.
My diagnosis was that the formatting method was somewhere unintentionally printing an extra new line. After checking it out, it looks like any versions that are grabbed by shelling out to `#{tool} --version` will have this problem, since the new line from the subprocess output is included in the `bundle env` output, together with its own line returns.
My fix is to prune any trailing new lines from the output of those subprocesses. 
I chose this fix because it seemed like the simplest way to fix the issue.
> Remove extra new lines from `bundle env` output

- lib/bundler/lazy_specification.rb
The search was checked previously, so maybe it should be checked also at this place.
This issue was identified by Coverity scanner:
~~~
Error: FORWARD_NULL (CWE-476):
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb:77: null_check: Comparing "search" to a null-like value implies that "search" might be null-like.
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb:83: property_access: Accessing a property of null-like value "search".
~~~
> Check if 'search' is initialized.

- lib/bundler/deprecate.rb
* Otherwise, it should be defined by this file.
* The issue is bundler/deprecate.rb checks `defined? Bundler::Deprecate`
and this would normally return true since an autoload is defined for
that constant. But since the autoload file is #require-d explicitly
(by bundler/psyched_yaml and bundler/shared_helpers), MRI makes it
undefined to save this pattern. This however requires a complex
autoload implementation and is confusing to debug, so let's simplify.
* Related to https://github.com/bundler/bundler/issues/6163 and https://github.com/rubinius/rubinius/issues/3769.
Bundler fails in TruffleRuby without this change.
We plan to fix this case in TruffleRuby, but since at least 2 Ruby implementations did not expect such a corner case, we should make the code simpler since it's easy enough in …
> Check that Bundler::Deprecate is not an autoload constant

- lib/bundler/cli/exec.rb
- lib/bundler/current_ruby.rb
- lib/bundler/dependency.rb
- lib/bundler/ruby_version.rb
- man/gemfile.5.ronn
- spec/bundler/dsl_spec.rb
- spec/bundler/ruby_version_spec.rb
- spec/other/bundle_ruby_spec.rb
- spec/other/platform_spec.rb
- spec/support/platforms.rb
Hello,
This PR adds support for TruffleRuby in Bundler.
I searched for `rbx` and `jruby` (case-insensitive) through the codebase to find all places which need changes and where tests use specific Ruby implementations. So hopefully this PR is complete, but please tell me if I missed something.
I'd also like to test TruffleRuby in Bundler's CI, but will do this as a separate PR, as we first need the next release of TruffleRuby so that it includes the fix for https://github.com/oracle/truffleruby/issues/1413.
> Add support for TruffleRuby

- lib/bundler/gem_version_promoter.rb
- lib/bundler/resolver.rb
- spec/resolver/basic_spec.rb
- spec/support/indexes.rb
The problem was `bundle update --patch` could cause a prerelease to be resolved, when it shouldn't have been.
Closes #6684.
My diagnosis was the resolver moved pre's to be first when no pre requirement was specified, but then the GVP did its own sorting.
My fix was to re-implement that "pre's go first unless they were explicitly requested" logic in the GVP.
I chose this fix because it allows the GVP to properly sort versions, making it entirely correct without dependence upon the resolver.
> [GemVersionPromoter] Prefer non-pre-release versions

- spec/commands/exec_spec.rb
This is another try at #6685.
The problem was that I get a failure when running the specs locally.
My diagnosis was that the result of this specs depends, not on whether we are on Travis or not, but on which platform the spec runs. 
My fix is to check for the platform so that each platform gets its expected result, regardless of whether the spec is run on Travis CI or not.
I chose this fix because hopefully it doesn't break local specs for @colby-swandale, and it fixes them for me :)
> Better conditional assertion

- lib/bundler/shared_helpers.rb
- spec/bundler/shared_helpers_spec.rb
There is a LoadError occurring in Bundler when an application has its Gemfile installed with `--path`, and the user has a recent version of RubyGems that installs a version of Bundler as a default gem.
If the user has some code that they're running with `bundle exec` (like a test suite) that is shelling out and executing `bundle exec` again, the user will receive an error saying that Bundler could not be loaded.
/home/travis/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load': cannot load such file -- /home/travis/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/bundler-1.16.3/exe/bundle (LoadError)
The problem that's happening is that when we run `bundle exec`, Bundler will set the Ruby environment to add the path of the current version of Bundler into the `LOAD_PATH` and also require …
> Fix loadError occurring in nested bundle exec calls

- spec/runtime/setup_spec.rb
- spec/spec_helper.rb
The problem was that bundler specs won't pass on my system. One of the two failures I was getting is the spec added by #6502.
My diagnosis was that my system has a similar setup as TravisCI (Linux with a ruby version manager on top), but I don't set the `TRAVIS` environment variable to run the tests. This means some trickery used in the specs to get them green on TravisCI is not applied to my local run, so specs failed.
My fix is to make this spec green independently from whether it's run on TravisCI or not. My changes also make this spec not delete any files from the rubygems installation where the specs are running. In https://github.com/bundler/bundler/pull/6502#issuecomment-403713916 @indirect said that the files being deleted here are put in there by `RVM`. However, I don't think …
> Fix local spec failure

- lib/bundler/env.rb
It seems that only single OpenSSL availability check should be enough to output or not output the OpenSSL information.
I split this into two commits, so you can cherry-pick, in case you want to be more cautious about the availability of specific constants, but since they were introduced in Ruby 1.8.0 (https://github.com/ruby/ruby/commit/78ff3833fb67c8005a9b851037e7), I would not bother.
Please note that that this code was pointed out by Coverity scanner (although it is definitely not an error):
~~~
Error: FORWARD_NULL (CWE-476):
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/env.rb:113: null_check: Calling "defined?(OpenSSL)" implies that "OpenSSL" might be null-like.
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/env.rb:114: property_access: …
> Output OpenSSL information only when OpenSSL is available.

- spec/commands/exec_spec.rb
- spec/install/redownload_spec.rb
- spec/update/redownload_spec.rb
I noticed a couple of places where assertions were being excluded and they shouldn't:
* One was introduced by me in #6702, where the specs added (and some already present) started being tested only on bundler 2.x.
* The other one was introduced in f7414bcb17fe1bd67246021251b5f0527bd6afd1, where one assertion would be run only if a certain env variable was not set. I think it was because of a TravisCI environmental issue that now seems fixed.
My diagnosis was that none of these exclusions are necessary.
My fix is to restore the excluded assertions to all environments and branches.
I chose this fix because it seems best to avoid future problems.
> Run more assertions in more cases 

- lib/bundler/definition.rb
- spec/commands/update_spec.rb
This is my attempt to fix #6529
Running `bundle update` with `BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS: "true"` resulted in a gem getting downgraded to a really old version in a certain edge case. Ironically it wouldn't get downgraded when `BUNDLE_ONLY_UPDATE_TO_NEWER_VERSIONS` was set to false.
My diagnosis was that https://github.com/bundler/bundler/commit/47256d20cb05ebc724ee67173094682153b6b4aa tried to solve the problem of still allowing manual downgrades in the Gemfile while `only_update_to_newer_versions` is true. But introduced a regression that prevented the `additional_base_requirements_for_resolve` method to work as intended:
This is the relevant change from that commit that tries to avoid adding the `>=` requirement if the  requirement in the Gemfile is different than the …
> Fix only_update_to_newer_versions regression

- lib/bundler/source/metadata.rb
I am not sure what is the purpose of this code neither I have idea if the proposed fix is actually correct, but I am quite sure that the condition does not make sense, because the assignment takes priority and therefore the branch is never accessible. So I just take a guess and submitted this PR to open the discussion ;)
Please note this was pointed out by Coverity scan of the Bundler code:
~~~
Error: DEADCODE (CWE-561):
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/source/metadata.rb:22: cond_return: Condition "nil && Bundler.rubygems().loaded_specs("bundler")", returning "nil". Now the type of "nil && Bundler.rubygems().loaded_specs("bundler")" must be null.
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/source/metadata.rb:22: assignment: …
> Fix assignment in condition.

- bundler.gemspec
When the users visit https://rubygems.org/gems/bundler and click the links, or access the gem metadata from scripts e.g. gem-src, we're seeing unneeded redirection from http://... to https://... because both github.com and bundler.io redirects http requests to https.
Rewrote all http:// URLs in the gemspec to https://.
> http:// URLs in the gemspec

- lib/bundler/source/git.rb
- spec/install/gemfile/git_spec.rb
Kind of a followup to https://github.com/bundler/bundler/pull/4272
As demonstrated by the updated test case, whenever a gem is changed (even a non-git one), bundler re-fetch all git gems, and recompile their extensions (if any).
You can repro that issue by running the modified `git_spec.rb` against master.
In that patch I simply make `Source::Git` skip the `fetch` step if the `cached_revision` matches the install path.
Since `install_path` uses only the first 10 characters of the full revision, there is a very very small chance of a collision happening, but It's so small that I think it can be ignored.
However my understanding of the codebase is too limited to be 100% sure the git gem would be properly updated if it's definition (`branch` / `ref` / `etc`) is updated. I tried to write a …
> Avoid fetching an rebuilding git gems when it's not necessary

- lib/bundler/cli.rb
- spec/bundler/cli_spec.rb
- spec/commands/show_spec.rb
- spec/other/cli_dispatch_spec.rb
- spec/plugins/command_spec.rb
- spec/support/helpers.rb
The problem was `bundle show` deprecation messages are incorrect:
```
$ bundle show yard
[DEPRECATED FOR 2.0] use `bundle list` instead of `bundle show`
Resolving dependencies...
/home/deivid/Code/activeadmin/.bundle/ruby/2.5.0/gems/yard-0.9.16
$ bundle list yard
ERROR: "bundle list" was called with arguments ["yard"]
Usage: "bundle list"
```
My diagnosis was that deprecation messages only mention `bundle list`, but in some cases, the replacement is `bundle info`.
My fix is to replace "show" in the original command with the appropriate alternative in each case.
I chose this fix because it was the most user friendly message, since it prints the exact command the user needs to type to get rid of the warning.
> Correct `bundle show` deprecation

- lib/bundler/build_metadata.rb
A change that was introduced in #6664 is breaking RubyGem's specs because the Build Metadata is not being generated correctly.
This is breaking because the change is checking for the `.git` to determine if the git hash should be fetched for the version string. This folder does not exist in the submodule in RubyGems' repo
See https://travis-ci.org/rubygems/rubygems/jobs/437576972
Check if `.git` exists either as a file or folder
> Check for file or folder when checking for git hash in build metadata

- spec/spec_helper.rb
- spec/support/helpers.rb
`win32-open3` gem was required Ruby 1.8 with Windows environment. Because RubyInstaller2 only provides the version of Ruby 2.1+.
Removed needless workaround.
> Removed win32-open3 workaround.

- spec/commands/newgem_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/support/helpers.rb
- spec/support/rubygems_ext.rb
In ruby core repository, We need to replace executable file like `ruby`, `rake`, `gem`. 
This pull request makes hard-coded executable file to the helper methods.
> Use helper method instead of hard-code path.

- Rakefile
- spec/support/path.rb
- spec/support/rubygems_ext.rb
@segiddins encouraged contributions towards support for Windows
https://github.com/bundler/bundler/issues/5992#issuecomment-326809543
As a first step towards this goal this commit introduces safe and
OS agnostic directory traversal in the first pieces of Ruby code
called when setting up a test environment.
See #5992.
File path concatenation explicitly used UNIX style file system separators.
Use `File.join` and `Pathname.join` instead. Define null device explicitly since Ruby 1.8.7 does not know `File::NULL`.
> Make RakeTask spec:deps OS agnostic

- .travis.yml
New versions of all the currently supported versions of Ruby we're released today. This PR is just updating .travis.yml to use these new versions of Ruby.
> update ruby to the latest versions in travis-ci

- lib/bundler/build_metadata.rb
We recently merged #6664 to prevent Bundler from (wrongly) claiming the
git commit of any parent directory when it is run from source. However,
Bundler is also run from source as a submodule in RubyGems, and in that
case it does not have its own git directory.
This commit resolves the failure in version_spec.rb that only appears
when the Bundler tests are run from a submodule, by explicitly checking
for that submodule, and using `git ls-tree` to get the sha if so.
Arguably, this is a bugfix compared to the previous behavior, which
would blindly print the current sha from the _RubyGems_ repo, while
claiming that it was the sha of Bundler.
> when running from source, find submodule shas too

- man/bundle-config.ronn
This PR is just adding documentation for the feature in #6024.
> Add docs for configuring bundler folders through ENV vars

- lib/bundler.rb
- spec/bundler/bundler_spec.rb
The problem was that `Pathname` instances in an array can not be sorted when there are string instances in the array also. Because of this, calling `.sort` before `.to_s` resulted in the error
```
[!] There was an error parsing `Gemfile`: comparison of Pathname with String failed. Bundler cannot continue.
```
you can easily see this issue doing
```
> require 'rails'
=> true
> [Pathname.new("/tmp/bundle")]
=> [#<Pathname:/tmp/bundle>]
> [Pathname.new("/tmp/bundle"), "test"]
=> [#<Pathname:/tmp/bundle>, "test"]
> [Pathname.new("/tmp/bundle"), "test"].sort
ArgumentError: comparison of Pathname with String failed
```
`sort` was called before `map` in the warn …
> fix error with path objects in array

- Rakefile
- lib/bundler/templates/newgem/newgem.gemspec.tt
- spec/bundler/gem_helper_spec.rb
- spec/commands/newgem_spec.rb
- spec/commands/pristine_spec.rb
- spec/support/builders.rb
- spec/support/helpers.rb
- spec/support/rubygems_ext.rb
I wrote this patch a while ago but I didn't propose it because I didn't think it would be accepted. Now I think we're ready.
The problem was that the specs have a lot of conditional behavior on `Gem::VERSION`.
My diagnosis was that this was necessary because of testing against a big range of rubygems versions on the latest stable branch.
My fix is to remove all the conditionals since we'll no longer test against rubygems versions that old on the latest stable, once #6763 lands.
I chose this fix because it makes test code simpler.
> Remove unnecessary stuff from specs

- lib/bundler/injector.rb
- spec/commands/remove_spec.rb
https://github.com/bundler/bundler/issues/6768
`remove_nested_blocks` considers any appearance of text matching a block method (`group source env install_if`) to be an occurrence of a nested block.
`remove_nested_blocks` should only reduce the scope of where a nested block method can occur.
Another approach would use word delimiters rather than `starts_with?` to find nested block methods, but this is probably fine.
> Fix `remove` when block method appears in gem name

- lib/bundler/templates/Executable.bundler
`bundle binstubs bundler` generates the file like followings.
```ruby
require "rubygems"
m = Module.new do
module_function
def invoked_as_script?
File.expand_path($0) == File.expand_path(__FILE__)
end
(snip)
end
```
the template's `module_function` line is not match to other lines.
I fix the template.
no other options.
> Fix indentation of bundler executable

- spec/bundler/plugin/installer_spec.rb
- spec/bundler/settings_spec.rb
- spec/bundler/source/git/git_proxy_spec.rb
- spec/bundler/source/rubygems/remote_spec.rb
- spec/commands/config_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/support/helpers.rb
The problem was that while working on #6713, I noticed several issues like order dependent failures, situations hard to debug, or specs doing too much and taking longer than they should.
My diagnosis was that:
* Sometimes specs leak settings and env variable modifications.
* When a hang happens inside a subprocess, it's hard to debug because logging is not printed out anywhere.
* Some specs create unnecessary gemfiles and run `bundle install` multiple times unnecessarily.
My fix for state leaks is to reset state after each spec, for the hangs is to reorder some lines in the `sys_exec` helper (https://github.com/bundler/bundler/commit/b305a5b2524a6457b05a9d39e9526f75c98a0752), and for the unnecessary operations, to refactor the specs to avoid them.
I chose this fix because it seems like …
> Spec reset state and refactorings

- lib/bundler/plugin/index.rb
- spec/bundler/plugin/index_spec.rb
The problem was running `plugin install` twice for a plugin withs hooks would cause that hook to be registered twice.
Closes #6771.
My diagnosis was a plugin's hooks should only be run once per event.
My fix is to `uniq` the list of plugins registered for each event.
> [Plugin::Index] Only register each plugin once for a given hook

- lib/bundler/cli/install.rb
- lib/bundler/resolver.rb
I've been working on a few repos for most of this year that use a privately-hosted gem with the same name (but completely different purpose) as a gem hosted at rubygems.org - whenever I start with a clean copy and `bundle install` for the first time, I am presented with a warning in red that the gem was found in multiple sources. The red text makes me think that something went wrong, even though bundler did exactly what I wanted it to do.
The user experience is wrong - a warning should not be red.
When I looked at the source, I saw immediately that the warning was using `Bundler.ui.error` instead of `Bundler.ui.warn`.
This is a bug fix with a limited lifespan - after setting up a local copy of bundler I see that 2.0's handling of multiple sources A) is smarter and bypasses the error in …
> Fix multiple source warning messages from `error` to `warn`

- spec/bundler/ssl_certs/certificate_manager_spec.rb
There was a typo mistake in a comment inside `spec/bundler/ssl_certs/certificate_manager_spec.rb#14`.
> Fix typo from `ssl_certs.rb`

- lib/bundler/definition.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gemfile/path_spec.rb
The problem was setting `only_update_to_newer_versions` would break using path gems.
Closes #6750
My diagnosis was path gems should _always_ get their version used, since there's 0 alternative versions from a path source.
My fix should circuits the list of additional requirements when the dependency's source is a path source.
I chose this fix because it solves the problem in the same place that has the feature flag conditional
> [Definition] Dont pin path deps to newer versions

- lib/bundler/lockfile_parser.rb
a task recommended by a TODO comment for the upgrade to Bundler 2.0
> removed string dup in lockfile_parser.rb for bundler 2.0

- lib/bundler/plugin.rb
- spec/plugins/install_spec.rb
The problem was installing a new plugin in deployment mode would fail with a suggestion the lock file was corrupted, when it installed fine without deployment mode.
Fixes #6795.
My diagnosis was deployment mode was interfering with installing a new plugin.
My fix overrides the deployment and frozen settings when creating the plugin Definition.
I chose this fix because having a "frozen" plugin bundle makes no sense, since plugins aren't written to the lockfile.
> [Plugin] Ignore the deployment setting

- lib/bundler/dsl.rb
- lib/bundler/feature_flag.rb
- spec/bundler/dsl_spec.rb
This PR is setting Git gems to be fetched over https by default.
Note: This PR is successing #6791 
Closes #6785
> Use https in the Github shortcut by default in Bundler 2

- .github/config.yml
I used the wrong block in the welcome message YAML. `>` strips the new line breaks, we want to use `|` instead.
> use '|' to preserve line breaks in welcome message

- .travis.yml
The problem was that we lost some CI matrix entries after #6830.
My diagnosis was that extra entries should be defined under `jobs:` now, specifying their stage.
My fix is to merge the `jobs` and `matrix` section, and specify the `stage` of each entry.
I chose this fix because it seems to bring back the matrix to the way it was before (except for the extra linting stage).
> Bring CI matrix back to its previous state

- spec/bundler/definition_spec.rb
The problem was the specs are brittle.
My diagnosis was  we should assume code can open other files.
My fix allows other files to be opened, and only raises when opening the file under test.
> Allow files other than Gemfile.lock to be opened in definition specs

- lib/bundler/inline.rb
- spec/runtime/inline_spec.rb
I'm using inline bundler on my CI minitest file. I wanted to make it quiet so output is clean and meaningful.
Bundler inline's gemfile method only accepted :ui option.
I added quiet option flag to gemfile method.
I chose this fix because it looked simple and clean.
> Added quiet flag to inline bundler

- man/bundle.ronn
The manual entry for `bundle remove` was missing in `bundle.ronn`
See #6846
Fixes #6846
> add bundle-remove entry to bundler man page

- lib/bundler/rubygems_gem_installer.rb
Installing gems on _really really_ old versions of RubyGems is not working. See #6839
We were accessing an instance variable which did not exist
instantiate the instance variable ourselves.
This was the simplest solution that can be easily merged with `1-17-stable`
Fixes #6839
> fix installing gems on _really_ old versions of RubyGems

- lib/bundler/source/metadata.rb
There is a *really* obscure bug in Bundler that is causing deploys in Heroku to fail for certain environments. 
The environment in this case being Ruby 1.9.3 and RubyGems 1.8
I also think that this is the same bug causing https://github.com/bundler/bundler/issues/6829
See https://gist.github.com/schneems/0247e3d5c3e079ecffd7cd10887c3cc9
Revert the commit that was causing this bug. The original PR can be found at https://github.com/bundler/bundler/pull/6687
I can confirm the fix by being able to deploy to Heroku succesfully using Bundler 1.17.2 + the commit to revert the change being applied on top.
```
$ git push heroku master
Enumerating objects: 87, done.
Counting objects: 100% (87/87), done.
Delta compression using up to 4 threads
Compressing objects: 100% (72/72), done.
Writing …
```
> revert commit b490e73

- lib/bundler.rb
- spec/other/major_deprecation_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
The problem was that I noticed that there's still some use cases where the current implementation of `Bundler.with_clean_env` can be useful. Whereas the most common use case is to go back to the original environment before bundler was loaded, sometimes you actually want a fully "unbundled" environment. For example, I wanted to test a rails template in isolation (`rails new my_app -m my_template.rb`) in a library where we specifically set `BUNDLE_GEMFILE` in CI. In that context, `with_original_env` won't do the trick for me, because to properly test my template i need to make sure no bundler environment is set at all.
My diagnosis was that we should probably undeprecate `(with_)clean_env`. But @indirect suggested that we should still deprecate the method name, because it's confusing what …
> Improve `clean_env` deprecation path

- .travis.yml
- Rakefile
- bundler.gemspec
- lib/bundler/current_ruby.rb
- lib/bundler/spec_set.rb
- man/gemfile.5.ronn
- spec/commands/exec_spec.rb
- spec/lock/lockfile_bundler_1_spec.rb
- spec/quality_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
- spec/support/path.rb
The problem was we weren't testing our compatibility with the latest and greatest.
> Test against Ruby 2.6 and RubyGems 3

- .travis.yml
- bundler.gemspec
It turns out that every existing version of RubyGems will ignore the required RubyGems version and try to install the newest version of Bundler... until the middle of the install, when it will raise an exception and fail. This PR tries to fix that in the least-bad way possible.
The end user problem is that running `gem install bundler` now produces an exception on any Ruby and RubyGems older than 2.6 or 3.0 respectively.
Unfortunately, RubyGems does not use the `required_rubygems_version` to select an older version of Bundler to install. Instead, RubyGems tries to install the newest version even though that version is not compatible, and then raises an exception during installation because it is not compatible.
Lower the `required_rubygems_version` in Bundler 2 back down to RubyGems 2.5 …
> Lower required RubyGems to 2.5 or greater

- spec/bundler/definition_spec.rb
I found the missing commit different with 1-17-stable. 
I picked 5fb389d49a1bfe89f711beb51681276d7ced418e from master branch.
> Merge #6834 for 2-0-stable

- lib/bundler/feature_flag.rb
The problem was that some code in the feature flags implementation seemed uncovered.
My diagnosis was that the code should be either covered or removed.
My fix was to remove the code.
I chose this fix because the scenario where that code would get covered is more likely to be unintentional and risk introducing a bug. Defining a feature flag without a default block is the same as don't defining a feature flag and just relying on the default value for the setting. In these circumstances, it's more likely that the developer forgot to include a default block, so letting that case crash would be better, I think.
> Remove unnecessary condition

- .travis.yml
- lib/bundler/env.rb
- lib/bundler/gem_helper.rb
- lib/bundler/installer/parallel_installer.rb
Nothing.
Bundler will never use them in version 2.
> Removed compatibility hack for old rubies.

- bundler.gemspec
- spec/support/less_than_proc.rb
We faced a lot of warnings with `rake spec` of bundler repository.
Ruby 2.7.0-dev added the warnings for `Object =~` comparison. 
I added the additional condition and bump a version of the development dependency.
> Ignore `Object =~` warnings.

- Rakefile
- bundler.gemspec
The problem was that tools like RubyGems.org or Bundix that use the gemspec as the source of truth for dependencies didn't pick up on the development dependency on Rubocop.
My diagnosis was that the reason for this, which was that Rubocop had a minimum Ruby version of 2.0.0, was no longer an issue, since Bundler 2 doesn't support Rubies that old anyway.
My fix was to move the Rubocop requirement into the gemspec.
I chose this fix because it addresses the problem I was having, feels right, and the old workaround doesn't look like it's necessary any more.
> Move Rubocop development dependency into gemspec

- lib/bundler/templates/newgem/newgem.gemspec.tt
- spec/commands/lock_spec.rb
- spec/commands/newgem_spec.rb
- spec/commands/show_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gems/compact_index_spec.rb
- spec/lock/lockfile_bundler_1_spec.rb
- spec/lock/lockfile_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/builders.rb
- spec/support/rubygems_ext.rb
Related with https://github.com/bundler/bundler/pull/6923
rake-10.x displayed the warnings of `Object =~` with Ruby 2.7.0-dev.
Rake 10.0 is EOL. I'm a maintainer of Rake. I have no plan to avoid `Object =~` warnings with Rake 10.x.
> Bump rake version to 12.0 on gemspec template

- CODE_OF_CONDUCT.md
- README.md
- doc/README.md
- doc/TROUBLESHOOTING.md
- doc/contributing/COMMUNITY.md
- doc/contributing/GETTING_HELP.md
- doc/contributing/HOW_YOU_CAN_HELP.md
- doc/contributing/ISSUES.md
- doc/contributing/README.md
- doc/documentation/README.md
- doc/documentation/VISION.md
- doc/documentation/WRITING.md
- lib/bundler/cli/issue.rb
- man/bundle-init.ronn
- man/bundle.ronn
- man/gemfile.5.ronn
- spec/resolver/basic_spec.rb
There are 3 documentation problems
* End-users experience 301 redirect when visiting http://www.bundler.io and http://bundler.io
* End-users might accidentally send email addresses via http version of https://slack.bundler.io, which is not redirected automatically.
* Partially fixing this is O.K., but consistent URLs throughout the documentation are easy to use.
I have manually visited the Slack invitation URL on https://bundler.io/ and noticed the problem.
Following are the simple curl command to explain this problem.
```
$ curl -I  http://slack.bundler.io
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 3726
Etag: W/"QPm3qygnJrqeFm+KK+VifA=="
Date: Mon, 28 Jan 2019 07:32:02 GMT
Via: 1.1 vegur
```
```
$ …
```
> Make URLs in document consistent and secure

- lib/bundler/cli/common.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/commands/update_spec.rb
Issue #5994 
As mentioned by @indirect I added a `patch` option in the bundler config, which by default is false. If set to true, patch level update are preferred if no update levels are specified. 
A patch level config option which can be opted into.
> Add patch option in bundle config

- lib/bundler/shared_helpers.rb
- spec/bundler/shared_helpers_spec.rb
In ruby core, the bundled bundler was located same as rubylibdir. When user used the specific version of default gems like json, Bundler uses default gems under the rubylibdir, not a specific version.
Fixed  https://bugs.ruby-lang.org/issues/15469
See the details: https://bugs.ruby-lang.org/issues/15469#note-4
I avoid adding bundler directory from RUBYLIB environmental variable Because its directory was already added $LOAD_PATH.
> Ignore to add bundler lib direcotry if it is same as rubylibdir

- .travis.yml
- Rakefile
- spec/commands/exec_spec.rb
- spec/commands/pristine_spec.rb
The problem was that we don't know whether bundler works against the latest patch level version of MRI 2.3.
My diagnosis was that we should test it.
My fix is to bump the 2.3 matrix entries in TravisCI config to 2.3.8. This MRI version comes with rubygems 2.7.8, so bump that too.
I chose this fix because it's the only one, given the CI setup we currently have.
> Bump test MRI 2.3 version in TravisCI

- bin/rake
The problem was that on a fresh ruby install (docker, I'm looking at you), running `bin/rake spec:deps` prints the following errors, even if nothing end up going wrong and the dependencies get installed:
```
Could not find 'automatiek' (~> 0.1.0) among 17 total gem(s)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.3.7:/usr/local/rvm/gems/ruby-2.3.7@global', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'mustache' (= 0.99.6) among 17 total gem(s)
Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.3.7:/usr/local/rvm/gems/ruby-2.3.7@global', execute `gem env` for more information (Gem::MissingSpecError)
Could not find 'rake' (~> 12.0) …
```
> Clean up first `bin/rake spec:deps` output

- Rakefile
The problem was that we are using old rubygems versions internally.
My diagnosis was that we should use the newest version of our own software.
My fix is to upgrade the rubygems version used in the Rakefile for development tasks.
I chose this fix because it's good for us.
> Bump base rubygems version to 3.0.2

- Rakefile
- bundler.gemspec
The problem was that I was confused about the `rdiscount` dependency since I didn't see it used anywhere.
My diagnosis was that it's just an indirect dependency (through ronn).
My fix is to remove the dependency.
I chose this fix because it will no longer confuse devs into thinking we're actually using it directly.
> Remove rdiscount indirect development dependency

- spec/commands/exec_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/runtime/require_spec.rb
- spec/runtime/setup_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
The problem was that sometimes one get warnings on the system rubygems files, or maybe when modifying the `tmp` copy of rubygems, the changes seem not applied.
My diagnosis was our specs sometimes use the system rubygems version, not the one controlled by the `RVG` environment variable.
My fix is to remove most occurrences of `:env => { :RUBYOPT => "-r#{spec_dir.join("support/hax")}" }` when spawning subprocesses. The reason is that in order to use the tmp copy of rubygems, our specs need to include `-I tmp/rubygems/lib` in the `RUBYOPT` environment variable. If we overwrite it in subprocesses, it won't use it. We can remove those however, since the "hax file" is already included in the main spec helper, while also keeping the previous value of `RUBYOPT`. …
> Don't leak to system rubygems during specs

- doc/contributing/BUG_TRIAGE.md
As discussed on Slack, this is the suggested process to deal with stale issues.
/cc @colby-swandale
> Add stale issues section to bug triage doc

- lib/bundler/templates/newgem/travis.yml.tt
I reviewed a PR in an Open Source project, and it had this defunct setting from Travis.
I was told the `bundle gem` command outputs this directive, and I looked here, and lo, it was.
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for historical detail about when it was removed.
My fix is to **drop** this **unused directive** from the template.
I chose this fix because it works the same for the user, with less configuration.
> Travis "bundle gem" template: Drop unused sudo: false option

- spec/quality_es_spec.rb
- spec/quality_spec.rb
- spec/support/matchers.rb
The problem was that the test suite spits some warnings
```
/home/deivid/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:72: warning: method redefined; discarding old be_well_formed
/home/deivid/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/rspec-expectations-3.8.2/lib/rspec/matchers/dsl.rb:72: warning: previous definition of be_well_formed was here
```
My diagnosis was that we are redefining an RSpec matcher.
My fix is to define the matcher just once.
I chose this fix because moving it to the centralized place where custom matchers are defined made sense to me.
> Fix redefinition warning

- lib/bundler/gem_helper.rb
- lib/bundler/shared_helpers.rb
- spec/commands/clean_spec.rb
- spec/quality_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
- spec/support/rubygems_ext.rb
RSpec example of the bundled bundler was failed on Ruby 2.7 from ruby core repository. I fixed some of the issues on ruby core repository.
1. I fixed the location of `lib/bundler.gemspec` to `lib/bundler/bundler.gemspec` for fixing gemspec issue of Ruby 2.6.1: https://github.com/ruby/ruby/commit/7c9771be02ddc707fea8ec96089c8a100c59f806
2. The current Bundler examples relied on the same versions of Ruby that are the first binary of PATH and rspec invocation binary. But the ruby core repository uses the different versions for them.
I fixed the location path of bundler.gemspec and uses `ENV['BUNDLE_GEM']` instead of hard-coded `gem` command.
There is no options on ruby core repository. I welcome to another options.
> Backport the latest commits on ruby core repository.

- bundler.gemspec
- spec/support/path.rb
On the ruby core repository has the original patch for the test suite. The current bundler repository was inconsistency status with it.
This pull-request was the missing commit of https://github.com/bundler/bundler/pull/6973
The test suite of bundler break the inconsistency gemspec location,
> Update the location of bundler gemspec.

- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- lib/bundler/shared_helpers.rb
- man/bundle-config.ronn
- spec/commands/show_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/install/redownload_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/support/matchers.rb
- spec/update/redownload_spec.rb
The problem was we've had deprecations in place for a long time, but we've never displayed them to users by default. 
My diagnosis was that the current strategy doesn't work because:
* Printing deprecations as an optin feature almost never get enabled, so most users don't know about the stuff we'll be deprecating in the future.
* Printing deprecations in "deprecation releases" doesn't work well either, because it's unclear how long the deprecation release should last and thus how long we need to hold the final release (that will inhibit installation of the deprecation release).
My fix is to remove the concept of deprecation releases, and to add a feature flag for printing major deprecations that it's enabled by default.
As a extra related change, I also reworded the deprecation messages, …
> Turn on deprecations by default

- lib/bundler/shared_helpers.rb
- spec/bundler/fetcher/compact_index_spec.rb
- spec/bundler/friendly_errors_spec.rb
- spec/bundler/shared_helpers_spec.rb
- spec/bundler/ui_spec.rb
- spec/cache/gems_spec.rb
- spec/commands/config_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/package_spec.rb
- spec/commands/viz_spec.rb
- spec/install/bundler_spec.rb
- spec/install/process_lock_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/realworld/double_check_spec.rb
- spec/realworld/edgecases_spec.rb
- spec/runtime/setup_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
The problem was there's a lot of unnecessary code, specially in specs, that's never run.
My diagnosis was that since dropping support for old ruby versions, this code is no longer necessary.
My fix is to remove the code.
I chose this fix because red is great on diffs.
> Remove unnecessary ruby filters

- lib/bundler/lockfile_parser.rb
- spec/lock/lockfile_bundler_1_spec.rb
- spec/lock/lockfile_spec.rb
Fixes #6909.
The problem was that we're recommending a command to make a warning go away that doesn't really make the warning go away.
My diagnosis was that the current recommendation installs the latest bundler, which might not be the same as the version the lock file was created with. If it's not the same, the warning will not go away.
My fix is to recommend installing exactly the version the lockfile was created with.
I chose this fix because it's really simple and it should work.
> Fix warning message about bundler version

- .travis.yml
Fixes #6956.
The problem was that we have a very slow CI
My diagnosis was that the CI matrix is very big, and that old rubies use more resources than new rubies.
My fix is to remove some entries and when it comes to testing old rubygems version, test only the rubygems version each tested MRI version shipped with.
I chose this fix because it saves us some time, and it gives all rubies the same amount of CI resources.
> Smaller ci matrix

- lib/bundler/source/rubygems.rb
- spec/plugins/install_spec.rb
Fixes #6946 
There was no check to ensure that the plugin was already installed or not. 
I added the check [here](https://github.com/bundler/bundler/compare/master...ankitkataria:plugin-fix?expand=1#diff-68bd939cd3589d8fdda08a12433659ebR109)
I also added a small test for the same
> Add check for already installed plugin

- spec/install/gemfile/git_spec.rb
- spec/support/builders.rb
The problem was that Azure logs are full of "error: pathspec 'COMMIT'' did not match any file(s) known to git." and other similar ones.
My diagnosis was that Windows' doesn't like single quotes.
My fix is to use double quotes, which is also consistent with our global style.
I chose this fix because it brings the number of spec failures on Windows from 657 to 474! :tada:
> Use double quotes for `git commit -m`

- .rubocop_todo.yml
- lib/bundler/cli/gem.rb
- lib/bundler/dsl.rb
- lib/bundler/fetcher.rb
- lib/bundler/gem_helpers.rb
- lib/bundler/graph.rb
- lib/bundler/resolver.rb
- lib/bundler/ruby_version.rb
- lib/bundler/similarity_detector.rb
- lib/bundler/source/path.rb
- spec/support/artifice/endpoint.rb
References https://github.com/bundler/bundler/pull/7009/files#r261892716.
The problem was just some leftover consistency offenses.
My diagnosis was that we can easily fix these globally.
My fix is to enable the three cops and run `rubocop --auto-correct`.
I chose this fix because these cops depend on each other, so enabling just one of them leaves weird indented code behind.
> Fix all offenses of some easy cops

- spec/bundler/shared_helpers_spec.rb
A specific test (#6890) was failing...
... because the comparison was missing the drive letter on Windows. 
I added expansion of the path that was already present in the implementation but not the test.
Makes the test pass and looks right.
---
closes #6890 
fixes 1 failing test on Windows
> Expand comparison path for Windows compat

- spec/commands/binstubs_spec.rb
- spec/commands/newgem_spec.rb
- spec/support/helpers.rb
Several tests were failing on Windows because of the same problem:
On macOS and Linux you can prepend `ENV_VAR=value` in front of a command to set an environment variable for just this command execution. 
On Windows this construct doesn't exit and such a command fails.
`Open3.popen3`, the method used to executed the command in `sys_exec`, also has an optional `env` parameter which you can use to supply a hash of environment variables. Instead of prepending on the command itself, the code now uses that parameter for the env variables. (Suggested by @deivid-rodriguez in https://github.com/bundler/bundler/issues/6886#issuecomment-452010623).
The parameter of `Open3.popen3` perfectly matches our use case.
---
Fixes 35 failing tests on Windows.
closes #6886
> Do not prepend ENV vars for sys_exec calls, but use env param of Open3.popen3

- spec/support/helpers.rb
Some tests were failing on Windows with strange paths not existing.
Turns out a regex in the helper for paths didn't fire on Windows paths as they start with something like `C:/`.
So I adapted the regex to also match Windows paths.
... which seemed like the right thing to do here.
---
Fixes 21 test failures on Windows.
closes #6892
> Adapt helper path regex to also work with Windows paths

- .rubocop.yml
- .rubocop_todo.yml
- Rakefile
- bin/rake
- bundler.gemspec
- lib/bundler/cli.rb
- lib/bundler/cli/doctor.rb
- lib/bundler/dsl.rb
- lib/bundler/friendly_errors.rb
- lib/bundler/graph.rb
- lib/bundler/lockfile_parser.rb
- lib/bundler/plugin/installer.rb
- lib/bundler/resolver.rb
- lib/bundler/retry.rb
- lib/bundler/ruby_version.rb
- lib/bundler/rubygems_integration.rb
- lib/bundler/settings.rb
- lib/bundler/source/rubygems.rb
- lib/bundler/worker.rb
- lib/bundler/yaml_serializer.rb
- spec/bundler/bundler_spec.rb
- spec/install/gemfile_spec.rb
- spec/install/gemspecs_spec.rb
- spec/quality_es_spec.rb
- spec/support/artifice/compact_index.rb
- spec/support/artifice/compact_index_api_missing.rb
- spec/support/artifice/endpoint_api_missing.rb
- spec/support/helpers.rb
- spec/support/matchers.rb
The problem was that a few cops with exceptions in the TODO file have been bothering me recently when moving files around.
My diagnosis was that we can just fix these offenses once and for all, or alternatively disable them inline, or moving them to the permanent config.
My fix is to:
* Auto-correct a few simple cops.
* Permanently disable `Style/GuardClause`, because I don't think it always leads to better code, and sometimes it forces artificial refactorings when making changes to methods, making the intention of the changes more obscure.
* Move `rescue Exception` disabling inline, so that when moving that code around, rubocop doesn't complain.
I chose this fix because this is my opinionated approach to this. :)
> Fix offenses for more cops

- spec/bundler/source_spec.rb
Fixes https://github.com/bundler/bundler/issues/6900
The current bundler examples were not supported on mswin and non-tty environments.
I make to skip them when Thor detected unsupported environment.
Thor is vendoered now. It's easy to fix bundler's example directly.
> skip colorize examples when the environment was mswin or non tty.

- lib/bundler/compact_index_client.rb
- lib/bundler/fetcher.rb
- lib/bundler/fetcher/compact_index.rb
- lib/bundler/fetcher/downloader.rb
- spec/install/gems/resolving_spec.rb
- spec/support/artifice/compact_index_rate_limited.rb
The problem is that sometimes `bundler` is unable to resolve certain gemfiles. Specifically, sometimes it does not respect the `required_ruby_version` setting. This causes some people to assume that `bundler` will always try to install the latest version of any dependency, regardless of the ruby version being run, because as a matter of fact, this feature sometimes just doesn't work. See for example the discussion at https://github.com/rspec/rspec/issues/25.
The problem was consistently reproducible until a few minutes ago with the following `Gemfile` under `ruby 2.3.7`
```ruby
source "https://rubygems.org"
ruby "2.3.7"
gem "berkshelf", "= 6.3.1"
```
```
$ docker run -it --rm --volume $(pwd):/app ruby:2.3.7 sh -c "cd /app && rm -f Gemfile.lock && bundle install"
Fetching gem metadata from …
```
> Fallback to sequentially fetching specs on 429s

- bundler.gemspec
- spec/quality_spec.rb
- task/release.rake
The initial problem was that the default bundler gemspec integrated in ruby-core was shipped nearly empty: https://bugs.ruby-lang.org/issues/15582. That caused issues in bundler: https://github.com/bundler/bundler/issues/6937  
I looked into ruby-core history, and still not fully sure how it happened but something I noticed is that bundler does not make this integration easy because ruby-core doesn't have a git environment available, so it needs to do a bit of juggling: https://github.com/ruby/ruby/blob/trunk/tool/rbinstall.rb#L802-L803. We could make things easier.
My fix is to stop subshelling to `git` from our own gemspec. I think we do this in the default generated gemspec so that newbie users don't accidentally ship generated files with their gems (although the current solution would …
> Remove git subshelling from gemspec

- lib/bundler/shared_helpers.rb
- spec/other/major_deprecation_spec.rb
The problem was the current message about deprecating `Gemfile` in favor of `gems.rb` was incorrect, and this I'm not sure when it was supposed to be displayed. Its corresponding test was also failing.
My diagnosis was that the intention was not to deprecate Gemfile's for the time being, but only warn if the user opts in to `gems.rb` but does not remove the old `Gemfile`.
My fix is to properly detect the situation where both `Gemfile` and `gems.rb` files are present, and show proper messages guiding the user to properly make the switch.
I chose this fix because I think it works and doesn't take this migration too far, since the ecosystem is not yet ready for this at all.
> Fix multiple gem files deprecation

- lib/bundler/dsl.rb
- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- spec/bundler/dsl_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/quality_spec.rb
The problem was that our plan for deprecating using `git` instead of `https` for custom sources under the hood, and to deprecating those custom sources itself was unclear.
My diagnosis was that we should give contradictory/confusing deprecation warnings to users, so we should do this is several steps.
My fix is to implement the following plan:
* In bundler 2 (next release, 2.1 for example), start using https by default for the custom sources (`:github`, `:gist`, `:bitbucket`), and deprecate setting the `github.https` setting to false.
* In bundler 3, make the setting `github.https` a noop, using `https` nevertheless, and go ahead and deprecate the sources.
I chose this fix because it's the friendlier path I could think of for our users.
> Git based sources and custom sources deprecation

- lib/bundler/cli.rb
- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- spec/other/major_deprecation_spec.rb
The problem was that deprecating sticky options is currently "useless" since we are removing the flags where the stickyness makes a difference at the same time. So, we don't help users adapt to (and understand) our changes. 
My diagnosis was that we should do this change in two steps, so that first users get a explanation about why we are removing the flags and what is the preferred alternative for them, and once nobody is no longer using these flags, we deprecate sticky options in general, since they are surprising and no longer useful, since we don't depend on them. 
My fix is to:
* In bundler 2 (next release, 2.1 for example), print a deprecation message to warn about the removal of all the flags that currently depend on the options being remembered.
* In bundler 3, remove the options …
> Fix sticky options deprecation

- spec/bundler/gem_helper_spec.rb
- spec/bundler/mirror_spec.rb
- spec/bundler/vendored_persistent_spec.rb
- spec/commands/info_spec.rb
- spec/commands/install_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
- spec/support/rubygems_ext.rb
The problem was that the current specs don't pass under docker.
My diagnosis was that we should use 0.0.0.0 instead of 127.0.0.1 for mirror specs, since docker likes it better and the change doesn't affect the intention of the specs.
My fix is to do that change, but also add a few extra simplifications that I created while setting up the specs to run inside a docker image.
I chose this fix because it works and makes the test setup simpler.
> Spec simplifications

- .azure-pipelines/steps.yml
The problem was that sometimes Azure is timing out. My guess is that this is not Azure slowness, but the big amount of failures currently present on the Windows build making it very slow.
My diagnosis was that we don't want red Azure builds for now, since we don't yet really fully support Windows.
My fix is to wrap the job that runs the specs with a [bash timeout](https://linux.die.net/man/1/timeout) with a limit under Azure's one hour limit. 
I chose this fix because I think it should prevent Azure statuses from getting in the middle for now.
> Try fix azure flakyness

- spec/commands/show_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gemfile/groups_spec.rb
- spec/install/gemfile/path_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/runtime/require_spec.rb
- spec/support/helpers.rb
- spec/support/matchers.rb
The problem was that deprecation specs, even though they are now passing, are very brittle. This is because most of them create multiple gem files (`gems.rb` and `Gemfile`), and thus display deprecation messages by default about that.
My diagnosis was that each deprecation should test its own message, instead of having the same deprecation printed by most specs.
My fix is to make the specs create a single gem file, except for the ones that test the deprecation about multiple gem files.
I chose this fix because it makes the tests less brittle and do less unnecessary things.
> Make deprecation specs less messy

- lib/bundler.rb
- lib/bundler/templates/newgem/newgem.gemspec.tt
- lib/bundler/templates/newgem/test/test_helper.rb.tt
- spec/commands/exec_spec.rb
- spec/commands/info_spec.rb
- spec/install/gemfile_spec.rb
- spec/install/gemspecs_spec.rb
- spec/plugins/list_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/artifice/vcr.rb
The problem was that find old ruby compatibility code can confuse contributors into thinking those versions are still supported.
My diagnosis was that we can remove this code, since we no longer support those versions.
My fix is to remove the code.
I chose this fix because we can do it :)
> Remove `RUBY_VERSION` leftovers

- lib/bundler/cli.rb
- lib/bundler/settings.rb
- spec/other/major_deprecation_spec.rb
The problem was that this deprecation message is almost always a false positive. I realized about this when being bitten by this deprecation message during on our own specs (see https://travis-ci.org/bundler/bundler/builds/506776354 for example).
My diagnosis was that people running things like `bundle install --retry 3` will be annoyed by this deprecation message, because they're not doing anything wrong, really. They have the option to set the flag permanently through configuration, but passing it per command is fine too. The fact that the flag will no longer be remembered is unlikely to cause any problems in my opinion.
My fix is to remove this message altogether. We already print deprecation messages for the flags that we are removing because they only are guaranteed to work when …
> Remove remembered options deprecation message

- spec/other/major_deprecation_spec.rb
The problem was that some deprecation specs were still skipped.
My diagnosis was that I should get all of them passing.
My fix is to uncomment the spec and get it passing. The only fix was to include the full deprecation message so that it matches the assertion.
I could've regexp-matched the existing message but I preferred to use the full message in the assertion instead. I chose this fix because although it makes it more brittle since changing the message _will_ break the test, having the whole messages inside the deprecation specs makes it easier to get a quick view and understand the stuff that we are deprecating and the quality of the existing deprecation messages.
> Unskip `--binstubs` flag deprecation

- lib/bundler/cli/config.rb
- man/bundle-config.ronn
- spec/other/major_deprecation_spec.rb
The problem was that the `bundle config` command interface changes needed a few tweaks.
My diagnosis was that:
* `bundle config` deprecation was not getting enabled until bundler 3.
* `bundle config` documentation was incorrect about `unset` not supporting `--global` or `--local`.
* `bundle config` deprecation didn't give actionable suggestions.
My fix is to move the version to deprecate the old interface to `bundler 2`, to fix the documentation, and to improve the deprecation messages to give actionable suggestions.
I chose this fix because it makes `bundle config` better.
> Review old `bundle config` interface deprecation

- Rakefile
- bin/rake
- bin/rspec
- bin/rubocop
- spec/spec_helper.rb
The problem was making changes in the development setup was brittle and led to hard to debug errors. For example, the ones in #6980. Also, it was hard to reproduce exactly what's going on in the current CI environment. Which is useful to setup other CI, or run the specs under a docker image.
My diagnosis was that we can simplify a lot of this stuff.
My fix is... a lot of simplifications, but the most important ones being:
* Now each binstub activates only its own dependency, not every development dependency. That means a contributor can perfectly work on manual pages installing only `rake` and `ronn` without having to install all development dependencies. Same with styling (`rubocop`), or with specs (`rspec`).
* Error messages are better now.
* The rake tasks for each main `Rakefile` …
> Development environment cleanup

- Rakefile
#7017 made a change that sets the RSpec format to `documentation` in CI. I'm against this change because it now takes _a lot_ more time to scroll to the build errors, and makes the build log have too much information. Maintainers care much more about the failing specs and their errors than the test descriptions in CI.
Explicitly set the RSpec format to `progress` in CI.
> Revert the RSpec format in CI back to dots

- lib/bundler/compatibility_guard.rb
- lib/bundler/rubygems_ext.rb
- lib/bundler/rubygems_integration.rb
The problem was that testing rubygems in ruby-core with warnings enabled prints a lot of ruby warnings.
My diagnosis was that while requiring `rubygems`, bundler is required [here](https://github.com/rubygems/rubygems/blob/dad8d252f2b1562c4517fa6d73eb39dfbd0c4f37/lib/rubygems.rb#L1184), and then while requiring `bundler`, `rubygems` is required in several places. Thus the circular require warnings are printed.
My fix is to not require `rubygems` from `bundler`. Rubygems is made available by default by `ruby` anyways unless you use the `--disable-gems` option. And if you use that option, requiring `bundler` makes no sense.
I chose this fix because it's cleaner than #6862, in my opinion. This PR closes #6862 by superseding it.
> Fix circular require warnings

- Rakefile
- lib/bundler/vendor/fileutils/lib/fileutils.rb
- lib/bundler/vendor/thor/lib/thor/actions.rb
- lib/bundler/vendor/thor/lib/thor/actions/file_manipulation.rb
- lib/bundler/vendor/thor/lib/thor/base.rb
- lib/bundler/vendor/thor/lib/thor/error.rb
- lib/bundler/vendor/thor/lib/thor/group.rb
- lib/bundler/vendor/thor/lib/thor/parser/options.rb
- lib/bundler/vendor/thor/lib/thor/runner.rb
- lib/bundler/vendor/thor/lib/thor/shell.rb
- lib/bundler/vendor/thor/lib/thor/shell/basic.rb
- lib/bundler/vendor/thor/lib/thor/version.rb
The problem was that we were not using the latest versions of some of our vendored dependencies.
My diagnosis was that we should upgrade them.
My fix is to upgrade them using `automatiek`, and add a few tweaks to our vendoring setup.
I chose this fix because.... I didn't really considered other options.
> Tweaking vendoring

- lib/bundler.rb
- spec/runtime/with_unbundled_env_spec.rb
The problem was that the `clean_system` and `clean_exec` would print deprecation messages, but there was not alternative for them.
My diagnosis was that the helpers are using deprecated behavior and that we should provide non deprecated alternatives.
My fix is to introduce `original_system`, `original_exec`, `unbundled_system`, and `unbundled_exec` for consistency with the rest of the helpers, and deprecate `clean_system` and `clean_exec`.
I chose this fix because while maybe not super pretty names, they offer an alternative consistent with the other helpers.
> Introduce  `original_system`, `original_exec`, `unbundled_system`, and `unbundled_exec` 

- lib/bundler/runtime.rb
- spec/commands/clean_spec.rb
Fixes #7058
This PR fixes it by adding the native extension directories for git gems to the ones for non-git gems.  This is used to get the unused extension directories (`stale_extension_dirs = extension_dirs - spec_extension_paths`) which was already excluding extension directories for git gems.
> Make `bundle clean` clean git extension directories

- .travis.yml
- Rakefile
- lib/bundler/rubygems_integration.rb
- lib/bundler/vendor/fileutils/lib/fileutils.rb
The problem was that hacks create confusion, even if they include TODO notes.
My diagnosis was that we can should upgrade to the latest ruby releases to reduce the number of hacks we need to maintain.
My fix is to upgrade rubies and remove hacks.
I chose this fix because it's a good change.
> Bump travis rubies

- lib/bundler/vendor/fileutils/lib/fileutils.rb
- lib/bundler/vendor/fileutils/lib/fileutils/version.rb
The problem was we manually updated some code in the vendored fileutils instead of using a released version.
My diagnosis was that we should use the recently released fileutils 1.2.0.
My fix is to vendor it through `bin/rake vendor:fileutils[v1.2.0]`.
I chose this fix because it properly upgrades the vendored code to match what's last released.
> Bump vendored fileutils to 1.2.0

- lib/bundler/cli.rb
- spec/commands/package_spec.rb
Fixes #7077.
The problem was #7077. When the `no_install` configuration is activated, this prevents `bundle update` from installing gems, but `no_install` is only meant to affect `bundle package`.
My diagnosis was that `bundle update` needs to ignore this setting.
My fix is to the same `bundle install` does to fix this problem.
I chose this fix because it's the most straightforward solution, although the handling of this flag could probably use some refactoring.
> Allow `update` to install when `--no-install` used

- Rakefile
- spec/support/rubygems_ext.rb
The problem was that our test setup could be simpler.
My diagnosis was that some lines installing test gem dependencies could be removed from the Rakefile, because the tests already detect this situation and auto-install test gems appropriately.
My fix is to remove the lines. However, removing the lines led to a single test failure that can be explained becase `FileUtils` ends up being required too late, thus skipping one call to `Gem.clear_paths` done in the tests setup so that stuff memoized by `rubygems` is cleared and tests can assume is not loaded yet. The situation is very intricate but I tried to explain it in the commit message.
I chose this fix because it fixes the test failure, but I also plan to propose to eliminate the `autoload` calls in rubygems that also contributed to this …
> Remove unnecessary test stuff

- .travis.yml
- Rakefile
- bin/with_rubygems
- spec/install/security_policy_spec.rb
- spec/runtime/setup_spec.rb
The problem was that we had on `rubygems`, we're not testing bundler against the rubygems checkout of each PR, but against master. That is confusing because developers assume that the PRs tests will run against the PRs code, but this is currently not true.
My diagnosis was that on rubygems we are [specifying `RGV=master`](https://github.com/rubygems/rubygems/blob/fa6e547330e97b417ed11f262d68d03c57abeeda/.travis.yml#L12) in our TravisCI matrix. And what `bundler` does with that is to clone rubygems master under `tmp/rubygems` and use that. Thus your rubygems PR is not really tested.
My fix is to rework the setup to accept an `RGV` environment variable when it contains. In that case, no git operations will be performed, and that path will be used directly and assumed to contain a rubygems …
> Improve cross repo integration

- spec/cache/gems_spec.rb
- spec/cache/git_spec.rb
- spec/commands/check_spec.rb
- spec/commands/clean_spec.rb
- spec/commands/config_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/inject_spec.rb
- spec/commands/outdated_spec.rb
- spec/commands/package_spec.rb
- spec/commands/update_spec.rb
- spec/install/allow_offline_install_spec.rb
- spec/install/bundler_spec.rb
- spec/install/deploy_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gemfile/lockfile_spec.rb
- spec/install/gemfile/platform_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/install/gemfile_spec.rb
- spec/install/gems/compact_index_spec.rb
- spec/install/gems/native_extensions_spec.rb
- spec/install/gems/sudo_spec.rb
- spec/install/global_cache_spec.rb
- spec/install/path_spec.rb
- spec/other/cli_dispatch_spec.rb
- spec/realworld/dependency_api_spec.rb
- spec/runtime/platform_spec.rb
- spec/runtime/setup_spec.rb
- spec/update/gemfile_spec.rb
- spec/update/gems/post_install_spec.rb
- spec/update/git_spec.rb
The problem was that some specs still use the deprecated `bundle config interface`
My fix is to use the newer interface.
> Remove `bundle config` deprecations from specs

- lib/bundler/cli/common.rb
- lib/bundler/cli/info.rb
- spec/commands/info_spec.rb
- spec/commands/show_spec.rb
The problem was that `bundler info GEM` did not have feature parity with `bundle show GEM`, and it should because it's the recommended alternative. Also, `bundle info bundler` was showing an incorrect path while `bundle show bundler` was correct.
My diagnosis was that some code should be pulled from `bundle show`.
My fix is to port the missing feature, bug fix, and specs to `bundle info` from `bundle show`.
I chose this fix because it guarantees that the recommended alternative will work similarly to the current show command.
> Add missing `bundle info` feature, bug fix, and specs

- lib/bundler/rubygems_integration.rb
- spec/commands/exec_spec.rb
The problem was that since `irb` and others were moved to default gems, users cannot directly use them in a bundler context, unless they add it to their gemfiles. In my opinion, this completely defeats the purpose of default gems, and makes bundler degrade the user experience instead of making it better.
My diagnosis was that when bundler replaces the set of gems known to rubygems, it restricts the world to what's in the Gemfile (or resolved from it), and that doesn't include default gems.
My fix is to also include the set of default gems, unless they are already included in the gemfile dependencies.
I chose this fix because it's reasonably simple and I think it shouldn't affect how other parts of bundler function.
Fixes #6929.
Fixes https://bugs.ruby-lang.org/issues/15503.
> Allow to `bundle exec` default gems

- spec/other/major_deprecation_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
This is a follow up to #7052.
The problem was that the `Bundle.with_clean_env` & `Bundle.with_original_env` family was missing some deprecation specs, and also the specs were spread out across different files.
My fix is to add the missing specs, and centralize them in the deprecation specs file.
> Complete some missing specs

- spec/cache/gems_spec.rb
- spec/cache/git_spec.rb
- spec/cache/platform_spec.rb
- spec/commands/clean_spec.rb
- spec/commands/package_spec.rb
- spec/commands/update_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gems/compact_index_spec.rb
- spec/install/gems/dependency_api_spec.rb
- spec/install/git_spec.rb
- spec/install/post_bundle_message_spec.rb
- spec/other/platform_spec.rb
- spec/realworld/parallel_spec.rb
- spec/support/helpers.rb
- spec/update/gemfile_spec.rb
- spec/update/gems/post_install_spec.rb
- spec/update/git_spec.rb
The problem was that some specs were still using `bundle update` to update all gems, which is deprecated.
My fix is to update all specs to use the new preferred command, namely, `bundle update --all`.
> Always pass the `--all` flag when needed

- spec/support/helpers.rb
The problem was if the installation if system gems failed during specs failed, that was being silently ignored.
My diagnosis was that if this installation fails, the specs that use this helper are not probably testing what they should
My fix is to use the bang method instead.
> Make sure spec fails if gems cannot be installed

- lib/bundler/source_list.rb
- spec/bundler/definition_spec.rb
- spec/bundler/source_list_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/lock/lockfile_spec.rb
- spec/plugins/source/example_spec.rb
- spec/update/git_spec.rb
This is more of a question PR, I created this patch to try it out and try to understand, not necessarily get it merged.
The problem was that once we enable the `lockfile_uses_separate_rubygems_sources` setting, all lockfiles in the world will become incompatible with the previous version. Actually, not necessarily incompatible, but bundler will reorder the sections when the setting is enabled, that will generate churn lock file diffs, and _maybe_ some confusion / merge conflicts, and so on.
My diagnosis was that maybe this is not necessary. I read over the issues where this setting was added and what I understood is that previously if a Gemfile specified multiple rubygems sources, they would all get merged together and that's dangerous because it's not deterministic from which source each …
> Remove lockfile incompatibility created by the `lockfile_uses_separate_rubygems_sources` setting

- spec/lock/lockfile_spec.rb
- spec/support/helpers.rb
- spec/support/matchers.rb
The problem was that bumping bundler's version in #7088 made a lockfile spec fail.
My diagnosis was that there was a combination of bugs that was making this spec pass, but the spec was incorrect.
My fix is to change the test version the spec uses to not hit https://github.com/rubygems/rubygems/issues/2595, and thus reproduce the failure. And then fix the spec that was incorrect because the lockfile written had different URLs (`file://localhost/<stuff>`) from the lockfile we were checking against (`file://<stuff>`), thus tricking `bundle install` into thinking something had changed, and thus making it rewrite it with an incorrect bundler version.
I chose this fix because it makes #7088 pass and it reduces surprises.
> Normalize file URIs in spec's lockfiles

- spec/commands/info_spec.rb
A test in the info command spec was using `bundle show` instead of `bundle info`.
This is causing specs in Bundler 3 to fail. See https://travis-ci.org/bundler/bundler/jobs/514507744
Change the test to use `bundle info` instead.
> Change info command spec to use `bundle info` instead of `bundle show`

- lib/bundler/version.rb
When we released the new version, We got the test failure or an error with a version number like 2.0.0.
We didn't test with new version number until release time.
I did bump to the minor version in the master branch.
We should develop with a new version number like 2.1.0.
> Bump version to 2.1.0.pre.1.

- lib/bundler/cli.rb
- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- spec/quality_spec.rb
The problem was that the `viz_command` and `console_command` settings are not meant to be something configured by users. These commands are going away, we don't want to support optionally keeping them.
My diagnosis was that we are using settings for two different things:
* Different supported behaviors that are configurable by users.
* Feature flags that allow us developers to easily maintain a single branch of code and making breaking changes more easily, and users to opt-in/out of certain new features/changes. 
The second case is valid but it's complicated because we need to commit to provide a proper life cycle for the setting:
* Allow opting in through the setting.
* Toggle the setting's default value.
* Deprecate the value for the setting enabling the old behavior.
* Deprecate the …
> Remove command removal settings

- lib/bundler/installer/gem_installer.rb
- spec/bundler/installer/gem_installer_spec.rb
- spec/install/gems/native_extensions_spec.rb
The problem was #6940. Build configurations with multiple whitepaced parameter are no longer properly handled.
My diagnosis was not mine, was @jeremy's: Since [shellscaping / shelljoining build arguments to the rubygems gem installer](https://github.com/bundler/bundler/issues/6940), these are no longer properly passed
My fix is not mine, it's @jeremy's: shellsplit settings before passing them.
I chose this fix because it works and it sounds like the proper followup to https://github.com/rubygems/rubygems/pull/2441.
Fixes #6940.
> Shellsplit build config

- lib/bundler.rb
- lib/bundler/worker.rb
- spec/realworld/dependency_api_spec.rb
- spec/realworld/gemfile_source_header_spec.rb
- spec/realworld/mirror_probe_spec.rb
It's provided by an embedded module in the modern Ruby.
> Remove explicitly loading thread library

- lib/bundler/cli.rb
- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/commands/list_spec.rb
- spec/commands/show_spec.rb
- spec/other/major_deprecation_spec.rb
The problem was there was some work to do regarding the deprecation of `bundle show` and the `bundle list` introduction.
* The command should error out in bundler 3 and was still there.
* The command would print erroneous deprecation messages for the `--verbose` and `--outdated` flags. These flags to `bundle show` are undocumented and will be removed in bundler 3.
* The `bundle list` help would show the help for the new `list` command that lists groups of (or all) gems in the Gemfile, but its implementation would just be an alias to `bundle show`.
My fix is to remove the command in bundler 3, to show a different deprecation message when `--outdated` or `--verbose` are used to inform about their removal without replacement, and the inconditionally introduce the new list command without any …
> Review `bundle show` deprecation

- .rubocop.yml
- .travis.yml
We run rubocop on every build that goes through every file looking for any breaking rules. Currently this takes about ~30s to execute. We also have the linting step required to pass before any other steps are executed, so having this step execute as fast as possible is important to developers.
I think there is a small optimize we can make to the build time by caching rubocop between builds.
Have travis cache the results from rubocop between builds to speed up build times
> Cache rubocop in travis-ci

- lib/bundler/dsl.rb
On Gemfile syntax error like `gem 'foo', :path => /unquoted/string/syntax/error`, Ruby 2.7 will show strange error message like:
```
[!] There was an error parsing `Gemfile`: unknown regexp options - trg - ...foo', :path => /unquoted/string/syntax/error
...                        ^~~~~~~. Bundler cannot continue.
```
due to recent change in Ruby trunk https://github.com/ruby/ruby/commit/b6468b01f7288789ef2e9bf548d81cdadb8ef053. This caused Bundler's [CI failure on ruby/ruby repository](https://dev.azure.com/rubylang/ruby/_build/results?buildId=180&view=logs&jobId=b6208202-37e9-506d-3aed-7f8fc7b76c87&taskId=a8620f99-3e9e-5782-41a8-f55e2d53059e&lineStart=94&lineEnd=95&colStart=1&colEnd=1).
Bundler's Travis ruby-head has not failed yet because Travis ruby-head is still a little old. It will …
> Strip unknown regexp option line from error format

- spec/other/major_deprecation_spec.rb
The problem was deprecation specs have become convoluted. The spawn many unnecessary subprocesses and do unnecessary work, and have complicated and redundant descriptions.
My fix is to reduce the nesting level of the specs, simplify descriptions, and refactor test setups so that each test only runs the bare minimum that it needs.
> Simplify deprecation specs

- task/build_metadata.rake
The problem was any Rake task depending on the `:build_metadata` task is currently failing with  ``NameError: undefined local variable or method `bundler_spec' for main:Object``. For example, the release or build tasks.
My diagnosis was that I probably broke this during the development environment refactoring.
My fix is to add the missing method to the file that needs it.
I chose this fix because it works and it restores working tasks.
> Add missing method to rake file

- spec/runtime/setup_spec.rb
The problem was that we were skipping this test on ruby 2.6. Skipping tests on old versions is not much of a problem, but doing it on the latest version is opening the door for regressions. So I want to fix it.
My diagnosis was that since bundler is now a default gem, that bundler version is being activated by the spec, but since we are on a 2.0.1 locked bundle, the spec runs into a version mismatch error.
My fix is to enable the `Kernel.require` rubygems monkeypatch for this case (the `bundle` gem itself), that requires default gem files without activating the specific default version, and thus not forcing end users to use that. Since... that's exactly the problem here.
I chose this fix because it makes sense to me.
> Fix symlink spec on ruby 2.6

- lib/bundler/gem_helper.rb
- spec/bundler/gem_helper_spec.rb
I'm working on getting https://github.com/bundler/bundler/pull/7108 into the v2.0.2 release but that code has not been kept up to date over time (i'm not sure why i haven't been doing this). Trying to cherry-pick the changes to `GemHelper` is proving to be not super fun to deal with. Instead, i'm just going to copy/paste the current file & specs into `2-0-stable`
There doesn't seem to be any breaking changes, so this should be ok to perform.
> Backport `GemHelper` changes for #7108

- lib/bundler/definition.rb
- lib/bundler/feature_flag.rb
- lib/bundler/lockfile_parser.rb
- lib/bundler/plugin/installer.rb
- lib/bundler/resolver.rb
- lib/bundler/settings.rb
- lib/bundler/source/rubygems.rb
- lib/bundler/source_list.rb
- spec/bundler/source_list_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/list_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/install/gems/flex_spec.rb
- spec/install/post_bundle_message_spec.rb
- spec/lock/lockfile_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/quality_spec.rb
The problem was that I had not yet reviewed the deprecation about multiple global sources being present on a Gemfile, and thus the specs were skipped.
My diagnosis was that we need to delay the removal of multiple sources support to bundler 3, so that we can show the deprecations in the 2.x series.
I also noticed that part of the deprecation message was inaccurate. In order to upgrade the warning to an error, you would also need to configure the `lockfile_uses_separate_rubygems_sources` setting. Otherwise you will get an error that these two settings depend on each other and can't be enabled separatedly.
My fix is to delay these feature flags to bundler 3 so that the deprecation specs pass. Also, since before giving this advice I'd like to study why we have two different settings that …
> Review multiple sources deprecation

- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- lib/bundler/shared_helpers.rb
- man/bundle-config.ronn
- spec/install/gemfile_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/update/gemfile_spec.rb
The problem was that we currently have a feature flag and setting, `prefer_gems_rb`, that currently does very very little, and it's not worth the maintenance cost in my opinion.
My diagnosis was that the only situation where this setting makes a difference at the moment is when a project has both a `Gemfile` _and_ a `gems.rb` file. In that case, if `prefer_gems_rb` is enabled, the warning will tell the user to remove the `Gemfile` because it's being ignored, whereas if not enabled, it will tell the user to remove the `gems.rb` file because it's being ignored.
I think this setting might've made sense when we actually planned to really deprecate Gemfile's in the short term. Since I think we're not planning to deprecate Gemfile's at the moment, I think it's better to remove the setting.
My …
> Remove `prefer_gems_rb` setting

- lib/bundler/cli/init.rb
- lib/bundler/feature_flag.rb
- spec/commands/init_spec.rb
The problem was that we have a feature flag to change the file name of the file where gems are defined from `Gemfile` to `gems.rb`, and it is unclear whether we will actually do this, and when.
My diagnosis was that a feature flag is not a good fit here. It's perfectly fine to configure this and allow users to use `gems.rb` by default for their gems, but we don't know when/if we will actually change the default so a plain setting feels better than a feature flag.
My fix is to convert the `init_gems_rb` feature flag into a plain setting.
> Make `init_gems_rb` a regular setting

- lib/bundler/rubygems_integration.rb
- spec/bundler/shared_helpers_spec.rb
- spec/commands/clean_spec.rb
- spec/commands/exec_spec.rb
- spec/install/binstubs_spec.rb
- spec/support/helpers.rb
The problem was that this specific deprecation I don't think it makes sense as a deprecation.
My diagnosis was that nothing is changing in bundler so that this needs to be a deprecation. This is just a potentially undesired situation that can be caused by gems shipping executables conflicting with the executables of other gems, and that can be fixed by using project specific binstubs.
My fix is to change this deprecation message to a warning, and to get it tested.
I chose this fix because it makes sense to me. With this, we can start printing this warning now without thinking of a deprecation path because I don't think we're changing anything here, really.
> Convert binstub conflict deprecation to a warning

- spec/bundler/gem_helper_spec.rb
- spec/commands/binstubs_spec.rb
- spec/commands/config_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/info_spec.rb
- spec/commands/newgem_spec.rb
- spec/commands/show_spec.rb
- spec/install/deploy_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/quality_es_spec.rb
- spec/quality_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/spec_helper.rb
The current master branch couldn't invoke with the ruby core repository.
1. We need to add explicitly declare `rspec` in spec_helper.rb
2. Some examples were failed on ruby core repository.
1. simply added.
2. update the `ruby_repo` labels for skipping to run.
> Backport to workaround from ruby core.

- lib/bundler/rubygems_ext.rb
- lib/bundler/rubygems_integration.rb
The problem was that I was unsure where I needed to add the compatibility layer to #6963, and it took me a bit to scan through the compatibility file and figure it out.
My diagnosis was that all this compatibility code is unused but makes this file harder to understand and scan through.
My fix is to remove the code.
I chose this fix because we can do it, I think.
> Remove old rubygems compatibility code

- spec/runtime/with_unbundled_env_spec.rb
The problem was the subprocess spawed by one spec was crashing, but that was not making the spec fail.
My diagnosis was that since the spec was checking for a failure status of the subprocess, that was not specific enough to detect the particular bug in this spec (it was calling `clean_system`, removed from bundler 3, instead of `unbundled_system`).
My fix is to restore the previous strategy for these specs, namely, check for a more specific status than 0
or 1.
> Fix spec calling incorrect helper

- bin/with_rubygems
This PR might be very specific to my setup, but it would certainly help me.
The problem was that sometimes I don't find out early about rubocop issues, so I have to push extra commits to fix them, and that means time and CI resources.
My diagnosis was that:
* I run rubocop automatically on save from `vim using [ale](https://github.com/w0rp/ale).
* I set `ENV["RGV"] = master`, so that I always run the latest rubygems.
Because of setting `ENV["RGV"]`, the `with_rubygems` script is run everytime a binstub is loaded (including `rubocop`). This script prints some git information to the standard output. Since ALE expects a very specific output from `rubocop`, the fact that the `with_rubygems` script prints stuff to the standard output means that ALE no longer works, and I don't get to early fix …
> Remove standard output from `with_rubygems`

- Rakefile
- task/release.rake
The problem was that `bin/rake install:local` fails on jruby.
My diagnosis was that the `ronn` gem does not support `jruby`. Since the `install:local` task builds docs on the fly, the task crashes.
My fix is to make the `man:build` task a noop on jruby, so that `bin/rake install:local` can be run on jruby, so jruby users can easily try out bundler's master.
I chose this fix because it sounds like a good workaround.
> Allow local install on jruby

- lib/bundler/cli.rb
- lib/bundler/dependency.rb
- lib/bundler/injector.rb
- man/bundle-add.ronn
- spec/commands/add_spec.rb
Closes #6841 These changes will allow to add a gem with the git or branch options.
```
bundle add redis --git "https://github.com/redis/redis-rb" --branch "staging"
```
The result in Gemfile will be: 
```
gem "redis", "~> 4.0", :git => "https://github.com/redis/redis-rb", :branch => "staging"
```
> Add git and branch options to `bundle add`

- lib/bundler/inline.rb
- spec/runtime/inline_spec.rb
Fixes #7114.
The problem was that the inline mode wouldn't work if `BUNDLE_FROZEN` is set.
My diagnosis was that since we're in frozen mode, the current platform doesn't get added to the definition, and thus platform validation fails.
My fix is to temporary ignore `BUNDLE_FROZEN` for the inline mode. The inline mode can't really be frozen since it has no lock file.
> Ignore `frozen` setting in inline mode

- lib/bundler/inline.rb
- spec/runtime/inline_spec.rb
Fixes #6822.
The problem was that inline mode prints platform warnings recommending to run `bundle lock` commands.
My diagnosis was that the platform is always missing in the lock file since there's no lock file here.
My fix is to skip platform warnings in this case.
I chose this fix because it's simple.
> Skip platform warnings in inline mode

- lib/bundler/cli/update.rb
- spec/commands/update_spec.rb
The problem was `bundle update` shows incorrect message when updating git gems
Closes #6325 
My diagnosis was we need to check if the source has changed
My fix only prints the message when the source has not changed
Note that is does not yet fix the "updated the git sha" case, since the locked spec and the new spec actually share the same source object!
> Stop printing “failed to update” message when changing sources

- lib/bundler/rubygems_integration.rb
The problem was that the rubygems integration file could be more consistent.
My fix is to lazily require `monitor`, just like it's done with the other requires in the file, and to define the methods that check the rubygems version a single time, just like the rest of the methods in the file.
> Tweak rubygems integration

- bundler.gemspec
- lib/bundler/templates/newgem/newgem.gemspec.tt
This is a follow up to #7100. Gemspec is another place where `require_relative` sounds like a win.
My fix changes bundler's gemspec to use `require_relative`, and extracts the relevant change from #4397 to also change the generated gemspec from `bundle gem`.
> Gemspec require relative

- lib/bundler/lockfile_parser.rb
- spec/lock/lockfile_spec.rb
- spec/support/platforms.rb
Closes #6993.
Complements rubygems/rubygems#2621.
The problem was that bundler 2 has become too unfriendly because it errors out when the running version does not match the version in the BUNDLED WITH section in the lockfile.
My diagnosis is that we still believe that making sure the exact same bundler version is always run for a specific application is a good thing, because it ensures resolution is always the same because it's resolved by the exact same code that generated the lockfile.
BUT, we need to ensure this in a more user friendly way, for example by auto-switching and auto-installing the right bundler version without any user intervention.
My fix is to downgrade this hard error to a warning that does not prevent bundler from running.
I chose this fix because it still shows the …
> Downgrade version mismatches to warnings

- lib/bundler.rb
- spec/bundler/bundler_spec.rb
#6024 added support for specifying an alternate bundler home directory via the `BUNDLE_USER_HOME` environment variable. Unfortunately bundler still checks for a writable user home directory even if the `BUNDLE_USER_HOME` override is specified resulting in warnings like this:
```
`/home/appuser` is not a directory.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
```
The fix for this problem is to only evaluate bundler path fallbacks if environment variable overrides are not specified.
> Don't check for the existence of a writable home directory if BUNDLE_USER_HOME is set

- lib/bundler/fetcher/downloader.rb
- lib/bundler/fetcher/index.rb
- spec/bundler/fetcher/downloader_spec.rb
- spec/bundler/fetcher/index_spec.rb
Some gem servers respond to bad username/password request with a 401 instead of a 403.
When a 401 response was received, bundler would automatically assume no credentials were supplied, leading to a response of
```
Authentication is required for http://moto@gems.motologic.com/.
Please supply credentials for this source. You can do this by running:
bundle config http://moto@gems.motologic.com/ username:password
```
even when a username and password was present in the bundler config.
There already exists a check for credentials in the request URI for 403 responses.  I took that pattern and implemented it for 401 responses as well.
I chose this fix because a very similar pattern already exists in bundler, I just applied the same logic to another response code.
> When a 401 response is received, raise BadAuthenticationError if credentials were present in the request URI

- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
**The problem was** when is outdated is ran always if the gem belongs to one group or more always show "groups" in plural.
**My diagnosis is** if the gem belongs to one group it's incorrect to show "groups" in plural.
**My fix was** if the gem belongs to one group it should show "group" in singular.
> Small fix with plural.

- lib/bundler/definition.rb
- spec/install/gemfile/path_spec.rb
Fix https://github.com/bundler/bundler/issues/6967
https://github.com/bundler/bundler/issues/6967
My diagnosis was https://github.com/bundler/bundler/blob/ec8f98574a90de1e87a50e00141180d761f161dc/lib/bundler/definition.rb#L806 is loose
My fix makes it strict
I think I don't have any other options
> Fix to update conservatively for gemspec update

- lib/bundler/cli/exec.rb
- spec/commands/exec_spec.rb
The problem was that `bundle exec` would not respect custom proctitles inside scripts.
My diagnosis was that the previous code was using the third form of `Kernel.exec`, documented as:
> In the third form (exec(["command", "argv0"], "arg1", ...)), starting a two-element array at the beginning of the command, the first element is the command to be executed, and the second argument is used as the argv[0] value, which may show up in process listings.
See https://ruby-doc.org/core-2.6.3/Kernel.html#method-i-exec.
However, since this form messes with proc titles, it seems to affect scripts settting their own proc titles.
My fix is to use the simpler form:
> In the second form (exec("command1", "arg1", ...)), the first is taken as a command name and the rest are passed as parameters to command …
> Get `bundle exec` respecting proc titles

- lib/bundler/shared_helpers.rb
- spec/bundler/cli_spec.rb
- spec/bundler/settings_spec.rb
- spec/bundler/shared_helpers_spec.rb
- spec/commands/check_spec.rb
- spec/commands/config_spec.rb
- spec/other/cli_dispatch_spec.rb
- spec/runtime/load_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
The problem was that our library code contains logic that's only necessary for bundler's specs. I think library code should not contain this kind of code, since it affects end users.
My fix is to remove the logic, and instead ensure the specs satisfy what the code wanted to ensure (that specs pass even when there's a Gemfile further up in the directory hierarchy outside of the bundler's development copy).
> Remove unnecessary `BUNDLER_SPEC_RUN` env variable

- .rubocop.yml
- bundler.gemspec
- lib/bundler/friendly_errors.rb
- lib/bundler/gem_version_promoter.rb
- lib/bundler/resolver.rb
- lib/bundler/uri_credentials_filter.rb
- lib/bundler/yaml_serializer.rb
- spec/realworld/gemfile_source_header_spec.rb
The problem was that our rubocop version is getting outdated. Also, I added [a PR to rubocop](https://github.com/rubocop-hq/rubocop/pull/6935) so that we can remove the exclusions in our configuration, and it has now been released.
My fix is to update rubocop to the latest version, update the configuration, and fix new offenses.
> Bump rubocop to 0.68.0

- lib/bundler/plugin.rb
- lib/bundler/rubygems_integration.rb
- lib/bundler/runtime.rb
This is a follow up to https://github.com/rubygems/rubygems/pull/2749.
My fix is to unify all LOAD_PATH manipulation in a single place, that uses rubygems logic if available.
> Use `Gem.add_to_load_path` if available

- lib/bundler/source/metadata.rb
- spec/commands/licenses_spec.rb
- spec/commands/show_spec.rb
- spec/other/major_deprecation_spec.rb
The problem was if you have rubygems's master installed globally, bundler specs no longer pass.
My diagnosis was that having rubygems master installed, installs bundler's master as a default gem. That actually makes bundler behave better. In particular, `bundle show` and `bundle licenses` start properly handling the `bundler` gem itself.
My fix is to change bundler's code to fix this specs in every situation, and not only when the bundler version being tested is also installed as a default gem.
NOTE: I also included some changes to unify `bundle show` deprecation specs in the file that tests all deprecations.
> Fix specs with rubygems master installed globally

- lib/bundler/definition.rb
Extracted from https://github.com/bundler/bundler/pull/7143#discussion_r279187838
> Also, I would split the variable rename, which is great because it makes the code more readable, to a separate commit
No end-user is affected because it's just local var name.
As a bundler contributor, I think it's much easier to understand if we rename them.
When I was investigating https://github.com/bundler/bundler/pull/7143, it's hard to understand what `other` stuff and `deps2` is.
> Rename local variables for readability

- lib/bundler/cli/update.rb
- spec/commands/update_spec.rb
The problem was that I introduced a regression with https://github.com/bundler/bundler/pull/6329. When running `bundle update <gem>`, where `<gem>` is included in the Gemfile, but it's for another platform from the current one, `bundle` would crash with the following error:
```
NoMethodError: undefined method `source' for nil:NilClass
/home/deivid/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.0.pre.1/lib/bundler/cli/update.rb:86:in `block in run'
/home/deivid/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.0.pre.1/lib/bundler/cli/update.rb:78:in `each'
/home/deivid/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.0.pre.1/lib/bundler/cli/update.rb:78:in `run'
/home/deivid/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.1.0.pre.1/lib/bundler/cli.rb: …
```
> Fix bundle update crash

- lib/bundler/dsl.rb
- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- spec/bundler/dsl_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/quality_spec.rb
The problem was that in https://github.com/bundler/bundler/pull/7000 I implemented a plan to migrate to https source by default and deprecate github/gist/bitbucket builtin sources, but I changed my mind and I think it's overkill.
The reasons I changed my mind are:
* We [actually announced the switch](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html) and the fact that it didn't happen was not intented. So this can be considered as fixing a bug.
* We have warned non https git sources for ages
https://github.com/bundler/bundler/blob/a6533c0fe6541cc929f895ee0b7a9b673d34cb4d/lib/bundler/source_list.rb#L144-L153
I think people should be ready by now.
Also, we introduced a new setting `github.https` that seems to do essentially the same thing as `git.allow_insecure`. 
My fix is to …
> Fully switch to https sources

- .azure-pipelines/steps.yml
- azure-pipelines.yml
The problem was that failures in Azure are not logged, so it hard to improve the situation.
My fix is to configure Azure to run until completion without any timeouts, and remove intercepting the global timeout (which we did to make sure build is still green when it times out), because it's no longer necessary. Now we should be able to see the failures on every PR.
> Improve azure configuration

- lib/bundler/vendor/fileutils/lib/fileutils.rb
The problem was there's [upstream changes in fileutils](https://github.com/ruby/fileutils/pull/35).
My fix is to port the upstream changes, which consist of using `require_relative` everywhere.
> Improve fileutils require

- lib/bundler.rb
- lib/bundler/fetcher.rb
- lib/bundler/fetcher/compact_index.rb
- lib/bundler/plugin/api.rb
- lib/bundler/plugin/installer.rb
- lib/bundler/settings.rb
- lib/bundler/shared_helpers.rb
- lib/bundler/source.rb
- lib/bundler/source/git.rb
- lib/bundler/source/path.rb
- lib/bundler/source/rubygems.rb
- lib/bundler/ui.rb
- lib/bundler/vendor/molinillo/lib/molinillo.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_edge_no_circular.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/add_vertex.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/delete_edge.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/detach_vertex_named.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/log.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/set_payload.rb
- lib/bundler/vendor/molinillo/lib/molinillo/dependency_graph/tag.rb
- lib/bundler/vendor/molinillo/lib/molinillo/errors.rb
- lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb
- lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb
- lib/bundler/vendor/thor/lib/thor/base.rb
- lib/bundler/vendor/thor/lib/thor/shell.rb
- lib/bundler/version.rb
- spec/bundler/shared_helpers_spec.rb
- spec/commands/exec_spec.rb
- spec/support/hax.rb
The problem was that we are doing some hacks in our version file that are... dangerous. At very least they cause "circular problems" like #6927, but I also have bad feelings about it.
My diagnosis was we're overwriting the version of the currently loaded bundler :grimacing:. This hack is _almost_ unnecessary (see the spec run here with the hack fully removed: https://travis-ci.org/bundler/bundler/builds/509497021. Only three jobs failed, and for old rubies/rubygems/bundler). 
My fix is to limit the hack to `bundler`'s spec run, since it's only needed there.
I chose this fix because fully getting the build green with the hack fully removed is a bit of work. I dedicated a bit of time to investigate one of the failures and it all comes down to the priority of loading default gems vs `-I`. So …
> Remove version overwriting hacks

- lib/bundler/shared_helpers.rb
- spec/bundler/cli_spec.rb
- spec/bundler/settings_spec.rb
- spec/bundler/shared_helpers_spec.rb
- spec/commands/check_spec.rb
- spec/commands/config_spec.rb
- spec/other/cli_dispatch_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/runtime/load_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
The problem was that in #7138 I removed some test specific code from lib, but it's not quite working.
My diagnosis was that the mocking I used to fix the issue of bundler looking for files outside of bundler's clone doesn't work inside subprocesses, which many of our specs use. That means some specs were currently failing if you have Gemfile's on `.bundle` folders up in the directory hierarchy ascending from your bundler's clone
My fix is revert to the previous approach of using a test specific environment variable to prevent search up higher than the test directory when running our specs.
I initially tried to monkeypatch the gemfile finding helpers only inside specs, but that caused load order issues (I monkeypatched the helpers insde `support/hax.rb`, that caused the monkeypatched lib …
> Better test specific file searching

- spec/spec_helper.rb
The problem was that I removed the `:git` filter from our specs in ac282dc9de5e20db85e9cdf23b97763a2a2cc292 because I thought it was unused, but it's not.
My diagnosis was that the filter is actually used once:
https://github.com/bundler/bundler/blob/3ec8165eec0a1af8c45ee258d3e7cb61fba875a2/spec/update/git_spec.rb#L162
My fix is to revert the commit.
> Revert "Remove unused filter"

- lib/bundler/feature_flag.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/install/bundler_spec.rb
- spec/install/gems/sudo_spec.rb
- spec/install/path_spec.rb
The problem was we're artificially holding shipping bug fixes like the fact the ruby scope is not included in the install path when `BUNDLE_PATH` is used as an environment variable or global setting.
My diagnosis was that we can remove the setting, and that it's fine that affected users rerun `bundle install` to get their installation paths fixed.
My fix is to remove the setting.
> Remove `global_path_appends_ruby_scope` setting

- .github/FUNDING.yml
Once this file is committed to the repo, GitHub will let us enable a "Sponsor" button, as part of [GitHub's new sponsorship system](https://github.blog/2019-05-23-announcing-github-sponsors-a-new-way-to-contribute-to-open-source/).
> Configure Sponsor button on GitHub

- spec/commands/newgem_spec.rb
The problem was that before I figured I needed to revert https://github.com/bundler/bundler/pull/7138 due to the specs no longer being stable, I debugged some failures in the `bundle gem` suite and ended up writing some refactorings.
My diagnosis was that something was wrong with these tests but in the end they were just flaky because of #7038.
In any case, I think the refactorings I wrote improve readabily. In particular, extending the global `reset!` method called before each spec, and reusing it again in the middle of some of these specs was kind of confusing.
> `bundle gem` spec refactor

- .rspec
- Rakefile
- spec/bundler/bundler_spec.rb
- spec/bundler/plugin/events_spec.rb
- spec/bundler/ruby_version_spec.rb
- spec/install/gems/sudo_spec.rb
- spec/spec_helper.rb
This is a follow-up to the work started by @colby-swandale in #7103.
The problem was that our specs do not run in random order, so the tests might be depending on state set by other tests to pass.
My diagnosis was that we should enable random test ordering.
My fix is to randomize the specs and fix the resulting failures.
> Random test order

- spec/bundler/fetcher/compact_index_spec.rb
The problem was that last master build failed with a test failure I had never seen: https://travis-ci.org/bundler/bundler/jobs/538089338.
My diagnosis was that this failure _is_ indeed order dependent, since it only appeared after enabling test suite randomization. BUT, this failure is not consistently reproducible.
This PR does not fix the problem. It only adds some debugging information, so we have more information to figure this out when it happens again.
I chose this ~fix~ change because it's no clear to me why this happened or how to fix it.
> Add debugging information to flaky test

- .azure-pipelines/patch_readline.sh
- .azure-pipelines/steps.yml
This is a followup to #7186.
The problem was that Azure CI is still unstable.
My diagnosis was that sometimes MRI 2.4.3 is used, and sometimes MRI 2.4.5 is used instead.
My fix, for now, is to make the steps independent from the ruby included in the container that it's run. 
I chose this fix because other better fixes require more work and I don't want to spend a lot of time on this at the moment.
> Second try at azure fix

- LICENSE.md
It seems like GitHub can't tell what license this is, despite explicitly
naming it inside the file. These changes make our license file closer to
other license files that GitHub does successfully recognize as MIT.
Hopefully it'll work.
> Try to help GitHub recognize the MIT license

- Rakefile
The problem was that `man:clobber` was listed under `bin/rake -T` but it wasn't working because it was trying to remove a non existent folder.
My diagnosis was that the correct task is actually `bin/rake man:clean`.
My fix is to remove `man:clobber` and move its description on top of `man:clean`, so that it's correctly listed under `bin/rake -T`.
> Remove incorrect `man:clobber` task

- exe/bundle
- lib/bundler.rb
- lib/bundler/vendor/thor/lib/thor.rb
- lib/bundler/vendor/thor/lib/thor/actions.rb
- lib/bundler/vendor/thor/lib/thor/actions/create_file.rb
- lib/bundler/vendor/thor/lib/thor/actions/create_link.rb
- lib/bundler/vendor/thor/lib/thor/actions/directory.rb
- lib/bundler/vendor/thor/lib/thor/actions/inject_into_file.rb
- lib/bundler/vendor/thor/lib/thor/base.rb
- lib/bundler/vendor/thor/lib/thor/group.rb
- lib/bundler/vendor/thor/lib/thor/line_editor.rb
- lib/bundler/vendor/thor/lib/thor/parser.rb
- lib/bundler/vendor/thor/lib/thor/runner.rb
- lib/bundler/vendor/thor/lib/thor/shell/color.rb
- lib/bundler/vendor/thor/lib/thor/shell/html.rb
- lib/bundler/vendored_thor.rb
This is a follow up to #7062 and #7100, migrating the last missing internal requires to use `require_relative`. I thought I had migrated everything already, but I had not.
As a note, I'm migrating thor's code here. I will open a PR to upstream's thor to incorporate this changes, but thor is still stuck with 1.8 support, so we have to wait a bit. Given the very low activity thor has, it's fine to make the changes here first, and wait until we can incorporate them upstream.
The problem was that sometimes we can end up requiring the default version of bundler, instead of the current copy that's being run, and that's dangerous and can cause version mismatch issues.
My fix is to always use `require_relative` for internal requires.
> More `require_relative`

- lib/bundler/dsl.rb
- spec/bundler/dsl_spec.rb
- spec/other/major_deprecation_spec.rb
The PR #6798 was not merged correctly in the `2.0.0` release. This was my fault. This PR resolves this.
Re-merge the PR back into the `2-0-stable` branch.
> Merge #6798 into `2-0-stable`

- lib/bundler/gem_helper.rb
- spec/bundler/gem_helper_spec.rb
- spec/commands/newgem_spec.rb
- spec/support/helpers.rb
This PR supersedes #7108 and #7005.
It fixes #6854.
The problem was that if users has 2FA authentication on their rubygems account, `rake release` doesn't really work at the moment, since it hangs asking for the OTP code, but without letting the user know.
My diagnosis was that we need to allow the `rake release` helper that shells out to `gem push` to read `gem push` output and show it to the user, so that she can introduce the requested information.
My fix is inspired by @segiddins's comment in https://github.com/bundler/bundler/issues/6854#issuecomment-450536844. `Kernel#system` works like we would expect in this situation. 
I chose this fix because #7108 had a few problems:
* It would update the `sh` helper, which is used in many different places. This was unnecessary since most of …
> Allow `rake release` to ask for input (3rd take)

- lib/bundler/ui/shell.rb
- spec/bundler/source_spec.rb
- spec/spec_helper.rb
The problem was that some specs have started to fail randomly in several unrelated PRs. See for example, https://travis-ci.org/bundler/bundler/jobs/500322731. Note that currently bundler specs always run in the same order ( :crying_cat_face: ), but enabling or disabling specs can still affect the final set of specs, and thus make this issue manifest.
My diagnosis was that the base thor's shell is being memoized the first time bundler instantiates a shell. That means further instantiations will not respect the "--no-color" option.
My fix is to reset the base thor's shell the proper color / non-color one, every time we instantiate a new shell, not only when "--color" is given. 
I chose this fix because it felt like a real issue that should be fixed in lib/, and not only with some state …
> Respect color option when instantiating shells

- spec/bundler/fetcher/compact_index_spec.rb
The problem was that sometimes CI fails randomly. For example, https://travis-ci.org/bundler/bundler/jobs/544642885.
My diagnosis was that the spec after it was mocking `Worker#stop` and thus preventing the threads to be actually stopped. That leak would after the spec checking for the number of threads.
My fix is to also call the original `#stop` method, so that no threads are left behind.
There's an alternative option, which is to completely remove this spec. In my opinion, this spec is checking exactly the same thing as the previous spec (the whole purpose of `Worker#stop` is to stop threads), but in a more brittle way. So I'm tempted to completely kill the spec instead.
> Fix thread leak in compact index specs

- lib/bundler/definition.rb
- spec/commands/clean_spec.rb
Fixes #7208.
The problem was that since rubygems 3.0, `bundle clean` incorrectly cleans git gems when they are installed to a symlinked location, but still being used.
My diagnosis was that since https://github.com/rubygems/rubygems/pull/2352, `Gem.dir` returns an array of realpaths, not symlinked ones. However, we don't do the same resolution on the `bundler` side, so in this situation git gems are not correctly skipped from the cleanup.
My fix is to resolve the array of paths `bundle clean` uses to do its thing into an array of real paths, just like rubygems does now.
I chose this fix because it fixes the problem.
> Use real paths for `bundle clean`

- bundler.gemspec
The problem was that [our build broke](https://travis-ci.org/bundler/bundler/jobs/548144536) due to a dependency incompatibility caused by a new release of `rubocop-performance`.
My diagnosis was that our requirements were very loose for `rubocop-performance`, but very strict for `rubocop`, so very likely to break on `rubocop-performance` releases.
My fix is to upgrade `rubocop` to fix the current issue, and to lock `rubocop-performance` so it doesn't happen again in the future.
I chose this fix because it works now and in the future.
> Bump rubocop to 0.71

- spec/runtime/executable_spec.rb
The problem was there's a typo on a comment.
My diagnosis was that typos are bad because they difficult reading and distract devs.
My fix is to spell bundler properly.
I chose this fix because `bundler` is the only word that makes sense in the context :)
> Fix a typo on a spec comment

- task/bundler_3.rake
The problem was that the `bundler_2:install` task is no longer meaningful.
My diagnosis was that master points to 2.x now, so this task is useless.
My fix is move it to `bundler_3:install`.
I chose this fix because it keeps the shortcut, but for a useful future version.
> Replace `bundler_2:install` task with `bundler_3:install`

- exe/bundle
The problem was that in https://github.com/bundler/bundler/pull/7193, I included [a commit](https://github.com/bundler/bundler/pull/7193/commits/d9d2bf6d522dd36d1ef2732e87cef8b7cba729fd) to migrate requires included in bundler's executable to use `require_relative`. That broke stuff.
My diagnosis was the assumption that if `<install_folder>/exe/bundle` lives on a folder, the corresponding bundler lib lives on `<install_folder>/lib` doesn't hold for default gems. Default gems for gems with executables live in `site_lib` but install their executables in the standard gem location. That means that the reference commit breaks bundler when it is installed as a default gem.
My fix is to revert the commit.
I chose this fix because it's the easiest way. The proper long term fix is probably to make …
> Revert "Migrate requires from exe/ to also be relative"

- lib/bundler/templates/newgem/newgem.gemspec.tt
- spec/commands/newgem_spec.rb
This PR is a finished version of #4397.
The problem was that the generated gemspec for new gems does not impose a minimum ruby version.
My fix is to set the minimum ruby version in the generated gemspec to the minimum ruby version supported by bundler itself.
I chose this fix because it's simple.
> Add a minimum ruby version to the generated gemspec 

- Rakefile
- lib/bundler/current_ruby.rb
- lib/bundler/installer/standalone.rb
- lib/bundler/ruby_version.rb
- spec/bundler/ruby_version_spec.rb
- spec/support/hax.rb
- spec/support/platforms.rb
The problem was that we have code checking that `RUBY_ENGINE` everytime it's used and I think it's unnecessary.
My diagnosis was that every ruby implementation newer than 1.8 should define this.
My fix is to remove the unnecessary code.
> RUBY_ENGINE should always be defined after 1.8.7

- man/bundle-config.ronn
The default path where `bundle package` puts the gems is `vendor/cache`, not `vendor/bundle`.
> Correct default cache path

- spec/runtime/inline_spec.rb
This addresses the problem described in issue #7131. `bundler/inline` does not respect `BUNDLE_PATH` env variable and installs gems to the default location.
`Bundler.configure` is not called at any point in `bundler/inline`.
To call it :)
When bundler is invoked via `bundle install` this method gets called.
---
The included test is failing without this change as expected.
I have also tested it manually using the code from the issue on ruby 2.6 and with bundler `1.17.2` & `2.0.1`.
> bundler/inline should install gems to BUNDLE_PATH

- lib/bundler/definition.rb
- spec/bundler/definition_spec.rb
The problem was that when you have locked platform gems in your lockfile for a platform different than the running one, the lockfile was always getting re-resolved.
My diagnosis was that the dependencies passed on to the `SpecSet#for` call that's supposed to check that no dependencies are missing for the current platform, always include all dependencies for all platforms. And thus platform missing dependencies are always detected. The reason for that is that `expand_dependencies` was being passed `remote = true`
https://github.com/bundler/bundler/blob/0b5da910e71760eb585b34d08d43ea31b988ca24/lib/bundler/definition.rb#L815-L816
and thus not excluding dependencies exclusive for other platforms
https://github.com/bundler/bundler/blob/0b5da910e71760eb585b34d08d43ea31b988ca24/lib/bundler/defini …
> Don't re-resolve locked platform specific gems

- spec/bundler/shared_helpers_spec.rb
The problem was I noticed that this test was missing one assertion. See 
https://github.com/bundler/bundler/blob/566cce0629a0f1a4d147195a34d494306269e1cf/lib/bundler/shared_helpers.rb#L77-L84
My diagnosis was that it should be added.
My fix is to add the missing expectation.
I chose this fix because regardless of how implementation dependent this spec is, it should probably be complete.
> Add missing expectation

- lib/bundler/cli/package.rb
- lib/bundler/definition.rb
- lib/bundler/installer.rb
- spec/commands/package_spec.rb
The problem was `bundle package --all-platforms` causes `bundle install` to ignore `--with` and `--without`.
Closes https://github.com/bundler/bundler/issues/6074.
My diagnosis was `Installer#resolve_if_needed` had to always resolve remotely for `--all-platforms`, because we would be trying to package things that weren't available locally.
I chose this fix because it avoids refactoring any of the other packaging code.
> [Package] Always resolve remotely for --all-platforms

- lib/bundler/source/git/git_proxy.rb
- spec/bundler/source/git/git_proxy_spec.rb
The problem was that sometimes we get the error "Revision xxxxxx does not exist in the repository https://github.com/my_user/my_repo. Maybe you misspelled?"
My diagnosis was that it's not always easy to troubleshoot this error, because you don't even know which git command failed in the first place.
My fix is to also include in the error the command that originally failed.
I chose this fix because I think it will help users with troubleshooting.
> Clearer `MissingRevision` git errors

- lib/bundler/templates/newgem/Gemfile.tt
- lib/bundler/templates/newgem/newgem.gemspec.tt
- spec/commands/newgem_spec.rb
The problem was that a lot of gems in the wild use `add_development_dependency` for their development dependencies, but using `Gemfile`'s for that is more useful.
My diagnosis was that the current situation is due to the fact that bundler generates a gem skeleton that uses `add_development_dependency` by default.
My fix is to stop using `add_development_dependency` in generated gems, and instead use the Gemfile.
I chose this fix because it encourages better practices.
> Remove `add_development_dependency` from new gems

- lib/bundler/shared_helpers.rb
The problem was that the `find_gemfile` method was receiving an `order_matters` parameter that's no longer used anywhere.
My fix is to remove the parameter.
> Remove unnecessary `order_matters` param

- Rakefile
- bin/bundle1
- bin/rake
- bin/rspec
- bin/rubocop
- bundler.gemspec
- spec/support/rubygems_ext.rb
The problem was that our development setup is complicated, and that we are using `add_development_dependency` even though in my opinion its usage should be discouraged.
My diagnosis was that our development dependencies are split between the gemspec and the `spec/support/rubygems_ext` file. We can simplify this and centralize everything in the support file.
My fix is to simplify our development setup by moving everything to `spec/support/rubygems_ext`, while also getting rid of `add_development_dependency` in our gemspec.
I chose this fix because it simplifies our setup and it further discourages usage of `add_development_dependency` (after #7222).
> Remove `add_development_dependency` from gemspec

- lib/bundler/cli/outdated.rb
- lib/bundler/definition.rb
- lib/bundler/dependency.rb
- lib/bundler/inline.rb
- lib/bundler/settings.rb
- man/bundle-config.ronn
- spec/commands/lock_spec.rb
- spec/install/gemfile/platform_spec.rb
- spec/runtime/require_spec.rb
The problem was that currently if the gemfile include gems for specific platforms, like the default `gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby] ` Rails uses, bundler will _always_ print a noisy warning, but I don't think users are doing anything wrong, just running `bundle install` on it.
Also, unless they run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`, and commit the resulting lockfile, they will continue to get the same warning over and over again.
My diagnosis was that the right thing to do is that instead of warning users, bundler does the right thing by default. That is:
* Resolve the gemfile and lock it for all platforms present in the Gemfile.
* Install gems for the current platform if requested.
My fix is to do just that.
I chose …
> Auto multiplatform

- lib/bundler/rubygems_integration.rb
- spec/runtime/setup_spec.rb
The problem was that rubygems/rubygems#2711 fails because the test in bundler that checks that `Gem.refresh` reveals no system gems fails.
My diagnosis was that we don't really need to make `Gem.refresh` a noop at all, because we already setup a `post_reset` hook to automatically go back to the set of specs bundler knows about, everytime `Gem::Specification.reset` is called. See https://github.com/bundler/bundler/blob/847db56c6b5d2156d27990d73a9949507693985a/lib/bundler/rubygems_integration.rb#L551-L554.
And `Gem::Specification.reset` is what `Gem.refresh` does: https://github.com/rubygems/rubygems/blob/564bb0a5bb310ccceaf6cd6391b3e67e0712edd5/lib/rubygems.rb#L861-L867.
My fix is to remove the redefinition of `Gem.refresh`. This makes sense to me not only because it's unnecessary, but …
> No need to make gem refresh a noop

- bundler.gemspec
- lib/bundler/rubygems_integration.rb
- lib/bundler/source/git.rb
- lib/bundler/stub_specification.rb
- spec/commands/exec_spec.rb
- spec/commands/info_spec.rb
The problem was that we have some conditional code in bundler dependent on the rubygems version being used, that could be easily removed if we dropped support for rubygems 2.5.0 and 2.5.1.
My diagnosis was that we could drop support for these versions now, to remove all of those conditionals and simplify the integration.
My fix is to drop support for rubygems 2.5.0 and 2.5.1.
I chose this fix because the oldest ruby we currently support, 2.3, ships with rubygems 2.5.2, so it's very unlikely that any user of the next bundler version will be using these old rubygems versions, because they would need to explicitly downgrade rubygems!
> Drop rubygems 2.5.0 and 2.5.1 support

- lib/bundler/shared_helpers.rb
- spec/bundler/shared_helpers_spec.rb
The problem was that when bundler is a default gem, nested `bundle exec` commands generate a LoadError.
```
/home/travis/.rvm/rubies/ruby-head/bin/bundle:30:in `load': cannot load such file --
/home/travis/.rvm/rubies/ruby-head/lib/bin/bundle (LoadError)
```
Not accounting for Bundler being installed as a default gem. When it's a default, the lib and exe folders do not share the same root folder.
This was the result of a change in https://github.com/bundler/bundler/commit/e742c3d5f458a4a59cf0eaab2567eca844f956d1 (#7100).
Using Ruby master/trunk/ruby-head (as of https://github.com/ruby/ruby/commit/0c6c937904aafc1809386bd892a2d114d22d01fe), from a folder where `bundle exec` can be ran:
```
bundle exec "bundle exec 'ruby -v'"
```
Small adjustment to logic for finding the correct exe/bundle …
> Fix nested bundle exec's when bundler is a default gem

- spec/bundler/shared_helpers_spec.rb
PR 7248 https://github.com/bundler/bundler/commit/3f57b102c76fea2f701152e087c88f53df17d3d0 incorrectly changed a path calculation.  This reverts.
This only affects testing when `ruby_core?` is true.
After running Azure Pipelines CI in my ruby/ruby fork and checking the  'bundler' jobs, the error was apparent...
> spec/bundler/shared_helpers_spec.rb - fixup after 7248

- lib/bundler/build_metadata.rb
- spec/bundler/dsl_spec.rb
Travis CI job on Ruby master was failing & had a nuisance warning.
1. dls_spec.rb - Minor change to the error msg regexp match string
2. build_metadata.rb - change `if @git_commit_sha` to `if instance_variable_defined? :@git_commit_sha`
> Fix ruby core dsl spec.rb failure, warning on build_metadata.rb

- lib/bundler/environment_preserver.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/spec_helper.rb
The problem was that the specs were removing some environment variables for every tests, but not all of them, causing problems on some environments (see #7251).
My diagnosis was that we don't really need to do this.
My fix is to stop doing it, and fix the very few specs that failed after the change. One of the failures actually led to a bug fix (I think), see 6c27ebb.
I chose this fix because I think it's cleaner than adding a public constant in `lib/` only to fix a problem with the specs, like it's done in #7251.
> Improve environment backup and restore

- lib/bundler/templates/newgem/README.md.tt
The generated README contains two different links to contributor covenant. Since the generated Code of Conduct *contains* the text of the Contributor Covenant, we can just point the generated README to the generated CoC, and explicitly refer to it as the code of conduct. 
The generated readme now points to the gems CoC (which contains the Contributor Covenant)
Closes #6905.
> Point to CoC which contains the contributor covenant

- spec/support/requirement_checker.rb
The problem was that current tests are very cryptic about the tests that are being excluded:
```
$ bin/rspec 
Run options: exclude {:non_windows=>false, :ruby_repo=>false, :bundler=>#<RequirementChecker:./spec/support/requirement_checker.rb:7>, :git=>#<RequirementChecker:./spec/support/requirement_checker.rb:7>, :rubygems=>#<RequirementChecker:./spec/support/requirement_checker.rb:7>, :ruby=>#<RequirementChecker:./spec/support/requirement_checker.rb:7>, :realworld=>true, :sudo=>true}
Randomized with seed 22209
...
```
My diagnosis was that the `RequirementChecker` class needs a better text representation.
My fix is to add an `inspect` method that informs better about the exclusion. Now:
```
$ bin/rspec
Run options: exclude {:non_windows=>false, :ruby_repo=>false, :bundler=>"!= 2", …
```
> Better info about spec exclusions

- .rubocop.yml
- lib/bundler/cli/config.rb
- lib/bundler/env.rb
- lib/bundler/shared_helpers.rb
- spec/bundler/definition_spec.rb
- spec/bundler/plugin/installer_spec.rb
- spec/bundler/shared_helpers_spec.rb
- spec/cache/git_spec.rb
- spec/commands/exec_spec.rb
- spec/install/gemfile/sources_spec.rb
The problem was that sometimes we have some unneeded string interpolations in our code base.
My diagnosis was that we could remove them, because interpolating string variables seems weird and redundant.
My fix is to remove the unnecessary interpolations, and enable the corresponding rubocop cop.
I chose this fix because it fixes the current issues and it enforces the style rule from now on.
> Enable `Style/UnneededInterpolation` cop

- spec/spec_helper.rb
When the users uses `BUNDLE_USER_*` environmental variables like `BUNDLE_USER_CONFIG`, the rspec example of Bundler affected by them failed.
The current spec_helper didn't clear and restore them.
I remove and restore them same as `Bundler::EnvironmentPreserver::BUNDLER_PREFIX`
This is the most simple solution with the current implementation.
> Removed the environmental variables that are BUNDLE_USER_*.

- lib/bundler/current_ruby.rb
- lib/bundler/gem_helpers.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/runtime/platform_spec.rb
The problem was using `gemspec` and `force_ruby_platform` on Windows would lead to gems not being requirable.
Fixes #6801.
My diagnosis was there was a place where `force_ruby_platform` wasn't being taken into account, namely the query methods on `Bundler.current_ruby`
My fix was to add a check for the local platform in `current_ruby`, so the `force_ruby_platform` override would be taken into account.
I chose this fix because it avoids hard-coding knowledge of the setting in more places.
> Fix using gemspec & force_ruby_platform on windows

- spec/bundler/definition_spec.rb
- spec/commands/add_spec.rb
- spec/commands/install_spec.rb
- spec/commands/post_bundle_message_spec.rb
- spec/install/bundler_spec.rb
- spec/install/gems/flex_spec.rb
- spec/install/yanked_spec.rb
- spec/other/platform_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/update/git_spec.rb
The problem was that Windows build is still red.
My diagnosis was that some functionality is actually working, but specs need to be adapted, because some error messages include the platform on Windows.
My fix is to use `force_ruby_platform` for those specs.
I chose this fix because... I'm not sure, maybe it's better to adapt the error messages to include the platform when run on Windows.
> Get some more Windows specs passing

- lib/bundler/cli.rb
- lib/bundler/cli/package.rb
- spec/cache/git_spec.rb
- spec/cache/path_spec.rb
- spec/commands/binstubs_spec.rb
- spec/commands/package_spec.rb
- spec/install/deploy_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/lock/lockfile_spec.rb
- spec/plugins/source/example_spec.rb
- spec/runtime/executable_spec.rb
- spec/support/helpers.rb
The problem was that I accidentally restored this flag on Bundler 3 in #7249, but the plan still is to remove it.
My diagnosis was that I need to remove it again.
My fix is to remove it.
I chose this fix because it's the original plan and makes sense.
> Restore the removal of the `--all` flag for `bundle cache` in Bundler 3

- lib/bundler/templates/Executable.bundler
- spec/commands/binstubs_spec.rb
The problem was that the logic to select bundler versions was different when bundler is run from a rubygems binstub that when bundler is run from a bundler binstub.
My diagnosis was that we should unify the logic.
My fix is to use the same logic implemented in the rubygems version finder, namely, only fail if the major version of bundler does not match.
I chose this fix because it makes things consistent.
Fixes #7243.
> Relax bundler binstub

- man/bundle-binstubs.ronn
There is a typo in the [binstubs documentation](https://bundler.io/v2.0/man/bundle-binstubs.1.html).
It currently reads 
> This gives you a file that can **by** run directly
It should read 
> This gives you a file that can **be** run directly
Fix the typo in the RONN file that is used to generate this documentation.
> Fix typo in binstubs documentation

- man/gemfile.5.ronn
The problem was that Gemfile's man page has incorrect syntax in the section where examples for `:ref`, `:tag` and `:branch` are given.
My diagnosis was that the section was incorrect since the examples were listed as a separate section. Also, the syntax seems incorrect, since building the docs with [ronn-ng]() (something I've been experimenting with lately) gives the following error:
```
$ bin/rake man/gemfile.5
/home/deivid/.rbenv/versions/2.6.3/bin/ruby -S ronn --roff --pipe man/gemfile.5.ronn > man/gemfile.5
warn: unrecognized inline tag: ["p"]
warn: unrecognized inline tag: ["p"]
warn: unrecognized inline tag: ["p"]
man/gemfile.5 ran for   0.000305   0.000038   0.317832 (  0.317939)
```
My fix is to correct the syntax. The comparison of the rendered man page is:
```
(...)
branch, tag, …
```
> Fix incorrect sectioning in `gemfile` man page

- lib/bundler/friendly_errors.rb
- lib/bundler/uri_credentials_filter.rb
- lib/bundler/yaml_serializer.rb
- spec/support/rubygems_ext.rb
The problem was that we are using an outdated rubocop version.
My diagnosis was that we should upgrade, specially because the newest version fixes an issue that made us disable a cop under some situations.
My fix is to upgrade rubocop and remove the now unneeded exclusions.
> Bump rubocop to 0.74.0

- lib/bundler.rb
- lib/bundler/rubygems_integration.rb
- spec/support/path.rb
When we try to remove `Gem::ConfigMap` on rubygems repository, It breaks the bundler examples.
https://github.com/rubygems/rubygems/pull/2848#issuecomment-515726585
Gem::ConfigMap is compatibility code for the old Ruby like 1.8/1.9.
Use RbConfig instead of `Gem::ConfigMap` directly. It was always provided after the Ruby 2.x.
> Use RbConfig::CONFIG directly instead of Gem::ConfigMap.

- spec/realworld/double_check_spec.rb
The problem was that master is unstable right now, and build fails a number of times. That makes merging PRs annoying because they have to be retried many times.
I'm currently investigating what's going on and found the first root cause. Sometimes specs end up falling back to the old dependency API, and we have no recorded cassettes for those request, so specs fail because those never recorded specs are not allowed to be performed. I'm now invetigating the cause for that and I have a hypothesis: previous specs are sometimes messing up the test user home, and that's why we're falling back.
I yet need to validate this hypothesis and find a fix, but I discovered that we have a mechanism in place for retrying failed specs.
My fix is to enable the mechanism for the time being to reduce …
> Enable retries on flaky spec

- lib/bundler/ruby_version.rb
- spec/bundler/ruby_version_spec.rb
- spec/support/hax.rb
- spec/support/platforms.rb
* RUBY_ENGINE and RUBY_ENGINE_VERSION are defined on every modern Ruby.
* There is no such constant as TRUFFLERUBY_VERSION or RBX_VERSION.
This blocks https://github.com/rubygems/rubygems/pull/2797.
Also see https://github.com/rubygems/rubygems/pull/2864
> Use the standard RUBY_ENGINE_VERSION instead of JRUBY_VERSION

- lib/bundler/source/path.rb
- spec/install/gemfile/path_spec.rb
The problem was that when a Gemfile would specify path sources with paths starting with "./", the generated lockfile would be inconsistent on `bundle install` and `bundle update`.
My diagnosis was that when running `bundle update`, the bundle would be unlocked, and bundler would order the path sources according to the path present in the Gemfile ("./aaa" for example). On the other hand, when running `bundle install`, bundler would read the relative paths from the lockfile, where they are normalized ("aaa" for example).
My fix is to normalize relative paths when creating the source list, so that "aaa" is always used over "./aaa".
I chose this fix because it fixes the problem and it's backwards compatible (as in, it doesn't break any specs that assert for specific lockfiles).
Fixes #7262.
> Consistent lockfiles

- spec/runtime/setup_spec.rb
The problem was for a while I've had a spec failing locally and that's annoying.
My diagnosis was that if you install a development version of bundler in your system (through `bin/rake install:local`), this spec starts failing with:
``` 
$ bin/rspec -e "orders the load pa"
Run options: include {:full_description=>/orders\ the\ load\ pa/}
Randomized with seed 55764
Bundler.setup
load order
$ /home/deivid/.rbenv/versions/2.6.3/bin/ruby \
-I/home/deivid/Code/bundler/lib:/home/deivid/Code/bundler/spec -rsupport/hax \
-r/home/deivid/Code/bundler/spec/support/artifice/fail /home/deivid/Code/bundler/exe/bundle \
install --retry 0
Fetching source index from file:///home/deivid/Code/bundler/tmp/gems/remote1/
Resolving dependencies...
Fetching rake 12.3.2
Installing rake 12.3.2
Fetching …
```
> Improve load path order spec

- spec/support/rubygems_ext.rb
The problem was that tests fail using rspec 3.7 or older.
My diagnosis was that we're using `config.bisect_runner` which is only available from 3.8.
My fix is to bump the requirement.
> Bump rspec dependency to 3.8

- .github/config.yml
- CODE_OF_CONDUCT.md
- README.md
- doc/contributing/COMMUNITY.md
- doc/contributing/GETTING_HELP.md
- doc/development/NEW_FEATURES.md
- doc/documentation/VISION.md
- doc/playbooks/RELEASING.md
End-users experience 301 redirect,  or unintentionally visit URL with http and may send email.
I noticed the problem when I was reading codes. Following are some examples using curl to explain this problem.
```
curl -I http://slack.bundler.io/
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 3726
Etag: W/"3Shz0DQR5y/DyBrYbyUBAQ=="
Date: Fri, 09 Aug 2019 14:16:23 GMT
Via: 1.1 vegur
```
```
curl -I http://contributor-covenant.org
HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=0, must-revalidate
Content-Length: 49
Content-Type: text/plain
Date: Sun, 04 Aug 2019 09:47:02 GMT
Location: https://contributor-covenant.org/
Age: 448201
Connection: keep-alive
Server: Netlify
X-NF-Request-ID: …
```
> Fix documents to refer to URLs with https

- lib/bundler/plugin/api/source.rb
Let me skip answering questions in the pull request template since it's obviously just fixing a typo!
> Fix typo in comment: attibutes -> attributes

- lib/bundler/shared_helpers.rb
The problem was that that test suite prints some deprecation messages to the screen and I think that's unintented. See for example https://travis-ci.org/bundler/bundler/jobs/568969249.
My diagnosis was that bundler is using a different UI than the one intented sometimes.
My fix is to make sure all deprecation messages go through bundler's UI.
I chose this fix because it stops deprecation messages from being interleaved with other output during the specs.
> Stop printing deprecation messages during specs

- spec/bundler/bundler/build_metadata_spec.rb
The problem was there is no spec of `Bundler::BuildMetadata`
My diagnosis was it's better to prepare spec
My fix is just adding spec file, has no impact on production codes.
I chose this fix because I saw the code coverage and there is enough space to contribute to this product.
> Add initial Bundler::BuildMetadata Spec

- .travis.yml
- Rakefile
The problem was than `ronn` behaves weird sometimes and updates the month in pages to an old month. This can be seen in #7292, but I've seen it too myself. 
My fix is to explicitly pass the current date when generating man pages. This has the disadvantage that the man pages will become out of sync if they haven't been updated for more than a month, because the month will change.
But I'd like to introduce it until I think of a better alternative.
> Fix `man:check`

- man/bundle-config.1
- man/bundle-config.1.txt
- man/bundle-config.ronn
- man/gemfile.5
- man/gemfile.5.ronn
- man/gemfile.5.txt
The problem was that the remembered options of `bundle install` were not documented in manpages.
Restore the section on remembered options from https://github.com/bundler/bundler/commit/e120f40f72fe53f55e05db9204f98d28f1065e81 and add description for some options.
They should be fully documented.
Closes #7198.
> Restore remembered options in manpages

- lib/bundler/shared_helpers.rb
- spec/bundler/source_spec.rb
- spec/commands/binstubs_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/newgem_spec.rb
- spec/spec_helper.rb
I'm going to merge https://github.com/bundler/bundler/pull/7274. But the ruby-core source has some of the changes for bundler source.
ruby core team fixed them:
* Removed circular require warning at `shared_helper.rb`
* Support test at GitHub Actions, It helps that bundler will migrate Actions from Azure Pipelines too.
* Fixed broken examples at ruby core repository
> Track changes from ruby core master

- lib/bundler/shared_helpers.rb
- spec/bundler/shared_helpers_spec.rb
- spec/commands/clean_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/newgem_spec.rb
- spec/quality_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
- spec/support/path.rb
- spec/support/rubygems_ext.rb
The problem was that sometimes we break specs when integrating bundler changes into core.
My diagnosis was that sometimes we use paths dependent on the structure of this repo, but that break under ruby-core's structure.
My fix is only some refactoring so that usage of structure independent helpers is encouraged. After this set of changes, if you grep the repo for `ruby_core?`, the only result will be `spec/support/path.rb`. That means that all logic dealing with repo folder structure lives in a single place. 
I chose this fix because it makes the integration in core cleaner.
> Refactor ruby core integration

- lib/bundler/cli/open.rb
- spec/commands/open_spec.rb
The problem was that `bundle open` doesn't currently support opening default gems, but crashes with a very verbose and unclear error when the user tries to do it. 
My diagnosis was that we should give a more clear error in this case.
My fix is a rebased and improved version of #4882, that detects the situation and gives a better error. 
I chose this fix because it was already created and it's simpler than adding support for opening default gems, which is more problematic because they can't be pristine'd easily if edited and might not be in a writable location.
Closes #4882.
Fixes #4436.
> Give a more clear error when user tries to `bundle open` a default gem

- .travis.yml
- Rakefile
The problem was that [rubygems 3.0.6 was released](https://blog.rubygems.org/2019/08/16/3.0.6-released.html), and we haven't yet tested against it.
My fix is to use the new rubygems in CI.
> Use the latest rubygems 3.0.6 in CI

- lib/bundler/cli/doctor.rb
- spec/commands/doctor_spec.rb
The problem was that `bundle doctor` crashes on very simple usages, like this:
````
$ bundle doctor
The Gemfile's dependencies are satisfied
--- ERROR REPORT TEMPLATE -------------------------------------------------------
Please fill out answers to these questions, it'll help us figure out
why things are going wrong.
- **What did you do?**
I ran the command `/home/deivid/.rbenv/versions/2.6.3/bin/bundle doctor`
- **What did you expect to happen?**
I expected Bundler to...
- **What happened instead?**
Instead, what happened was...
- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**
I tried...
- **Have you read our issues document, https://github.com/bundler/bundler/blob/master/doc/contributing/ISSUES.md?**
...
```
Errno::ENOENT: No …
> Fix `bundle doctor` command

- lib/bundler/dsl.rb
- spec/commands/install_spec.rb
I have a Gemfile where some gems appear in two distinct groups. When I run Bundle, the following warning is displayed:
> Your Gemfile lists the gem #{gem} more than once.
> You should probably keep only one of them.
> Remove any duplicate entries and specify the gem **only once (per group)**.
> While it's not a problem now, it could cause errors if you change the version of one of them later.                                                           
Example Gemfile:
```rb
source "https://rubygems.org"
group :production do
end
group :development do
gem "rake"
end
group :ci, optional: true do
gem "rake"
end
```
I think the message is misleading, because it shows even if all gems are specified **only once per group**.
I removed the _(per group)_ mention from the warning message in order to …
> Bundler displays a duplicate gem entries warning even if gems only appear once per group

- Rakefile
- exe/bundle
- lib/bundler/plugin.rb
- lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb
- lib/bundler/vendor/net-http-persistent/lib/net/http/persistent/pool.rb
- lib/bundler/vendored_fileutils.rb
- spec/bundler/bundler_spec.rb
- spec/bundler/settings_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/pristine_spec.rb
- spec/install/gemfile/groups_spec.rb
- spec/plugins/source/example_spec.rb
- spec/realworld/double_check_spec.rb
- spec/runtime/inline_spec.rb
- spec/runtime/load_spec.rb
- spec/runtime/require_spec.rb
- spec/runtime/setup_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/support/artifice/endpoint.rb
- spec/support/hax.rb
- spec/support/helpers.rb
The problem was that in some places, it was still possible to end up requiring files in a different copy of bundler (the default copy). I noticed this when I removed a rubygems monkeypatch from the test suite that was preventing the default copy of bundler from being activated when requiring files.
This thing:
https://github.com/bundler/bundler/blob/e1c518363641208429f397170354054b3d28effd/spec/support/hax.rb#L15-L20
My diagnosis was that I should use relative requires wherever they were missing.
My fix is to remove the rubygems hack, migrate the rest of the internal requires to be relative, and also introduce some hacks on our specs to make sure we never load the incorrect copy of bundler.
I think this PR should fix the issues in https://github.com/rubygems/rubygems/pull/2863.
> Fix more leaks to default copy of bundler

- lib/bundler/cli/exec.rb
- lib/bundler/spec_set.rb
- spec/bundler/dsl_spec.rb
- spec/quality_es_spec.rb
- spec/spec_helper.rb
The problem was that was still some code specific to old rubies we no longer support.
My fix is to remove that code.
> Remove old rubies stuff no longer needed

- spec/bundler/build_metadata_spec.rb
The problem was it will potentially fail if tests are executed around midnight
My diagnosis was it should freeze time when executing spec
My fix is mocking `Time.now` when executing `Bundler::BuildMetadata` specs
I chose this fix because it doesn't have effects on other specs.
> Freeze time to avoid failures at midnight

- Rakefile
The problem was that unfortunately #7317 broken rubygems test suite. See https://github.com/rubygems/rubygems/pull/2888.
My diagnosis was that it has some issues.
My fix is to not (yet) use it in CI, so we can keep using it locally and investigating these issues without interfering with our CI. In a while we reevaluate how it is working a consider enabling in CI.
> Don't (yet) enable parallelization in CI

- lib/bundler.rb
- lib/bundler/capistrano.rb
- lib/bundler/cli/gem.rb
- lib/bundler/friendly_errors.rb
- lib/bundler/similarity_detector.rb
- lib/bundler/source/git/git_proxy.rb
- lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt
- spec/bundler/bundler_spec.rb
End-users experience 301 redirect, or unintentionally visit URL with http.
Following are some examples using curl to explain this problem.
```
$ curl -I http://github.com/capistrano/bundler
HTTP/1.1 301 Moved Permanently
Content-length: 0
Location: https://github.com/capistrano/bundler
```
```
$ curl -I http://guides.rubygems.org/gems-with-extensions/
HTTP/1.1 301 Moved Permanently
Content-Type: text/html
Server: GitHub.com
Location: https://guides.rubygems.org/gems-with-extensions/
X-GitHub-Request-Id: 0A1A:1377:32938B:35C160:5D5D5A84
Content-Length: 162
Accept-Ranges: bytes
Date: Wed, 21 Aug 2019 14:51:49 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-tyo19949-TYO
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1566399109.014809,VS0,VE168
Vary: Accept-Encoding …
```
> Fix comments and messages to refer to https url

- lib/bundler/gem_helper.rb
- lib/bundler/shared_helpers.rb
- spec/bundler/cli_spec.rb
- spec/bundler/env_spec.rb
- spec/bundler/gem_helper_spec.rb
- spec/bundler/mirror_spec.rb
- spec/commands/config_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/info_spec.rb
- spec/commands/newgem_spec.rb
- spec/commands/open_spec.rb
- spec/commands/show_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gems/resolving_spec.rb
- spec/quality_es_spec.rb
- spec/quality_spec.rb
- spec/runtime/setup_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/spec_helper.rb
- spec/support/builders.rb
- spec/support/hax.rb
- spec/support/path.rb
This pull request is backported from https://github.com/ruby/ruby/pull/2380
> Remove `:ruby_core` tag for ruby core

- lib/bundler/cli/outdated.rb
- lib/bundler/definition.rb
- lib/bundler/inline.rb
- lib/bundler/settings.rb
- man/bundle-config.1
- man/bundle-config.1.txt
- man/bundle-config.ronn
- spec/install/gemfile/platform_spec.rb
- spec/runtime/require_spec.rb
The problem was that since #7215, more Gemfiles are going to fail resolution because of the current issues with multiplatform support, and that we'll be pushing current multiplatform problems into all users because bundler will resolve and lock all platforms included on a Gemfile by default. 
My diagnosis was that we probably need better multiplatform support before we start resolving all platforms by default.
My fix is to revert the relevant commits from #7215. I'll try to revisit in the future.
I chose this fix because it goes back to how things were before.
Closes #7315.
> Undo auto multiplatform

- lib/bundler/cli.rb
- spec/commands/check_spec.rb
- spec/other/major_deprecation_spec.rb
The problem was that this flag should also be deprecated for these commands in preparation for bundler no longer remembering CLI flags.
My diagnosis was that, on bundler 3, the standard use case for `bundle check --path` will no longer work, namely:
```
$ bundle check --path .bundle
The following gems are missing
* rake (12.3.3)
Install missing gems with `bundle install`
$ bundle install
Fetching gem metadata from https://rubygems.org/.
Installing rake 12.3.3
Using bundler 2.1.0.pre.1
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Bundled gems are installed into `./.bundle`
```
In the case of `bundle cache --path`, it has never really work as I expect
So we should deprecate `bundle check --path` and instead use whatever path is configured.
The cache of `bundle cache --path` …
> Deprecate `--path` flag to `bundle check` (and related fixes)

- CHANGELOG.md
- UPGRADING.md
The problem was that I want to release a first pre-release of bundler 2.1.0, but I don't have a changelog for it.
My diagnosis was that I needed to compile a changelog.
My fix is write the changelog.
I chose this fix because we used to have some automated change log handling, but I'm not sure how it work, so I instead just through each PR including user facing changes manually, with the aid of some helper tasks we have in our Rakefile.
This is still a WIP, because I might include some more PRs, and I also want to elaborate a bit on the deprecations that will get enabled, but it should be ready for an initial review.
> Changelog for first 2.1.0 pre-release 

- doc/playbooks/RELEASING.md
The problem was that I'm about to release bundler, but I'm unsure which one is the right version number.
My diagnosis was that the release playbook is probably wrong, because looking at https://rubygems.org/gems/bundler/versions, we don't really ship `.pre.0`. versions.
My fix is to document `.pre.1` as the first prerelease on a minor series, since that's what we usually do.
> Fix version number in release playbook

- spec/cache/git_spec.rb
The problem was v1.15 seemed to break installing without git when the git deps had already been packaged (see https://github.com/bundler/bundler/issues/6066).
My diagnosis was we actually seemed to have fixed this for 1.16.
My fix adds a test to ensure we won't regress.
> Add a spec for installing git deps after packaging without git

- lib/bundler/vendor/thor/lib/thor.rb
- spec/runtime/inline_spec.rb
`make test-bundler` in Ruby repository failed with recent changes to separate keyword arguments from positional arguments (see https://bugs.ruby-lang.org/issues/14183).
Bundler's specs check for lack of warnings, and the new changes cause warnings that cause Bundler's specs to fail.
In one case, I fix the code to work with keyword arguments and positional arguments in positional arguments.  In the other case, I fix the spec to ignore the keyword argument separation warnings.
I fixed this upstream in Ruby already (https://github.com/ruby/ruby/commit/b5b3afadfab4072f55320075ccac6afe333a140c). So this is a request to make bundler use the same patch.  You can certainly fix it differently, and there are more related issues to fix I think (they just don't cause test failures yet).  The issues …
> Fix a couple of bundler issues with keyword argument separation

- Rakefile
- task/release.rake
The problem was several issues I had when releasing bundler:
* The prerequisites can fail, but the gem is still pushed to rubygems.
* Some error messages could be better.
* The github release is a postrequisite not a prerequisite for the release task.
My diagnosis was that we need to make every prerequisite a prerequisite to the `rubygems:push` task to be really sure the gem is not pushed until every thing else is satisfied.
My fix implements that idea, plus other few improvements to the release task.
> Release task improvements

- CHANGELOG.md
- lib/bundler/definition.rb
- spec/commands/clean_spec.rb
The problem was that `bundle clean` is crashing under some conditions.
My diagnosis was that sometimes (when the bundle includes git sourced gems with extensions), it assumes that some paths exist, but they don't.
My fix is to ignore those paths.
I chose this fix because it fixes the issue.
Fixes #7338.
> Fix bundle clean issue

- lib/bundler/resolver/spec_group.rb
- spec/commands/exec_spec.rb
- spec/runtime/inline_spec.rb
- spec/spec_helper.rb
The master branch of Bundler with Ruby 2.7 fails some of tests.
It caused by deprecation warnings of Ruby 2.7 and some environmental issues.
I fixed them.
* rspec examples of Bundler failed randomly on GitHub Actions of ruby/ruby. We fixed it on `spec_group.rb`
* `github_action_linux` label is no longer required. The current test suite is all green status with GitHub Actions.
* The keyword separation feature warns stub code under the `inline_spec.rb`. I ignore them.
> Backport the latest ruby core changes

- Rakefile
- spec/support/rubygems_ext.rb
The problem was that I added a feature to automatiek to vendor subdependencies, but we were not using it because it had not yet been released.
My fix is to start using the feature now that it has been released.
I chose this fix because it allows us to manage the `net-http-persistent` dependency in an easier way.
> Start using automatiek 0.3.0

- CHANGELOG.md
The problem was that the changelog needs to be filled before releasing the next pre.
My fix is to fill in the user facing changes that I plan to include.
> Add 2.1.0.pre.2 changelog entries

- man/bundle-exec.1
- man/bundle-exec.1.txt
- man/bundle-exec.ronn
The latter does not work on Ruby 2.6.3.
The problem was a broken example in the docs.
Ibid.
My fix was to write what was likely intended.
I chose this fix because the solution space is pretty small.
> require `rubygems`, not `ubygems` in example

- doc/playbooks/RELEASING.md
- task/release.rake
The problem was that I removed too much code in #7350.
My diagnosis was that since I removed the auto-bumping `version.rb`, the task no longer works before it tries to cherry-pick changes for the _current_, not the _to be released_ version, so I fails because it finds no open PR for that milestone (because it's already been released).
My fix is to restore the code that automatically bumps the version to the next patch level version, and commits that to the release branch.
I chose this fix because it works for me.
> Restore version bumping to `release:prepare_patch`

- CHANGELOG.md
- task/release.rake
I just released [2.1.0.pre.2](https://rubygems.org/gems/bundler/versions/2.1.0.pre.2). It went smoother than 2.1.0.pre.1, but I still got an issue where I unintentionally pushed a release named "v" to github releases.
My diagnosis was that the release task by default should use the version in the gemspec for the `release:github` tasks.
My fix adds that fallback.
I chose this fix because it does what the user expects when the task is not passed any arguments.
> More release fixes

- .azure-pipelines/steps.yml
- .rspec
- .rspec_parallel
- Rakefile
The problem was that our default RSpec formatter is `--documentation`, but we're overriding it almost everywhere to use `--progress`.
My diagnosis was that we should probably use the default formatter, since I think we all prefer it.
My fix is to do that.
> Consistenly use the default RSpec formatter

- spec/support/rubygems_version_manager.rb
The problem was that #7296 broke rubygems CI.
My diagnosis was that the handling of `ENV["RGV"]` when it contains the path of a rubygems checkout instead of a rubygems version (like it happens in the rubygems repo) was incorrect.
My fix is to correct the behaviour. I was able to reproduce the CI failures in https://github.com/rubygems/rubygems/pull/2924, and verify they are be fixed by this PR by patching the vendored bundler locally.
Fixes #7363.
> Follow up to `ENV["RGV"]` handling refactor

- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
The problem was that while working on a better `bundle outdated` format (essentially getting #4474 ready to merge), I noticed a bunch of logic in `bundle outdated` that's overly complicated and not necessary.
My diagnosis was that I should simplify the implementation before changing the output.
My fix is to add my improvements as a separate PR. Afterwards I'll rebase and get #4474 ready.
I chose this fix because including this improvements with #4474 made that PR too big and hard to understand.
> Refactor `bundle outdated`

- lib/bundler.rb
- lib/bundler/shared_helpers.rb
- spec/other/major_deprecation_spec.rb
The problem was that some deprecations mention usage of deprecated methods, but include no information about where the deprecated method is being called.
My diagnosis was that we should include this information with this kind of deprecation messages, to make migration easier.
My fix is to add an optional argument to the `major_deprecation` method, to print the location of the deprecated caller.
I chose this fix because it required little code changes.
> Add caller information to some deprecation messages

- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
The problem was that the refactoring in #7365 introduced a regression involving groupless dependencies.
My diagnosis was that `nil` groups were not being properly handled when sorting groups by name, and when this kind of outdated deps would be involved, `bundle outdated` would crash with a backtrace like the following:
```
NoMethodError: undefined method `split' for nil:NilClass
/home/deivid/Code/bundler/lib/bundler/cli/outdated.rb:105:in `block in run'
/home/deivid/Code/bundler/lib/bundler/cli/outdated.rb:104:in `each'
/home/deivid/Code/bundler/lib/bundler/cli/outdated.rb:104:in `run'
/home/deivid/Code/bundler/lib/bundler/cli.rb:412:in `outdated'
/home/deivid/Code/bundler/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/deivid/Code/bundler/lib/bundler/vendor/thor/lib/thor/in …
```
> Fix `bunde outdated` regression with groupless dependencies

- Rakefile
- lib/bundler/vendor/fileutils/lib/fileutils.rb
- lib/bundler/vendor/fileutils/lib/fileutils/version.rb
The problem was that we were not using a released version of fileutils.
My diagnosis was that we can upgrade, because 1.3.0 has been released.
My fix is to upgrade.
> Bump vendored fileutils to 1.3.0

- lib/bundler/cli.rb
- lib/bundler/cli/outdated.rb
- spec/commands/outdated_spec.rb
- spec/install/gemfile/path_spec.rb
- spec/other/platform_spec.rb
Haven't fixed tests since wanted buy-in.
Before:
```
Outdated gems included in the bundle:
* active_model_serializers (newest 0.9.5, installed 0.8.3, requested ~> 0.8.0) in group "default"
* activerecord-import (newest 0.13.0, installed 0.10.0) in group "default"
* addressable (newest 2.4.0, installed 2.3.5, requested = 2.3.5) in group "default"
* airbrake (newest 5.2.3, installed 5.1.0) in group "default"
* bootstrap-sass (newest 3.3.6, installed 3.3.5.1) in group "default"
* capistrano (newest 3.5.0, installed 3.4.0, requested ~> 3.4) in group "development"
* capistrano-rails (newest 1.1.6, installed 1.1.3, requested ~> 1.1.1) in group "development"
```
After:
```
--pretty
Outdated gems included in the bundle:
Gem Name                New        Installed  Requested  Groups
airbrake …
```
> Improve readability of outdated

- lib/bundler/templates/newgem/newgem.gemspec.tt
It is common to prefer double quotes, unless single quotes are needed.  It is also generally preferred to use a consistent quote style (whether double quotes or single quotes).
Switch the anomalous single quotes to double quotes.
> Switch to double quotes to match rest of file

- lib/bundler/dsl.rb
- lib/bundler/rubygems_ext.rb
- lib/bundler/shared_helpers.rb
- lib/bundler/source/git.rb
- lib/bundler/vendor/fileutils/lib/fileutils.rb
Ruby 2.7 is deprecating taint support. 
See https://bugs.ruby-lang.org/issues/16131 for details.
Bundler still uses `untaint` in a few places, which will cause deprecation warnings on Ruby 2.7.
`s/\.untaint/.tap{|x| x.untaint if RUBY_VERSION < "2.7" }/g`
It seemed simplest.
> Remove taint usage on Ruby 2.7+

- lib/bundler/gem_helpers.rb
This PR suppresses the following `Warning: no department given for MutableConstant`.
```console
% cd path/to/bundler
% bundle exec rubocop -v
0.75.1
% bundle exec rubocop --parallel
(snip)
/Users/koic/src/github.com/bundler/bundler/lib/bundler/gem_helpers.rb:
Warning: no department given for MutableConstant. Run `rubocop -a --only
Migration/DepartmentName` to fix.
```
> Suppress `Warning: no department given for MutableConstant`

- Rakefile
- lib/bundler/cli.rb
- lib/bundler/cli/cache.rb
- man/bundle-cache.1
- man/bundle-cache.1.txt
- man/bundle-cache.ronn
- man/bundle-package.1
- man/bundle-package.1.txt
- man/bundle-package.ronn
- man/index.txt
- spec/cache/cache_path_spec.rb
- spec/cache/git_spec.rb
- spec/cache/path_spec.rb
- spec/commands/cache_spec.rb
- spec/install/deploy_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/lock/lockfile_spec.rb
- spec/other/platform_spec.rb
- spec/plugins/source/example_spec.rb
The problem was that after https://github.com/bundler/bundler/pull/7249, we added the current `bundle package` functionality to the current `bundle cache` command, so that these commands are now aliases of each other.
The initial plan was to do this in a more careful manner but we concluded that this was only _adding_ functionality to `bundle cache`, so not backwards incompatible.
We still need to wrap up the original plan, where `bundle cache` is the preferred command.
My fix is to migrate docs, tests and help text to use `bundle cache`, and to remove duplicated specs for `bundle cache` and `bundle package`, since they are testing the exact same code.
> Wrap up `bundle cache` migration to current `bundle package`

- lib/bundler/cli.rb
- spec/bundler/cli_spec.rb
The problem was that the output of `bundle help install` and `bundle install --help` was inconstent with `bundle i --help`, and the same issue with all of the other command aliases. 
My diagnosis was that the command reformatting so that `bundle <cmd> --help` "redirects" to `bundle help <cmd>` was ignoring command aliases.
My fix is to make this logic aware of command aliases.
> Fix help with command aliases

- lib/bundler/cli/info.rb
- spec/commands/info_spec.rb
- spec/support/builders.rb
Rubygems has supported [gemspec metadata](https://guides.rubygems.org/specification-reference/#metadata) since version 2.0. I think it'd be great to display this information in response to the `bundle info <gem>` command.
Added a check for `metadata`, outputting this extra information if it has been included with the gem release. For example:
```
> bundle info rspec-mocks
* rspec-mocks (3.8.1)
Summary: rspec-mocks-3.8.1
Homepage: https://github.com/rspec/rspec-mocks
Documentation: https://rspec.info/documentation/
Source Code: https://github.com/rspec/rspec-mocks
Changelog: https://github.com/rspec/rspec-mocks/blob/v3.8.1/Changelog.md
Bug Tracker: https://github.com/rspec/rspec-mocks/issues
Mailing List: https://groups.google.com/forum/#!forum/rspec
Path: …
```
> bundle info prints gem metadata

- lib/bundler.rb
- lib/bundler/cli.rb
- lib/bundler/cli/exec.rb
- lib/bundler/friendly_errors.rb
- lib/bundler/gem_helper.rb
- lib/bundler/inline.rb
- lib/bundler/rubygems_integration.rb
- lib/bundler/setup.rb
- lib/bundler/shared_helpers.rb
- spec/bundler/friendly_errors_spec.rb
- spec/bundler/source_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/realworld/edgecases_spec.rb
- spec/runtime/platform_spec.rb
- spec/runtime/with_unbundled_env_spec.rb
- spec/spec_helper.rb
- spec/support/filters.rb
- spec/support/helpers.rb
The problem was that bundler defaults to a silent UI:
https://github.com/bundler/bundler/blob/e70643c1be3a4417bd537d7e63470265465e693e/lib/bundler.rb#L66-L68
In my opinion, this isn't a good behavior for a CLI tool, and forces us to override it in many many different places. It has also caused several issues, for example, https://github.com/bundler/bundler/issues/3710 where `bundle list` was printing nothing.
The [solution to that issues](https://github.com/bundler/bundler/pull/3707) led us to add yet more places where we override the default UI, and @indirect [predicting that having to unset the UI everytime we want it to not be silent](https://github.com/bundler/bundler/pull/3707#issuecomment-108646127) would cause many headaches.
Well, yeah... I've lost a lot of time trying to figure …
> Stop silencing output by default

- spec/realworld/edgecases_spec.rb
The problem was that this helper was printing nothing to the standard output, so the specs in this file were just checking if lockfiles contained the empty string, which is obviously true. For example,
https://github.com/bundler/bundler/blob/e70643c1be3a4417bd537d7e63470265465e693e/spec/realworld/edgecases_spec.rb#L31
My diagnosis was that the helper needs to actually print the extracted information about the resolved gem, so it can be checked that the lockfile is correct.
My fix adds the missing `puts`.
> Fix some realworld specs testing nothing

- .azure-pipelines/steps.yml
- azure-pipelines.yml
The problem was that our Azure build was using outdated versions of ruby and rubygems.
My diagnosis was that we should update them.
My fix is to update them. With the latest versions, failures go down to 319.
> Try out specs against MRI 2.6 + Rubygems 3.0

- lib/bundler.rb
- lib/bundler/lockfile_parser.rb
Since Bundler became part of the standard library, it renders in Ruby's docs. Unfortunately, what renders there...  is not really helpful: https://docs.ruby-lang.org/en/master/Bundler.html
I've added rudimentary documentation for `Bundler` module and two of its most user-facing methods to solve this problem at least partially.
> Add inline RDoc documentation

- lib/bundler/cli/add.rb
- spec/commands/add_spec.rb
The problem was that when calling `bundle add` with cache_all as true, I have to call an additional `bundle install` to vendor gems.
My diagnosis was that a call to Bundler.load.cache was missing. For example Bundler::CLI::Update does the same after installing gems.
My fix was to call Bundler.load.cache when `Bundler.app_cache.exist? ` 
I chose this fix because it looks like this makes the behavior consistent with other commands.
I should also say that, as this is my first PR here, I'm not sure that this is the best solution, and it seems an easy fix for #7384.
> Make 'bundle add' cache newly added gems when needed

- lib/bundler/source/git/git_proxy.rb
The `tempfile` dependency was dropped in [1], but the require was left in there. This could cause gem conflicts because `tempfile` requires `tmpdir` which requires `fileutils`, which loads the default gem instead of our namespaced version, and that could cause fileutils version mismatches and code overriding warnings.
[1]: https://github.com/bundler/bundler/commit/4a37d66f3f222739178d798b30fb135f2429fe45
My fix is to drop the unnecessary require.
> Drop unnecessary `tempfile` require

- .azure-pipelines/steps.yml
- spec/support/rubygems_ext.rb
The problem was that specs cannot be run on windows unless you add the ugly workaround currently included in the azure pipelines config.
My diagnosis was that the `tmp/tmpdir` and `tmp/home` folder (which act as `ENV["HOME"]` and `ENV["TMPDIR"]` for our specs) are emptied in an `around(:each)` hook, but there's some stuff going before that and after `ENV["HOME"]` and `ENV["TMPDIR"]` are set (on a `before(:suite)` hook) that might require the folders they point to to exist.
This is the case of rb-readline, used on Windows:
https://github.com/ConnorAtherton/rb-readline/blob/9fba246073f78831b7c7129c76cc07d8476a8892/lib/rbreadline.rb#L1096
or any bundler's code that uses `Bundler.user_home`:
https://github.com/bundler/bundler/blob/f83412ae8cda9c933b8cf33ec2abfb78a408daab/lib/bundler.rb#L227 …
> Properly avoid readline crashes when running specs on Windows

- spec/bundler/source_spec.rb
- spec/support/filters.rb
This reverts commit 36816866581147ba7bd491a2a658ac35a2f03afe.
The problem was that in #7401, after I got specs passing against a non-silenced by default UI, I started undoing workarounds that I thought were due to the silent by default UI. 
My diagnosis was that in the case I'm reverting here this is not actually fixed, [as the Azure Pipelines logs confirm](https://dev.azure.com/bundler/bundler/_build/results?buildId=2662&view=ms.vss-test-web.build-test-results-tab&runId=1003360&resultId=101526&paneView=debug).
My fix is to unrevert the specific commit that I shouldn't have reverted.
> Revert "I don't think we need this now"

- spec/support/helpers.rb
The problem was that Windows has trouble with commands of the form `BUNDLE_FROZEN=true bundle install`.
My diagnosis was that we should use `Open3.popen3` explicit `env` argument instead of passing a command line that has environment variables in the front.
My fix is to do just that. This is a follow up to #7011, but specifically for the `ruby` test helper. I expect this to fix some more Windows failures.
> Pass `env` as a parameter to `sys_exec`

- lib/bundler.rb
- spec/bundler/bundler_spec.rb
- spec/bundler/settings_spec.rb
> Don't use insecure temporary directory as home directory

- lib/bundler/inline.rb
> Fix bundler/inline warning: method redefined; discarding old root

- task/release.rake
The problem was some more little issues with the `bin/rake release:prepare_patch` task.
My fix is to improve the task with better fallbacks and better informational and error messages.
> Improve `release:prepare_patch` task

- lib/bundler/cli.rb
- lib/bundler/cli/gem.rb
- lib/bundler/templates/newgem/Gemfile.tt
- lib/bundler/templates/newgem/Rakefile.tt
- spec/commands/newgem_spec.rb
Based upon #6451.
The problem was I always have to remember how to add RuboCop to my Rakefile when I set up a new gem.
My diagnosis was that RuboCop has become enough of a community standard that it makes sense to offer it in `bundle gem`.
My fix adds an option to `bundle gem` to add in RuboCop, in the same way options like `:coc`and `:mit` are handled.
I chose this fix because it does not require bundler have an opinion on _how_ rubocop is configured.
> [CLI::Gem] Add a --rubocop option

- lib/bundler/gem_helper.rb
- spec/install/binstubs_spec.rb
- spec/lock/lockfile_spec.rb
- spec/other/major_deprecation_spec.rb
- spec/other/platform_spec.rb
- spec/runtime/inline_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/hax.rb
- spec/support/matchers.rb
- spec/support/rubygems_ext.rb
The problem was that testing the latest version of bundler as a vendored copy inside rubygems surfaced some more issues about requiring the wrong code, or activating default gems too early.
My diagnosis was that we should follow similar techniques I've used in other PRs: delay as much as possible requiring default gems, and don't rely on the LOAD_PATH for internal requires.
My fix does just that, and also removes a bunch of `require`'s that were not necessary at all.
> More lazy loading and relative requires

- spec/install/gemfile/git_spec.rb
- spec/install/gemfile/path_spec.rb
- spec/rubygems/rubygems.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
- spec/support/path.rb
- spec/support/rubygems.rb
- spec/support/rubygems_ext.rb
- spec/support/rubygems_version_manager.rb
The problem was that using `RGV` (the environment variable we use to select the proper rubygems version to test bundler against) with a path was not quite working.
Setting `RGV` to a path (`RGV=..`) is used in the rubygems repo to test the vendored copy of bundler (that lives at `bundler/` inside that repo) against the checked out copy of the repository.
My diagnosis was that the previous approach to switch the `rubygems` version, namely, reexec'ing with `--disable-gems` and explicitly requiring our "version switching code" was not quite working because nested subprocesses would end up "leaking" to the system copy of `rubygems` again.
My fix is to use `RUBYOPT` to configure the path to the rubygems copy that should be used, since I found that even the `require "rubygems"` present's in …
> Fix RGV env variable specified as a path

- spec/commands/binstubs_spec.rb
The problem was that I run into some failures when testing rubygems against the latest bundler 2-1-stable branch of bundler.
In certain contexts, the previous approach of overwriting the version constant led into version mismatch issues.
Since in this case we are actually testing some rubygems stuff present in the generated binstub, but we don't really care what the bundler gem is actually doing, we can follow the same approach as other specs and install a "dummy" bundler gem to the system gems home used by our specs.
I chose this fix because it still tests the same thing but in a more resilient way, I believe.
> Improve binstub specs

- .travis.yml
The problem was that CI failed in #7437 due to a network issue.
My diagnosis was that we should add `travis_retry` in the task that failed and other short tasks that may touch the network.
My fix is to do just that.
> Add missing `travis_retry`'s to TravisCI config

- spec/runtime/inline_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
The problem was that we're missing verbose warnings like the one fixed by #7417.
My diagnosis was that our specs should let us know about this.
My fix is to enable warnings from our helpers that shell out, and fix the warnings they print. There's also some unrelated changes here that I'll try to split out once I get this green.
I chose this fix because it makes it so that our specs help us catching these warnings earlier.
> Turn on warning mode for specs

- CHANGELOG.md
The problems were typos in the Changelog
Fix the typos
> Fix typo's in Changelog

- CHANGELOG.md
- lib/bundler/version.rb
The problem was that the master branch needs to be updated with Changelog and version bump from the 2.1.0.pre.3 release.
My fix is to update it.
> Pick up changelog and version bump from 2-1-stable

- lib/bundler/cli/exec.rb
- spec/commands/exec_spec.rb
The problem was that #7401 caused a regression where `bundle exec`'ing to rubygems would silence rubygems output.
My diagnosis was that the removal of:
* Code where `Bundler::RGProxy` would be only set conditionally on `Bundler.ui =` not being passed `nil`.
* Code setting `Bundler.ui` to `nil` right before shelling during `bundle exec`.
caused rubygems UI to be silent during `bundle exec gem`.
My fix is to explictly "unsilence" rubygems UI before `bundle exec` calls.
I chose this fix because it's more explicit than the previous one.
Fixes #7441.
> Fix `bundle exec`'ing to rubygems being silent

- lib/bundler/source/git.rb
- spec/install/git_spec.rb
> Add :glob to git source uniqueness

- lib/bundler/source/git/git_proxy.rb
- spec/support/helpers.rb
The problem was `open3` will be gemified in ruby 2.7, and since we use it inside `bundler`, we might activate a version causing a conflict with the user's choice.
My diagnosis was that only loading it when needed should be better.
My fix is to lazily load it.
I expect this PR to fix [some of the errors](https://travis-ci.org/bundler/bundler/jobs/615940817) currently happening in our CI against ruby-head.
> Lazily load `open3`

- lib/bundler/friendly_errors.rb
The problem was that our ruby-head build is failing in CI.
My diagnosis was that since `cgi` is now a default gem on ruby 2.7, we're getting someunintended activations of the new default gem inside our specs.
My fix is to lazily load CGI.
> Lazily load CGI

- spec/bundler/definition_spec.rb
- spec/bundler/friendly_errors_spec.rb
- spec/commands/binstubs_spec.rb
- spec/commands/install_spec.rb
- spec/install/deploy_spec.rb
- spec/install/gemfile/path_spec.rb
- spec/install/gems/compact_index_spec.rb
- spec/install/gems/resolving_spec.rb
- spec/install/gems/sudo_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/helpers.rb
The original problem was that currently we are having some issues because ruby-core gemified some libraries that we use inside bundler. We shouldn't use default gems during `bundler/setup` because activating them might cause activation conflicts later on if the user has chosen a different version of the default gem from the one that's selected by default.
The good news is that we have some nice specs that check that we never activate default gems, and they've been very useful lately for detecting this kind of breakage.
The bad news is that some of these specs usually fail with really verbose error messages that make it difficult to find the root cause of the problems.
My diagnosis was that we could improve these specs to give better errors.
My fix is to improve the specs with several …
> Improve default gem activation specs

- spec/support/path.rb
The problem was after 5003a436765eb50d9208ffdce4bbe46cf0d6d63b backported from ruby-core, quality_specs are no longer run, not even in our repo.
My diagnosis was that the condition to check whether the root folder is a git folder was incorrect.
My fix is to correct the condition.
> Unskip quality specs

- .rspec_parallel
When running tests using the `parallel_test` tool, there will be no output on the terminal to show the progress or result of the test suit.
```
$ ./bin/parallel_rspec spec         
8 processes for 162 specs, ~ 20 specs per process
Took 576 seconds (9:36)
```
You have to go diving into a file that's located in `tmp/parallel_runtime_rspec.log`.
It would be better to have the output that we get from the regular `./bin/rspec` and show the progress/result of the test suit.
Run the parallel test suit using `./bin/parallel_rspec spec`
Add the additional `progress` formatter to the parallel rspec configuration
> Set parallel_tests to output progress in the same format as regular RSpec

- lib/bundler/inline.rb
- spec/runtime/inline_spec.rb
[Without spacing changes](https://github.com/bundler/bundler/pull/7418/files?w=1)
Closes #7159
> Restore previous BUNDLE_GEMFILE in bundler/inline

- spec/rubygems/rubygems.rb
- spec/spec_helper.rb
- spec/support/rubygems_ext.rb
- spec/support/rubygems_version_manager.rb
The problem was we have some code in our tests to make sure that the `ENV["RGV"]` variable we use to set the rubygems version we want to test bundler against is always respected, including every subprocess our tests start. However:
* The code was overly complicated.
* It didn't support custom branches, for example, `RGV=lazily_load_uri`. This is a feature I find very useful when a PR you're working on also need some changes in the rubygems side, like it happened to me at #7460.
My diagnosis was that all the code needs to do is:
* Set up the location of the rubygems code we'll test bundler against, be it a path, a branch, or a released version.
* Modify `RUBYOPT` to include that location in the LOAD_PATH, so that `rubygems` is always loaded from there instead of the system's version.
My …
> Improve rubygems switcher

- lib/bundler/vendor/fileutils/lib/fileutils.rb
- lib/bundler/vendor/fileutils/lib/fileutils/version.rb
The problem was no big deal. Just a discrepancy between the fileutils version we're vendoring and the one that will ship with ruby 2.7. This doesn't cause any issues, but I prefer that they match.
My fix is to `bin/rake vendor:fileutils[v1.4.1]` and commit the result.
> Vendor fileutils 1.4.1

- doc/development/SETUP.md
We do not have any documentation for running the test suite in parallel. Developers working on Bundler may be unaware that the test suite can be executed in parallel to help speed up the time needed to run tests.
Document how to run the parallel Bundler test suit in the Contributing docs.
> Document running tests in parallel inside a dev environment

- lib/bundler/gem_helper.rb
- spec/commands/clean_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/outdated_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/path.rb
The problem was that I noticed `bundle exec rake install` was failing on my gem using the latest prerelease of bundler.
My diagnosis was that `bundler` silences output of rubygems by default, and in a `bundle exec` context, `bundler/setup` is always required by subprocesses. So, the `rake install` task is silencing rubygems, but it requires it to not be silent:
https://github.com/bundler/bundler/blob/bada03dd6d4d15828fb5b2cf7f744948e88a69a3/lib/bundler/gem_helper.rb#L91-L92
My fix is to wrap the execution of the rubygems subprocess with `Bundler.with_original_env` so that the `gem` command runs without `bundler` involved.
> Fix `bundle exec rake install` failing

- .rubocop.yml
- spec/support/rubygems_ext.rb
RuboCop 0.77.0 has been released.
https://github.com/rubocop-hq/rubocop/releases/tag/v0.77.0
This PR updates the following changes.
```console
% bin/rake rubocop
bin/rubocop --parallel
Error: The `Layout/AlignArray` cop has been renamed to
`Layout/ArrayAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/AlignParameters` cop has been renamed to
`Layout/ParameterAlignment`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentAssignment` cop has been renamed to
`Layout/AssignmentIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The `Layout/IndentFirstArgument` cop has been renamed to
`Layout/FirstArgumentIndentation`.
(obsolete configuration found in .rubocop.yml, please update it)
The …
```
> Bump RuboCop to 0.77.0

- lib/bundler/cli/config.rb
- lib/bundler/cli/update.rb
- lib/bundler/feature_flag.rb
- spec/other/major_deprecation_spec.rb
The problem I was thinking about the upcoming release of bundler 2.1.0, and I'm not convinced about these two deprecations.
I'm not necessarily against them, but these command are very common IMO, and we'll be making them harder to run. Again, maybe for good reasons, but still. That will be combined with the fact that:
* In this same release, we'll be enabling all of the other deprecations.
* Ruby 2.7 will include bundler 2.1 and ruby 2.7 will also come with a lot of warnings about keyword arguments. 
My diagnosis was that I think it's better to postpone these two deprecations for now. Get the other deprecations going and get user feedback about them, and then worry about these two later.
My fix is to delay both deprecations.
I chose this fix because I don't want to be too annoying to …
> Delay deprecation of `bundle config` and `bundle update` without args

- spec/runtime/setup_spec.rb
`ruby-head` build [is broken again](https://travis-ci.org/bundler/bundler/jobs/624581155).
Ruby 2.7 will turn `did_you_mean` into a default gem. That means that bundler tests that make sure that an arbritary version of default gems can be specified in the `Gemfile` will now run against `did_you_mean`. And this doesn't work because `did_you_mean` is activated in ruby's `prelude.rb`, way before `bundler/setup` is required, so the latest version will always be activated, regardless of what the user specifies. If these versions are not the same, a gem activation conflict error will happen.
Note that this problem is not specific to ruby 2.7, it simply gets triggered by the change of making it a default gem, but it would also happen on older versions if the user `did_you_mean` version specified …
> Skip `did_you_mean` and `delegate` failures on MRI 2.7

- spec/install/redownload_spec.rb
- spec/support/builders.rb
This reverts commit f11c4757a17bea029e1a83ad67c425ccf16133ff.
The problem was that since #7451, azure logs are flooded with messages like
```
The file will have its original line endings in your working directory
warning: LF will be replaced by CRLF in foo.gemspec.
```
This makes it hard to scan for other potential errors.
My diagnosis was that some commit in that PR introduced this warnings.
My fix is to revert the offending commit.
> Revert "Write & read dummy gems binarily"

- lib/bundler/vendor/thor/lib/thor/base.rb
- lib/bundler/vendor/thor/lib/thor/nested_context.rb
- lib/bundler/vendor/thor/lib/thor/version.rb
The problem was that `thor` 1.0.0 has been released, so we should vendor it.
My fix is to vendor it.
> Vendor thor 1.0.0

- spec/runtime/setup_spec.rb
The problem was that delegate is now supported since `did_you_mean` drop its dependency on it at https://github.com/ruby/ruby/commit/e2708068ad65f7f9986adf4fb3a4fa660f430a5a.
My diagnosis was that we can test that arbitrary `delegate` versions can be included in Gemfiles again.
My fix removes `delegate` from the exemptions.
> Delegate should be supported now

- spec/bundler/gem_helper_spec.rb
- spec/commands/exec_spec.rb
- spec/support/path.rb
- spec/support/rubygems_ext.rb
Some of the examples failed with ruby-core repository.
The ruby-core repository used `gem` commands under the its repository named `bin/gem` directory. But the current examples points `gem` command with a global path.
I fixed them used by `ruby_core?` helper methods.
> Fixed test failures with gem command path on ruby core repo

- lib/bundler/cli/exec.rb
- lib/bundler/setup.rb
- spec/commands/exec_spec.rb
The problem was that we still have some issues where using the `gem` script on a `bundler` context is silenced.
My diagnosis was that `bundle exec` adds `-rbundler/setup` to RUBYOPT which silences `rubygems` output, and that we need to reset `rubygems` UI after that so that if we end up shelling out to `gem`, it is not silent. The previous approach worked for loading the `gem` script in-process, but didn't work in other case.
My fix is to reset rubygems UI right after `bundler/setup`.
I chose this fix because it fixes the problem independently of the rubygems version being run, but we can probably also fix this more cleanly inside the `gem` script by adding something like `Gem::DefaultUserInteraction.ui = Gem::ConsoleUI.new` at the top of the script.
Fixes #7490.
> Fix another silent rubygems issue

- .travis.yml
- Rakefile
- lib/bundler/rubygems_integration.rb
The problem was that `bundler install` on a `ruby` installation using `rvm` is broken by default.
My diagnosis was that during 2.1.0 development phase I removed some stuff I thought it was internal and nobody would be using.
My fix is to restore a minimal compatibility layer so that this stuff works again.
I chose this fix because I think this is the minimum set of additions that gets stuff working again.
Fixes #7488.
> Add compatibility methods for `rubygems-bundler` gem

- .travis.yml
- Rakefile
- task/release.rake
The problem was that merging #7505 failed.
My diagnosis was that some `apt` operation installing `graphviz` failed, but installing `graphviz` was unnecessary in the specific job that failed.
My fix is to only modifying the OS when strictly necessary.
Also fixed another test issue with the recently added test for integration with the `rubygems-bundler` gem by `rvm`.
> Remove unnecessary CI steps

- lib/bundler/rubygems_integration.rb
- spec/runtime/setup_spec.rb
The problem was some setups have `--disable=gem` in `RUBYOPT`, and sometimes use `bundler` without modifying that env.
My diagnosis was that we shouldn't break those setups just to save a `require`.
My fix is to add a `require "rubygems"` on top of the file that needs it.
Fixes #7487.
> Make sure to `require "rubygems"` explicitly

- .travis.yml
The problem was another failed build due to [apt-get install failing](https://travis-ci.org/bundler/bundler/jobs/627348743).
My diagnosis was TravisCI networking is unstable at the moment.
Not a permanent fix, since that doesn't depend on us, but using `travis_retry` should increase reliability.
> Add `travis_retry` to apt-get operation

- lib/bundler/gem_helper.rb
- spec/runtime/gem_tasks_spec.rb
The problem was that `rake build` can no longer be run from a path that has spaces on it.
My diagnosis was that we need to escape the path for the shell somewhere.
My fix is to add `.shellescape` at the right place.
I chose this fix because it fixes the problem.
Fixes #7512.
> Fix `rake build` when path has spaces on it

- lib/bundler/gem_helper.rb
`gem push` makes you add other parameters, and is awkward to figure out the details. `gem signin` is a more direct way of doing this.
> Improve error message when not logged in

- .travis.yml
So that it's only run once.
The problem was that `bin/rake man:check` is run for every CI matrix entry and that's useless.
My diagnosis was that we should move the check to the linting phase and run it only once, like we did for `rubocop` at https://github.com/bundler/bundler/pull/6830.
My fix is to do that.
> Move `bin/rake man:check` to `linting` phase

- lib/bundler/gem_helper.rb
The problem was that I almost went crazy when trying to release the last bundler version. `rake release` was hanging and I didn't know why.
Thanks to passing `DEBUG=true` to the task, I noticed that it was `git push` and `git push --tags` commands that were hanging:
```
$ DEBUG=true bin/rake release
["gem", "build", "-V", "/home/deivid/Code/bundler/bundler.gemspec"]
bundler 2.1.2 built to pkg/bundler-2.1.2.gem.
["git", "diff", "--exit-code"]
["git", "diff-index", "--quiet", "--cached", "HEAD"]
["git", "tag"]
["git", "tag", "-m", "Version 2.1.2", "v2.1.2"]
Tagged v2.1.2.
git push git push  --tags
^Crake aborted!
Interrupt: 
/home/deivid/Code/bundler/lib/bundler/gem_helper.rb:198:in `read'
/home/deivid/Code/bundler/lib/bundler/gem_helper.rb:198:in `popen' …
```
> Don't spawn a shell when git pushing on release

- lib/bundler/rubygems_integration.rb
The require causes circular require.  See https://github.com/bundler/bundler/pull/7505#issuecomment-568832933
```
$ touch empty_file
$ RUBYGEMS_GEMDEPS=empty_file ./local/bin/ruby -w -e ''
/home/mame/work/ruby/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92: warning: /home/mame/work/ruby/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92: warning: loading in progress, circular require considered harmful - /home/mame/work/ruby/local/lib/ruby/2.7.0/rubygems.rb
from <internal:gem_prelude>:1:in  `<internal:gem_prelude>'
from <internal:gem_prelude>:1:in  `require'
from /home/mame/work/ruby/local/lib/ruby/2.7.0/rubygems.rb:1417:in  `<top (required)>'
from /home/mame/work/ruby/local/lib/ruby/2.7.0/rubygems.rb:1203:in  `use_gemdeps'
from …
```
> Do `require "rubygems"` only when needed

- spec/support/artifice/endpoint.rb
- spec/support/artifice/endpoint_500.rb
- spec/support/artifice/windows.rb
This PR doesn't fix any end-user problem.
This PR fixes a developer problem. Our CI is failed with mustermann 1.1.0.
This is caused because mustermann 1.1.0 starts depending on ruby2_keyword gem but our test script doesn't add a load path for ruby2_keyword gem yet.
See also:
* The PR that adds ruby2_keyword gem dependency to mustermann: https://github.com/sinatra/mustermann/pull/97
* Error message on CI: https://github.com/bundler/bundler/pull/7523#issuecomment-569736683
My fix adds a load path for ruby2_keywrod gem installed in `tmp/1/gems/`.
I don't have another option.
> Fix CI failure with mustermann 1.1.0

- spec/support/helpers.rb
This PR doesn't fix any end-user problem.
This PR just fixes a developer problem.
Some specs runs external commands by `sys_exec` in `spec/support/helpers.rb`. They may be stuck when they outputs many text to its stderr.
`sys_exec` uses `open3`. It uses pipe to communicate an external command. If `rspec` process doesn't read stderr of the external command, the external command is stuck when the external command writes many text to its stderr. Because the external command can't write to pipe infinitely.
The current `sys_exec` tries to fix this situation but it's incomplete:
```ruby
command_execution.stdout = Thread.new { stdout.read }.value.strip
command_execution.stderr = Thread.new { stderr.read }.value.strip
```
`Thread.new { stderr.read ` isn't started until `Thread.new { stdout.read …
> Fix rspec stuck problem for large stderr external command

- spec/support/indexes.rb
This PR doesn't fix any end-user problem.
This PR fixes a developer problem.
RSpec doesn't provide `flunk` method. It's a method name in test-unit and minitest.
3edfddbf7ebe4b942e1e2b6d693afd582e9a8147 may use `flunk` accidentally.
My fix uses `raise` instead of `flunk`.
I don't have another option.
> Use raise instead of flunk

- lib/bundler/cli/install.rb
- spec/commands/outdated_spec.rb
- spec/commands/update_spec.rb
- spec/install/deploy_spec.rb
The problem was that while addressing comments for https://github.com/docker-library/official-images/pull/7188, I noticed that the alternative we're recommending for `bundle install --deployment`, i.e., `bundle config set deployment true`, is not equivalent to it.
My diagnosis was that whereas `bundle install --deployment` configures bundler to be frozen AND to install gems to `vendor/bundle`, `bundle config deployment true` only configures bundler to be frozen.
My fix is to make `bundle config deployment true`  behave just like `bundle install --deployment` in regards to configuration. 
I chose this fix because all the commands we're suggesting as alternatives for deprecations should be actual alternatives that work exactly in the same way.
Also, note that there's a change scheduled for …
> Make `bundle config deployment true` equivalent to `bundle install --deployment` in regards to configuration

- lib/bundler/version.rb
The problem was that master version is set to the latest patch level release, but the code in master doesn't really match the latest patch level release.
My fix is to use 2.2.0.dev to name master's development version.
> Set master's version to 2.2.0.dev

- spec/bundler/bundler_spec.rb
The problem was that this spec was failing under Windows.
My diagnosis was that the test needs Windows specific paths.
My fix is to separate the test per OS.
I chose this fix because it was discussed and considered the better fix at https://github.com/bundler/bundler/issues/6875.
Closes https://github.com/bundler/bundler/issues/6875.
> Adapt `Bundler#which` test to Windows

- spec/bundler/dsl_spec.rb
The problem was that a test for the `gemspec` DSL is failing on Windows.
My diagnosis was that the test uses local platforms (that change between OS) but asserts for ruby platforms.
My fix is to add a proper stub.
I chose this fix because it was suggested in https://github.com/bundler/bundler/issues/6887 by @janpio and looks good.
Closes #6687.
> Make test platform independent

- spec/bundler/shared_helpers_spec.rb
The problem was `SharedHelpers#in_bundle?` specs could fail depending on the run order.
My diagnosis was that the test Gemfile needs to be removed after the test because other specs rely on it being missing.
My fix is to remove the `Gemfile` after the test.
Closes #6891.
> Fix flaky test failures

- spec/commands/clean_spec.rb
- spec/commands/doctor_spec.rb
- spec/support/filters.rb
The problem was that some specs fail under Windows because permissions are not supported the way they are supported on Unix.
My fix is to exclude this tests on Windows.
I chose this fix because it was proposed at https://github.com/bundler/bundler/issues/6897 and makes sense to me.
Closes #6897.
> Ignore tests needing file permissions on Windows

- lib/bundler/inline.rb
- spec/runtime/inline_spec.rb
The problem was that if `BUNDLE_GEMFILE` is not set before requiring `bundler/inline`, we're removing it back again. That means that when requiring gems after that, `bundler` will go through the "Gemfile resolution" logic again and fail if a Gemfile is not found in the filesystem.
My diagnosis was that the file resolution logic should be skipped after requiring `bundler/inline`, since we want to use the "inline bundle".
My fix is to instead reset `BUNDLE_GEMFILE` to the empty string if it had no previous value, since that skips searching the filesystem for a `Gemfile`.
I chose this fix because it seems to fix the issue.
Fixes #7536.
> Reset `Gemfile` to the empty string after bundler/inline

- lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb
- spec/commands/pristine_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/plugins/source/example_spec.rb
- spec/runtime/require_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/builders.rb
- spec/support/matchers.rb
See issue https://github.com/bundler/bundler/issues/7521.
My diagnosis was If you have net-http-pipeline gem installed bundler loads it and you can't vendor it.
My fix is remove the optional require of net-http-pipeline.
I chose this fix because was a recommendation in the issue by @deivid-rodriguez 
Fixes #7521.
> Remove optional require net-http-pipeline from vendored net-http-persistent.

- spec/commands/exec_spec.rb
- spec/commands/install_spec.rb
- spec/commands/show_spec.rb
- spec/install/gemfile/git_spec.rb
- spec/install/gemfile_spec.rb
- spec/install/gems/standalone_spec.rb
- spec/install/global_cache_spec.rb
- spec/quality_es_spec.rb
- spec/quality_spec.rb
- spec/runtime/gem_tasks_spec.rb
- spec/spec_helper.rb
- spec/support/helpers.rb
- spec/support/path.rb
The problem was that some specs were failing under Windows, with error messages like the following:
```
Permission denied @ rb_file_s_rename - (D:/a/1/s/tmp/1/bundled_app, D:/a/1/s/tmp/1/bundled_app2)
Failure/Error: FileUtils.mv(bundled_app, "#{bundled_app}2")
Errno::EACCES:
Permission denied @ rb_file_s_rename - (D:/a/1/s/tmp/1/bundled_app, D:/a/1/s/tmp/1/bundled_app2)
Commands:
$ C:/hostedtoolcache/windows/Ruby/2.6.3/x64/bin/ruby.exe -ID:/a/1/s/lib\;D:/a/1/s/spec -rsupport/hax \
-rsupport/artifice/fail D:/a/1/s/exe/bundle install --path D:/a/1/s/tmp/1/bundled_app/bundle \
--standalone
Fetching d:/a/1/s/tmp/1/libs/devise-1.0
Fetching source index from file:///D:/a/1/s/tmp/1/gems/remote1/
Resolving dependencies...
Fetching rake 12.3.2
Installing rake 12.3.2
Fetching activesupport 2.3.2 …
```
> Don't rename folders while being inside

- spec/runtime/require_spec.rb
- spec/support/command_execution.rb
- spec/support/helpers.rb
The problem was that some specs are failing on Windows due to commands like the following failing:
```
$ C:/hostedtoolcache/windows/Ruby/2.6.3/x64/bin/ruby.exe -Id:/a/bundler/bundler/lib -w -e  \
<<EOS
begin
$:.unshift File.expand_path("bundle")
require "bundler/setup"
require "actionpack"
puts ACTIONPACK
require "spec"
rescue LoadError => e
$stderr.puts "ZOMG LOAD ERROR"# if e.message.include?("-- spec")
end
EOS
-e:2: syntax error, unexpected backslash
\$:.unshift File.expand_path("...
^
-e:10: syntax error, unexpected backslash
\$stderr.puts "ZOMG LOAD ERROR...
^
```
My diagnosis was that if the code being run via `ruby -e` in a subprocess include "$", it was not being properly escaped under Windows.
My fix is to use `shellsplit` and `shellescape`.
I chose this fix because after a bit …
> Fix escaping of some subprocesses during specs

- spec/support/rubygems_ext.rb
The problem was CI is failing due to a rack warning.
My diagnosis was that our CI shouldn't break because of third party changes.
My fix is to lock the rack version our tests use.
I chose this fix because it gives us a more deterministic test environment, which is good.
> Lock rack to 2.0.8 for tests

- spec/bundler/fetcher/compact_index_spec.rb
The problem was failing CI:  https://github.com/rubygems/bundler/runs/386607433.
My diagnosis was that it could be caused by autoloading not being thread safe. The `CompactIndexClient` constant is autoloaded. If two parallel threads try to autoload the constant at the same time, it could happen that one of them sees the constant in an incomplete state (no `initialize` method defined yet).
My fix is to load the constant upfront.
I chose this fix because even if I could stop autoloading the constant, I don't want to touch code in `lib` at the moment just to fix a testing issue.
> Load `CompactIndexClient` upfront during specs

- lib/bundler/compact_index_client/cache.rb
- lib/bundler/compact_index_client/gem_parser.rb
- spec/bundler/compact_index_client/gem_parser_spec.rb
The end-user can't use multiple Ruby version requirements (e.g. ">= 2.2, < 2.7.dev") provided by each gem to resolve suitable version. 
See also: https://github.com/bundler/bundler/pull/7522#issuecomment-571090513
https://rubygems.org/info/ffi returns the following information:
```text
1.11.3-x86-mingw32 |checksum:99e4845796c8dec1c3fc80dc772860a01633b33291bd7534007f5c7724f0b876,ruby:>= 2.2, < 2.7.dev
```
The current parser doesn't parse the line correctly. It drops "< 2.7.dev" requirement for Ruby version.
It means that the parsed requirement is "ruby >= 2.2" instead of "ruby >=2.2 && ruby < 2.7.dev".
I implemented a new parsing logic for "requirements". It assumes that "requirements" has at most three fields: "checksum", "ruby" and "rubygems". Because …
> Fix ruby version parsing in compact index

- lib/bundler/lazy_specification.rb
- lib/bundler/match_platform.rb
- spec/install/gems/resolving_spec.rb
This is a follow-up change of #7522.
The problem was installing wrong platform gem even when resolver resolves the correct platform gem.
See also:
* https://github.com/rubygems/bundler/pull/7522#issuecomment-574628275
* https://github.com/rubygems/bundler/pull/7522#issuecomment-574882536
My diagnosis was `Bundler::LazySpecification#__materialize__` doesn't care about the resolved platform information.
My fix cares about the resolved platform information.
I chose this fix because we should respect the resolved platform information to install correct gem.
> Don't ignore resolved platform information

- lib/bundler/definition.rb
- spec/install/gems/resolving_spec.rb
The code was changed in commit 38b0e7ed64c3ca1c40f43c5aa9a1ead2f6cd7049 so that RubyVersion.system was no longer respected. This is reactivated now and specs are adjusted accordingly.
Not known.
I read the bundler source code and noticed this.
My fix re-adds the ruby version as it was before commit 38b0e7ed64c3ca1c40f43c5aa9a1ead2f6cd7049 , since it seems to be a mistake.
As a alternative I added #7558 that removes the code in question.
> Reactivate usused code for ruby version resolution

- CHANGELOG.md
Related: #7572 ("Update all references to old repo location to new one")
Follow-up for: #7577 ("Update references to old repo location")
This updates all the links in `CHANGELOG.md`. It's a large enough diff that I decided to make a separate PR for it, to avoid blocking #7577.
Command used to update the file:
sed -i 's|https://github.com/bundler/bundler|https://github.com/rubygems/bundler|' CHANGELOG.md
> Update GitHub links in CHANGELOG.md

- spec/runtime/gem_tasks_spec.rb
The problem was that sometimes a spec is failing on Windows because the rename syscall sometimes is raising Errno::EXDEV.
I don't really know why this problem is happening.
My fix is to stop renaming the folder and copy it instead.
I chose this fix because copying will no longer make a rename syscall, so at least it should no longer fail in the same way.
> Fix flaky test failure

- .github/config.yml
- CODE_OF_CONDUCT.md
- README.md
- bundler.gemspec
- doc/POLICIES.md
- doc/contributing/COMMUNITY.md
- doc/contributing/HOW_YOU_CAN_HELP.md
- doc/contributing/ISSUES.md
- doc/contributing/README.md
- doc/development/NEW_FEATURES.md
- doc/development/PULL_REQUESTS.md
- doc/development/SETUP.md
- doc/documentation/README.md
- doc/documentation/WRITING.md
- doc/playbooks/RELEASING.md
- doc/playbooks/TEAM_CHANGES.md
- lib/bundler/remote_specification.rb
- lib/bundler/rubygems_integration.rb
- spec/bundler/bundler_spec.rb
- spec/bundler/compact_index_client/updater_spec.rb
- spec/commands/binstubs_spec.rb
- spec/commands/exec_spec.rb
- spec/commands/lock_spec.rb
- spec/commands/show_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gemfile/ruby_spec.rb
- spec/install/gemfile/sources_spec.rb
- spec/realworld/edgecases_spec.rb
Related: #7572.
A lot of things use the outdated `https://github.com/bundler/bundler` URL (and similarly for e.g. `bundler/bundler-site`).
My fix was to update the outdated URLs. :slightly_smiling_face:
> Update references to old repo location

- lib/bundler/gem_version_promoter.rb
- lib/bundler/resolver.rb
- spec/install/gems/resolving_spec.rb
DEBUG_RESOLVER is used in RubyGems too. So we can't enable it only for
Bundler.
The problem was not the end-user problem. It's a developer problem.
My diagnosis was RubyGems also uses `DEBUG_RESOLVER` environment variable. So we can't use `DEBUG_RESOLVER` environment variable to enable debug mode only for Bundler. We can use `DEBUG_RESOLVER_TREE` instead of `DEBUG_RESOLVER` only for `Bundler::Resolver`. But we can't do it for `Bundler::GemVersionPromoter`.
My fix adds `BUNDLER_` prefix to `DEBUG_RESOLVER` and `DEBUG_RESOLVER_TREE` like other environment variables for Bundler such as `BUNDLER_EDITOR` do.
I chose this fix because adding prefix is a common way. Bundlerd Molinillo and Thor also use this way such as `MOLINILLO_DEBUG` and `THOR_SHELL`.
> Add support for BUNDLER_ prefixed debug environment variables

- spec/bundler/compact_index_client/updater_spec.rb
The problem is the following error when running tests:
```
$ bin/rspec ./spec/bundler/compact_index_client/updater_spec.rb:47
Randomized with seed 40401
/home/deivid/.rbenv/versions/2.7.0/lib/ruby/2.7.0/tmpdir.rb:81: warning: method redefined; discarding old mktmpdir
/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-mocks-3.9.1/lib/rspec/mocks/method_double.rb:63: warning: previous definition of mktmpdir was here
F
Retried examples: 0
Failures:
1) Bundler::CompactIndexClient::Updater when bundler doesn't have permissions on Dir.tmpdir Errno::EACCES is raised
Failure/Error:
expect do
updater.update(local_path, remote_path)
end.to raise_error(Bundler::PermissionError)
expected Bundler::PermissionError, got #<RSpec::Mocks::MockExpectationError: #<Double :fetcher> received …
```
> Fix running compact client updater spec in isolation

- spec/bundler/friendly_errors_spec.rb
The problem was flaky tests: https://www.travis-ci.org/rubygems/bundler/jobs/639403049.
My diagnosis was that if our test code happens to run `Gem.configuration` before `ENV["HOME"]` is changed for our tests, this test starts failing because the test first writes to the global `~/.gemrc` file (not in `tmp/`), because `Gem.config_file` has that value memoized. Then, however, the `bundle install` subprocess infers `Gem.config_file` from the modified `ENV["HOME"]` and tries to read `tmp/home/.gemrc`. However, that file doesn't exist, so rubygems configuration is ignored and doesn't print an error like the test expects.
My fix is to make this test independent from the specific rubygems configuration in the main test process.
> Fix flaky spec failure

- lib/bundler/friendly_errors.rb
- spec/bundler/friendly_errors_spec.rb
See #7192.
Bundler discards `LoadError` class and message when reporting it.
Report class and message of the original exception when reporting `LoadError`.
Fixes #7192
> Report original exception when failing to load openssl

- spec/cache/path_spec.rb
I noticed that when running specs on Windows, sometime I got a `_gem` leftover folder in the root of the repo.
My fix is to run the particular spec creating this test folder in `tmp`, just like the rest of the specs.
> Improve cache specs

- doc/POLICIES.md
The POLICIES file was a bit contradictory, saying in one place that Ruby versions would be dropped in minor releases, and in another place that Ruby versions would be dropped in major releases.
The POLICIES file was not fully updated after several Bundler and RubyGems team discussions, agreements, and public statements during 2019.
This PR updates the POLICIES file to be consistent both with itself and with my understanding of the agreements and statements made by the Bundler and RubyGems teams in 2019.
/cc @deivid-rodriguez @colby-swandale
> Revise compatibility policies

- lib/bundler/friendly_errors.rb
- spec/bundler/friendly_errors_spec.rb
Related to #7192 and #7527. When trying to run bundler without OpenSSL, the resulting warning recommends recompiling Ruby, changing the Gemfile sources to http, and then gives an RVM-specific link that won't be helpful for everyone.
I think the error message is now specific enough to stand on its own and help people debug, so we should remove the warning entirely. (Open to other opinions, though.)
> Don't call Warn on LoadError

- CHANGELOG.md
The problem is that the changelog is up to date on 2-1-stable, but not in master.
My fix is to bring it up to date.
Closes #7607.
> Merge 2.1.4 changelog

- lib/bundler/gem_helper.rb
- spec/bundler/gem_helper_spec.rb
Get rid of escaping and splitting shell code repeatedly.
No changes for the end-users.
As `built_gem_path` in `install_gems` is not escaped, this may fix a trouble in the case the argument have shell special characters.
> Simplify arguments to `sh`

- .github/workflows/jruby.yml
- .rubocop.yml
- lib/bundler/source/path.rb
- spec/realworld/fixtures/warbler/.gitignore
- spec/realworld/fixtures/warbler/Gemfile
- spec/realworld/fixtures/warbler/bin/warbler-example.rb
- spec/realworld/fixtures/warbler/demo/demo.gemspec
The problem is that if a Gemfile contains `:path` gem with a relative path, the bundler environment no longer works when the app is packaged as a `jar` with [warbler](https://github.com/jruby/warbler).
Issue was introduced https://github.com/rubygems/bundler/commit/c7532ced89bbc8ddc7296c56391c1c3cc981c54a, since when `jruby` deals with urls of the form "uri:classloader", it has a weird inconsistency where `Pathname#expand_path` with an argument always returns `uri:classloader://` (double slash) as the canonical version of the path, while `Pathname#expand_path` without an argument always returns `uri:classloader/` (single slash) as the canonical version of it.
```
Pathname.new("uri:classloader://foo/bar").expand_path
Pathname.new("uri:classloader:/foo/bar").expand_path …
```
> Workaround jruby issue

- spec/support/builders.rb
- spec/support/path.rb
The developer problem is that CI is still failing sometimes. The reason is most likely due to side effects when parallelizing specs, since specs still change the current folder globally sometimes.
My changes stop changing folders globally in more places, to try to alleviate these issues.
> More paralelization improvements

- lib/bundler.rb
- spec/commands/config_spec.rb
The problem was that if `BUNDLE_APP_CONFIG` is set to an absolute path, and there's no Gemfile up in the directory hierarchy, bundler would end up using the default config location instead of the customized one.
My fix is to completely avoid bundler's root resolution for resolving the config path in this case, since `BUNDLE_APP_CONFIG` includes all the information we need to know.
Fixes #7610.
> Fix config location edge case

- lib/bundler.rb
When trying to install gems to the system RubyGems and it fails, bundler shows a message as follows:
```
$ bundle install
Your user account isn't allowed to install to the system RubyGems.
You can cancel this installation and run:
bundle install --path vendor/bundle
to install the gems into ./vendor/bundle/, or you can enter your password
and install the bundled gems to RubyGems using sudo.
```
But the `--path` flag is deprecated, `bundle install --path vendor/bundle` shows:
```
$ bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
```
This PR changes the …
> Use `bundle config` instead of a deprecated flag in an error message.

- lib/bundler/templates/newgem/CODE_OF_CONDUCT.md.tt
- spec/quality_spec.rb
The Contributor Covenant was updated to version 2.0 last year, but bundler was still using the old version.
I updated the `.md.tt` file containing the template, careful to preserve the interpolation of the email address.
> Update code of conduct template to CC2.0

- spec/realworld/fixtures/warbler/.gitignore
- spec/realworld/fixtures/warbler/Gemfile.lock
The problem is that our CI is broken after the jruby-9.2.10.0 release.
My workaround is to pin the jruby-jars dependency of the warbler test to 9.2.9.0.
> Pin jruby-jars in warbler test

- spec/support/rubygems_ext.rb
Running `bin/rake spec:deps` from jruby crashes with:
```
rake aborted!
FrozenError: can't modify frozen Hash
/path/to/bundler/spec/support/rubygems_ext.rb:36:in `dev_setup'
/path/to/bundler/Rakefile:29:in `block in <main>'
/path/to/bundler/Rakefile:14:in `block in invoke'
/path/to/bundler/Rakefile:13:in `invoke'
/path/to/bundler/spec/support/rubygems_ext.rb:98:in `gem_load_and_activate'
/path/to/bundler/spec/support/rubygems_ext.rb:45:in `gem_load'
Tasks: TOP => spec:deps
(See full trace by running task with --trace)
```
Unfreeze the hashes, since we are modifying them.
> Unfreeze dependency hashes

- spec/install/gems/resolving_spec.rb
The problem is that in some dev ruby builds, `RUBY_PATCHLEVEL` is `-1`, so the spec crashes because of an ill-formed requirement.
See for example https://github.com/rubygems/rubygems/pull/3077/checks?check_run_id=457988784.
My fix is to change the spec to respect a `RUBY_PATCHLEVEL` equal to `-1`, by reusing code that handles that case.
> Fix resolving specs when run against a dev ruby snapshot

- .travis.yml
- lib/bundler/templates/newgem/Gemfile.tt
- spec/commands/lock_spec.rb
- spec/commands/newgem_spec.rb
- spec/commands/show_spec.rb
- spec/install/gemfile/gemspec_spec.rb
- spec/install/gems/compact_index_spec.rb
- spec/lock/lockfile_spec.rb
- spec/runtime/setup_spec.rb
- spec/support/builders.rb
- spec/support/rubygems_ext.rb
The problem is rake 12 prints a bunch of warnings on ruby 2.7.
My fix is to upgrade rake everywhere.
> Bump rake version to 13.0 everywhere

- lib/bundler.rb
- lib/bundler/cli/gem.rb
- lib/bundler/cli/init.rb
Fixes #7626.
Resolving gemfile name preference - original `Gemfile` or newer `gems.rb` moved to Bundler's singleton as being shared by multiple classes, ie. because of DRY principle.
> Adhere to gemfile name preference also for project skeleton.

- lib/bundler/resolver.rb
- spec/install/gems/resolving_spec.rb
The problem was not a end-user problem. This was a developer problem.
If we have many debug messages (for example, I added many `pp [...]` to debug #7522), it's difficult to find resolver's debug messages.
My diagnosis was no common keywords in resolver's debug message is a problem. If we have a common keyword, we can find resolver's debug messages from many debug messages easily.
My fix prepends `BUNDLER: ` to all resolver's debug messages. If we have the same label in all resolver's debug messages, we can find resolver's debug message easily. For example, we can use "/BUNDLER:" in less.
I chose this fix because `BUNDLER: ` will not conflict. Other candidate is `DEBUG: ` but it may be used by other library. If the keyword conflicts, it's not easy to find resolver's debug messages. …
> Prepend debug label to resolver's debug message

- lib/bundler/cli/outdated.rb
- lib/bundler/definition.rb
- lib/bundler/inline.rb
- lib/bundler/settings.rb
- man/bundle-config.1
- man/bundle-config.1.txt
- man/bundle-config.ronn
- spec/install/gemfile/platform_spec.rb
- spec/runtime/require_spec.rb
This PR is a reintroduction of #7215, now that I consider the multiplatform feature usable enough.
The problem was that currently if the gemfile include gems for specific platforms, like the default `gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]` Rails uses, bundler will always print a noisy warning, but I don't think users are doing anything wrong, just running `bundle install` on it.
Also, unless they run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`, and commit the resulting lockfile, they will continue to get the same warning over and over again.
My diagnosis is that the fact that some gems will be unused under some platforms is inherent to the multiplatform feature itself, so we shouldn't warn about it because it's expected.
Take the …
> Automultiplatform again

- UPGRADING.md
Upgrading document talks about bundler 2.1 in future tense, but it has already been released.
Update text to reflect the deprecation texts are already added in version 2.1, and that version 2.1 has already been released
> Reformulation of changes after bundler 2.1 has been released

- CODE_OF_CONDUCT.md
Bundler has had a code of conduct since before the Contributor Covenant was available as an option. In my (admittedly somewhat vague) memory, we continued to use our own custom CoC based on wanting clear enforcement examples directly in the CoC. The Contributor Covenant now contains enforcement examples as of 2.0, so I am proposing that we migrate Bundler's CoC to CC 2.0.
Additional benefits:
- Merging with RubyGems gets easier, since RubyGems uses CC already (rubygems/rubygems#3157).
- The `bundle gem` template and Bundler itself will now use the same CoC.
> Revise CoC based on Contributor Covenant 2.0

- .travis.yml
- Rakefile
The developer problem is that sudo specs are not correctly setting the environment (except for ruby 2.3). The specs are accidentally passing but you can tell that they are running against the system ruby by the [warning messages they print](https://travis-ci.org/rubygems/bundler/jobs/658272719#L531-L558).
This causes problems when migrating to github actions. See https://github.com/rubygems/bundler/pull/7660#discussion_r385616844.
Another problem is that the environment is setup manually outside of `rake spec:sudo`, so there's no easy way of running sudo specs manually if your system does not have the right sudoers configuration.
My fix is to properly set sudo configuration to preserve the environment so that the correct ruby can be found by sudo specs, and also to move the logic inside …
> Fix sudo specs environment
